### ISSUE TITLE
R 3.3.1 package missing jpeg, png, tiff, and cairo support

### ISSUE THREAD

**Issue by jnm** [ContinuumIO/anaconda-issues#1063]
Would it be possible to restore these capabilities? They were present in the 3.2.2 package:

```
$ conda install --quiet -c r r=3.2.2
Fetching package metadata .........
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /home/fubar/miniconda2:
#
r                         3.2.2                         0    r
$ echo 'capabilities()' | R --no-save --quiet
> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua 
       TRUE        TRUE        TRUE        TRUE       FALSE       FALSE 
   http/ftp     sockets      libxml        fifo      cledit       iconv 
       TRUE        TRUE        TRUE        TRUE       FALSE        TRUE 
        NLS     profmem       cairo         ICU long.double     libcurl 
       TRUE       FALSE        TRUE       FALSE        TRUE       FALSE 
```

With 3.3.1, they're gone:

```
$ conda install --quiet -c r r=3.3.1
Fetching package metadata .........
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /home/fubar/miniconda2:
#
r                         3.3.1                  r3.3.1_0    r
$ echo 'capabilities()' | R --no-save --quiet
> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua 
      FALSE       FALSE       FALSE        TRUE       FALSE       FALSE 
   http/ftp     sockets      libxml        fifo      cledit       iconv 
       TRUE        TRUE        TRUE        TRUE       FALSE        TRUE 
        NLS     profmem       cairo         ICU long.double     libcurl 
       TRUE        TRUE       FALSE        TRUE        TRUE        TRUE 
```

Thank you.

**Comment by mingwandroid** [comment]
Please show the output of:
`conda info`
and:
`conda list --show-channel-urls`

**Comment by jnm** [comment]
Here they are with 3.3.1 installed. Let me know if you'd also like the `conda list` output while 3.2.2 is installed.
```
$ conda info
Current conda install:

             platform : linux-64
        conda version : 4.1.12
    conda-env version : 2.5.2
  conda-build version : not installed
       python version : 2.7.12.final.0
     requests version : 2.10.0
     root environment : /home/fubar/miniconda2  (writable)
  default environment : /home/fubar/miniconda2
     envs directories : /home/fubar/miniconda2/envs
        package cache : /home/fubar/miniconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False
```

```
$ conda list --show-channel-urls
# packages in environment at /home/fubar/miniconda2:
#
bzip2                     1.0.6                         3    defaults
cairo                     1.12.18                       6    defaults
conda                     4.1.12                   py27_0    defaults
conda-env                 2.5.2                    py27_0    defaults
curl                      7.49.0                        1    defaults
fontconfig                2.11.1                        6    defaults
freetype                  2.5.5                         1    defaults
icu                       54.1                          0    defaults
jbig                      2.1                           0    defaults
jpeg                      8d                            1    defaults
libffi                    3.2.1                         0    defaults
libpng                    1.6.22                        0    defaults
libtiff                   4.0.6                         2    defaults
libxml2                   2.9.2                         0    defaults
openssl                   1.0.2h                        1    defaults
pcre                      8.39                          0    defaults
pip                       8.1.2                    py27_0    defaults
pixman                    0.32.6                        0    defaults
pycosat                   0.6.1                    py27_1    defaults
pycrypto                  2.6.1                    py27_4    defaults
python                    2.7.12                        1    defaults
pyyaml                    3.11                     py27_4    defaults
glib                      2.43.0                        2    r
gsl                       1.16                          1    r
harfbuzz                  0.9.35                        6    r
libgcc                    4.8.5                         1    r
ncurses                   5.9                           8    r
pango                     1.36.8                        3    r
r                         3.3.1                  r3.3.1_0    r
r-base                    3.3.1                         3    r
r-boot                    1.3_18                 r3.3.1_0    r
r-class                   7.3_14                 r3.3.1_0    r
r-cluster                 2.0.4                  r3.3.1_0    r
r-codetools               0.2_14                 r3.3.1_0    r
r-foreign                 0.8_66                 r3.3.1_0    r
r-kernsmooth              2.23_15                r3.3.1_0    r
r-lattice                 0.20_33                r3.3.1_0    r
r-mass                    7.3_45                 r3.3.1_0    r
r-matrix                  1.2_6                  r3.3.1_0    r
r-mgcv                    1.8_12                 r3.3.1_0    r
r-nlme                    3.1_128                r3.3.1_0    r
r-nnet                    7.3_12                 r3.3.1_0    r
r-recommended             3.3.1                  r3.3.1_0    r
r-rpart                   4.1_10                 r3.3.1_0    r
r-spatial                 7.3_11                 r3.3.1_0    r
r-survival                2.39_4                 r3.3.1_0    r
readline                  6.2                           2    defaults
requests                  2.10.0                   py27_0    defaults
ruamel_yaml               0.11.14                  py27_0    defaults
setuptools                23.0.0                   py27_0    defaults
sqlite                    3.13.0                        0    defaults
tk                        8.5.18                        0    defaults
wheel                     0.29.0                   py27_0    defaults
xz                        5.2.2                         0    defaults
yaml                      0.1.6                         0    defaults
zlib                      1.2.8                         3    defaults
```

**Comment by leipzig** [comment]
```
$ conda create -n cairobug r==3.3.1

$ source activate cairobug

(cairobug)$ conda install --quiet -c r r-cairo

(cairobug)$ R

> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua 
      FALSE       FALSE       FALSE        TRUE       FALSE       FALSE 
   http/ftp     sockets      libxml        fifo      cledit       iconv 
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE 
        NLS     profmem       cairo         ICU long.double     libcurl 
       TRUE        TRUE       FALSE        TRUE        TRUE        TRUE 
Warning message:
In doTryCatch(return(expr), name, parentenv, handler) :
  unable to load shared object '/home/leipzigj/conda/envs/cairobug/lib64/R/modules//R_X11.so':
  libjpeg.so.8: cannot open shared object file: No such file or directory

(cairobug)$ conda install jpeg=8
(cairobug)$ R

> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua 
      FALSE       FALSE       FALSE        TRUE       FALSE       FALSE 
   http/ftp     sockets      libxml        fifo      cledit       iconv 
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE 
        NLS     profmem       cairo         ICU long.double     libcurl 
       TRUE        TRUE       FALSE        TRUE        TRUE        TRUE 
Warning message:
In doTryCatch(return(expr), name, parentenv, handler) :
  unable to load shared object '/home/leipzigj/conda/envs/cairobug/lib64/R/modules//R_X11.so':
  libjpeg.so.9: cannot open shared object file: No such file or directory
```

**Comment by parente** [comment]
The problem seems to have appeared somehow between between r-base 3.3.1 build 1 and r-base 3.3.1 build 3 (https://github.com/conda/conda-recipes/compare/601fd5d16627371e9595e65b4c8e79c305942c6d...dfe2d55f7616a22242c1616ab32ad25ee5806dfd).

**Comment by flying-sheep** [comment]
you switched around the deps quite a bit in [dee9542](https://github.com/conda/conda-recipes/commit/dee9542272b2bcc1e49f5ac23ab5d46fbe37e926?w=1). that *might* be it.

you should maybe add a test for R like `Rscript -e "stopifnot(all(capabilities(c('cairo', 'png'))))"`

**Comment by mingwandroid** [comment]
@flying-sheep I didn't change any dependencies in https://github.com/conda/conda-recipes/commit/dee9542272b2bcc1e49f5ac23ab5d46fbe37e926. The only change there is renaming the jinja2 template variable `pfx` to `native`.

I actually already do test the capabilities are as I expect them to be before I upload each release, and I have never encountered this problem, nor have I been able to reproduce it (on a range of Linux distros).

I suspect it is a bad interaction between the system libraries and the conda libraries due to the fact the R is happy to mess with `LD_LIBRARY_PATH` instead of using `RPATH`. Today I worked on a [patch](https://github.com/mingwandroid/conda-recipes/blob/master/r-base/0011-Linux-Do-not-modify-LD_LIBRARY_PATH.patch) to address this and uploaded new [builds](https://anaconda.org/rdonnellyr/r-base). If anyone would like to test them I'd appreciate it:

```
conda update -c r r-essentials
conda update -c rdonnellyr r-base
```

Thanks!

**Comment by baixia84** [comment]
use conda install r-base 3.3.1-1 can solve this problem, this version is also compatible with r-rJava 0.9_8

**Comment by mingwandroid** [comment]
@baixia84, did you also try:

```
conda update -c r r-essentials
conda update -c rdonnellyr r-base
```

**Comment by jnm** [comment]
Hi @mingwandroid, sorry for the delay on my end. I just tried your new builds; unfortunately they did not solve the issue for me. Since you mentioned not having an environment to reproduce the problem, I started my latest test using a fresh Docker container created with the `ubuntu:trusty` image. Sorry for the verbosity, but perhaps the output will be of some use (especially the `R: 12: [: Linux: unexpected operator` part?):
```
host-machine # docker run -it ubuntu:trusty
root@ce54393fc27d:/# apt-get -qq update
root@ce54393fc27d:/# apt-get -qq install wget
[snip]
root@ce54393fc27d:/# wget 'https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh'
[snip]
root@ce54393fc27d:/# bash Miniconda2-latest-Linux-x86_64.sh 

Welcome to Miniconda2 4.2.12 (by Continuum Analytics, Inc.)

In order to continue the installation process, please review the license
agreement.
Please, press ENTER to continue
>>> 
=================
Miniconda License
=================
[snip]
Do you approve the license terms? [yes|no]
>>> yes

Miniconda2 will now be installed into this location:
/root/miniconda2

  - Press ENTER to confirm the location
  - Press CTRL-C to abort the installation
  - Or specify a different location below

[/root/miniconda2] >>> 
PREFIX=/root/miniconda2
installing: python-2.7.12-1 ...
installing: conda-env-2.6.0-0 ...
installing: enum34-1.1.6-py27_0 ...
installing: openssl-1.0.2j-0 ...
installing: pycosat-0.6.1-py27_1 ...
installing: readline-6.2-2 ...
installing: requests-2.11.1-py27_0 ...
installing: ruamel_yaml-0.11.14-py27_0 ...
installing: sqlite-3.13.0-0 ...
installing: tk-8.5.18-0 ...
installing: yaml-0.1.6-0 ...
installing: zlib-1.2.8-3 ...
installing: conda-4.2.12-py27_0 ...
installing: pycrypto-2.6.1-py27_4 ...
installing: pip-8.1.2-py27_0 ...
installing: wheel-0.29.0-py27_0 ...
installing: setuptools-27.2.0-py27_0 ...
Python 2.7.12 :: Continuum Analytics, Inc.
creating default environment...
installation finished.
Do you wish the installer to prepend the Miniconda2 install location
to PATH in your /root/.bashrc ? [yes|no]
[no] >>> 

You may wish to edit your .bashrc or prepend the Miniconda2 install location:

$ export PATH=/root/miniconda2/bin:$PATH

Thank you for installing Miniconda2!

Share your notebooks and packages on Anaconda Cloud!
Sign up for free: https://anaconda.org

root@ce54393fc27d:/# /root/miniconda2/bin/conda create -n test
Fetching package metadata .......
.Solving package specifications: .
Package plan for installation in environment /root/miniconda2/envs/test:

The following empty environments will be CREATED:

/root/miniconda2/envs/test

Proceed ([y]/n)? 

#
# To activate this environment, use:
# > source activate test
#
# To deactivate this environment, use:
# > source deactivate test
#

root@ce54393fc27d:/# source /root/miniconda2/bin/activate test
(test) root@ce54393fc27d:/# conda install -c rdonnellyr r-base
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /root/miniconda2/envs/test:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bzip2-1.0.6                |                3          83 KB
    icu-54.1                   |                0        11.3 MB
    jbig-2.1                   |                0          29 KB
    jpeg-8d                    |                2         806 KB
    libffi-3.2.1               |                0          36 KB
    libgcc-5.2.0               |                0         1.1 MB
    pixman-0.32.6              |                0         2.4 MB
    xz-5.2.2                   |                0         644 KB
    curl-7.49.0                |                1         543 KB
    glib-2.43.0                |                1         5.4 MB
    gsl-2.1                    |                1         7.3 MB
    libpng-1.6.22              |                0         214 KB
    libtiff-4.0.6              |                2         1.5 MB
    libxml2-2.9.2              |                0         4.2 MB
    ncurses-5.9                |                8         836 KB
    pcre-8.39                  |                0         553 KB
    freetype-2.5.5             |                1         2.5 MB
    fontconfig-2.11.1          |                6         405 KB
    cairo-1.12.18              |                6         594 KB
    harfbuzz-0.9.39            |                1         1.1 MB
    pango-1.39.0               |                1         668 KB
    r-base-3.3.1               |                5        21.7 MB  rdonnellyr
    ------------------------------------------------------------
                                           Total:        63.7 MB

The following NEW packages will be INSTALLED:

    bzip2:      1.0.6-3             
    cairo:      1.12.18-6           
    curl:       7.49.0-1            
    fontconfig: 2.11.1-6            
    freetype:   2.5.5-1             
    glib:       2.43.0-1            
    gsl:        2.1-1               
    harfbuzz:   0.9.39-1            
    icu:        54.1-0              
    jbig:       2.1-0               
    jpeg:       8d-2                
    libffi:     3.2.1-0             
    libgcc:     5.2.0-0             
    libpng:     1.6.22-0            
    libtiff:    4.0.6-2             
    libxml2:    2.9.2-0             
    ncurses:    5.9-8               
    openssl:    1.0.2j-0            
    pango:      1.39.0-1            
    pcre:       8.39-0              
    pixman:     0.32.6-0            
    r-base:     3.3.1-5   rdonnellyr
    readline:   6.2-2               
    tk:         8.5.18-0            
    xz:         5.2.2-0             
    zlib:       1.2.8-3             

Proceed ([y]/n)? 

Fetching packages ...
bzip2-1.0.6-3. 100% |##############################################################| Time: 0:00:00  13.44 MB/s
icu-54.1-0.tar 100% |##############################################################| Time: 0:00:00  20.09 MB/s
jbig-2.1-0.tar 100% |##############################################################| Time: 0:00:00  14.84 MB/s
jpeg-8d-2.tar. 100% |##############################################################| Time: 0:00:00  13.25 MB/s
libffi-3.2.1-0 100% |##############################################################| Time: 0:00:00   8.91 MB/s
libgcc-5.2.0-0 100% |##############################################################| Time: 0:00:00  14.21 MB/s
pixman-0.32.6- 100% |##############################################################| Time: 0:00:00  20.49 MB/s
xz-5.2.2-0.tar 100% |##############################################################| Time: 0:00:00  12.35 MB/s
curl-7.49.0-1. 100% |##############################################################| Time: 0:00:00  19.91 MB/s
glib-2.43.0-1. 100% |##############################################################| Time: 0:00:00  18.67 MB/s
gsl-2.1-1.tar. 100% |##############################################################| Time: 0:00:00  22.46 MB/s
libpng-1.6.22- 100% |##############################################################| Time: 0:00:00  13.46 MB/s
libtiff-4.0.6- 100% |##############################################################| Time: 0:00:00  22.17 MB/s
libxml2-2.9.2- 100% |##############################################################| Time: 0:00:00  18.14 MB/s
ncurses-5.9-8. 100% |##############################################################| Time: 0:00:00  16.17 MB/s
pcre-8.39-0.ta 100% |##############################################################| Time: 0:00:00  18.59 MB/s
freetype-2.5.5 100% |##############################################################| Time: 0:00:00  24.21 MB/s
fontconfig-2.1 100% |##############################################################| Time: 0:00:00  10.87 MB/s
cairo-1.12.18- 100% |##############################################################| Time: 0:00:00  17.50 MB/s
harfbuzz-0.9.3 100% |##############################################################| Time: 0:00:00  12.62 MB/s
pango-1.39.0-1 100% |##############################################################| Time: 0:00:00  11.39 MB/s
r-base-3.3.1-5 100% |##############################################################| Time: 0:00:01  14.93 MB/s
Extracting packages ...
[      COMPLETE      ]|#################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|#################################################################################| 100%
(test) root@ce54393fc27d:/# R
/root/miniconda2/envs/test/bin/R: 12: [: Linux: unexpected operator

R version 3.3.1 (2016-06-21) -- "Bug in Your Hair"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua 
      FALSE       FALSE       FALSE        TRUE       FALSE       FALSE 
   http/ftp     sockets      libxml        fifo      cledit       iconv 
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE 
        NLS     profmem       cairo         ICU long.double     libcurl 
       TRUE        TRUE       FALSE        TRUE        TRUE        TRUE 
Warning message:
In doTryCatch(return(expr), name, parentenv, handler) :
  unable to load shared object '/root/miniconda2/envs/test/lib/R/modules//R_X11.so':
  libSM.so.6: cannot open shared object file: No such file or directory
> 
```

**Comment by dakl** [comment]
I have the same as @jnm issue with R 3.3.1 but on centos7. 

```
$ conda install --file conda-list.txt
Fetching package metadata .............
Solving package specifications: ..........
Warning: 2 possible package resolutions (only showing differing packages):
  - bioconda::bioconductor-biobase-2.32.0-r3.3.1_0.tar.bz2
  - bioconda::bioconductor-biobase-2.32.0-0.tar.bz2

Package plan for installation in environment /home/vagrant/miniconda2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bcftools-1.3.1             |                1         1.7 MB  bioconda
    r-digest-0.6.9             |         r3.3.1_0         110 KB  bioconda
    r-jsonlite-0.9.19          |         r3.3.1_0         913 KB  bioconda
    r-ggplot2-2.1.0            |         r3.3.1_0         2.0 MB  bioconda
    ------------------------------------------------------------
                                           Total:         4.7 MB

The following NEW packages will be INSTALLED:

    bioconductor-annotationdbi:        1.36.0-r3.3.1_1   bioconda
    bioconductor-biobase:              2.32.0-r3.3.1_0   bioconda
    bioconductor-biocgenerics:         0.20.0-r3.3.1_0   bioconda
    bioconductor-biocparallel:         1.6.6-r3.3.1_0    bioconda
    bioconductor-biomart:              2.28.0-r3.3.1_0   bioconda
    bioconductor-biostrings:           2.40.0-r3.3.1_0   bioconda
    bioconductor-bsgenome:             1.40.1-r3.3.1_0   bioconda
    bioconductor-cghbase:              1.32.0-r3.3.1_1   bioconda
    bioconductor-cghcall:              2.34.1-r3.3.1_0   bioconda
    bioconductor-dnacopy:              1.46.0-r3.3.1_0   bioconda
    bioconductor-genomeinfodb:         1.8.7-r3.3.1_0    bioconda
    bioconductor-genomicalignments:    1.10.0-r3.3.1_0   bioconda
    bioconductor-genomicfeatures:      1.26.0-r3.3.1_2   bioconda
    bioconductor-genomicranges:        1.26.1-r3.3.1_1   bioconda
    bioconductor-impute:               1.46.0-r3.3.1_0   bioconda
    bioconductor-iranges:              2.8.0-r3.3.1_0    bioconda
    bioconductor-limma:                3.29.0-r3.3.1_0   bioconda
    bioconductor-marray:               1.50.0-r3.3.1_1   bioconda
    bioconductor-qdnaseq:              1.8.0-0           bioconda
    bioconductor-rsamtools:            1.26.1-r3.3.1_0   bioconda
    bioconductor-rtracklayer:          1.34.1-r3.3.1_0   bioconda
    bioconductor-s4vectors:            0.12.0-r3.3.1_0   bioconda
    bioconductor-summarizedexperiment: 1.4.0-r3.3.1_0    bioconda
    bioconductor-variantannotation:    1.16.4-0          bioconda
    bioconductor-xvector:              0.12.1-r3.3.1_0   bioconda
    bioconductor-zlibbioc:             1.18.0-r3.3.1_0   bioconda
    cnvkit:                            0.7.9-py27_0      bioconda
    r-base:                            3.3.1-3           r       
    r-boot:                            1.3_18-r3.3.1_0   r       
    r-cghflasso:                       0.2_1-r3.3.1_0    bioconda
    r-chron:                           2.3_47-r3.3.1_0   r       
    r-class:                           7.3_14-r3.3.1_0   r       
    r-cluster:                         2.0.4-r3.3.1_0    r       
    r-codetools:                       0.2_14-r3.3.1_0   r       
    r-colorspace:                      1.2_6-r3.3.1_0    r       
    r-curl:                            0.9.7-r3.3.1_0    r       
    r-data.table:                      1.9.6-r3.3.1_0    r       
    r-dbi:                             0.4_1-r3.3.1_0    r       
    r-devtools:                        1.11.1-r3.3.1_0   r       
    r-digest:                          0.6.9-r3.3.1_0    bioconda
    r-foreign:                         0.8_66-r3.3.1_0   r       
    r-futile.logger:                   1.4.1-r3.3.1_0    bioconda
    r-futile.options:                  1.0.0-r3.3.1_0    bioconda
    r-future:                          0.9.0-r3.3.1_0    bioconda
    r-getopt:                          1.20.0-r3.3.1_0   bioconda
    r-ggplot2:                         2.1.0-r3.3.1_0    bioconda
    r-git2r:                           0.15.0-r3.3.1_0   r       
    r-globals:                         0.6.0-r3.3.1_0    bioconda
    r-gtable:                          0.2.0-r3.3.1_0    r       
    r-httr:                            1.2.0-r3.3.1_0    r       
    r-jsonlite:                        0.9.19-r3.3.1_0   bioconda
    r-kernsmooth:                      2.23_15-r3.3.1_0  r       
    r-lambda.r:                        1.1.7-r3.3.1_0    bioconda
    r-lattice:                         0.20_33-r3.3.1_0  r       
    r-listenv:                         0.5.0-r3.3.1_0    bioconda
    r-mass:                            7.3_45-r3.3.1_0   r       
    r-matrix:                          1.2_6-r3.3.1_0    r       
    r-matrixstats:                     0.50.1-r3.3.1_0   bioconda
    r-memoise:                         1.0.0-r3.3.1_0    r       
    r-mgcv:                            1.8_12-r3.3.1_0   r       
    r-mime:                            0.4-r3.3.1_0      r       
    r-munsell:                         0.4.3-r3.3.1_0    r       
    r-nlme:                            3.1_128-r3.3.1_0  r       
    r-nnet:                            7.3_12-r3.3.1_0   r       
    r-openssl:                         0.9.4-r3.3.1_0    r       
    r-plyr:                            1.8.4-r3.3.1_0    r       
    r-pscbs:                           0.60.0-r3.3.1_0   bioconda
    r-r.cache:                         0.12.0-r3.3.1_0   bioconda
    r-r.methodss3:                     1.7.0-r3.3.1_0    bioconda
    r-r.oo:                            1.19.0-r3.3.1_0   bioconda
    r-r.utils:                         2.2.0-r3.3.1_0    bioconda
    r-r6:                              2.1.2-r3.3.1_0    r       
    r-rcpp:                            0.12.5-r3.3.1_0   r       
    r-rcurl:                           1.95_4.8-r3.3.1_0 r       
    r-recommended:                     3.3.1-r3.3.1_0    r       
    r-reshape:                         0.8.5-r3.3.1_3    r       
    r-reshape2:                        1.4.1-r3.3.1_2    r       
    r-rpart:                           4.1_10-r3.3.1_0   r       
    r-rsqlite:                         1.0.0-r3.3.1_2    r       
    r-rstudioapi:                      0.5-r3.3.1_0      r       
    r-scales:                          0.4.0-r3.3.1_0    r       
    r-snow:                            0.4_1-r3.3.1_0    bioconda
    r-snowfall:                        1.84_6.1-r3.3.1_0 bioconda
    r-spatial:                         7.3_11-r3.3.1_0   r       
    r-stringi:                         1.1.1-r3.3.1_0    r       
    r-stringr:                         1.0.0-r3.3.1_0    r       
    r-survival:                        2.39_4-r3.3.1_0   r       
    r-withr:                           1.0.2-r3.3.1_0    r       
    r-xml:                             3.98_1.4-r3.3.1_0 r       

The following packages will be UPDATED:

    bcftools:                          1.2-2             bioconda --> 1.3.1-1        bioconda
    r:                                 3.1.2-2           r        --> 3.3.1-r3.3.1_0 r       
    r-rjsonio:                         1.3_0-0a          r        --> 1.3_0-r3.3.1_2 r       

Proceed ([y]/n)? y

Pruning fetched packages from the cache ...
Fetching packages ...
bcftools-1.3.1 100% |###########################################################################################| Time: 0:00:01   1.29 MB/s
r-digest-0.6.9 100% |###########################################################################################| Time: 0:00:00 153.98 kB/s
r-jsonlite-0.9 100% |###########################################################################################| Time: 0:00:01 868.64 kB/s
r-ggplot2-2.1. 100% |###########################################################################################| Time: 0:00:01   1.36 MB/s
Extracting packages ...
[      COMPLETE      ]|##############################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##############################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|##############################################################################################################| 100%

$ R

R version 3.3.1 (2016-06-21) -- "Bug in Your Hair"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> png()
Error in .External2(C_X11, paste("png::", filename, sep = ""), g$width,  : 
  unable to start device PNG
In addition: Warning message:
In png() : unable to open connection to X11 display ''
```

**Comment by MaxPowerWasTaken** [comment]
@baixia84 wrote "use conda install r-base 3.3.1-1 can solve this problem" but I tried 
`conda install r-base 3.3.1-1` and
`conda install r-base=3.3.1-1`

...and each returned PackageNotFoundError...

**Comment by parente** [comment]
@MaxPowerWasTaken try `conda install 'r-base=3.3.1 1'` with the space.

**Comment by mingwandroid** [comment]
r 3.3.2 is available now. This Cairo issue is fixed on Linux and macOS and I also added a large amount of new packages including the tidyverse.

`conda update -c r r-essentials`

**Comment by abalter** [comment]
This did not fix my problem. Also tried reverting to v3.1.3 with no avail:

I tried going back to v3.1.3 and still having the X11 problem:

```
> sessionInfo()
R version 3.1.3 (2015-03-09)
Platform: x86_64-unknown-linux-gnu (64-bit)
Running under: CentOS release 6.5 (Final)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base
> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua
       TRUE        TRUE        TRUE        TRUE       FALSE       FALSE
   http/ftp     sockets      libxml        fifo      cledit       iconv
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE
        NLS     profmem       cairo         ICU long.double
       TRUE       FALSE        TRUE       FALSE        TRUE
Warning message:
In doTryCatch(return(expr), name, parentenv, handler) :
  unable to load shared object '/home/.../Applications/miniconda3/envs/r311/lib/R/modules//R_X11.so':
  libjpeg.so.8: cannot open shared object file: No such file or directory
> plot(1:10,1:10)
Error in (function (display = "", width, height, pointsize, gamma, bg,  :
  X11 module cannot be loaded
```

I've ssh'd in with X. `xclock` opens and I can plot in python.

Furthermore: 

```
(r311) balter@server:~$ ls -l /home/.../Applications/miniconda3/envs/r311/lib/R/modules/
total 13
-rwxr-xr-x 2 balter somegroup  89840 Jun  2  2015 internet.so
-rwxr-xr-x 2 balter somegroup  45779 Jun  2  2015 lapack.so
-rwxr-xr-x 2 balter somegroup  69296 Jun  2  2015 R_de.so
-rwxr-xr-x 2 balter somegroup 169562 Jun  2  2015 R_X11.so
-rwxr-xr-x 2 balter somegroup 616020 Jun  2  2015 vfonts.so
```

So, why can't it load `R_X11.so`? Is the double slash `//` the problem?

**Comment by mingwandroid** [comment]
If you want to try with R 3.3.2 then I can try to help you. What is `...` in this case? Is it an actual folder-name?

I recommend starting from scratch with your installation if possible and installing R via:

`conda install -c r r-essentials=1.5.1`

If it doesn't work after that then please show the output from `conda info` and `conda list --show-package-urls`.

**Comment by abalter** [comment]
@mingwandroid `...` is because I can't show our actual paths for security. Sorry about that. What I showed above is inside a conda  environment for v3.1.3. I also tried a 3.2.2 environment. I did not try installing a specific version of `r-essentials`.

It would be best to avoid a complete reinstall. 

```
conda list
# packages in environment at /home/exacloud/lustre1/BioCoders/Applications/miniconda3/envs/r322:
#
bleach                    1.4.2                    py35_0    bioconda
bzip2                     1.0.6                         3  
ca-certificates           2016.9.26                     0    conda-forge
cairo                     1.14.6                        3    conda-forge
certifi                   2016.9.26                py35_0    conda-forge
curl                      7.45.0                        2    bioconda
decorator                 4.0.11                   py35_0    conda-forge
entrypoints               0.2.2                    py35_1    conda-forge
fontconfig                2.12.1                        3    conda-forge
freetype                  2.7                           0    conda-forge
gettext                   0.19.8                        0    bioconda
glib                      2.51.0                        2    conda-forge
gmp                       6.1.2                         0    conda-forge
gsl                       2.2.1                         1    conda-forge
harfbuzz                  1.3.4                         1    conda-forge
html5lib                  0.999                    py35_0  
icu                       56.1                          4    conda-forge
ipykernel                 4.5.2                    py35_0    conda-forge
ipython                   5.1.0                    py35_2    conda-forge
ipython_genutils          0.1.0                    py35_0    conda-forge
jinja2                    2.8                      py35_1    conda-forge
jpeg                      9b                            0    bioconda
jsonschema                2.5.1                    py35_0    conda-forge
jupyter_client            4.4.0                    py35_0    conda-forge
jupyter_core              4.2.1                    py35_0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgcc                    5.2.0                         0  
libiconv                  1.14                          4    conda-forge
libpng                    1.6.28                        0    conda-forge
libsodium                 1.0.10                        0    conda-forge
libtiff                   4.0.6                         7    conda-forge
libxml2                   2.9.3                         0    bioconda
markupsafe                0.23                     py35_1    conda-forge
mistune                   0.7.3                    py35_0    conda-forge
nbconvert                 5.1.1                    py35_0    conda-forge
nbformat                  4.2.0                    py35_0    conda-forge
ncurses                   5.9                          10    conda-forge
notebook                  4.3.1                    py35_0    conda-forge
openssl                   1.0.2h                        3    conda-forge
pandoc                    1.19.1                        0    conda-forge
pandocfilters             1.4.1                    py35_0    conda-forge
pango                     1.40.3                        2    conda-forge
pcre                      8.39                          0    conda-forge
pexpect                   4.2.1                    py35_0    conda-forge
pickleshare               0.7.3                    py35_0    conda-forge
pip                       9.0.1                    py35_0    conda-forge
pixman                    0.34.0                        0    conda-forge
prompt_toolkit            1.0.9                    py35_0    conda-forge
ptyprocess                0.5.1                    py35_0    conda-forge
pygments                  2.2.0                    py35_0    conda-forge
python                    3.5.3                         0    conda-forge
pyzmq                     16.0.2                   py35_0    conda-forge
r                         3.3.2                  r3.3.2_0    r
r-assertthat              0.1                    r3.3.2_4    r
r-backports               1.0.4                  r3.3.2_0    r
r-base                    3.3.2                         2    conda-forge
r-base64enc               0.1_3                  r3.3.2_0    r
r-bh                      1.62.0_1               r3.3.2_0    r
r-bitops                  1.0_6                  r3.3.2_2    r
r-boot                    1.3_18                 r3.3.2_0    r
r-broom                   0.4.1                  r3.3.2_0    r
r-car                     2.1_4                  r3.3.2_0    r
r-caret                   6.0_73                 r3.3.2_0    r
r-catools                 1.17.1                 r3.3.2_2    r
r-class                   7.3_14                 r3.3.2_0    r
r-cluster                 2.0.5                  r3.3.2_0    r
r-codetools               0.2_15                 r3.3.2_0    r
r-colorspace              1.3_1                  r3.3.2_0    r
r-crayon                  1.3.2                  r3.3.2_0    r
r-curl                    2.3                    r3.3.2_0    r
r-data.table              1.10.0                 r3.3.2_0    r
r-dbi                     0.5_1                  r3.3.2_0    r
r-dichromat               2.0_0                  r3.3.2_2    r
r-digest                  0.6.10                 r3.3.2_0    r
r-dplyr                   0.5.0                  r3.3.2_0    r
r-essentials              1.5.1                         0    r
r-evaluate                0.10                   r3.3.2_0    r
r-forcats                 0.1.1                  r3.3.2_0    r
r-foreach                 1.4.3                  r3.3.2_0    r
r-foreign                 0.8_67                 r3.3.2_0    r
r-formatr                 1.4                    r3.3.2_0    r
r-ggplot2                 2.2.0                  r3.3.2_0    r
r-gistr                   0.3.6                  r3.3.2_0    r
r-glmnet                  2.0_5                  r3.3.2_0    r
r-gtable                  0.2.0                  r3.3.2_0    r
r-haven                   1.0.0                  r3.3.2_0    r
r-hexbin                  1.27.1                 r3.3.2_0    r
r-highr                   0.6                    r3.3.2_0    r
r-hms                     0.3                    r3.3.2_0    r
r-htmltools               0.3.5                  r3.3.2_0    r
r-htmlwidgets             0.8                    r3.3.2_0    r
r-httpuv                  1.3.3                  r3.3.2_0    r
r-httr                    1.2.1                  r3.3.2_0    r
r-irdisplay               0.4.4                  r3.3.2_0    r
r-irkernel                0.7.1                  r3.3.2_0    r
r-iterators               1.0.8                  r3.3.2_0    r
r-jsonlite                1.1                    r3.3.2_0    r
r-kernsmooth              2.23_15                r3.3.2_0    r
r-knitr                   1.15.1                 r3.3.2_0    r
r-labeling                0.3                    r3.3.2_2    r
r-lattice                 0.20_34                r3.3.2_0    r
r-lazyeval                0.2.0                  r3.3.2_0    r
r-lme4                    1.1_12                 r3.3.2_0    r
r-lubridate               1.6.0                  r3.3.2_0    r
r-magrittr                1.5                    r3.3.2_2    r
r-maps                    3.1.1                  r3.3.2_0    r
r-markdown                0.7.7                  r3.3.2_2    r
r-mass                    7.3_45                 r3.3.2_0    r
r-matrix                  1.2_7.1                r3.3.2_0    r
r-matrixmodels            0.4_1                  r3.3.2_0    r
r-mgcv                    1.8_16                 r3.3.2_0    r
r-mime                    0.5                    r3.3.2_0    r
r-minqa                   1.2.4                  r3.3.2_2    r
r-mnormt                  1.5_5                  r3.3.2_0    r
r-modelmetrics            1.1.0                  r3.3.2_0    r
r-modelr                  0.1.0                  r3.3.2_0    r
r-munsell                 0.4.3                  r3.3.2_0    r
r-nlme                    3.1_128                r3.3.2_0    r
r-nloptr                  1.0.4                  r3.3.2_2    r
r-nnet                    7.3_12                 r3.3.2_0    r
r-openssl                 0.9.5                  r3.3.2_0    r
r-pbdzmq                  0.2_4                  r3.3.2_0    r
r-pbkrtest                0.4_6                  r3.3.2_0    r
r-plyr                    1.8.4                  r3.3.2_0    r
r-pryr                    0.1.2                  r3.3.2_0    r
r-psych                   1.6.9                  r3.3.2_0    r
r-purrr                   0.2.2                         0    bioconda
r-quantmod                0.4_7                  r3.3.2_0    r
r-quantreg                5.29                   r3.3.2_0    r
r-r6                      2.2.0                  r3.3.2_0    r
r-randomforest            4.6_12                 r3.3.2_0    r
r-rbokeh                  0.5.0                  r3.3.2_0    r
r-rcolorbrewer            1.1_2                  r3.3.2_3    r
r-rcpp                    0.12.8                 r3.3.2_0    r
r-rcppeigen               0.3.2.9.0              r3.3.2_0    r
r-readr                   1.0.0                  r3.3.2_0    r
r-readxl                  0.1.1                  r3.3.2_0    r
r-recommended             3.3.2                  r3.3.2_0    r
r-repr                    0.10                   r3.3.2_0    r
r-reshape2                1.4.2                  r3.3.2_0    r
r-rmarkdown               1.2                    r3.3.2_0    r
r-rpart                   4.1_10                 r3.3.2_0    r
r-rprojroot               1.1                    r3.3.2_0    r
r-rvest                   0.3.2                  r3.3.2_0    r
r-scales                  0.4.1                  r3.3.2_0    r
r-selectr                 0.3_0                  r3.3.2_0    r
r-shiny                   0.14.2                 r3.3.2_0    r
r-sourcetools             0.1.5                  r3.3.2_0    r
r-sparsem                 1.74                   r3.3.2_0    r
r-spatial                 7.3_11                 r3.3.2_0    r
r-stringi                 1.1.2                  r3.3.2_0    r
r-stringr                 1.1.0                  r3.3.2_0    r
r-survival                2.40_1                 r3.3.2_0    r
r-tibble                  1.2                    r3.3.2_0    r
r-tidyr                   0.6.0                  r3.3.2_0    r
r-tidyverse               1.0.0                  r3.3.2_0    r
r-ttr                     0.23_1                 r3.3.2_0    r
r-uuid                    0.1_2                  r3.3.2_0    r
r-xml2                    1.0.0                  r3.3.2_0    r
r-xtable                  1.8_2                  r3.3.2_0    r
r-xts                     0.9_7                  r3.3.2_2    r
r-yaml                    2.1.14                 r3.3.2_0    r
r-zoo                     1.7_13                 r3.3.2_0    r
readline                  6.2                           0    conda-forge
setuptools                33.1.0                   py35_0    conda-forge
simplegeneric             0.8.1                    py35_0    conda-forge
six                       1.10.0                   py35_1    conda-forge
sqlite                    3.13.0                        1    conda-forge
terminado                 0.6                      py35_0    conda-forge
testpath                  0.3                      py35_0    conda-forge
tk                        8.5.19                        1    conda-forge
tornado                   4.4.2                    py35_0    conda-forge
traitlets                 4.3.0                    py35_0    conda-forge
wcwidth                   0.1.7                    py35_0    conda-forge
wheel                     0.29.0                   py35_0    conda-forge
xz                        5.2.2                         0    conda-forge
zeromq                    4.1.5                         0    conda-forge
zlib                      1.2.8                         3    conda-forge
```

```
conda info --show-channel_urls
# packages in environment at /home/exacloud/lustre1/BioCoders/Applications/miniconda3/envs/r322:
#
bleach                    1.4.2                    py35_0    bioconda
bzip2                     1.0.6                         3    defaults
ca-certificates           2016.9.26                     0    conda-forge
cairo                     1.14.6                        3    conda-forge
certifi                   2016.9.26                py35_0    conda-forge
curl                      7.45.0                        2    bioconda
decorator                 4.0.11                   py35_0    conda-forge
entrypoints               0.2.2                    py35_1    conda-forge
fontconfig                2.12.1                        3    conda-forge
freetype                  2.7                           0    conda-forge
gettext                   0.19.8                        0    bioconda
glib                      2.51.0                        2    conda-forge
gmp                       6.1.2                         0    conda-forge
gsl                       2.2.1                         1    conda-forge
harfbuzz                  1.3.4                         1    conda-forge
html5lib                  0.999                    py35_0    defaults
icu                       56.1                          4    conda-forge
ipykernel                 4.5.2                    py35_0    conda-forge
ipython                   5.1.0                    py35_2    conda-forge
ipython_genutils          0.1.0                    py35_0    conda-forge
jinja2                    2.8                      py35_1    conda-forge
jpeg                      9b                            0    bioconda
jsonschema                2.5.1                    py35_0    conda-forge
jupyter_client            4.4.0                    py35_0    conda-forge
jupyter_core              4.2.1                    py35_0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgcc                    5.2.0                         0    defaults
libiconv                  1.14                          4    conda-forge
libpng                    1.6.28                        0    conda-forge
libsodium                 1.0.10                        0    conda-forge
libtiff                   4.0.6                         7    conda-forge
libxml2                   2.9.3                         0    bioconda
markupsafe                0.23                     py35_1    conda-forge
mistune                   0.7.3                    py35_0    conda-forge
nbconvert                 5.1.1                    py35_0    conda-forge
nbformat                  4.2.0                    py35_0    conda-forge
ncurses                   5.9                          10    conda-forge
notebook                  4.3.1                    py35_0    conda-forge
openssl                   1.0.2h                        3    conda-forge
pandoc                    1.19.1                        0    conda-forge
pandocfilters             1.4.1                    py35_0    conda-forge
pango                     1.40.3                        2    conda-forge
pcre                      8.39                          0    conda-forge
pexpect                   4.2.1                    py35_0    conda-forge
pickleshare               0.7.3                    py35_0    conda-forge
pip                       9.0.1                    py35_0    conda-forge
pixman                    0.34.0                        0    conda-forge
prompt_toolkit            1.0.9                    py35_0    conda-forge
ptyprocess                0.5.1                    py35_0    conda-forge
pygments                  2.2.0                    py35_0    conda-forge
python                    3.5.3                         0    conda-forge
pyzmq                     16.0.2                   py35_0    conda-forge
r                         3.3.2                  r3.3.2_0    r
r-assertthat              0.1                    r3.3.2_4    r
r-backports               1.0.4                  r3.3.2_0    r
r-base                    3.3.2                         2    conda-forge
r-base64enc               0.1_3                  r3.3.2_0    r
r-bh                      1.62.0_1               r3.3.2_0    r
r-bitops                  1.0_6                  r3.3.2_2    r
r-boot                    1.3_18                 r3.3.2_0    r
r-broom                   0.4.1                  r3.3.2_0    r
r-car                     2.1_4                  r3.3.2_0    r
r-caret                   6.0_73                 r3.3.2_0    r
r-catools                 1.17.1                 r3.3.2_2    r
r-class                   7.3_14                 r3.3.2_0    r
r-cluster                 2.0.5                  r3.3.2_0    r
r-codetools               0.2_15                 r3.3.2_0    r
r-colorspace              1.3_1                  r3.3.2_0    r
r-crayon                  1.3.2                  r3.3.2_0    r
r-curl                    2.3                    r3.3.2_0    r
r-data.table              1.10.0                 r3.3.2_0    r
r-dbi                     0.5_1                  r3.3.2_0    r
r-dichromat               2.0_0                  r3.3.2_2    r
r-digest                  0.6.10                 r3.3.2_0    r
r-dplyr                   0.5.0                  r3.3.2_0    r
r-essentials              1.5.1                         0    r
r-evaluate                0.10                   r3.3.2_0    r
r-forcats                 0.1.1                  r3.3.2_0    r
r-foreach                 1.4.3                  r3.3.2_0    r
r-foreign                 0.8_67                 r3.3.2_0    r
r-formatr                 1.4                    r3.3.2_0    r
r-ggplot2                 2.2.0                  r3.3.2_0    r
r-gistr                   0.3.6                  r3.3.2_0    r
r-glmnet                  2.0_5                  r3.3.2_0    r
r-gtable                  0.2.0                  r3.3.2_0    r
r-haven                   1.0.0                  r3.3.2_0    r
r-hexbin                  1.27.1                 r3.3.2_0    r
r-highr                   0.6                    r3.3.2_0    r
r-hms                     0.3                    r3.3.2_0    r
r-htmltools               0.3.5                  r3.3.2_0    r
r-htmlwidgets             0.8                    r3.3.2_0    r
r-httpuv                  1.3.3                  r3.3.2_0    r
r-httr                    1.2.1                  r3.3.2_0    r
r-irdisplay               0.4.4                  r3.3.2_0    r
r-irkernel                0.7.1                  r3.3.2_0    r
r-iterators               1.0.8                  r3.3.2_0    r
r-jsonlite                1.1                    r3.3.2_0    r
r-kernsmooth              2.23_15                r3.3.2_0    r
r-knitr                   1.15.1                 r3.3.2_0    r
r-labeling                0.3                    r3.3.2_2    r
r-lattice                 0.20_34                r3.3.2_0    r
r-lazyeval                0.2.0                  r3.3.2_0    r
r-lme4                    1.1_12                 r3.3.2_0    r
r-lubridate               1.6.0                  r3.3.2_0    r
r-magrittr                1.5                    r3.3.2_2    r
r-maps                    3.1.1                  r3.3.2_0    r
r-markdown                0.7.7                  r3.3.2_2    r
r-mass                    7.3_45                 r3.3.2_0    r
r-matrix                  1.2_7.1                r3.3.2_0    r
r-matrixmodels            0.4_1                  r3.3.2_0    r
r-mgcv                    1.8_16                 r3.3.2_0    r
r-mime                    0.5                    r3.3.2_0    r
r-minqa                   1.2.4                  r3.3.2_2    r
r-mnormt                  1.5_5                  r3.3.2_0    r
r-modelmetrics            1.1.0                  r3.3.2_0    r
r-modelr                  0.1.0                  r3.3.2_0    r
r-munsell                 0.4.3                  r3.3.2_0    r
r-nlme                    3.1_128                r3.3.2_0    r
r-nloptr                  1.0.4                  r3.3.2_2    r
r-nnet                    7.3_12                 r3.3.2_0    r
r-openssl                 0.9.5                  r3.3.2_0    r
r-pbdzmq                  0.2_4                  r3.3.2_0    r
r-pbkrtest                0.4_6                  r3.3.2_0    r
r-plyr                    1.8.4                  r3.3.2_0    r
r-pryr                    0.1.2                  r3.3.2_0    r
r-psych                   1.6.9                  r3.3.2_0    r
r-purrr                   0.2.2                         0    bioconda
r-quantmod                0.4_7                  r3.3.2_0    r
r-quantreg                5.29                   r3.3.2_0    r
r-r6                      2.2.0                  r3.3.2_0    r
r-randomforest            4.6_12                 r3.3.2_0    r
r-rbokeh                  0.5.0                  r3.3.2_0    r
r-rcolorbrewer            1.1_2                  r3.3.2_3    r
r-rcpp                    0.12.8                 r3.3.2_0    r
r-rcppeigen               0.3.2.9.0              r3.3.2_0    r
r-readr                   1.0.0                  r3.3.2_0    r
r-readxl                  0.1.1                  r3.3.2_0    r
r-recommended             3.3.2                  r3.3.2_0    r
r-repr                    0.10                   r3.3.2_0    r
r-reshape2                1.4.2                  r3.3.2_0    r
r-rmarkdown               1.2                    r3.3.2_0    r
r-rpart                   4.1_10                 r3.3.2_0    r
r-rprojroot               1.1                    r3.3.2_0    r
r-rvest                   0.3.2                  r3.3.2_0    r
r-scales                  0.4.1                  r3.3.2_0    r
r-selectr                 0.3_0                  r3.3.2_0    r
r-shiny                   0.14.2                 r3.3.2_0    r
r-sourcetools             0.1.5                  r3.3.2_0    r
r-sparsem                 1.74                   r3.3.2_0    r
r-spatial                 7.3_11                 r3.3.2_0    r
r-stringi                 1.1.2                  r3.3.2_0    r
r-stringr                 1.1.0                  r3.3.2_0    r
r-survival                2.40_1                 r3.3.2_0    r
r-tibble                  1.2                    r3.3.2_0    r
r-tidyr                   0.6.0                  r3.3.2_0    r
r-tidyverse               1.0.0                  r3.3.2_0    r
r-ttr                     0.23_1                 r3.3.2_0    r
r-uuid                    0.1_2                  r3.3.2_0    r
r-xml2                    1.0.0                  r3.3.2_0    r
r-xtable                  1.8_2                  r3.3.2_0    r
r-xts                     0.9_7                  r3.3.2_2    r
r-yaml                    2.1.14                 r3.3.2_0    r
r-zoo                     1.7_13                 r3.3.2_0    r
readline                  6.2                           0    conda-forge
setuptools                33.1.0                   py35_0    conda-forge
simplegeneric             0.8.1                    py35_0    conda-forge
six                       1.10.0                   py35_1    conda-forge
sqlite                    3.13.0                        1    conda-forge
terminado                 0.6                      py35_0    conda-forge
testpath                  0.3                      py35_0    conda-forge
tk                        8.5.19                        1    conda-forge
tornado                   4.4.2                    py35_0    conda-forge
traitlets                 4.3.0                    py35_0    conda-forge
wcwidth                   0.1.7                    py35_0    conda-forge
wheel                     0.29.0                   py35_0    conda-forge
xz                        5.2.2                         0    conda-forge
zeromq                    4.1.5                         0    conda-forge
zlib                      1.2.8                         3    conda-forge
```

**Comment by mingwandroid** [comment]
You cannot use `conda-forge` software together with `conda defaults` software. The endeavours are not Binary Compatible, unfortunately.

**Comment by abalter** [comment]
Ok. What would be the easiest way to replace my default packages with conda forge ones?

I removed the default channel from my `.condarc`. The default ones I see are:

```
https://repo.continuum.io/pkgs/free/linux-64/bzip2-1.0.6-3.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libgcc-5.2.0-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/html5lib-0.999-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/bzip2-1.0.6-3.tar.bz2
```

**Comment by mingwandroid** [comment]
You can't since China forge doesn't have an R infrastructure yet. This is being worked on.

**Comment by abalter** [comment]
This is what happens when I remove the default channel:

```
balter@exalab3:~$ conda install pandas
Fetching package metadata .........
Solving package specifications: .


PackageNotFoundError: Package not found: '' Dependency missing in current linux-64 channels:
  - pandas -> numpy 1.11* -> blas 1.1 openblas -> openblas -> libgfortran

You can search for packages on anaconda.org with

    anaconda search -t conda libgfortran


balter@exalab3:~$ conda install ibgfortran
Fetching package metadata .........
Solving package specifications: .


PackageNotFoundError: Package not found: '' Package missing in current linux-64 channels:
  - ibgfortran

You can search for packages on anaconda.org with

    anaconda search -t conda ibgfortran


balter@exalab3:~$ conda install latex
Fetching package metadata .........
Solving package specifications: .


PackageNotFoundError: Package not found: '' Package missing in current linux-64 channels:
  - latex

You can search for packages on anaconda.org with

    anaconda search -t conda latex


balter@exalab3:~$ conda install natsort
Fetching package metadata .........
Solving package specifications: .


PackageNotFoundError: Package not found: '' Package missing in current linux-64 channels:
  - natsort

You can search for packages on anaconda.org with

    anaconda search -t conda natsort


balter@exalab3:~$ conda install nodejs
Fetching package metadata .........
Solving package specifications: .


PackageNotFoundError: Package not found: '' Dependency missing in current linux-64 channels:
  - nodejs -> libgcc

Close matches found; did you mean one of these?

    libgcc: libgd, libmagic

You can search for packages on anaconda.org with

    anaconda search -t conda libgcc


balter@exalab3:~$ conda install numpy
Fetching package metadata .........
Solving package specifications: .


PackageNotFoundError: Package not found: '' Dependency missing in current linux-64 channels:
  - numpy -> blas 1.1 openblas -> openblas -> libgfortran

You can search for packages on anaconda.org with

    anaconda search -t conda libgfortran

```

**Comment by mingwandroid** [comment]
You're going to have to start from scratch here really.

**Comment by mingwandroid** [comment]
Fixed.

**Comment by bsolomon1124** [comment]
@mingwandroid can you clarify what fixed this issue? Still seeing with R 4.0.3 Ubuntu Eoan rocker/tidyverse Docker container.

**Comment by DawnEve** [comment]
Still face the same issue on my CentOS7.5 server:

$ R
R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"

> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua 
      FALSE       FALSE       FALSE        TRUE       FALSE       FALSE
