### ISSUE TITLE
dll loading issue with python 3.7.2 on Windows

### ISSUE THREAD

**Issue by pratik-r** [ContinuumIO/anaconda-issues#10651]
I recently updated to Python 3.7.2 on Windows, and I tried:

import torch
torch.cuda.is_available()

It returns False and gives me the following error:

python.exe - Entry Point Not Found
The procedure entry point fatBinaryCtl_createHandle could not be located in the dynamic link library C:\WINDOWS\system32\nvcuda.dll. 

I have all the drivers and dependencies installed, so I checked with pytorch. They say this is a dll loading issue associated with conda. Apparently, it has to with the following: "they (the Anaconda team) are using `AddDllDirectory` in their PRs so the sequence is not ensured." 

Can you please look into this?

Thanks.

**Comment by msarahan** [comment]
Try the latest from the conda-canary channel.  I think it's less about sequence and more about whether certain paths are present.  @mingwandroid and @katietz are the experts here, though.  If you try the python from the conda-canary channel, please be sure to tell them how it works for you.

**Comment by csoja** [comment]
I think the latest python to try is on https://anaconda.org/c3i_test  (https://anaconda.org/c3i_test/python) and not the conda-canary channel.

**Comment by pratik-r** [comment]
@csoja I just tried installing python from c3i_test. I'm still facing the same issue with this new version.

**Comment by icyblade** [comment]
Facing the same issue on Windows 10 (1809)/Driver 418.81/CUDA 10.1.
Tried 3.6.8 and 3.7.2, both default channel and c3i_test, with no luck.

**Comment by fourier79** [comment]
What is the status on this? I have the same problem with Windows 10/Cuda10.1/Driver418.91. Same results with 3.6.8 and 3.7.2. It is not only torch as described in the first message, tensorflow also cannot access gpu.
I can use my gpu for deep learning training with dlib (C++); so, the issue is not related to drivers or cuda.

**Comment by mingwandroid** [comment]
This should be fixed now. `conda update python`, sorry about the trouble.

**Comment by icyblade** [comment]
@mingwandroid Still getting this error.

Environment: Windows 10 64bit, CUDA v10.0, 1080ti.

```
(DeepLearning) D:\work\DeepLearningWorkspace>conda list
# packages in environment at C:\Anaconda3\envs\DeepLearning:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
certifi                   2016.2.28                py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
cffi                      1.10.0                   py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
cudatoolkit               10.0.130                      0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
freetype                  2.9.1                ha9979f8_1    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
icc_rt                    2019.0.0             h0cc432a_1    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
intel-openmp              2019.1                      144    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
jpeg                      9b                   hb83a4c4_2    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
libpng                    1.6.36               h2a8f88b_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
libtiff                   4.0.10               hb898794_2    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
mkl                       2019.1                      144    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
mkl_fft                   1.0.10           py36h14836fe_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
mkl_random                1.0.2            py36h343c172_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
ninja                     1.8.2            py36he980bc4_1    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
numpy                     1.15.4           py36h19fb1c0_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
numpy-base                1.15.4           py36hc3f5095_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
olefile                   0.44                     py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
pandas                    0.24.1           py36ha925a31_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
pillow                    5.4.1            py36hdc69c19_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
pip                       9.0.1                    py36_1    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
pycparser                 2.18                     py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
python                    3.6.8                h9f7ef89_1    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
python-dateutil           2.6.1                    py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
pytorch                   1.0.1           py3.6_cuda100_cudnn7_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
pytz                      2017.2                   py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
scipy                     1.2.0            py36h29ff71c_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
setuptools                36.4.0                   py36_1    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
six                       1.10.0                   py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
sqlite                    3.26.0               he774522_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
tk                        8.6.8                hfa6e2cd_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
torchvision               0.2.1                      py_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch

vc                        14.1                 h0510ff6_4    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
vs2015_runtime            14.15.26706          h3a45250_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
wheel                     0.29.0                   py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
wincertstore              0.2                      py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
xz                        5.2.4                h2fa13f4_4    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
zlib                      1.2.11               h62dcd97_3    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
zstd                      1.3.7                h508b16e_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main

(DeepLearning) D:\work\DeepLearningWorkspace>conda update python
Solving environment: done

# All requested packages already installed.


(DeepLearning) D:\work\DeepLearningWorkspace>
```

**Comment by mingwandroid** [comment]
> python                    3.6.8                h9f7ef89_1    https://mirrors.ustc.edu.cn/anaconda/pkgs/main

This is not the python package in which we fixed this. You are using an unofficial mirror of our repositories here, we are not in control of those.

**Comment by icyblade** [comment]
@mingwandroid It seems the fixed version has not been synced to this mirror. Thanks for your explanation.
