### ISSUE TITLE
error download_api._download:234 in anaconda-navigator

### ISSUE THREAD

**Issue by Memoradd** [ContinuumIO/anaconda-issues#10711]
### Actual Behavior

After running Anaconda-navigator on win 10 command gives: 
ERROR download_api._download:234 Invalid url https://www.anaconda.com/api/events

ERROR download_api._download:234 Invalid url https://www.anaconda.com/api/videos

ERROR download_api._download:234 Invalid url https://www.anaconda.com/api/webinars

any one has any idea how to solve it ?

**Comment by goanpeca** [comment]
@Memoradd we are working on this. The issue should not affect Navigator operation but the content from the community and learning tabs will be reduced.

**Comment by Memoradd** [comment]
@goanpeca thanks for your reply. I have also the issue that after starting anaconda-navigator and jupyter notebook and running the kernel --> It isn't possible to import brightway. 

--> import brightway as bw --> just calculating the kernel with no output

Do you have an idea about that?

**Comment by goanpeca** [comment]
> I have also the issue that after starting anaconda-navigator and jupyter notebook and running the kernel --> It isn't possible to import brightway.

That seems unrelated to this issue

**Comment by akhoso** [comment]
im having this same issue on ubuntu linux

**Comment by nikheal25** [comment]
I'm also getting the same error after opening the jupyter. It shows the connection is blocked in the browser.

**Comment by jpheffne** [comment]
Any updates on this? Like @goanpeca said it's not causing any problems but it's a little annoying since it means I can't open the Navigator as an app (have to use Anaconda prompt line).

**Comment by nikheal25** [comment]
My issue is resolved. It was caused because of VPN add-on my browser. After disabling the VPN it's working fine.

**Comment by RoentgenL** [comment]
Same Issue here. Navigator only opens via console with all the ERROR download_api._download:234
New and clean installation on Windows 10, before and after executing:
_conda update -n root conda
conda update --all_

"2019-04-01 16:31:41,606 - ERROR download_api._download:234
Invalid url https://www.anaconda.com/wp-content/uploads/2016/04/webinar_datashader_0.png" --> This page doesn't seem to exist.

**Comment by HarlanThomas** [comment]
I have met the same error report . 
The worse thing is that I cannot launch any tool in anaconda navigator .Even though I  can launch Jupyter and spyer, but they both can not connect to the kernel. 
And  vscode failed to launch in any way.  what's  wrong with my conda?

**Comment by GuerridaWidad** [comment]
the solution that i found is to put << Applications on "my_env">> instead of "base (root)". It works for me !

**Comment by zoongit** [comment]
with this error, I am not able to update the anaconda navigator when an alert message comes up. Any idea how to update anaconda-navigator?

**Comment by zoongit** [comment]
Hello,
I tried to update anaconda-navigator, but I keep having these errors

2019-04-25 09:08:54,960 - ERROR download_api._download:234
Invalid url https://www.anaconda.com/api/events

2019-04-25 09:08:55,497 - ERROR download_api._download:234
Invalid url https://www.anaconda.com/api/videos

2019-04-25 09:08:55,679 - ERROR download_api._download:234
Invalid url https://www.anaconda.com/api/webinars

2019-04-25 09:09:23,416 - ERROR download_api._download:234
Invalid url https://www.anaconda.com/api/events

2019-04-25 09:09:23,701 - ERROR download_api._download:234
Invalid url https://www.anaconda.com/api/videos

2019-04-25 09:09:24,159 - ERROR download_api._download:234
Invalid url https://www.anaconda.com/api/webinars

Would someone help me with this?

Thanks

**Comment by csoja** [comment]
@zoongit  Those errors just mean you won't see some of the content you used to see on the Community and Learning tabs of Navigator.  The error is not on the Navigator side, it is on the www.anaconda.com side - and we are aware and working to fix it.  Is your Navigator otherwise working ok?

**Comment by cd632** [comment]
@csoja   I am having the same problem,but my Anaconda Navigator is not opening

**Comment by zoongit** [comment]
My Navigator is working fine, but it is not updated. I solved this problem by doing the upgrade in the command prompt using conda command. Now, my Navigator is up to date and works well. Thanks for looking into it.

**Comment by fcashman** [comment]
I have the same issue regarding the "ERROR download_api._download:234 ... invalid URL" discussion. It began after I updated anaconda-navigator. 

I understand that the errors should only affect the Community and Learning tabs, however, I am also unable to launch Jupyter notebook. It worked perfectly fine yesterday as version 5.2.2, then I updated it to 5.7.8 via the update application link in the UI tile settings. 
The application launch error is:
Traceback (most recent call last):
File "/home/fcashman/anaconda3/bin/jupyter-notebook", line 7, in 
from notebook.notebookapp import main
File "/home/fcashman/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 42, in 
from zmq.eventloop import ioloop
File "/home/fcashman/anaconda3/lib/python3.6/site-packages/zmq/__init__.py", line 47, in 
from zmq import backend
File "/home/fcashman/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in 
reraise(*exc_info)
File "/home/fcashman/anaconda3/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
raise value
File "/home/fcashman/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in 
_ns = select_backend(first)
File "/home/fcashman/anaconda3/lib/python3.6/site-packages/zmq/backend/select.py", line 26, in select_backend
mod = __import__(name, fromlist=public_api)
File "/home/fcashman/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: libsodium.so.23: cannot open shared object file: No such file or directory

I reverted back to version 5.2.2, but it still will not work. It produced a list of packages that were causing inconsistencies. I updated each package, but the application launch error persist. It will not launch in the terminal or in the application. I am running Linux Fedora 22.

**Comment by davidanger** [comment]
I have the same problem. With windows client.

**Comment by grosssven** [comment]
I have same problem.
I am behind a proxy/ firewall. 
I have setup a .condarc with proxy servers.

Conda works and updating with anaconda navigator works fine, too.

But if I click "Update index" or "Chanels" it doesn`t come back. 

In log I found
`[
    {
        "level": "ERROR", 
        "line": 234, 
        "message": "Invalid url https://www.anaconda.com/wp-content/uploads/2017/05/Webinar20-20Three20Ways20to20Move20your20Data20Science20Projects20to20Production.png", 
        "method": "_download", 
        "module": "download_api", 
        "path": "C:/ProgramData/Anaconda2/lib/site-packages/anaconda_navigator/api/download_api.py", 
        "time": "2019-06-26 10:45:49,073"
    }
]`

Browser tells me "This page doesn't seem to exist."

`     active environment : base
    active env location : C:\ProgramData\Anaconda2
            shell level : 1
       user config file : C:\Users\XXX\.condarc
 populated config files : C:\Users\XXX\.condarc
          conda version : 4.6.14
    conda-build version : 3.17.8
         python version : 2.7.16.final.0
       base environment : C:\ProgramData\Anaconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda2\pkgs
                          C:\Users\XXX\.conda\pkgs
                          C:\Users\XXX\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda2\envs
                          C:\Users\XXX\.conda\envs
                          C:\Users\XXX\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/2.7.16 Windows/10 Windows/10.0.14393
          administrator : True
             netrc file : None
           offline mode : False`

**Comment by MarcosCarreira** [comment]
I have the same problem as @grosssven ; unable to update as detailed here:
https://github.com/ContinuumIO/anaconda-issues/issues/11049
Looking at the log I see:
```json
[
    {
        "level": "ERROR",
        "line": 234,
        "message": "Invalid url https://www.anaconda.com/wp-content/uploads/2017/05/Webinar20-20Three20Ways20to20Move20your20Data20Science20Projects20to20Production.png",
        "method":   "_download",
        "module": "download_api",
        "path":   "/Applications/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/download_api.py",
       "time": "2019-07-02 21:53:59,565"
    }
]
```

**Comment by MarcosCarreira** [comment]
@msarahan is anyone looking into this problem?

**Comment by sliawatimena** [comment]
This is the code inside ~/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/download_api.py  line 233-235. 

```
    if status_code != 200:
        logger.error('Invalid url {0}'.format(url))
        return path
```

It does not have specific image in that page. I think better ignore this error.
My error says:
```
2019-08-07 08:58:56,364 - ERROR download_api._download:234
Invalid url https://www.anaconda.com/wp-content/uploads/2017/05/Webinar20-20Three20Ways20to20Move20your20Data20Science20Projects20to20Production.png

```

**Comment by mgavish** [comment]
same problem on every package I attempt to update; url paths vary slightly

````json
[
    {
        "level": "ERROR",
        "line": 234,
        "message": "Invalid url https://www.anaconda.com/api/events",
        "method": "_download",
        "module": "download_api",
        "path": "C:/Users/john/Anaconda3/lib/site-packages/anaconda_navigator/api/download_api.py",
        "time": "2019-02-09 18:35:35,385"
    }
]
```

`

**Comment by faizanurrahman** [comment]
> I have met the same error report.
> The worse thing is that I cannot launch any tool in anaconda navigator .Even though I can launch Jupyter and spyer, but they both can not connect to the kernel.
> And vscode failed to launch in any way. what's wrong with my conda?

I faced the same issue that the spyder kernel is not connected. But after running anaconda prompt with administrative mode issue of kernel connection is solved.

**Comment by shwetarks-2020** [comment]
I have installed anaconda recently with all new updates but still facing same issue.  Anaconda Navigator launches from Terminal and not from Launcher in MACOS. Has there any updates to this issue ?

YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe.

ERROR download_api._download:234
Invalid url https://www.anaconda.com/wp-content/uploads/Screen-Shot-2018-07-16-at-10.21.36-AM.png

I am still getting these errors

**Comment by csoja** [comment]
Can you update to the latest version of Navigator and see if you are still having these issues?  Navigator v1.9.12.  Thank you!

**Comment by yly1526** [comment]
> Can you update to the latest version of Navigator and see if you are still having these issues? Navigator v1.9.12. Thank you!

I have no issue with the latest v1.9.12 version. Works perfectly for me, Thank you !

**Comment by oluwaseun-Adesina** [comment]
> the solution that i found is to put << Applications on "my_env">> instead of "base (root)". It works for me !

pls how

**Comment by raoulsigne** [comment]
Please do let us know how to solve this issue

**Comment by Koustav546** [comment]
while opening anaconda I face this error and was not able to resolve it.

XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
2021-07-21 13:41:26,873 - ERROR ads._log_errors:23
Tried to load advertisement data from https://www.anaconda.com/api/navigator. URL is not reachable

<urlopen error [Errno -3] Temporary failure in name resolution>
<urlopen error [Errno -3] Temporary failure in name resolution>
<urlopen error [Errno -3] Temporary failure in name resolution>
<urlopen error [Errno -3] Temporary failure in name resolution>
<urlopen error [Errno -3] Temporary failure in name resolution>
<urlopen error [Errno -3] Temporary failure in name resolution>
2021-07-21 13:41:40,239 - ERROR client_api._get_api_info:640
HTTPSConnectionPool(host='api.anaconda.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fea432a1940>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
2021-07-21 13:41:50,014 - ERROR download_api._download:216
HTTPSConnectionPool(host='www.anaconda.com', port=443): Max retries exceeded with url: /api/events (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fea431ee1f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
