### ISSUE TITLE
Anaconda3 does not install successfully on Ubuntu 18.04 LTS latest version

### ISSUE THREAD

**Issue by mjanson** [ContinuumIO/anaconda-issues#11371]
### Actual Behavior

Fresh install of Anaconda3 on Linux x86_64 cannot be updated or facilitate install of packages.

### Expected Behavior

conda update --all and conda update anaconda should run successfully without error

### Steps to Reproduce

Post install from this link, I receive the following errors:

https://repo.anaconda.com/archive/Anaconda3-2019.07-Linux-x86_64.sh

(base) $ conda update --all
Collecting package metadata (current_repodata.json): done
Solving environment: failed with current_repodata.json, will retry with next repodata source.

UnsatisfiableError: 

(base) $  conda update anaconda

...

    The following specifications were found to be incompatible with each other:
    
   
    
    Package certifi conflicts for:
    python=3.7 -> pip -> wheel -> setuptools -> certifi[version='>=2016.09']
    anaconda -> python[version='>=3.6,<3.7.0a0'] -> pip -> wheel -> setuptools -> certifi[version='>=2016.09']
    Package pip conflicts for:
    anaconda -> python[version='>=3.6,<3.7.0a0'] -> pip
    python=3.7 -> pip
    Package setuptools conflicts for:
    anaconda -> python[version='>=3.6,<3.7.0a0'] -> pip -> wheel -> setuptools
    python=3.7 -> pip -> wheel -> setuptools
    Package wheel conflicts for:
    anaconda -> python[version='>=3.6,<3.7.0a0'] -> pip -> wheel
    python=3.7 -> pip -> wheel

....

$ python --version
Python 3.7.3
$ conda --version
conda 4.7.10
$ uname -a
Linux XXX-linux 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

##### `conda info`

<details>

```
$ conda info

     active environment : base
    active env location : /home/maj/anaconda3
            shell level : 1
       user config file : /home/maj/.condarc
 populated config files : /home/maj/.condarc
          conda version : 4.7.10
    conda-build version : 3.18.8
         python version : 3.7.3.final.0
       virtual packages : __cuda=9.1
       base environment : /home/maj/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/maj/anaconda3/pkgs
                          /home/maj/.conda/pkgs
       envs directories : /home/maj/anaconda3/envs
                          /home/maj/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.10 requests/2.22.0 CPython/3.7.3 Linux/4.15.0-65-generic ubuntu/18.04.3 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```

</details>

##### `conda list --show-channel-urls`

<details>

```
$ conda list --show-channel-urls
# packages in environment at /home/maj/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0    defaults
_libgcc_mutex             0.1                        main    defaults
alabaster                 0.7.12                   py37_0    defaults
anaconda                  2019.07                  py37_0    defaults
anaconda-client           1.7.2                    py37_0    defaults
anaconda-navigator        1.9.7                    py37_0    defaults
anaconda-project          0.8.3                      py_0    defaults
asn1crypto                0.24.0                   py37_0    defaults
astroid                   2.2.5                    py37_0    defaults
astropy                   3.2.1            py37h7b6447c_0    defaults
atomicwrites              1.3.0                    py37_1    defaults
attrs                     19.1.0                   py37_1    defaults
babel                     2.7.0                      py_0    defaults
backcall                  0.1.0                    py37_0    defaults
backports                 1.0                        py_2    defaults
backports.functools_lru_cache 1.5                        py_2    defaults
backports.os              0.1.1                    py37_0    defaults
backports.shutil_get_terminal_size 1.0.0                    py37_2    defaults
backports.tempfile        1.0                        py_1    defaults
backports.weakref         1.0.post1                  py_1    defaults
beautifulsoup4            4.7.1                    py37_1    defaults
bitarray                  0.9.3            py37h7b6447c_0    defaults
bkcharts                  0.2                      py37_0    defaults
blas                      1.0                         mkl    defaults
bleach                    3.1.0                    py37_0    defaults
blosc                     1.16.3               hd408876_0    defaults
bokeh                     1.2.0                    py37_0    defaults
boto                      2.49.0                   py37_0    defaults
bottleneck                1.2.1            py37h035aef0_1    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
ca-certificates           2019.5.15                     0    defaults
cairo                     1.14.12              h8948797_3    defaults
certifi                   2019.6.16                py37_0    defaults
cffi                      1.12.3           py37h2e261b9_0    defaults
chardet                   3.0.4                    py37_1    defaults
click                     7.0                      py37_0    defaults
cloudpickle               1.2.1                      py_0    defaults
clyent                    1.2.2                    py37_1    defaults
colorama                  0.4.1                    py37_0    defaults
conda                     4.7.10                   py37_0    defaults
conda-build               3.18.8                   py37_0    defaults
conda-env                 2.6.0                         1    defaults
conda-package-handling    1.3.11                   py37_0    defaults
conda-verify              3.4.2                      py_1    defaults
contextlib2               0.5.5                    py37_0    defaults
cryptography              2.7              py37h1ba5d50_0    defaults
curl                      7.65.2               hbc83047_0    defaults
cycler                    0.10.0                   py37_0    defaults
cython                    0.29.12          py37he6710b0_0    defaults
cytoolz                   0.10.0           py37h7b6447c_0    defaults
dask                      2.1.0                      py_0    defaults
dask-core                 2.1.0                      py_0    defaults
dbus                      1.13.6               h746ee38_0    defaults
decorator                 4.4.0                    py37_1    defaults
defusedxml                0.6.0                      py_0    defaults
distributed               2.1.0                      py_0    defaults
docutils                  0.14                     py37_0    defaults
entrypoints               0.3                      py37_0    defaults
et_xmlfile                1.0.1                    py37_0    defaults
expat                     2.2.6                he6710b0_0    defaults
fastcache                 1.1.0            py37h7b6447c_0    defaults
filelock                  3.0.12                     py_0    defaults
flask                     1.1.1                      py_0    defaults
fontconfig                2.13.0               h9420a91_0    defaults
freetype                  2.9.1                h8a8886c_1    defaults
fribidi                   1.0.5                h7b6447c_0    defaults
future                    0.17.1                   py37_0    defaults
get_terminal_size         1.0.0                haa9412d_0    defaults
gevent                    1.4.0            py37h7b6447c_0    defaults
glib                      2.56.2               hd408876_0    defaults
glob2                     0.7                        py_0    defaults
gmp                       6.1.2                h6c8ec71_1    defaults
gmpy2                     2.0.8            py37h10f8cd9_2    defaults
graphite2                 1.3.13               h23475e2_0    defaults
greenlet                  0.4.15           py37h7b6447c_0    defaults
gst-plugins-base          1.14.0               hbbd80ab_1    defaults
gstreamer                 1.14.0               hb453b48_1    defaults
h5py                      2.9.0            py37h7918eee_0    defaults
harfbuzz                  1.8.8                hffaf4a1_0    defaults
hdf5                      1.10.4               hb1b8bf9_0    defaults
heapdict                  1.0.0                    py37_2    defaults
html5lib                  1.0.1                    py37_0    defaults
icu                       58.2                 h9c2bf20_1    defaults
idna                      2.8                      py37_0    defaults
imageio                   2.5.0                    py37_0    defaults
imagesize                 1.1.0                    py37_0    defaults
importlib_metadata        0.17                     py37_1    defaults
intel-openmp              2019.4                      243    defaults
ipykernel                 5.1.1            py37h39e3cac_0    defaults
ipython                   7.6.1            py37h39e3cac_0    defaults
ipython_genutils          0.2.0                    py37_0    defaults
ipywidgets                7.5.0                      py_0    defaults
isort                     4.3.21                   py37_0    defaults
itsdangerous              1.1.0                    py37_0    defaults
jbig                      2.1                  hdba287a_0    defaults
jdcal                     1.4.1                      py_0    defaults
jedi                      0.13.3                   py37_0    defaults
jeepney                   0.4                      py37_0    defaults
jinja2                    2.10.1                   py37_0    defaults
joblib                    0.13.2                   py37_0    defaults
jpeg                      9b                   h024ee3a_2    defaults
json5                     0.8.4                      py_0    defaults
jsonschema                3.0.1                    py37_0    defaults
jupyter                   1.0.0                    py37_7    defaults
jupyter_client            5.3.1                      py_0    defaults
jupyter_console           6.0.0                    py37_0    defaults
jupyter_core              4.5.0                      py_0    defaults
jupyterlab                1.0.2            py37hf63ae98_0    defaults
jupyterlab_server         1.0.0                      py_0    defaults
keyring                   18.0.0                   py37_0    defaults
kiwisolver                1.1.0            py37he6710b0_0    defaults
krb5                      1.16.1               h173b8e3_7    defaults
lazy-object-proxy         1.4.1            py37h7b6447c_0    defaults
libarchive                3.3.3                h5d8350f_5    defaults
libcurl                   7.65.2               h20c2e04_0    defaults
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
liblief                   0.9.0                h7725739_2    defaults
libpng                    1.6.37               hbc83047_0    defaults
libsodium                 1.0.16               h1bed415_0    defaults
libssh2                   1.8.2                h1ba5d50_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libtiff                   4.0.10               h2733197_2    defaults
libtool                   2.4.6                h7b6447c_5    defaults
libuuid                   1.0.3                h1bed415_2    defaults
libxcb                    1.13                 h1bed415_1    defaults
libxml2                   2.9.9                hea5a465_1    defaults
libxslt                   1.1.33               h7d1a2b0_0    defaults
llvmlite                  0.29.0           py37hd408876_0    defaults
locket                    0.2.0                    py37_1    defaults
lxml                      4.3.4            py37hefd8a0e_0    defaults
lz4-c                     1.8.1.2              h14c3975_0    defaults
lzo                       2.10                 h49e0be7_2    defaults
markupsafe                1.1.1            py37h7b6447c_0    defaults
matplotlib                3.1.0            py37h5429711_0    defaults
mccabe                    0.6.1                    py37_1    defaults
mistune                   0.8.4            py37h7b6447c_0    defaults
mkl                       2019.4                      243    defaults
mkl-service               2.0.2            py37h7b6447c_0    defaults
mkl_fft                   1.0.12           py37ha843d7b_0    defaults
mkl_random                1.0.2            py37hd81dba3_0    defaults
mock                      3.0.5                    py37_0    defaults
more-itertools            7.0.0                    py37_0    defaults
mpc                       1.1.0                h10f8cd9_1    defaults
mpfr                      4.0.1                hdf1c602_3    defaults
mpmath                    1.1.0                    py37_0    defaults
msgpack-python            0.6.1            py37hfd86e86_1    defaults
multipledispatch          0.6.0                    py37_0    defaults
navigator-updater         0.2.1                    py37_0    defaults
nbconvert                 5.5.0                      py_0    defaults
nbformat                  4.4.0                    py37_0    defaults
ncurses                   6.1                  he6710b0_1    defaults
networkx                  2.3                        py_0    defaults
nltk                      3.4.4                    py37_0    defaults
nose                      1.3.7                    py37_2    defaults
notebook                  6.0.0                    py37_0    defaults
numba                     0.44.1           py37h962f231_0    defaults
numexpr                   2.6.9            py37h9e4a6bb_0    defaults
numpy                     1.16.4           py37h7e9f1db_0    defaults
numpy-base                1.16.4           py37hde5b4d6_0    defaults
numpydoc                  0.9.1                      py_0    defaults
olefile                   0.46                     py37_0    defaults
openpyxl                  2.6.2                      py_0    defaults
openssl                   1.1.1c               h7b6447c_1    defaults
packaging                 19.0                     py37_0    defaults
pandas                    0.24.2           py37he6710b0_0    defaults
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py37_1    defaults
pango                     1.42.4               h049681c_0    defaults
parso                     0.5.0                      py_0    defaults
partd                     1.0.0                      py_0    defaults
patchelf                  0.9                  he6710b0_3    defaults
path.py                   12.0.1                     py_0    defaults
pathlib2                  2.3.4                    py37_0    defaults
patsy                     0.5.1                    py37_0    defaults
pcre                      8.43                 he6710b0_0    defaults
pep8                      1.7.1                    py37_0    defaults
pexpect                   4.7.0                    py37_0    defaults
pickleshare               0.7.5                    py37_0    defaults
pillow                    6.1.0            py37h34e0f95_0    defaults
pip                       19.1.1                   py37_0    defaults
pixman                    0.38.0               h7b6447c_0    defaults
pkginfo                   1.5.0.1                  py37_0    defaults
pluggy                    0.12.0                     py_0    defaults
ply                       3.11                     py37_0    defaults
prometheus_client         0.7.1                      py_0    defaults
prompt_toolkit            2.0.9                    py37_0    defaults
psutil                    5.6.3            py37h7b6447c_0    defaults
ptyprocess                0.6.0                    py37_0    defaults
py                        1.8.0                    py37_0    defaults
py-lief                   0.9.0            py37h7725739_2    defaults
pycodestyle               2.5.0                    py37_0    defaults
pycosat                   0.6.3            py37h14c3975_0    defaults
pycparser                 2.19                     py37_0    defaults
pycrypto                  2.6.1            py37h14c3975_9    defaults
pycurl                    7.43.0.3         py37h1ba5d50_0    defaults
pyflakes                  2.1.1                    py37_0    defaults
pygments                  2.4.2                      py_0    defaults
pylint                    2.3.1                    py37_0    defaults
pyodbc                    4.0.26           py37he6710b0_0    defaults
pyopenssl                 19.0.0                   py37_0    defaults
pyparsing                 2.4.0                      py_0    defaults
pyqt                      5.9.2            py37h05f1152_2    defaults
pyrsistent                0.14.11          py37h7b6447c_0    defaults
pysocks                   1.7.0                    py37_0    defaults
pytables                  3.5.2            py37h71ec239_1    defaults
pytest                    5.0.1                    py37_0    defaults
pytest-arraydiff          0.3              py37h39e3cac_0    defaults
pytest-astropy            0.5.0                    py37_0    defaults
pytest-doctestplus        0.3.0                    py37_0    defaults
pytest-openfiles          0.3.2                    py37_0    defaults
pytest-remotedata         0.3.1                    py37_0    defaults
python                    3.7.3                h0371630_0    defaults
python-dateutil           2.8.0                    py37_0    defaults
python-libarchive-c       2.8                     py37_11    defaults
pytz                      2019.1                     py_0    defaults
pywavelets                1.0.3            py37hdd07704_1    defaults
pyyaml                    5.1.1            py37h7b6447c_0    defaults
pyzmq                     18.0.0           py37he6710b0_0    defaults
qt                        5.9.7                h5867ecd_1    defaults
qtawesome                 0.5.7                    py37_1    defaults
qtconsole                 4.5.1                      py_0    defaults
qtpy                      1.8.0                      py_0    defaults
readline                  7.0                  h7b6447c_5    defaults
requests                  2.22.0                   py37_0    defaults
rope                      0.14.0                     py_0    defaults
ruamel_yaml               0.15.46          py37h14c3975_0    defaults
scikit-image              0.15.0           py37he6710b0_0    defaults
scikit-learn              0.21.2           py37hd81dba3_0    defaults
scipy                     1.3.0            py37h7c811a0_0    defaults
seaborn                   0.9.0                    py37_0    defaults
secretstorage             3.1.1                    py37_0    defaults
send2trash                1.5.0                    py37_0    defaults
setuptools                41.0.1                   py37_0    defaults
simplegeneric             0.8.1                    py37_2    defaults
singledispatch            3.4.0.3                  py37_0    defaults
sip                       4.19.8           py37hf484d3e_0    defaults
six                       1.12.0                   py37_0    defaults
snappy                    1.1.7                hbae5bb6_3    defaults
snowballstemmer           1.9.0                      py_0    defaults
sortedcollections         1.1.2                    py37_0    defaults
sortedcontainers          2.1.0                    py37_0    defaults
soupsieve                 1.8                      py37_0    defaults
sphinx                    2.1.2                      py_0    defaults
sphinxcontrib             1.0                      py37_1    defaults
sphinxcontrib-applehelp   1.0.1                      py_0    defaults
sphinxcontrib-devhelp     1.0.1                      py_0    defaults
sphinxcontrib-htmlhelp    1.0.2                      py_0    defaults
sphinxcontrib-jsmath      1.0.1                      py_0    defaults
sphinxcontrib-qthelp      1.0.2                      py_0    defaults
sphinxcontrib-serializinghtml 1.1.3                      py_0    defaults
sphinxcontrib-websupport  1.1.2                      py_0    defaults
spyder                    3.3.6                    py37_0    defaults
spyder-kernels            0.5.1                    py37_0    defaults
sqlalchemy                1.3.5            py37h7b6447c_0    defaults
sqlite                    3.29.0               h7b6447c_0    defaults
statsmodels               0.10.0           py37hdd07704_0    defaults
sympy                     1.4                      py37_0    defaults
tblib                     1.4.0                      py_0    defaults
terminado                 0.8.2                    py37_0    defaults
testpath                  0.4.2                    py37_0    defaults
tk                        8.6.8                hbc83047_0    defaults
toolz                     0.10.0                     py_0    defaults
tornado                   6.0.3            py37h7b6447c_0    defaults
tqdm                      4.32.1                     py_0    defaults
traitlets                 4.3.2                    py37_0    defaults
unicodecsv                0.14.1                   py37_0    defaults
unixodbc                  2.3.7                h14c3975_0    defaults
urllib3                   1.24.2                   py37_0    defaults
wcwidth                   0.1.7                    py37_0    defaults
webencodings              0.5.1                    py37_1    defaults
werkzeug                  0.15.4                     py_0    defaults
wheel                     0.33.4                   py37_0    defaults
widgetsnbextension        3.5.0                    py37_0    defaults
wrapt                     1.11.2           py37h7b6447c_0    defaults
wurlitzer                 1.0.2                    py37_0    defaults
xlrd                      1.2.0                    py37_0    defaults
xlsxwriter                1.1.8                      py_0    defaults
xlwt                      1.3.0                    py37_0    defaults
xz                        5.2.4                h14c3975_4    defaults
yaml                      0.1.7                had09818_2    defaults
zeromq                    4.3.1                he6710b0_3    defaults
zict                      1.0.0                      py_0    defaults
zipp                      0.5.1                      py_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.3.7                h0b5b093_0    defaults

```

</details>

**Comment by mjanson** [comment]
I see that there is now a new installer at

**Comment by mjanson** [comment]
I see that there is now a new installer at

https://repo.anaconda.com/archive/Anaconda2-2019.10-Linux-x86_64.sh

However, that also causes update errors with a fully updated Ubuntu 18.04 LTS:

$ conda update --all
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                              

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - conda-env -> python[version='2.7.*|3.4.*|3.5.*']

Your python: python=3.7

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with each other:



Package pytest-doctestplus conflicts for:
anaconda==2019.10=py37_0 -> pytest-doctestplus==0.4.0=py_0
Package fontconfig conflicts for:
anaconda==2019.10=py37_0 -> fontconfig==2.13.0=h9420a91_0
Package spyder-kernels conflicts for:
anaconda==2019.10=py37_0 -> spyder-kernels==0.5.2=py37_0
Package pylint conflicts for:
anaconda==2019.10=py37_0 -> pylint==2.4.2=py37_0
Package dask-core conflicts for:
anaconda==2019.10=py37_0 -> dask-core==2.5.2=py_0
Package h5py conflicts for:
anaconda==2019.10=py37_0 -> h5py==2.9.0=py37h7918eee_0
Package harfbuzz conflicts for:
anaconda==2019.10=py37_0 -> harfbuzz==1.8.8=hffaf4a1_0
Package libstdcxx-ng conflicts for:
python=3.7 -> libstdcxx-ng[version='>=4.9|>=7.2.0|>=7.3.0']
anaconda==2019.10=py37_0 -> libstdcxx-ng==9.1.0=hdf63c60_0
Package lz4-c conflicts for:
anaconda==2019.10=py37_0 -> lz4-c==1.8.1.2=h14c3975_0
Package pycosat conflicts for:
anaconda==2019.10=py37_0 -> pycosat==0.6.3=py37h14c3975_0
conda[version='>=4.7.12'] -> pycosat[version='>=0.6.3']
Package scandir conflicts for:
conda-build -> scandir
Package sphinx conflicts for:
anaconda==2019.10=py37_0 -> sphinx==2.2.0=py_0
Package jinja2 conflicts for:
conda-build -> jinja2
conda-verify -> jinja2
anaconda==2019.10=py37_0 -> jinja2==2.10.3=py_0
Package ncurses conflicts for:
python=3.7 -> ncurses[version='>=6.1,<6.2.0a0|>=6.1,<7.0a0']
anaconda==2019.10=py37_0 -> ncurses==6.1=he6710b0_1
Package pytest-arraydiff conflicts for:
anaconda==2019.10=py37_0 -> pytest-arraydiff==0.3=py37h39e3cac_0
Package beautifulsoup4 conflicts for:
anaconda==2019.10=py37_0 -> beautifulsoup4==4.8.0=py37_0
conda-build -> beautifulsoup4
Package click conflicts for:
anaconda==2019.10=py37_0 -> click==7.0=py37_0
conda-verify -> click
Package importlib_metadata conflicts for:
anaconda==2019.10=py37_0 -> importlib_metadata==0.23=py37_0
Package cytoolz conflicts for:
anaconda==2019.10=py37_0 -> cytoolz==0.10.0=py37h7b6447c_0
conda[version='>=4.7.12'] -> cytoolz[version='>=0.8.1']
Package singledispatch conflicts for:
anaconda==2019.10=py37_0 -> singledispatch==3.4.0.3=py37_0
Package jupyterlab conflicts for:
anaconda==2019.10=py37_0 -> jupyterlab==1.1.4=pyhf63ae98_0
_ipyw_jlab_nb_ext_conf -> jupyterlab
Package tqdm conflicts for:
anaconda==2019.10=py37_0 -> tqdm==4.36.1=py_0
conda-build -> tqdm
conda-verify -> tqdm
Package tk conflicts for:
python=3.7 -> tk[version='>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
anaconda==2019.10=py37_0 -> tk==8.6.8=hbc83047_0
Package libxslt conflicts for:
anaconda==2019.10=py37_0 -> libxslt==1.1.33=h7d1a2b0_0
Package pycurl conflicts for:
anaconda==2019.10=py37_0 -> pycurl==7.43.0.3=py37h1ba5d50_0
Package pickleshare conflicts for:
anaconda==2019.10=py37_0 -> pickleshare==0.7.5=py37_0
Package futures conflicts for:
conda[version='>=4.7.12'] -> futures[version='>=3.0.0']
conda-build -> futures
Package mccabe conflicts for:
anaconda==2019.10=py37_0 -> mccabe==0.6.1=py37_1
Package mkl_random conflicts for:
anaconda==2019.10=py37_0 -> mkl_random==1.1.0=py37hd6b4f25_0
Package html5lib conflicts for:
anaconda==2019.10=py37_0 -> html5lib==1.0.1=py37_0
Package py conflicts for:
anaconda==2019.10=py37_0 -> py==1.8.0=py37_0
Package lazy-object-proxy conflicts for:
anaconda==2019.10=py37_0 -> lazy-object-proxy==1.4.2=py37h7b6447c_0
Package krb5 conflicts for:
anaconda==2019.10=py37_0 -> krb5==1.16.1=h173b8e3_7
Package nltk conflicts for:
anaconda==2019.10=py37_0 -> nltk==3.4.5=py37_0
Package gmpy2 conflicts for:
anaconda==2019.10=py37_0 -> gmpy2==2.0.8=py37h10f8cd9_2
Package pexpect conflicts for:
anaconda==2019.10=py37_0 -> pexpect==4.7.0=py37_0
Package pytz conflicts for:
anaconda==2019.10=py37_0 -> pytz==2019.3=py_0
conda-build -> pytz
Package pip conflicts for:
anaconda==2019.10=py37_0 -> pip==19.2.3=py37_0
python=3.7 -> pip
Package backports conflicts for:
anaconda==2019.10=py37_0 -> backports==1.0=py_2
Package hdf5 conflicts for:
anaconda==2019.10=py37_0 -> hdf5==1.10.4=hb1b8bf9_0
Package partd conflicts for:
anaconda==2019.10=py37_0 -> partd==1.0.0=py_0
Package _libgcc_mutex conflicts for:
anaconda==2019.10=py37_0 -> _libgcc_mutex==0.1=main
Package toolz conflicts for:
anaconda==2019.10=py37_0 -> toolz==0.10.0=py_0
Package qtpy conflicts for:
anaconda-navigator -> qtpy[version='>=1.2|>=1.4.1']
anaconda==2019.10=py37_0 -> qtpy==1.9.0=py_0
navigator-updater -> qtpy[version='>=1.2']
Package fsspec conflicts for:
anaconda==2019.10=py37_0 -> fsspec==0.5.2=py_0
Package defusedxml conflicts for:
anaconda==2019.10=py37_0 -> defusedxml==0.6.0=py_0
Package docutils conflicts for:
anaconda==2019.10=py37_0 -> docutils==0.15.2=py37_0
Package tblib conflicts for:
anaconda==2019.10=py37_0 -> tblib==1.4.0=py_0
Package ruamel_yaml conflicts for:
anaconda==2019.10=py37_0 -> ruamel_yaml==0.15.46=py37h14c3975_0
conda[version='>=4.7.12'] -> ruamel_yaml[version='>=0.11.14,<0.16']
Package psutil conflicts for:
conda-build -> psutil
anaconda-navigator -> psutil
anaconda==2019.10=py37_0 -> psutil==5.6.3=py37h7b6447c_0
Package requests conflicts for:
anaconda-navigator -> requests
anaconda==2019.10=py37_0 -> requests==2.22.0=py37_0
conda[version='>=4.7.12'] -> requests[version='>=2.18.4,<3']
Package ipython conflicts for:
anaconda==2019.10=py37_0 -> ipython==7.8.0=py37h39e3cac_0
Package pluggy conflicts for:
anaconda==2019.10=py37_0 -> pluggy==0.13.0=py37_0
Package imagesize conflicts for:
anaconda==2019.10=py37_0 -> imagesize==1.1.0=py37_0
Package wrapt conflicts for:
anaconda==2019.10=py37_0 -> wrapt==1.11.2=py37h7b6447c_0
Package expat conflicts for:
anaconda==2019.10=py37_0 -> expat==2.2.6=he6710b0_0
Package qt conflicts for:
anaconda==2019.10=py37_0 -> qt==5.9.7=h5867ecd_1
Package pytables conflicts for:
anaconda==2019.10=py37_0 -> pytables==3.5.2=py37h71ec239_1
Package pillow conflicts for:
anaconda-navigator -> pillow
anaconda==2019.10=py37_0 -> pillow==6.2.0=py37h34e0f95_0
Package pytest-openfiles conflicts for:
anaconda==2019.10=py37_0 -> pytest-openfiles==0.4.0=py_0
Package pyyaml conflicts for:
anaconda-navigator -> pyyaml
conda-build -> pyyaml
anaconda==2019.10=py37_0 -> pyyaml==5.1.2=py37h7b6447c_0
conda-verify -> pyyaml
Package libgcc-ng conflicts for:
anaconda==2019.10=py37_0 -> libgcc-ng==9.1.0=hdf63c60_0
python=3.7 -> libgcc-ng[version='>=4.9|>=7.2.0|>=7.3.0']
Package anaconda-client conflicts for:
anaconda==2019.10=py37_0 -> anaconda-client==1.7.2=py37_0
anaconda-navigator -> anaconda-client[version='>=1.6.14|>=1.6|>=1.6.12']
Package asn1crypto conflicts for:
anaconda==2019.10=py37_0 -> asn1crypto==1.0.1=py37_0
Package patchelf conflicts for:
anaconda==2019.10=py37_0 -> patchelf==0.9=he6710b0_3
conda-build -> patchelf
Package rope conflicts for:
anaconda==2019.10=py37_0 -> rope==0.14.0=py_0
Package fastcache conflicts for:
anaconda==2019.10=py37_0 -> fastcache==1.1.0=py37h7b6447c_0
Package boto conflicts for:
anaconda==2019.10=py37_0 -> boto==2.49.0=py37_0
Package sphinxcontrib-devhelp conflicts for:
anaconda==2019.10=py37_0 -> sphinxcontrib-devhelp==1.0.1=py_0
Package markupsafe conflicts for:
anaconda==2019.10=py37_0 -> markupsafe==1.1.1=py37h7b6447c_0
Package libarchive conflicts for:
conda-build -> libarchive
anaconda==2019.10=py37_0 -> libarchive==3.3.3=h5d8350f_5
Package numexpr conflicts for:
anaconda==2019.10=py37_0 -> numexpr==2.7.0=py37h9e4a6bb_0
Package backports.shutil_get_terminal_size conflicts for:
anaconda==2019.10=py37_0 -> backports.shutil_get_terminal_size==1.0.0=py37_2
Package sympy conflicts for:
anaconda==2019.10=py37_0 -> sympy==1.4=py37_0
Package six conflicts for:
conda-build -> six
anaconda==2019.10=py37_0 -> six==1.12.0=py37_0
conda-verify -> six
Package qtconsole conflicts for:
anaconda==2019.10=py37_0 -> qtconsole==4.5.5=py_0
Package cycler conflicts for:
anaconda==2019.10=py37_0 -> cycler==0.10.0=py37_0
Package sortedcollections conflicts for:
anaconda==2019.10=py37_0 -> sortedcollections==1.1.2=py37_0
Package mpc conflicts for:
anaconda==2019.10=py37_0 -> mpc==1.1.0=h10f8cd9_1
Package pango conflicts for:
anaconda==2019.10=py37_0 -> pango==1.42.4=h049681c_0
Package libgfortran-ng conflicts for:
anaconda==2019.10=py37_0 -> libgfortran-ng==7.3.0=hdf63c60_0
Package libxcb conflicts for:
anaconda==2019.10=py37_0 -> libxcb==1.13=h1bed415_1
Package scikit-learn conflicts for:
anaconda==2019.10=py37_0 -> scikit-learn==0.21.3=py37hd81dba3_0
Package nbformat conflicts for:
anaconda==2019.10=py37_0 -> nbformat==4.4.0=py37_0
Package ca-certificates conflicts for:
anaconda==2019.10=py37_0 -> ca-certificates==2019.8.28=0
Package unixodbc conflicts for:
anaconda==2019.10=py37_0 -> unixodbc==2.3.7=h14c3975_0
Package libtool conflicts for:
anaconda==2019.10=py37_0 -> libtool==2.4.6=h7b6447c_5
Package conda-package-handling conflicts for:
conda[version='>=4.7.12'] -> conda-package-handling[version='>=1.3.0']
conda-build -> conda-package-handling[version='>=1.1|>=1.3']
conda-verify -> conda-package-handling[version='>=1.0.4|>=1.1']
Package cloudpickle conflicts for:
anaconda==2019.10=py37_0 -> cloudpickle==1.2.2=py_0
Package conda-build conflicts for:
conda[version='>=4.7.12'] -> conda-build[version='>=3']
conda-verify -> conda-build[version='>=3.12.0']
Package msgpack-python conflicts for:
anaconda==2019.10=py37_0 -> msgpack-python==0.6.1=py37hfd86e86_1
Package locket conflicts for:
anaconda==2019.10=py37_0 -> locket==0.2.0=py37_1
Package ipython_genutils conflicts for:
anaconda==2019.10=py37_0 -> ipython_genutils==0.2.0=py37_0
Package jupyter conflicts for:
anaconda==2019.10=py37_0 -> jupyter==1.0.0=py37_7
Package cairo conflicts for:
anaconda==2019.10=py37_0 -> cairo==1.14.12=h8948797_3
Package mistune conflicts for:
anaconda==2019.10=py37_0 -> mistune==0.8.4=py37h7b6447c_0
Package openssl conflicts for:
anaconda==2019.10=py37_0 -> openssl==1.1.1d=h7b6447c_2
python=3.7 -> openssl[version='>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a']
Package jeepney conflicts for:
anaconda==2019.10=py37_0 -> jeepney==0.4.1=py_0
Package numpy-base conflicts for:
anaconda==2019.10=py37_0 -> numpy-base==1.17.2=py37hde5b4d6_0
Package mock conflicts for:
anaconda==2019.10=py37_0 -> mock==3.0.5=py37_0
Package keyring conflicts for:
anaconda==2019.10=py37_0 -> keyring==18.0.0=py37_0
Package heapdict conflicts for:
anaconda==2019.10=py37_0 -> heapdict==1.0.1=py_0
Package spyder conflicts for:
anaconda==2019.10=py37_0 -> spyder==3.3.6=py37_0
Package patsy conflicts for:
anaconda==2019.10=py37_0 -> patsy==0.5.1=py37_0
Package backports.os conflicts for:
anaconda==2019.10=py37_0 -> backports.os==0.1.1=py37_0
Package chardet conflicts for:
anaconda==2019.10=py37_0 -> chardet==3.0.4=py37_1003
conda-build -> chardet
anaconda-navigator -> chardet
Package setuptools conflicts for:
anaconda-navigator -> setuptools
conda-build -> setuptools
anaconda==2019.10=py37_0 -> setuptools==41.4.0=py37_0
conda[version='>=4.7.12'] -> setuptools[version='>=31.0.1']
Package joblib conflicts for:
anaconda==2019.10=py37_0 -> joblib==0.13.2=py37_0
Package python-libarchive-c conflicts for:
conda-build -> python-libarchive-c
anaconda==2019.10=py37_0 -> python-libarchive-c==2.8=py37_13
Package jupyter_console conflicts for:
anaconda==2019.10=py37_0 -> jupyter_console==6.0.0=py37_0
Package olefile conflicts for:
anaconda==2019.10=py37_0 -> olefile==0.46=py37_0
Package libedit conflicts for:
anaconda==2019.10=py37_0 -> libedit==3.1.20181209=hc058e9b_0
Package numba conflicts for:
anaconda==2019.10=py37_0 -> numba==0.45.1=py37h962f231_0
Package pandas conflicts for:
anaconda==2019.10=py37_0 -> pandas==0.25.1=py37he6710b0_0
Package multipledispatch conflicts for:
anaconda==2019.10=py37_0 -> multipledispatch==0.6.0=py37_0
Package intel-openmp conflicts for:
anaconda==2019.10=py37_0 -> intel-openmp==2019.4=243
Package llvmlite conflicts for:
anaconda==2019.10=py37_0 -> llvmlite==0.29.0=py37hd408876_0
Package glob2 conflicts for:
conda-build -> glob2[version='>=0.6']
anaconda==2019.10=py37_0 -> glob2==0.7=py_0
Package packaging conflicts for:
anaconda==2019.10=py37_0 -> packaging==19.2=py_0
Package pyqt conflicts for:
anaconda-navigator -> pyqt[version='>=5.6|>=5.6,<6.0a0']
navigator-updater -> pyqt[version='>=5.6']
anaconda==2019.10=py37_0 -> pyqt==5.9.2=py37h05f1152_2
Package traitlets conflicts for:
anaconda==2019.10=py37_0 -> traitlets==4.3.3=py37_0
Package backports.tempfile conflicts for:
conda-verify -> backports.tempfile
Package libsodium conflicts for:
anaconda==2019.10=py37_0 -> libsodium==1.0.16=h1bed415_0
Package certifi conflicts for:
anaconda==2019.10=py37_0 -> certifi==2019.9.11=py37_0
Package blosc conflicts for:
anaconda==2019.10=py37_0 -> blosc==1.16.3=hd408876_0
Package xz conflicts for:
anaconda==2019.10=py37_0 -> xz==5.2.4=h14c3975_4
python=3.7 -> xz[version='>=5.2.3,<5.3.0a0|>=5.2.4,<5.3.0a0|>=5.2.4,<6.0a0']
Package sphinxcontrib conflicts for:
anaconda==2019.10=py37_0 -> sphinxcontrib==1.0=py37_1
Package jdcal conflicts for:
anaconda==2019.10=py37_0 -> jdcal==1.4.1=py_0
Package ipywidgets conflicts for:
anaconda==2019.10=py37_0 -> ipywidgets==7.5.1=py_0
_ipyw_jlab_nb_ext_conf -> ipywidgets
Package readline conflicts for:
python=3.7 -> readline[version='>=7.0,<8.0a0|>=8.0,<9.0a0']
anaconda==2019.10=py37_0 -> readline==7.0=h7b6447c_5
Package secretstorage conflicts for:
anaconda==2019.10=py37_0 -> secretstorage==3.1.1=py37_0
Package libuuid conflicts for:
anaconda==2019.10=py37_0 -> libuuid==1.0.3=h1bed415_2
Package backports.functools_lru_cache conflicts for:
conda-verify -> backports.functools_lru_cache
Package et_xmlfile conflicts for:
anaconda==2019.10=py37_0 -> et_xmlfile==1.0.1=py37_0
Package webencodings conflicts for:
anaconda==2019.10=py37_0 -> webencodings==0.5.1=py37_1
Package parso conflicts for:
anaconda==2019.10=py37_0 -> parso==0.5.1=py_0
Package zstd conflicts for:
anaconda==2019.10=py37_0 -> zstd==1.3.7=h0b5b093_0
Package unicodecsv conflicts for:
anaconda==2019.10=py37_0 -> unicodecsv==0.14.1=py37_0
Package pathlib2 conflicts for:
anaconda==2019.10=py37_0 -> pathlib2==2.3.5=py37_0
Package gstreamer conflicts for:
anaconda==2019.10=py37_0 -> gstreamer==1.14.0=hb453b48_1
Package isort conflicts for:
anaconda==2019.10=py37_0 -> isort==4.3.21=py37_0
Package xlwt conflicts for:
anaconda==2019.10=py37_0 -> xlwt==1.3.0=py37_0
Package notebook conflicts for:
anaconda==2019.10=py37_0 -> notebook==6.0.1=py37_0
Package soupsieve conflicts for:
anaconda==2019.10=py37_0 -> soupsieve==1.9.3=py37_0
Package mpmath conflicts for:
anaconda==2019.10=py37_0 -> mpmath==1.1.0=py37_0
Package send2trash conflicts for:
anaconda==2019.10=py37_0 -> send2trash==1.5.0=py37_0
Package imageio conflicts for:
anaconda==2019.10=py37_0 -> imageio==2.6.0=py37_0
Package ptyprocess conflicts for:
anaconda==2019.10=py37_0 -> ptyprocess==0.6.0=py37_0
Package scikit-image conflicts for:
anaconda==2019.10=py37_0 -> scikit-image==0.15.0=py37he6710b0_0
Package sqlite conflicts for:
python=3.7 -> sqlite[version='>=3.24.0,<4.0a0|>=3.25.1,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.28.0,<4.0a0|>=3.29.0,<4.0a0']
anaconda==2019.10=py37_0 -> sqlite==3.30.0=h7b6447c_0
Package colorama conflicts for:
anaconda==2019.10=py37_0 -> colorama==0.4.1=py37_0
Package widgetsnbextension conflicts for:
anaconda==2019.10=py37_0 -> widgetsnbextension==3.5.1=py37_0
_ipyw_jlab_nb_ext_conf -> widgetsnbextension
Package sphinxcontrib-jsmath conflicts for:
anaconda==2019.10=py37_0 -> sphinxcontrib-jsmath==1.0.1=py_0
Package pyflakes conflicts for:
anaconda==2019.10=py37_0 -> pyflakes==2.1.1=py37_0
Package nose conflicts for:
anaconda==2019.10=py37_0 -> nose==1.3.7=py37_2
Package pandocfilters conflicts for:
anaconda==2019.10=py37_0 -> pandocfilters==1.4.2=py37_1
Package pcre conflicts for:
anaconda==2019.10=py37_0 -> pcre==8.43=he6710b0_0
Package jupyter_core conflicts for:
anaconda==2019.10=py37_0 -> jupyter_core==4.5.0=py_0
Package gmp conflicts for:
anaconda==2019.10=py37_0 -> gmp==6.1.2=h6c8ec71_1
Package cryptography conflicts for:
anaconda==2019.10=py37_0 -> cryptography==2.7=py37h1ba5d50_0
Package dask conflicts for:
anaconda==2019.10=py37_0 -> dask==2.5.2=py_0
Package filelock conflicts for:
anaconda==2019.10=py37_0 -> filelock==3.0.12=py_0
conda-build -> filelock
Package zipp conflicts for:
anaconda==2019.10=py37_0 -> zipp==0.6.0=py_0
Package libxml2 conflicts for:
anaconda==2019.10=py37_0 -> libxml2==2.9.9=hea5a465_1
Package ripgrep conflicts for:
conda-build -> ripgrep
anaconda==2019.10=py37_0 -> ripgrep==0.10.0=hc07d326_0
Package wcwidth conflicts for:
anaconda==2019.10=py37_0 -> wcwidth==0.1.7=py37_0
Package clyent conflicts for:
anaconda==2019.10=py37_0 -> clyent==1.2.2=py37_1
Package kiwisolver conflicts for:
anaconda==2019.10=py37_0 -> kiwisolver==1.1.0=py37he6710b0_0
Package pyopenssl conflicts for:
anaconda==2019.10=py37_0 -> pyopenssl==19.0.0=py37_0
conda[version='>=4.7.12'] -> pyopenssl[version='>=16.2.0']
Package cffi conflicts for:
anaconda==2019.10=py37_0 -> cffi==1.12.3=py37h2e261b9_0
Package jbig conflicts for:
anaconda==2019.10=py37_0 -> jbig==2.1=hdba287a_0
Package zict conflicts for:
anaconda==2019.10=py37_0 -> zict==1.0.0=py_0
Package icu conflicts for:
anaconda==2019.10=py37_0 -> icu==58.2=h9c2bf20_1
Package py-lief conflicts for:
conda-build -> py-lief
anaconda==2019.10=py37_0 -> py-lief==0.9.0=py37h7725739_2
Package get_terminal_size conflicts for:
anaconda==2019.10=py37_0 -> get_terminal_size==1.0.0=haa9412d_0
Package fribidi conflicts for:
anaconda==2019.10=py37_0 -> fribidi==1.0.5=h7b6447c_0
Package mkl conflicts for:
anaconda==2019.10=py37_0 -> mkl==2019.4=243
Package zlib conflicts for:
python=3.7 -> zlib[version='>=1.2.11,<1.3.0a0']
anaconda==2019.10=py37_0 -> zlib==1.2.11=h7b6447c_3
Package atomicwrites conflicts for:
anaconda==2019.10=py37_0 -> atomicwrites==1.3.0=py37_1
Package urllib3 conflicts for:
anaconda==2019.10=py37_0 -> urllib3==1.24.2=py37_0
Package wheel conflicts for:
anaconda==2019.10=py37_0 -> wheel==0.33.6=py37_0
Package jsonschema conflicts for:
anaconda==2019.10=py37_0 -> jsonschema==3.0.2=py37_0
Package mkl_fft conflicts for:
anaconda==2019.10=py37_0 -> mkl_fft==1.0.14=py37ha843d7b_0
Package cython conflicts for:
anaconda==2019.10=py37_0 -> cython==0.29.13=py37he6710b0_0
Package python-dateutil conflicts for:
anaconda==2019.10=py37_0 -> python-dateutil==2.8.0=py37_0
Package pytest-remotedata conflicts for:
anaconda==2019.10=py37_0 -> pytest-remotedata==0.3.2=py37_0
Package nbconvert conflicts for:
anaconda==2019.10=py37_0 -> nbconvert==5.6.0=py37_1
Package qtawesome conflicts for:
anaconda==2019.10=py37_0 -> qtawesome==0.6.0=py_0
Package ply conflicts for:
anaconda==2019.10=py37_0 -> ply==3.11=py37_0
Package sphinxcontrib-serializinghtml conflicts for:
anaconda==2019.10=py37_0 -> sphinxcontrib-serializinghtml==1.1.3=py_0
Package conda-verify conflicts for:
conda-build -> conda-verify
Package json5 conflicts for:
anaconda==2019.10=py37_0 -> json5==0.8.5=py_0
Package pkginfo conflicts for:
conda-build -> pkginfo
anaconda==2019.10=py37_0 -> pkginfo==1.5.0.1=py37_0
Package enum34 conflicts for:
conda[version='>=4.7.12'] -> enum34
conda-build -> enum34
Package sphinxcontrib-qthelp conflicts for:
anaconda==2019.10=py37_0 -> sphinxcontrib-qthelp==1.0.2=py_0
Package libffi conflicts for:
python=3.7 -> libffi[version='>=3.2.1,<3.3.0a0|>=3.2.1,<4.0a0']
anaconda==2019.10=py37_0 -> libffi==3.2.1=hd88cf55_4
Package liblief conflicts for:
anaconda==2019.10=py37_0 -> liblief==0.9.0=h7725739_2
Package pywavelets conflicts for:
anaconda==2019.10=py37_0 -> pywavelets==1.0.3=py37hdd07704_1
Package pep8 conflicts for:
anaconda==2019.10=py37_0 -> pep8==1.7.1=py37_0
Package bokeh conflicts for:
anaconda==2019.10=py37_0 -> bokeh==1.3.4=py37_0
Package contextlib2 conflicts for:
anaconda==2019.10=py37_0 -> contextlib2==0.6.0=py_0
conda-build -> contextlib2
Package libpng conflicts for:
anaconda==2019.10=py37_0 -> libpng==1.6.37=hbc83047_0
Package idna conflicts for:
anaconda==2019.10=py37_0 -> idna==2.8=py37_0
Package pandoc conflicts for:
anaconda==2019.10=py37_0 -> pandoc==2.2.3.2=0
Package sip conflicts for:
anaconda==2019.10=py37_0 -> sip==4.19.8=py37hf484d3e_0
Package lzo conflicts for:
anaconda==2019.10=py37_0 -> lzo==2.10=h49e0be7_2
Package libssh2 conflicts for:
anaconda==2019.10=py37_0 -> libssh2==1.8.2=h1ba5d50_0
Package graphite2 conflicts for:
anaconda==2019.10=py37_0 -> graphite2==1.3.13=h23475e2_0
Package alabaster conflicts for:
anaconda==2019.10=py37_0 -> alabaster==0.7.12=py37_0
Package glib conflicts for:
anaconda==2019.10=py37_0 -> glib==2.56.2=hd408876_0
Package lxml conflicts for:
anaconda==2019.10=py37_0 -> lxml==4.4.1=py37hefd8a0e_0
Package xlrd conflicts for:
anaconda==2019.10=py37_0 -> xlrd==1.2.0=py37_0
Package bottleneck conflicts for:
anaconda==2019.10=py37_0 -> bottleneck==1.2.1=py37h035aef0_1
Package matplotlib conflicts for:
anaconda==2019.10=py37_0 -> matplotlib==3.1.1=py37h5429711_0
Package pixman conflicts for:
anaconda==2019.10=py37_0 -> pixman==0.38.0=h7b6447c_0
Package pysocks conflicts for:
anaconda==2019.10=py37_0 -> pysocks==1.7.1=py37_0
Package xlsxwriter conflicts for:
anaconda==2019.10=py37_0 -> xlsxwriter==1.2.1=py_0
Package seaborn conflicts for:
anaconda==2019.10=py37_0 -> seaborn==0.9.0=py37_0
Package prompt_toolkit conflicts for:
anaconda==2019.10=py37_0 -> prompt_toolkit==2.0.10=py_0
Package wurlitzer conflicts for:
anaconda==2019.10=py37_0 -> wurlitzer==1.0.3=py37_0
Package pygments conflicts for:
anaconda==2019.10=py37_0 -> pygments==2.4.2=py_0
Package anaconda-project conflicts for:
anaconda-navigator -> anaconda-project[version='>=0.4']
anaconda==2019.10=py37_0 -> anaconda-project==0.8.3=py_0
Package numpy conflicts for:
anaconda==2019.10=py37_0 -> numpy==1.17.2=py37haad9e8e_0
Package pytest conflicts for:
anaconda==2019.10=py37_0 -> pytest==5.2.1=py37_0
Package networkx conflicts for:
anaconda==2019.10=py37_0 -> networkx==2.3=py_0
Package jedi conflicts for:
anaconda==2019.10=py37_0 -> jedi==0.15.1=py37_0
Package itsdangerous conflicts for:
anaconda==2019.10=py37_0 -> itsdangerous==1.1.0=py37_0
Package entrypoints conflicts for:
anaconda==2019.10=py37_0 -> entrypoints==0.3=py37_0
Package sortedcontainers conflicts for:
anaconda==2019.10=py37_0 -> sortedcontainers==2.1.0=py37_0
Package path.py conflicts for:
anaconda==2019.10=py37_0 -> path.py==12.0.1=py_0
Package snappy conflicts for:
anaconda==2019.10=py37_0 -> snappy==1.1.7=hbae5bb6_3
Package pycparser conflicts for:
anaconda==2019.10=py37_0 -> pycparser==2.19=py37_0
Package snowballstemmer conflicts for:
anaconda==2019.10=py37_0 -> snowballstemmer==2.0.0=py_0
Package sphinxcontrib-htmlhelp conflicts for:
anaconda==2019.10=py37_0 -> sphinxcontrib-htmlhelp==1.0.2=py_0
Package conda-env conflicts for:
conda[version='>=4.7.12'] -> conda-env[version='>=2.6']
Package gevent conflicts for:
anaconda==2019.10=py37_0 -> gevent==1.4.0=py37h7b6447c_0
Package mpfr conflicts for:
anaconda==2019.10=py37_0 -> mpfr==4.0.1=hdf1c602_3
Package scipy conflicts for:
anaconda==2019.10=py37_0 -> scipy==1.3.1=py37h7c811a0_0
Package numpydoc conflicts for:
anaconda==2019.10=py37_0 -> numpydoc==0.9.1=py_0
Package pyrsistent conflicts for:
anaconda==2019.10=py37_0 -> pyrsistent==0.15.4=py37h7b6447c_0
Package zeromq conflicts for:
anaconda==2019.10=py37_0 -> zeromq==4.3.1=he6710b0_3
Package yaml conflicts for:
anaconda==2019.10=py37_0 -> yaml==0.1.7=had09818_2
Package sqlalchemy conflicts for:
anaconda==2019.10=py37_0 -> sqlalchemy==1.3.9=py37h7b6447c_0
Package astroid conflicts for:
anaconda==2019.10=py37_0 -> astroid==2.3.1=py37_0
Package decorator conflicts for:
anaconda==2019.10=py37_0 -> decorator==4.4.0=py37_1
Package sphinxcontrib-applehelp conflicts for:
anaconda==2019.10=py37_0 -> sphinxcontrib-applehelp==1.0.1=py_0
Package testpath conflicts for:
anaconda==2019.10=py37_0 -> testpath==0.4.2=py37_0
Package distributed conflicts for:
anaconda==2019.10=py37_0 -> distributed==2.5.2=py_0
Package libcurl conflicts for:
anaconda==2019.10=py37_0 -> libcurl==7.65.3=h20c2e04_0
Package future conflicts for:
conda-verify -> future
Package jupyterlab_server conflicts for:
anaconda==2019.10=py37_0 -> jupyterlab_server==1.0.6=py_0
Package bzip2 conflicts for:
anaconda==2019.10=py37_0 -> bzip2==1.0.8=h7b6447c_0
python=3.7 -> bzip2[version='>=1.0.6,<2.0a0']
Package statsmodels conflicts for:
anaconda==2019.10=py37_0 -> statsmodels==0.10.1=py37hdd07704_0
Package pyodbc conflicts for:
anaconda==2019.10=py37_0 -> pyodbc==4.0.27=py37he6710b0_0
Package pycodestyle conflicts for:
anaconda==2019.10=py37_0 -> pycodestyle==2.5.0=py37_0
Package conda conflicts for:
conda-build -> conda[version='>=4.1,<4.4|>=4.1|>=4.1,<4.3|>=4.3|>=4.5']
Package tornado conflicts for:
anaconda==2019.10=py37_0 -> tornado==6.0.3=py37h7b6447c_0
Package prometheus_client conflicts for:
anaconda==2019.10=py37_0 -> prometheus_client==0.7.1=py_0
Package astropy conflicts for:
anaconda==2019.10=py37_0 -> astropy==3.2.2=py37h7b6447c_0
Package pyzmq conflicts for:
anaconda==2019.10=py37_0 -> pyzmq==18.1.0=py37he6710b0_0
Package mkl-service conflicts for:
anaconda==2019.10=py37_0 -> mkl-service==2.3.0=py37he904b0f_0
Package dbus conflicts for:
anaconda==2019.10=py37_0 -> dbus==1.13.6=h746ee38_0
Package pyparsing conflicts for:
anaconda==2019.10=py37_0 -> pyparsing==2.4.2=py_0
Package sphinxcontrib-websupport conflicts for:
anaconda==2019.10=py37_0 -> sphinxcontrib-websupport==1.1.2=py_0
Package curl conflicts for:
anaconda==2019.10=py37_0 -> curl==7.65.3=hbc83047_0
Package babel conflicts for:
anaconda==2019.10=py37_0 -> babel==2.7.0=py_0
Package libtiff conflicts for:
anaconda==2019.10=py37_0 -> libtiff==4.0.10=h2733197_2
Package greenlet conflicts for:
anaconda==2019.10=py37_0 -> greenlet==0.4.15=py37h7b6447c_0
Package jupyter_client conflicts for:
anaconda==2019.10=py37_0 -> jupyter_client==5.3.3=py37_1
Package more-itertools conflicts for:
anaconda==2019.10=py37_0 -> more-itertools==7.2.0=py37_0
Package pytest-astropy conflicts for:
anaconda==2019.10=py37_0 -> pytest-astropy==0.5.0=py37_0
Package backcall conflicts for:
anaconda==2019.10=py37_0 -> backcall==0.1.0=py37_0
Package bitarray conflicts for:
anaconda==2019.10=py37_0 -> bitarray==1.0.1=py37h7b6447c_0
Package gst-plugins-base conflicts for:
anaconda==2019.10=py37_0 -> gst-plugins-base==1.14.0=hbbd80ab_1
Package freetype conflicts for:
anaconda==2019.10=py37_0 -> freetype==2.9.1=h8a8886c_1
Package werkzeug conflicts for:
anaconda==2019.10=py37_0 -> werkzeug==0.16.0=py_0
Package ipykernel conflicts for:
anaconda==2019.10=py37_0 -> ipykernel==5.1.2=py37h39e3cac_0
Package jpeg conflicts for:
anaconda==2019.10=py37_0 -> jpeg==9b=h024ee3a_2
Package openpyxl conflicts for:
anaconda==2019.10=py37_0 -> openpyxl==3.0.0=py_0
Package terminado conflicts for:
anaconda==2019.10=py37_0 -> terminado==0.8.2=py37_0
Package pycrypto conflicts for:
conda-build -> pycrypto
anaconda==2019.10=py37_0 -> pycrypto==2.6.1=py37h14c3975_9
Package simplegeneric conflicts for:
anaconda==2019.10=py37_0 -> simplegeneric==0.8.1=py37_2
Package tbb conflicts for:
anaconda==2019.10=py37_0 -> tbb==2019.4=hfd86e86_0
Package flask conflicts for:
anaconda==2019.10=py37_0 -> flask==1.1.1=py_0
Package bkcharts conflicts for:
anaconda==2019.10=py37_0 -> bkcharts==0.2=py37_0
Package blas conflicts for:
anaconda==2019.10=py37_0 -> blas==1.0=mkl
Package bleach conflicts for:
anaconda==2019.10=py37_0 -> bleach==3.1.0=py37_0
Package attrs conflicts for:
anaconda==2019.10=py37_0 -> attrs==19.2.0=py_0
Note that strict channel priority may have removed packages required for satisfiability.

$

**Comment by jageshmaharjan** [comment]
Same issue.

Current_repodata.json causes system  to freeze in ubuntu 18.04.3

**Comment by normanisrael** [comment]
having the same issue. i notice this has been posted since oct, has this been solved at all?

**Comment by mjanson** [comment]
I don't think so--I just re-queried in the anaconda dev group to see if we can have someone look into this.

In the meantime, I have found a workaround by downloading an older installer -- https://repo.anaconda.com/archive/Anaconda2-2019.03-Linux-x86_64.sh -- which has fewer confliects.  I then found that first running 'conda remove bkcharts' removes the conflicts and appears to update to current version (haven't switched to it yet from my current virtualenv "workaround").

**Comment by ZhangAustin** [comment]
2021 still the same issue for Anaconda3-2021.05-Linux-x86_64 on Ubuntu 18.04
