### ISSUE TITLE
After updating to Anaconda navigator 2.1.1, unable to close it.

### ISSUE THREAD

**Issue by ImRobot777** [ContinuumIO/anaconda-issues#12721]
### Actual Behavior

Unable to close Anaconda navigator, "quit" button on final popup seems to be inactive

### Expected Behavior

Close Anaconda should be closed

### Steps to Reproduce

Run jupyter lab, and try to close anaconda navigator !

##### Anaconda or Miniconda version:
2.1.1

##### Operating System:
Windows 10 pro

##### `conda info`

<details>

```
active environment : envP3
    active env location : C:\Users\conra\anaconda3\envs\envP3
            shell level : 1
       user config file : C:\Users\conra\.condarc
 populated config files : C:\Users\conra\.condarc
          conda version : 4.10.3
    conda-build version : 3.21.4
         python version : 3.8.8.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\conra\anaconda3  (writable)
      conda av data dir : C:\Users\conra\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\conra\anaconda3\pkgs
                          C:\Users\conra\.conda\pkgs
                          C:\Users\conra\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\conra\anaconda3\envs
                          C:\Users\conra\.conda\envs
                          C:\Users\conra\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.8.8 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False

```

</details>

##### `conda list --show-channel-urls`

<details>

```
# packages in environment at C:\Users\conra\anaconda3\envs\envP3:
#
# Name                    Version                   Build  Channel
ansi2html                 1.6.0                    pypi_0    pypi
ansicolors                1.1.8                    pypi_0    pypi
ansiwrap                  0.8.4                    pypi_0    pypi
anyio                     2.2.0            py39haa95532_2    defaults
argon2-cffi               20.1.0           py39h2bbff1b_1    defaults
async_generator           1.10               pyhd3eb1b0_0    defaults
attrs                     21.2.0             pyhd3eb1b0_0    defaults
babel                     2.9.1              pyhd3eb1b0_0    defaults
backcall                  0.2.0              pyhd3eb1b0_0    defaults
beautifulsoup4            4.9.3                    pypi_0    pypi
bleach                    4.0.0              pyhd3eb1b0_0    defaults
bqplot                    0.12.31                  pypi_0    pypi
branca                    0.4.2                    pypi_0    pypi
brotli                    1.0.9                    pypi_0    pypi
brotlipy                  0.7.0           py39h2bbff1b_1003    defaults
ca-certificates           2021.10.26           haa95532_2    defaults
certifi                   2021.10.8        py39haa95532_0    defaults
cffi                      1.14.6           py39h2bbff1b_0    defaults
chainmap                  1.0.3                    pypi_0    pypi
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
click                     8.0.3                    pypi_0    pypi
colorama                  0.4.4              pyhd3eb1b0_0    defaults
colorlover                0.3.0                    pypi_0    pypi
combomethod               1.0.12                   pypi_0    pypi
counter                   1.0.0                    pypi_0    pypi
cryptography              3.4.7            py39h71e12ea_0    defaults
cycler                    0.10.0                   pypi_0    pypi
dash-core-components      2.0.0                    pypi_0    pypi
dash-html-components      2.0.0                    pypi_0    pypi
dash-table                5.0.0                    pypi_0    pypi
decorator                 5.0.9              pyhd3eb1b0_0    defaults
defusedxml                0.7.1              pyhd3eb1b0_0    defaults
entrypoints               0.3              py39haa95532_0    defaults
flask                     2.0.2                    pypi_0    pypi
flask-compress            1.10.1                   pypi_0    pypi
folium                    0.12.1                   pypi_0    pypi
icu                       58.2                 ha925a31_3    defaults
idna                      3.2                pyhd3eb1b0_0    defaults
importlib-metadata        3.10.0           py39haa95532_0    defaults
importlib_metadata        3.10.0               hd3eb1b0_0    defaults
intspan                   1.6.1                    pypi_0    pypi
ipykernel                 5.3.4            py39h7b7c402_0    defaults
ipython                   7.26.0           py39hd4e2768_0    defaults
ipython_genutils          0.2.0              pyhd3eb1b0_1    defaults
ipywidgets                7.6.3              pyhd3eb1b0_1    defaults
itsdangerous              2.0.1                    pypi_0    pypi
jedi                      0.18.0           py39haa95532_1    defaults
jinja2                    3.0.1              pyhd3eb1b0_0    defaults
joblib                    1.0.1                    pypi_0    pypi
jpeg                      9b                   hb83a4c4_2    defaults
json5                     0.9.6              pyhd3eb1b0_0    defaults
jsonschema                3.2.0                      py_2    defaults
jupyter                   1.0.0            py39haa95532_7    defaults
jupyter-kite              2.0.2                    pypi_0    pypi
jupyter_client            6.1.12             pyhd3eb1b0_0    defaults
jupyter_console           6.4.0              pyhd3eb1b0_0    defaults
jupyter_core              4.7.1            py39haa95532_0    defaults
jupyter_server            1.4.1            py39haa95532_0    defaults
jupyterlab                3.2.1              pyhd3eb1b0_1    defaults
jupyterlab-kite           2.0.2                    pypi_0    pypi
jupyterlab_pygments       0.1.2                      py_0    defaults
jupyterlab_server         2.7.1              pyhd3eb1b0_0    defaults
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1    defaults
kiwisolver                1.3.2                    pypi_0    pypi
libpng                    1.6.37               h2a8f88b_0    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
markupsafe                2.0.1            py39h2bbff1b_0    defaults
matplotlib                3.4.3                    pypi_0    pypi
matplotlib-inline         0.1.2              pyhd3eb1b0_2    defaults
mementos                  1.3.1                    pypi_0    pypi
mistune                   0.8.4           py39h2bbff1b_1000    defaults
msys2-conda-epoch         20160418                      1    defaults
nbclassic                 0.2.6              pyhd3eb1b0_0    defaults
nbclient                  0.5.3              pyhd3eb1b0_0    defaults
nbconvert                 6.1.0            py39haa95532_0    defaults
nbformat                  5.1.3              pyhd3eb1b0_0    defaults
nest-asyncio              1.5.1              pyhd3eb1b0_0    defaults
notebook                  6.4.5            py39haa95532_0    defaults
nulltype                  2.3.1                    pypi_0    pypi
numpy                     1.21.2                   pypi_0    pypi
openssl                   1.1.1l               h2bbff1b_0    defaults
options                   1.4.10                   pypi_0    pypi
packaging                 21.0               pyhd3eb1b0_0    defaults
pandas                    1.3.2                    pypi_0    pypi
pandocfilters             1.4.3            py39haa95532_1    defaults
parso                     0.8.2              pyhd3eb1b0_0    defaults
pickleshare               0.7.5           pyhd3eb1b0_1003    defaults
pillow                    8.3.1                    pypi_0    pypi
pip                       21.2.4           py38haa95532_0    defaults
plotly                    5.3.1                    pypi_0    pypi
prometheus_client         0.11.0             pyhd3eb1b0_0    defaults
prompt-toolkit            3.0.17             pyh06a4308_0    defaults
prompt_toolkit            3.0.17               hd3eb1b0_0    defaults
pycparser                 2.20                       py_2    defaults
pygments                  2.10.0             pyhd3eb1b0_0    defaults
pyopenssl                 20.0.1             pyhd3eb1b0_1    defaults
pyparsing                 2.4.7              pyhd3eb1b0_0    defaults
pyqt                      5.9.2            py39hd77b12b_6    defaults
pyrsistent                0.18.0           py39h2bbff1b_0    defaults
pysocks                   1.7.1            py39haa95532_0    defaults
python                    3.9.6                h6244533_1    defaults
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
pytz                      2021.1             pyhd3eb1b0_0    defaults
pywin32                   228              py39hbaba5e8_1    defaults
pywinpty                  0.5.7            py39haa95532_0    defaults
pyzmq                     22.2.1           py39hd77b12b_1    defaults
qt                        5.9.7            vc14h73c81de_0    defaults
qtconsole                 5.1.1              pyhd3eb1b0_0    defaults
qtpy                      1.9.0                      py_0    defaults
requests                  2.26.0             pyhd3eb1b0_0    defaults
retrying                  1.3.3                    pypi_0    pypi
say                       1.6.6                    pypi_0    pypi
scikit-learn              0.24.2                   pypi_0    pypi
scipy                     1.7.1                    pypi_0    pypi
seaborn                   0.11.2                   pypi_0    pypi
send2trash                1.5.0              pyhd3eb1b0_1    defaults
setuptools                52.0.0           py39haa95532_0    defaults
simplere                  1.2.13                   pypi_0    pypi
sip                       4.19.13          py39hd77b12b_0    defaults
six                       1.12.0                   pypi_0    pypi
sklearn                   0.0                      pypi_0    pypi
sniffio                   1.2.0            py39haa95532_1    defaults
soupsieve                 2.2.1                    pypi_0    pypi
sqlite                    3.36.0               h2bbff1b_0    defaults
tenacity                  8.0.1                    pypi_0    pypi
terminado                 0.9.4            py39haa95532_0    defaults
testpath                  0.5.0              pyhd3eb1b0_0    defaults
textdata                  2.4.1                    pypi_0    pypi
textwrap3                 0.9.2                    pypi_0    pypi
threadpoolctl             2.2.0                    pypi_0    pypi
tornado                   6.1              py39h2bbff1b_0    defaults
traitlets                 5.0.5              pyhd3eb1b0_0    defaults
traittypes                0.2.1                    pypi_0    pypi
tzdata                    2021a                h5d7bf9c_0    defaults
urllib3                   1.26.6             pyhd3eb1b0_1    defaults
vc                        14.2                 h21ff451_1    defaults
voila                     0.2.16                   pypi_0    pypi
vs2015_runtime            14.27.29016          h5e58377_2    defaults
wcwidth                   0.2.5                      py_0    defaults
webencodings              0.5.1            py39haa95532_1    defaults
werkzeug                  2.0.2                    pypi_0    pypi
wheel                     0.37.0             pyhd3eb1b0_0    defaults
widgetsnbextension        3.5.1            py39haa95532_0    defaults
win_inet_pton             1.1.0            py39haa95532_0    defaults
wincertstore              0.2              py39h2bbff1b_0    defaults
winpty                    0.4.3                         4    defaults
zipp                      3.5.0              pyhd3eb1b0_0    defaults
zlib                      1.2.11               h62dcd97_4    defaults

```

</details>

**Comment by ImRobot777** [comment]
Anyone to help ?

**Comment by yshmatov-anaconda** [comment]
Thanks for leaving bug report!

I'm currently trying to replicate your issue, but whatever I try - Navigator closes with no problems.

Could you, please, provide more details on the issue?
- Do you have this issue every time you open Jupyter Lab, or is it only occasional?
- Does this issue occur only with Jupyter Lab, or is it also applies to other applications (e.g. Jupyter Notebook, IPython Qt Console)?
- Do you select to close Jupyter Lab in the "close running applications" dialog?
- How long do you wait between opening Jupyter Lab and closing the Navigator?
- Could you also, please, provide `conda list --show-channel-urls` of the base environment where the Navigator is installed?

You could also disable a "Close running applications" by checking "Hide running applications dialog" in the preferences.

**Comment by ImRobot777** [comment]
Hi, 
   
   - Do you have this issue every time you open Jupyter Lab, or is it only occasional?
   - Does this issue occur only with Jupyter Lab, or is it also applies to other applications (e.g. Jupyter Notebook, IPython Qt Console)?
   - How long do you wait between opening Jupyter Lab and closing the Navigator?

 Sorry i should have given the details, so most of the time there is no problem, but when a heavy notbook (jupiterlab + jupyter notbook) had run during the day, and i want to close navigator at the end of the day, then the close button does not work, i have to kill the python process in order make the navigator window close (force disappearing).


   
   - Do you select to close Jupyter Lab in the "close running applications" dialog?
Both, when selected or not 

   
   - Could you also, please, provide conda list --show-channel-urls of the base environment where the Navigator is installed?

(base) C:\Users\conra>conda list --show-channel-urls# packages in environment at C:\Users\conra\anaconda3:## Name                    Version                   Build  Channel_anaconda_depends         2020.07                  py38_0    defaults_ipyw_jlab_nb_ext_conf    0.1.0                    py38_0    defaultsalabaster                 0.7.12             pyhd3eb1b0_0    defaultsanaconda                  custom                   py38_1    defaultsanaconda-client           1.8.0            py38haa95532_0    defaultsanaconda-navigator        2.1.1                    py38_0    defaultsanaconda-project          0.10.1             pyhd3eb1b0_0    defaultsanyio                     2.2.0            py38haa95532_2    defaultsappdirs                   1.4.4                      py_0    defaultsargh                      0.26.2                   py38_0    defaultsargon2-cffi               20.1.0           py38h2bbff1b_1    defaultsarrow                     0.13.1                   py38_0    defaultsasn1crypto                1.4.0                      py_0    defaultsastroid                   2.6.6            py38haa95532_0    defaultsastropy                   4.3.post1        py38h080aedc_1    defaultsasync_generator           1.10               pyhd3eb1b0_0    defaultsatomicwrites              1.4.0                      py_0    defaultsattrs                     21.2.0             pyhd3eb1b0_0    defaultsautopep8                  1.5.6              pyhd3eb1b0_0    defaultsbabel                     2.9.1              pyhd3eb1b0_0    defaultsbackcall                  0.2.0              pyhd3eb1b0_0    defaultsbackports                 1.0                pyhd3eb1b0_2    defaultsbackports.functools_lru_cache 1.6.4              pyhd3eb1b0_0    defaultsbackports.shutil_get_terminal_size 1.0.0              pyhd3eb1b0_3    defaultsbackports.tempfile        1.0                pyhd3eb1b0_1    defaultsbackports.weakref         1.0.post1                  py_1    defaultsbcrypt                    3.2.0            py38he774522_0    defaultsbeautifulsoup4            4.9.3              pyha847dfd_0    defaultsbinaryornot               0.4.4              pyhd3eb1b0_1    defaultsbitarray                  2.2.3            py38h2bbff1b_1    defaultsbkcharts                  0.2                      py38_0    defaultsblack                     19.10b0                    py_0    defaultsblas                      1.0                         mkl    defaultsbleach                    4.0.0              pyhd3eb1b0_0    defaultsblosc                     1.21.0               h19a0ad4_0    defaultsbokeh                     2.3.3            py38haa95532_0    defaultsboto                      2.49.0                   py38_0    defaultsbottleneck                1.3.2            py38h2a96729_1    defaultsbrotli                    1.0.9                ha925a31_2    defaultsbrotlipy                  0.7.0           py38h2bbff1b_1003    defaultsbzip2                     1.0.8                he774522_0    defaultsca-certificates           2021.10.26           haa95532_2    defaultscertifi                   2021.10.8        py38haa95532_0    defaultscffi                      1.14.6           py38h2bbff1b_0    defaultscfitsio                   3.470                he774522_6    defaultschardet                   4.0.0           py38haa95532_1003    defaultscharls                    2.2.0                h6c2663c_0    defaultsclick                     8.0.1              pyhd3eb1b0_0    defaultscloudpickle               1.6.0                      py_0    defaultsclyent                    1.2.2                    py38_1    defaultscolorama                  0.4.4              pyhd3eb1b0_0    defaultscomtypes                  1.1.10          py38haa95532_1002    defaultsconda                     4.10.3           py38haa95532_0    defaultsconda-build               3.21.4           py38haa95532_0    defaultsconda-content-trust       0.1.1              pyhd3eb1b0_0    defaultsconda-env                 2.6.0                         1    defaultsconda-pack                0.6.0              pyhd3eb1b0_0    defaultsconda-package-handling    1.7.3            py38h8cc25b3_1    defaultsconda-repo-cli            1.0.4              pyhd3eb1b0_0    defaultsconda-token               0.3.0              pyhd3eb1b0_0    defaultsconda-verify              3.4.2                      py_1    defaultsconsole_shortcut          0.1.1                         4    defaultscontextlib2               0.6.0.post1                py_0    defaultscookiecutter              1.7.2              pyhd3eb1b0_0    defaultscryptography              3.4.7            py38h71e12ea_0    defaultscurl                      7.71.1               h86230a5_2    defaultscycler                    0.10.0                   py38_0    defaultscython                    0.29.24          py38hd77b12b_0    defaultscytoolz                   0.11.0           py38he774522_0    defaultsdask                      2021.7.2           pyhd3eb1b0_0    defaultsdask-core                 2021.7.2           pyhd3eb1b0_0    defaultsdecorator                 5.0.9              pyhd3eb1b0_0    defaultsdefusedxml                0.7.1              pyhd3eb1b0_0    defaultsdiff-match-patch          20200713                   py_0    defaultsdistributed               2021.7.2         py38haa95532_0    defaultsdocutils                  0.17.1           py38haa95532_1    defaultsentrypoints               0.3                      py38_0    defaultset_xmlfile                1.1.0            py38haa95532_0    defaultsfastcache                 1.1.0            py38he774522_0    defaultsfilelock                  3.0.12             pyhd3eb1b0_1    defaultsflake8                    3.9.0              pyhd3eb1b0_0    defaultsflask                     1.1.2              pyhd3eb1b0_0    defaultsfonttools                 4.25.0             pyhd3eb1b0_0    defaultsfreetype                  2.10.4               hd328e21_0    defaultsfsspec                    2021.7.0           pyhd3eb1b0_0    defaultsfuture                    0.18.2                   py38_1    defaultsget_terminal_size         1.0.0                h38e98db_0    defaultsgevent                    21.8.0           py38h2bbff1b_1    defaultsgiflib                    5.2.1                h62dcd97_0    defaultsglob2                     0.7                pyhd3eb1b0_0    defaultsgmpy2                     2.0.8            py38h7edee0f_3    defaultsgreenlet                  1.1.0            py38hd77b12b_0    defaultsh5py                      2.10.0           py38h5e291fa_0    defaultshdf5                      1.10.4               h7ebc959_0    defaultsheapdict                  1.0.1                      py_0    defaultshtml5lib                  1.1                        py_0    defaultsicc_rt                    2019.0.0             h0cc432a_1    defaultsicu                       58.2                 ha925a31_3    defaultsidna                      2.10               pyhd3eb1b0_0    defaultsimagecodecs               2021.6.8         py38h5da4933_0    defaultsimageio                   2.9.0              pyhd3eb1b0_0    defaultsimagesize                 1.2.0              pyhd3eb1b0_0    defaultsimportlib-metadata        3.10.0           py38haa95532_0    defaultsimportlib_metadata        3.10.0               hd3eb1b0_0    defaultsinflection                0.5.1            py38haa95532_0    defaultsiniconfig                 1.1.1              pyhd3eb1b0_0    defaultsintel-openmp              2021.3.0          haa95532_3372    defaultsintervaltree              3.1.0                      py_0    defaultsipykernel                 5.3.4            py38h5ca1d4c_0    defaultsipython                   7.26.0           py38hd4e2768_0    defaultsipython_genutils          0.2.0              pyhd3eb1b0_1    defaultsipywidgets                7.6.3              pyhd3eb1b0_1    defaultsisort                     5.9.2              pyhd3eb1b0_0    defaultsitsdangerous              2.0.1              pyhd3eb1b0_0    defaultsjdcal                     1.4.1                      py_0    defaultsjedi                      0.17.2           py38haa95532_1    defaultsjinja2                    2.11.3             pyhd3eb1b0_0    defaultsjinja2-time               0.2.0              pyhd3eb1b0_2    defaultsjoblib                    1.0.1              pyhd3eb1b0_0    defaultsjpeg                      9b                   hb83a4c4_2    defaultsjson5                     0.9.6              pyhd3eb1b0_0    defaultsjsonschema                3.2.0                      py_2    defaultsjupyter                   1.0.0                    py38_7    defaultsjupyter_client            6.1.12             pyhd3eb1b0_0    defaultsjupyter_console           6.4.0              pyhd3eb1b0_0    defaultsjupyter_core              4.7.1            py38haa95532_0    defaultsjupyter_server            1.4.1            py38haa95532_0    defaultsjupyterlab                3.1.4              pyhd3eb1b0_0    defaultsjupyterlab_pygments       0.1.2                      py_0    defaultsjupyterlab_server         2.6.2              pyhd3eb1b0_0    defaultsjupyterlab_widgets        1.0.0              pyhd3eb1b0_1    defaultskeyring                   23.0.1           py38haa95532_0    defaultskiwisolver                1.3.1            py38hd77b12b_0    defaultskrb5                      1.19.2               h5b6d351_0    defaultslazy-object-proxy         1.6.0            py38h2bbff1b_0    defaultslcms2                     2.12                 h83e58a3_0    defaultslerc                      2.2.1                hd77b12b_0    defaultslibaec                    1.0.4                h33f27b4_1    defaultslibarchive                3.4.2                h5e25573_0    defaultslibcurl                   7.71.1               h86230a5_2    defaultslibdeflate                1.7                  h2bbff1b_5    defaultslibiconv                  1.15                 h1df5818_7    defaultsliblief                   0.10.1               ha925a31_0    defaultslibllvm9                  9.0.1                h21ff451_0    defaultslibpng                    1.6.37               h2a8f88b_0    defaultslibsodium                 1.0.18               h62dcd97_0    defaultslibspatialindex           1.9.3                h6c2663c_0    defaultslibssh2                   1.9.0                h7a1dbc1_1    defaultslibtiff                   4.2.0                hd0e1b90_0    defaultslibxml2                   2.9.12               h0ad7f3c_0    defaultslibxslt                   1.1.34               he774522_0    defaultslibzopfli                 1.0.3                ha925a31_0    defaultsllvmlite                  0.36.0           py38h34b8924_4    defaultslocket                    0.2.1            py38haa95532_1    defaultslxml                      4.6.3            py38h9b66d53_0    defaultslz4-c                     1.9.3                h2bbff1b_1    defaultslzo                       2.10                 he774522_2    defaultsm2w64-gcc-libgfortran     5.3.0                         6    defaultsm2w64-gcc-libs            5.3.0                         7    defaultsm2w64-gcc-libs-core       5.3.0                         7    defaultsm2w64-gmp                 6.1.0                         2    defaultsm2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaultsmarkupsafe                1.1.1            py38he774522_0    defaultsmatplotlib                3.4.2            py38haa95532_0    defaultsmatplotlib-base           3.4.2            py38h49ac443_0    defaultsmatplotlib-inline         0.1.2              pyhd3eb1b0_2    defaultsmccabe                    0.6.1                    py38_1    defaultsmenuinst                  1.4.16           py38he774522_1    defaultsmistune                   0.8.4           py38he774522_1000    defaultsmkl                       2021.3.0           haa95532_524    defaultsmkl-service               2.4.0            py38h2bbff1b_0    defaultsmkl_fft                   1.3.0            py38h277e83a_2    defaultsmkl_random                1.2.2            py38hf11a4ad_0    defaultsmock                      4.0.3              pyhd3eb1b0_0    defaultsmore-itertools            8.8.0              pyhd3eb1b0_0    defaultsmpc                       1.1.0                h7edee0f_1    defaultsmpfr                      4.0.2                h62dcd97_1    defaultsmpir                      3.0.0                hec2e145_1    defaultsmpmath                    1.2.1            py38haa95532_0    defaultsmsgpack-python            1.0.2            py38h59b6b97_1    defaultsmsys2-conda-epoch         20160418                      1    defaultsmultipledispatch          0.6.0                    py38_0    defaultsmunkres                   1.1.4                      py_0    defaultsmypy_extensions           0.4.3                    py38_0    defaultsmysql-connector-python    8.0.27                   pypi_0    pypinavigator-updater         0.2.1                    py38_0    defaultsnbclassic                 0.2.6              pyhd3eb1b0_0    defaultsnbclient                  0.5.3              pyhd3eb1b0_0    defaultsnbconvert                 6.1.0            py38haa95532_0    defaultsnbformat                  5.1.3              pyhd3eb1b0_0    defaultsnest-asyncio              1.5.1              pyhd3eb1b0_0    defaultsnetworkx                  2.6.2              pyhd3eb1b0_0    defaultsnltk                      3.6.2              pyhd3eb1b0_0    defaultsnose                      1.3.7           pyhd3eb1b0_1006    defaultsnotebook                  6.4.1            py38haa95532_0    defaultsnumba                     0.53.1           py38hf11a4ad_0    defaultsnumexpr                   2.7.3            py38hb80d3ca_1    defaultsnumpy                     1.20.3           py38ha4e8547_0    defaultsnumpy-base                1.20.3           py38hc2deb75_0    defaultsnumpydoc                  1.1.0              pyhd3eb1b0_1    defaultsolefile                   0.46                       py_0    defaultsopenjpeg                  2.3.0                h5ec785f_1    defaultsopenpyxl                  3.0.7              pyhd3eb1b0_0    defaultsopenssl                   1.1.1l               h2bbff1b_0    defaultspackaging                 21.0               pyhd3eb1b0_0    defaultspandas                    1.3.1            py38h6214cd6_0    defaultspandoc                    2.12                 haa95532_0    defaultspandocfilters             1.4.3            py38haa95532_1    defaultsparamiko                  2.7.2                      py_0    defaultsparso                     0.7.0                      py_0    defaultspartd                     1.2.0              pyhd3eb1b0_0    defaultspath                      16.0.0           py38haa95532_0    defaultspath.py                   12.5.0                        0    defaultspathlib2                  2.3.6            py38haa95532_2    defaultspathspec                  0.7.0                      py_0    defaultspathtools                 0.1.2                      py_1    defaultspatsy                     0.5.1                    py38_0    defaultspep8                      1.7.1                    py38_0    defaultspexpect                   4.8.0              pyhd3eb1b0_3    defaultspickleshare               0.7.5           pyhd3eb1b0_1003    defaultspillow                    8.3.1            py38h4fa10fc_0    defaultspip                       21.2.2           py38haa95532_0    defaultspkginfo                   1.7.1            py38haa95532_0    defaultspluggy                    0.13.1           py38haa95532_0    defaultsply                       3.11                     py38_0    defaultspowershell_shortcut       0.0.1                         3    defaultspoyo                      0.5.0              pyhd3eb1b0_0    defaultsprometheus_client         0.11.0             pyhd3eb1b0_0    defaultsprompt-toolkit            3.0.17             pyh06a4308_0    defaultsprompt_toolkit            3.0.17               hd3eb1b0_0    defaultspsutil                    5.8.0            py38h2bbff1b_1    defaultsptyprocess                0.7.0              pyhd3eb1b0_2    defaultspy                        1.10.0             pyhd3eb1b0_0    defaultspy-lief                   0.10.1           py38ha925a31_0    defaultspycodestyle               2.6.0              pyhd3eb1b0_0    defaultspycosat                   0.6.3            py38h2bbff1b_0    defaultspycparser                 2.20                       py_2    defaultspycurl                    7.43.0.6         py38h7a1dbc1_0    defaultspydocstyle                6.1.1              pyhd3eb1b0_0    defaultspyerfa                    2.0.0            py38h2bbff1b_0    defaultspyflakes                  2.2.0              pyhd3eb1b0_0    defaultspygments                  2.9.0              pyhd3eb1b0_0    defaultspyjwt                     2.1.0            py38haa95532_0    defaultspylint                    2.9.6            py38haa95532_1    defaultspyls-black                0.4.6                hd3eb1b0_0    defaultspyls-spyder               0.3.2              pyhd3eb1b0_0    defaultspynacl                    1.4.0            py38h62dcd97_1    defaultspyodbc                    4.0.31           py38hd77b12b_0    defaultspyopenssl                 20.0.1             pyhd3eb1b0_1    defaultspyparsing                 2.4.7              pyhd3eb1b0_0    defaultspyqt                      5.9.2            py38ha925a31_4    defaultspyreadline                2.1                      py38_1    defaultspyrsistent                0.17.3           py38he774522_0    defaultspysocks                   1.7.1            py38haa95532_0    defaultspytables                  3.6.1            py38ha5be198_0    defaultspytest                    6.2.4            py38haa95532_2    defaultspython                    3.8.8                hdbf39b2_5    defaultspython-dateutil           2.8.2              pyhd3eb1b0_0    defaultspython-jsonrpc-server     0.4.0                      py_0    defaultspython-language-server    0.36.2             pyhd3eb1b0_0    defaultspython-libarchive-c       2.9                pyhd3eb1b0_1    defaultspython-slugify            5.0.2              pyhd3eb1b0_0    defaultspytz                      2021.1             pyhd3eb1b0_0    defaultspywavelets                1.1.1            py38he774522_2    defaultspywin32                   228              py38hbaba5e8_1    defaultspywin32-ctypes            0.2.0                 py38_1000    defaultspywinpty                  0.5.7                    py38_0    defaultspyyaml                    5.4.1            py38h2bbff1b_1    defaultspyzmq                     22.2.1           py38hd77b12b_1    defaultsqdarkstyle                3.0.2              pyhd3eb1b0_0    defaultsqstylizer                 0.1.10             pyhd3eb1b0_0    defaultsqt                        5.9.7            vc14h73c81de_0    defaultsqtawesome                 1.0.2              pyhd3eb1b0_0    defaultsqtconsole                 5.1.0              pyhd3eb1b0_0    defaultsqtpy                      1.9.0                      py_0    defaultsregex                     2021.4.4         py38h2bbff1b_0    defaultsrequests                  2.25.1             pyhd3eb1b0_0    defaultsrope                      0.19.0             pyhd3eb1b0_0    defaultsrtree                     0.9.7            py38h2eaa2aa_1    defaultsruamel_yaml               0.15.100         py38h2bbff1b_0    defaultsscikit-image              0.18.1           py38hf11a4ad_0    defaultsscikit-learn              0.24.2           py38hf11a4ad_1    defaultsscipy                     1.6.2            py38h66253e8_1    defaultsseaborn                   0.11.1             pyhd3eb1b0_0    defaultssend2trash                1.5.0              pyhd3eb1b0_1    defaultssetuptools                52.0.0           py38haa95532_0    defaultssimplegeneric             0.8.1                    py38_2    defaultssingledispatch            3.6.2           pyhd3eb1b0_1001    defaultssip                       4.19.13          py38ha925a31_0    defaultssix                       1.16.0             pyhd3eb1b0_0    defaultssnappy                    1.1.8                h33f27b4_0    defaultssniffio                   1.2.0            py38haa95532_1    defaultssnowballstemmer           2.1.0              pyhd3eb1b0_0    defaultssortedcollections         2.1.0              pyhd3eb1b0_0    defaultssortedcontainers          2.4.0              pyhd3eb1b0_0    defaultssoupsieve                 2.2.1              pyhd3eb1b0_0    defaultssphinx                    4.0.2              pyhd3eb1b0_0    defaultssphinxcontrib             1.0                      py38_1    defaultssphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0    defaultssphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0    defaultssphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0    defaultssphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0    defaultssphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0    defaultssphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0    defaultssphinxcontrib-websupport  1.2.4                      py_0    defaultsspyder                    5.0.5            py38haa95532_2    defaultsspyder-kernels            2.0.5            py38haa95532_0    defaultssqlalchemy                1.4.22           py38h2bbff1b_0    defaultssqlite                    3.36.0               h2bbff1b_0    defaultsstatsmodels               0.12.2           py38h2bbff1b_0    defaultssympy                     1.8              py38haa95532_0    defaultstbb                       2020.3               h74a9793_0    defaultstblib                     1.7.0                      py_0    defaultsterminado                 0.9.4            py38haa95532_0    defaultstestpath                  0.5.0              pyhd3eb1b0_0    defaultstext-unidecode            1.3                        py_0    defaultstextdistance              4.2.1              pyhd3eb1b0_0    defaultsthreadpoolctl             2.2.0              pyhb85f177_0    defaultsthree-merge               0.1.1              pyhd3eb1b0_0    defaultstifffile                  2021.7.2           pyhd3eb1b0_2    defaultstinycss                   0.4             pyhd3eb1b0_1002    defaultstk                        8.6.10               he774522_0    defaultstoml                      0.10.2             pyhd3eb1b0_0    defaultstoolz                     0.11.1             pyhd3eb1b0_0    defaultstornado                   6.1              py38h2bbff1b_0    defaultstqdm                      4.62.0             pyhd3eb1b0_1    defaultstraitlets                 5.0.5              pyhd3eb1b0_0    defaultstyped-ast                 1.4.3            py38h2bbff1b_1    defaultstyping_extensions         3.10.0.0           pyh06a4308_0    defaultsujson                     4.0.2            py38hd77b12b_0    defaultsunicodecsv                0.14.1                   py38_0    defaultsunidecode                 1.2.0              pyhd3eb1b0_0    defaultsurllib3                   1.26.6             pyhd3eb1b0_1    defaultsvc                        14.2                 h21ff451_1    defaultsvs2015_runtime            14.27.29016          h5e58377_2    defaultswatchdog                  2.1.3            py38haa95532_0    defaultswcwidth                   0.2.5                      py_0    defaultswebencodings              0.5.1                    py38_1    defaultswerkzeug                  1.0.1              pyhd3eb1b0_0    defaultswheel                     0.36.2             pyhd3eb1b0_0    defaultswhichcraft                0.6.1              pyhd3eb1b0_0    defaultswidgetsnbextension        3.5.1                    py38_0    defaultswin_inet_pton             1.1.0            py38haa95532_0    defaultswin_unicode_console       0.5                      py38_0    defaultswincertstore              0.2                      py38_0    defaultswinpty                    0.4.3                         4    defaultswrapt                     1.12.1           py38he774522_1    defaultsxlrd                      2.0.1              pyhd3eb1b0_0    defaultsxlsxwriter                1.4.4              pyhd3eb1b0_0    defaultsxlwings                   0.24.6           py38haa95532_0    defaultsxlwt                      1.3.0                    py38_0    defaultsxmltodict                 0.12.0                     py_0    defaultsxz                        5.2.5                h62dcd97_0    defaultsyaml                      0.2.5                he774522_0    defaultsyapf                      0.31.0             pyhd3eb1b0_0    defaultszeromq                    4.3.4                hd77b12b_0    defaultszfp                       0.5.5                hd77b12b_6    defaultszict                      2.0.0              pyhd3eb1b0_0    defaultszipp                      3.5.0              pyhd3eb1b0_0    defaultszlib                      1.2.11               h62dcd97_4    defaultszope                      1.0                      py38_1    defaultszope.event                4.5.0                    py38_0    defaultszope.interface            5.4.0            py38h2bbff1b_0    defaultszstd                      1.4.9                h19a0ad4_0    defaults

Hope it'll help !
Thanks in advance
Best regards, M. GUITARIAN Guillaume
07.70.01.66.42 

    Le vendredi 19 novembre 2021, 15:55:27 UTC+1, yshmatov-anaconda ***@***.***> a écrit :  
 
 


Thanks for leaving bug report!

I'm currently trying to replicate your issue, but whatever I try - Navigator closes with no problems.

Could you, please, provide more details on the issue?
   
   - Do you have this issue every time you open Jupyter Lab, or is it only occasional?
   - Does this issue occur only with Jupyter Lab, or is it also applies to other applications (e.g. Jupyter Notebook, IPython Qt Console)?
   - Do you select to close Jupyter Lab in the "close running applications" dialog?
   - How long do you wait between opening Jupyter Lab and closing the Navigator?
   - Could you also, please, provide conda list --show-channel-urls of the base environment where the Navigator is installed?

You could also disable a "Close running applications" by checking "Hide running applications dialog" in the preferences.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ImRobot777** [comment]
Hi,
Just for your information, it happens each day when anaconda navigator and jupyter lab are open during several hours.
Best regards, M. GUITARIAN Guillaume
07.70.01.66.42 

    Le vendredi 19 novembre 2021, 17:42:36 UTC+1, GUITARIAN Guillaume ***@***.***> a écrit :  
 
 Hi, 
   
   - Do you have this issue every time you open Jupyter Lab, or is it only occasional?
   - Does this issue occur only with Jupyter Lab, or is it also applies to other applications (e.g. Jupyter Notebook, IPython Qt Console)?
   - How long do you wait between opening Jupyter Lab and closing the Navigator?

 Sorry i should have given the details, so most of the time there is no problem, but when a heavy notbook (jupiterlab + jupyter notbook) had run during the day, and i want to close navigator at the end of the day, then the close button does not work, i have to kill the python process in order make the navigator window close (force disappearing).


   
   - Do you select to close Jupyter Lab in the "close running applications" dialog?
Both, when selected or not 

   
   - Could you also, please, provide conda list --show-channel-urls of the base environment where the Navigator is installed?

(base) C:\Users\conra>conda list --show-channel-urls# packages in environment at C:\Users\conra\anaconda3:## Name                    Version                   Build  Channel_anaconda_depends         2020.07                  py38_0    defaults_ipyw_jlab_nb_ext_conf    0.1.0                    py38_0    defaultsalabaster                 0.7.12             pyhd3eb1b0_0    defaultsanaconda                  custom                   py38_1    defaultsanaconda-client           1.8.0            py38haa95532_0    defaultsanaconda-navigator        2.1.1                    py38_0    defaultsanaconda-project          0.10.1             pyhd3eb1b0_0    defaultsanyio                     2.2.0            py38haa95532_2    defaultsappdirs                   1.4.4                      py_0    defaultsargh                      0.26.2                   py38_0    defaultsargon2-cffi               20.1.0           py38h2bbff1b_1    defaultsarrow                     0.13.1                   py38_0    defaultsasn1crypto                1.4.0                      py_0    defaultsastroid                   2.6.6            py38haa95532_0    defaultsastropy                   4.3.post1        py38h080aedc_1    defaultsasync_generator           1.10               pyhd3eb1b0_0    defaultsatomicwrites              1.4.0                      py_0    defaultsattrs                     21.2.0             pyhd3eb1b0_0    defaultsautopep8                  1.5.6              pyhd3eb1b0_0    defaultsbabel                     2.9.1              pyhd3eb1b0_0    defaultsbackcall                  0.2.0              pyhd3eb1b0_0    defaultsbackports                 1.0                pyhd3eb1b0_2    defaultsbackports.functools_lru_cache 1.6.4              pyhd3eb1b0_0    defaultsbackports.shutil_get_terminal_size 1.0.0              pyhd3eb1b0_3    defaultsbackports.tempfile        1.0                pyhd3eb1b0_1    defaultsbackports.weakref         1.0.post1                  py_1    defaultsbcrypt                    3.2.0            py38he774522_0    defaultsbeautifulsoup4            4.9.3              pyha847dfd_0    defaultsbinaryornot               0.4.4              pyhd3eb1b0_1    defaultsbitarray                  2.2.3            py38h2bbff1b_1    defaultsbkcharts                  0.2                      py38_0    defaultsblack                     19.10b0                    py_0    defaultsblas                      1.0                         mkl    defaultsbleach                    4.0.0              pyhd3eb1b0_0    defaultsblosc                     1.21.0               h19a0ad4_0    defaultsbokeh                     2.3.3            py38haa95532_0    defaultsboto                      2.49.0                   py38_0    defaultsbottleneck                1.3.2            py38h2a96729_1    defaultsbrotli                    1.0.9                ha925a31_2    defaultsbrotlipy                  0.7.0           py38h2bbff1b_1003    defaultsbzip2                     1.0.8                he774522_0    defaultsca-certificates           2021.10.26           haa95532_2    defaultscertifi                   2021.10.8        py38haa95532_0    defaultscffi                      1.14.6           py38h2bbff1b_0    defaultscfitsio                   3.470                he774522_6    defaultschardet                   4.0.0           py38haa95532_1003    defaultscharls                    2.2.0                h6c2663c_0    defaultsclick                     8.0.1              pyhd3eb1b0_0    defaultscloudpickle               1.6.0                      py_0    defaultsclyent                    1.2.2                    py38_1    defaultscolorama                  0.4.4              pyhd3eb1b0_0    defaultscomtypes                  1.1.10          py38haa95532_1002    defaultsconda                     4.10.3           py38haa95532_0    defaultsconda-build               3.21.4           py38haa95532_0    defaultsconda-content-trust       0.1.1              pyhd3eb1b0_0    defaultsconda-env                 2.6.0                         1    defaultsconda-pack                0.6.0              pyhd3eb1b0_0    defaultsconda-package-handling    1.7.3            py38h8cc25b3_1    defaultsconda-repo-cli            1.0.4              pyhd3eb1b0_0    defaultsconda-token               0.3.0              pyhd3eb1b0_0    defaultsconda-verify              3.4.2                      py_1    defaultsconsole_shortcut          0.1.1                         4    defaultscontextlib2               0.6.0.post1                py_0    defaultscookiecutter              1.7.2              pyhd3eb1b0_0    defaultscryptography              3.4.7            py38h71e12ea_0    defaultscurl                      7.71.1               h86230a5_2    defaultscycler                    0.10.0                   py38_0    defaultscython                    0.29.24          py38hd77b12b_0    defaultscytoolz                   0.11.0           py38he774522_0    defaultsdask                      2021.7.2           pyhd3eb1b0_0    defaultsdask-core                 2021.7.2           pyhd3eb1b0_0    defaultsdecorator                 5.0.9              pyhd3eb1b0_0    defaultsdefusedxml                0.7.1              pyhd3eb1b0_0    defaultsdiff-match-patch          20200713                   py_0    defaultsdistributed               2021.7.2         py38haa95532_0    defaultsdocutils                  0.17.1           py38haa95532_1    defaultsentrypoints               0.3                      py38_0    defaultset_xmlfile                1.1.0            py38haa95532_0    defaultsfastcache                 1.1.0            py38he774522_0    defaultsfilelock                  3.0.12             pyhd3eb1b0_1    defaultsflake8                    3.9.0              pyhd3eb1b0_0    defaultsflask                     1.1.2              pyhd3eb1b0_0    defaultsfonttools                 4.25.0             pyhd3eb1b0_0    defaultsfreetype                  2.10.4               hd328e21_0    defaultsfsspec                    2021.7.0           pyhd3eb1b0_0    defaultsfuture                    0.18.2                   py38_1    defaultsget_terminal_size         1.0.0                h38e98db_0    defaultsgevent                    21.8.0           py38h2bbff1b_1    defaultsgiflib                    5.2.1                h62dcd97_0    defaultsglob2                     0.7                pyhd3eb1b0_0    defaultsgmpy2                     2.0.8            py38h7edee0f_3    defaultsgreenlet                  1.1.0            py38hd77b12b_0    defaultsh5py                      2.10.0           py38h5e291fa_0    defaultshdf5                      1.10.4               h7ebc959_0    defaultsheapdict                  1.0.1                      py_0    defaultshtml5lib                  1.1                        py_0    defaultsicc_rt                    2019.0.0             h0cc432a_1    defaultsicu                       58.2                 ha925a31_3    defaultsidna                      2.10               pyhd3eb1b0_0    defaultsimagecodecs               2021.6.8         py38h5da4933_0    defaultsimageio                   2.9.0              pyhd3eb1b0_0    defaultsimagesize                 1.2.0              pyhd3eb1b0_0    defaultsimportlib-metadata        3.10.0           py38haa95532_0    defaultsimportlib_metadata        3.10.0               hd3eb1b0_0    defaultsinflection                0.5.1            py38haa95532_0    defaultsiniconfig                 1.1.1              pyhd3eb1b0_0    defaultsintel-openmp              2021.3.0          haa95532_3372    defaultsintervaltree              3.1.0                      py_0    defaultsipykernel                 5.3.4            py38h5ca1d4c_0    defaultsipython                   7.26.0           py38hd4e2768_0    defaultsipython_genutils          0.2.0              pyhd3eb1b0_1    defaultsipywidgets                7.6.3              pyhd3eb1b0_1    defaultsisort                     5.9.2              pyhd3eb1b0_0    defaultsitsdangerous              2.0.1              pyhd3eb1b0_0    defaultsjdcal                     1.4.1                      py_0    defaultsjedi                      0.17.2           py38haa95532_1    defaultsjinja2                    2.11.3             pyhd3eb1b0_0    defaultsjinja2-time               0.2.0              pyhd3eb1b0_2    defaultsjoblib                    1.0.1              pyhd3eb1b0_0    defaultsjpeg                      9b                   hb83a4c4_2    defaultsjson5                     0.9.6              pyhd3eb1b0_0    defaultsjsonschema                3.2.0                      py_2    defaultsjupyter                   1.0.0                    py38_7    defaultsjupyter_client            6.1.12             pyhd3eb1b0_0    defaultsjupyter_console           6.4.0              pyhd3eb1b0_0    defaultsjupyter_core              4.7.1            py38haa95532_0    defaultsjupyter_server            1.4.1            py38haa95532_0    defaultsjupyterlab                3.1.4              pyhd3eb1b0_0    defaultsjupyterlab_pygments       0.1.2                      py_0    defaultsjupyterlab_server         2.6.2              pyhd3eb1b0_0    defaultsjupyterlab_widgets        1.0.0              pyhd3eb1b0_1    defaultskeyring                   23.0.1           py38haa95532_0    defaultskiwisolver                1.3.1            py38hd77b12b_0    defaultskrb5                      1.19.2               h5b6d351_0    defaultslazy-object-proxy         1.6.0            py38h2bbff1b_0    defaultslcms2                     2.12                 h83e58a3_0    defaultslerc                      2.2.1                hd77b12b_0    defaultslibaec                    1.0.4                h33f27b4_1    defaultslibarchive                3.4.2                h5e25573_0    defaultslibcurl                   7.71.1               h86230a5_2    defaultslibdeflate                1.7                  h2bbff1b_5    defaultslibiconv                  1.15                 h1df5818_7    defaultsliblief                   0.10.1               ha925a31_0    defaultslibllvm9                  9.0.1                h21ff451_0    defaultslibpng                    1.6.37               h2a8f88b_0    defaultslibsodium                 1.0.18               h62dcd97_0    defaultslibspatialindex           1.9.3                h6c2663c_0    defaultslibssh2                   1.9.0                h7a1dbc1_1    defaultslibtiff                   4.2.0                hd0e1b90_0    defaultslibxml2                   2.9.12               h0ad7f3c_0    defaultslibxslt                   1.1.34               he774522_0    defaultslibzopfli                 1.0.3                ha925a31_0    defaultsllvmlite                  0.36.0           py38h34b8924_4    defaultslocket                    0.2.1            py38haa95532_1    defaultslxml                      4.6.3            py38h9b66d53_0    defaultslz4-c                     1.9.3                h2bbff1b_1    defaultslzo                       2.10                 he774522_2    defaultsm2w64-gcc-libgfortran     5.3.0                         6    defaultsm2w64-gcc-libs            5.3.0                         7    defaultsm2w64-gcc-libs-core       5.3.0                         7    defaultsm2w64-gmp                 6.1.0                         2    defaultsm2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaultsmarkupsafe                1.1.1            py38he774522_0    defaultsmatplotlib                3.4.2            py38haa95532_0    defaultsmatplotlib-base           3.4.2            py38h49ac443_0    defaultsmatplotlib-inline         0.1.2              pyhd3eb1b0_2    defaultsmccabe                    0.6.1                    py38_1    defaultsmenuinst                  1.4.16           py38he774522_1    defaultsmistune                   0.8.4           py38he774522_1000    defaultsmkl                       2021.3.0           haa95532_524    defaultsmkl-service               2.4.0            py38h2bbff1b_0    defaultsmkl_fft                   1.3.0            py38h277e83a_2    defaultsmkl_random                1.2.2            py38hf11a4ad_0    defaultsmock                      4.0.3              pyhd3eb1b0_0    defaultsmore-itertools            8.8.0              pyhd3eb1b0_0    defaultsmpc                       1.1.0                h7edee0f_1    defaultsmpfr                      4.0.2                h62dcd97_1    defaultsmpir                      3.0.0                hec2e145_1    defaultsmpmath                    1.2.1            py38haa95532_0    defaultsmsgpack-python            1.0.2            py38h59b6b97_1    defaultsmsys2-conda-epoch         20160418                      1    defaultsmultipledispatch          0.6.0                    py38_0    defaultsmunkres                   1.1.4                      py_0    defaultsmypy_extensions           0.4.3                    py38_0    defaultsmysql-connector-python    8.0.27                   pypi_0    pypinavigator-updater         0.2.1                    py38_0    defaultsnbclassic                 0.2.6              pyhd3eb1b0_0    defaultsnbclient                  0.5.3              pyhd3eb1b0_0    defaultsnbconvert                 6.1.0            py38haa95532_0    defaultsnbformat                  5.1.3              pyhd3eb1b0_0    defaultsnest-asyncio              1.5.1              pyhd3eb1b0_0    defaultsnetworkx                  2.6.2              pyhd3eb1b0_0    defaultsnltk                      3.6.2              pyhd3eb1b0_0    defaultsnose                      1.3.7           pyhd3eb1b0_1006    defaultsnotebook                  6.4.1            py38haa95532_0    defaultsnumba                     0.53.1           py38hf11a4ad_0    defaultsnumexpr                   2.7.3            py38hb80d3ca_1    defaultsnumpy                     1.20.3           py38ha4e8547_0    defaultsnumpy-base                1.20.3           py38hc2deb75_0    defaultsnumpydoc                  1.1.0              pyhd3eb1b0_1    defaultsolefile                   0.46                       py_0    defaultsopenjpeg                  2.3.0                h5ec785f_1    defaultsopenpyxl                  3.0.7              pyhd3eb1b0_0    defaultsopenssl                   1.1.1l               h2bbff1b_0    defaultspackaging                 21.0               pyhd3eb1b0_0    defaultspandas                    1.3.1            py38h6214cd6_0    defaultspandoc                    2.12                 haa95532_0    defaultspandocfilters             1.4.3            py38haa95532_1    defaultsparamiko                  2.7.2                      py_0    defaultsparso                     0.7.0                      py_0    defaultspartd                     1.2.0              pyhd3eb1b0_0    defaultspath                      16.0.0           py38haa95532_0    defaultspath.py                   12.5.0                        0    defaultspathlib2                  2.3.6            py38haa95532_2    defaultspathspec                  0.7.0                      py_0    defaultspathtools                 0.1.2                      py_1    defaultspatsy                     0.5.1                    py38_0    defaultspep8                      1.7.1                    py38_0    defaultspexpect                   4.8.0              pyhd3eb1b0_3    defaultspickleshare               0.7.5           pyhd3eb1b0_1003    defaultspillow                    8.3.1            py38h4fa10fc_0    defaultspip                       21.2.2           py38haa95532_0    defaultspkginfo                   1.7.1            py38haa95532_0    defaultspluggy                    0.13.1           py38haa95532_0    defaultsply                       3.11                     py38_0    defaultspowershell_shortcut       0.0.1                         3    defaultspoyo                      0.5.0              pyhd3eb1b0_0    defaultsprometheus_client         0.11.0             pyhd3eb1b0_0    defaultsprompt-toolkit            3.0.17             pyh06a4308_0    defaultsprompt_toolkit            3.0.17               hd3eb1b0_0    defaultspsutil                    5.8.0            py38h2bbff1b_1    defaultsptyprocess                0.7.0              pyhd3eb1b0_2    defaultspy                        1.10.0             pyhd3eb1b0_0    defaultspy-lief                   0.10.1           py38ha925a31_0    defaultspycodestyle               2.6.0              pyhd3eb1b0_0    defaultspycosat                   0.6.3            py38h2bbff1b_0    defaultspycparser                 2.20                       py_2    defaultspycurl                    7.43.0.6         py38h7a1dbc1_0    defaultspydocstyle                6.1.1              pyhd3eb1b0_0    defaultspyerfa                    2.0.0            py38h2bbff1b_0    defaultspyflakes                  2.2.0              pyhd3eb1b0_0    defaultspygments                  2.9.0              pyhd3eb1b0_0    defaultspyjwt                     2.1.0            py38haa95532_0    defaultspylint                    2.9.6            py38haa95532_1    defaultspyls-black                0.4.6                hd3eb1b0_0    defaultspyls-spyder               0.3.2              pyhd3eb1b0_0    defaultspynacl                    1.4.0            py38h62dcd97_1    defaultspyodbc                    4.0.31           py38hd77b12b_0    defaultspyopenssl                 20.0.1             pyhd3eb1b0_1    defaultspyparsing                 2.4.7              pyhd3eb1b0_0    defaultspyqt                      5.9.2            py38ha925a31_4    defaultspyreadline                2.1                      py38_1    defaultspyrsistent                0.17.3           py38he774522_0    defaultspysocks                   1.7.1            py38haa95532_0    defaultspytables                  3.6.1            py38ha5be198_0    defaultspytest                    6.2.4            py38haa95532_2    defaultspython                    3.8.8                hdbf39b2_5    defaultspython-dateutil           2.8.2              pyhd3eb1b0_0    defaultspython-jsonrpc-server     0.4.0                      py_0    defaultspython-language-server    0.36.2             pyhd3eb1b0_0    defaultspython-libarchive-c       2.9                pyhd3eb1b0_1    defaultspython-slugify            5.0.2              pyhd3eb1b0_0    defaultspytz                      2021.1             pyhd3eb1b0_0    defaultspywavelets                1.1.1            py38he774522_2    defaultspywin32                   228              py38hbaba5e8_1    defaultspywin32-ctypes            0.2.0                 py38_1000    defaultspywinpty                  0.5.7                    py38_0    defaultspyyaml                    5.4.1            py38h2bbff1b_1    defaultspyzmq                     22.2.1           py38hd77b12b_1    defaultsqdarkstyle                3.0.2              pyhd3eb1b0_0    defaultsqstylizer                 0.1.10             pyhd3eb1b0_0    defaultsqt                        5.9.7            vc14h73c81de_0    defaultsqtawesome                 1.0.2              pyhd3eb1b0_0    defaultsqtconsole                 5.1.0              pyhd3eb1b0_0    defaultsqtpy                      1.9.0                      py_0    defaultsregex                     2021.4.4         py38h2bbff1b_0    defaultsrequests                  2.25.1             pyhd3eb1b0_0    defaultsrope                      0.19.0             pyhd3eb1b0_0    defaultsrtree                     0.9.7            py38h2eaa2aa_1    defaultsruamel_yaml               0.15.100         py38h2bbff1b_0    defaultsscikit-image              0.18.1           py38hf11a4ad_0    defaultsscikit-learn              0.24.2           py38hf11a4ad_1    defaultsscipy                     1.6.2            py38h66253e8_1    defaultsseaborn                   0.11.1             pyhd3eb1b0_0    defaultssend2trash                1.5.0              pyhd3eb1b0_1    defaultssetuptools                52.0.0           py38haa95532_0    defaultssimplegeneric             0.8.1                    py38_2    defaultssingledispatch            3.6.2           pyhd3eb1b0_1001    defaultssip                       4.19.13          py38ha925a31_0    defaultssix                       1.16.0             pyhd3eb1b0_0    defaultssnappy                    1.1.8                h33f27b4_0    defaultssniffio                   1.2.0            py38haa95532_1    defaultssnowballstemmer           2.1.0              pyhd3eb1b0_0    defaultssortedcollections         2.1.0              pyhd3eb1b0_0    defaultssortedcontainers          2.4.0              pyhd3eb1b0_0    defaultssoupsieve                 2.2.1              pyhd3eb1b0_0    defaultssphinx                    4.0.2              pyhd3eb1b0_0    defaultssphinxcontrib             1.0                      py38_1    defaultssphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0    defaultssphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0    defaultssphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0    defaultssphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0    defaultssphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0    defaultssphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0    defaultssphinxcontrib-websupport  1.2.4                      py_0    defaultsspyder                    5.0.5            py38haa95532_2    defaultsspyder-kernels            2.0.5            py38haa95532_0    defaultssqlalchemy                1.4.22           py38h2bbff1b_0    defaultssqlite                    3.36.0               h2bbff1b_0    defaultsstatsmodels               0.12.2           py38h2bbff1b_0    defaultssympy                     1.8              py38haa95532_0    defaultstbb                       2020.3               h74a9793_0    defaultstblib                     1.7.0                      py_0    defaultsterminado                 0.9.4            py38haa95532_0    defaultstestpath                  0.5.0              pyhd3eb1b0_0    defaultstext-unidecode            1.3                        py_0    defaultstextdistance              4.2.1              pyhd3eb1b0_0    defaultsthreadpoolctl             2.2.0              pyhb85f177_0    defaultsthree-merge               0.1.1              pyhd3eb1b0_0    defaultstifffile                  2021.7.2           pyhd3eb1b0_2    defaultstinycss                   0.4             pyhd3eb1b0_1002    defaultstk                        8.6.10               he774522_0    defaultstoml                      0.10.2             pyhd3eb1b0_0    defaultstoolz                     0.11.1             pyhd3eb1b0_0    defaultstornado                   6.1              py38h2bbff1b_0    defaultstqdm                      4.62.0             pyhd3eb1b0_1    defaultstraitlets                 5.0.5              pyhd3eb1b0_0    defaultstyped-ast                 1.4.3            py38h2bbff1b_1    defaultstyping_extensions         3.10.0.0           pyh06a4308_0    defaultsujson                     4.0.2            py38hd77b12b_0    defaultsunicodecsv                0.14.1                   py38_0    defaultsunidecode                 1.2.0              pyhd3eb1b0_0    defaultsurllib3                   1.26.6             pyhd3eb1b0_1    defaultsvc                        14.2                 h21ff451_1    defaultsvs2015_runtime            14.27.29016          h5e58377_2    defaultswatchdog                  2.1.3            py38haa95532_0    defaultswcwidth                   0.2.5                      py_0    defaultswebencodings              0.5.1                    py38_1    defaultswerkzeug                  1.0.1              pyhd3eb1b0_0    defaultswheel                     0.36.2             pyhd3eb1b0_0    defaultswhichcraft                0.6.1              pyhd3eb1b0_0    defaultswidgetsnbextension        3.5.1                    py38_0    defaultswin_inet_pton             1.1.0            py38haa95532_0    defaultswin_unicode_console       0.5                      py38_0    defaultswincertstore              0.2                      py38_0    defaultswinpty                    0.4.3                         4    defaultswrapt                     1.12.1           py38he774522_1    defaultsxlrd                      2.0.1              pyhd3eb1b0_0    defaultsxlsxwriter                1.4.4              pyhd3eb1b0_0    defaultsxlwings                   0.24.6           py38haa95532_0    defaultsxlwt                      1.3.0                    py38_0    defaultsxmltodict                 0.12.0                     py_0    defaultsxz                        5.2.5                h62dcd97_0    defaultsyaml                      0.2.5                he774522_0    defaultsyapf                      0.31.0             pyhd3eb1b0_0    defaultszeromq                    4.3.4                hd77b12b_0    defaultszfp                       0.5.5                hd77b12b_6    defaultszict                      2.0.0              pyhd3eb1b0_0    defaultszipp                      3.5.0              pyhd3eb1b0_0    defaultszlib                      1.2.11               h62dcd97_4    defaultszope                      1.0                      py38_1    defaultszope.event                4.5.0                    py38_0    defaultszope.interface            5.4.0            py38h2bbff1b_0    defaultszstd                      1.4.9                h19a0ad4_0    defaults

Hope it'll help !
Thanks in advance
Best regards, M. GUITARIAN Guillaume
07.70.01.66.42 

    Le vendredi 19 novembre 2021, 15:55:27 UTC+1, yshmatov-anaconda ***@***.***> a écrit :  
 
 


Thanks for leaving bug report!

I'm currently trying to replicate your issue, but whatever I try - Navigator closes with no problems.

Could you, please, provide more details on the issue?
   
   - Do you have this issue every time you open Jupyter Lab, or is it only occasional?
   - Does this issue occur only with Jupyter Lab, or is it also applies to other applications (e.g. Jupyter Notebook, IPython Qt Console)?
   - Do you select to close Jupyter Lab in the "close running applications" dialog?
   - How long do you wait between opening Jupyter Lab and closing the Navigator?
   - Could you also, please, provide conda list --show-channel-urls of the base environment where the Navigator is installed?

You could also disable a "Close running applications" by checking "Hide running applications dialog" in the preferences.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yshmatov-anaconda** [comment]
Thanks for the details!

We are working on a solution to this problem. We will post an update when the fix is ready and available.

Current workarounds I could think of before the fix is ready:
- close the Navigator right after launching the Jupyter, but don't close it in Navigator running application dialogs. You should still be able to close Jupyter in it's web interface.
- downgrade to Navigator 2.1.0 (with `conda install anaconda-navigator=2.1.0` in the base environment).

**Comment by ImRobot777** [comment]
Hi,
Thanks for the workarounds and good luck in fixing this issue.
Have a nice day,
Best regards, M. GUITARIAN Guillaume
07.70.01.66.42 

    Le jeudi 25 novembre 2021, 15:33:43 UTC+1, yshmatov-anaconda ***@***.***> a écrit :  
 
 


Thanks for the details!

We are working on a solution to this problem. We will post an update when the fix is ready and available.

Current workarounds I could think of before the fix is ready:
   
   - close the Navigator right after launching the Jupyter, but don't close it in Navigator running application dialogs. You should still be able to close Jupyter in it's web interface.
   - downgrade to Navigator 2.1.0 (with conda install anaconda-navigator=2.1.0 in the base environment).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sandro-byte32** [comment]
i have also problems closing anaconda.
But that's not related with Jupyter

**Comment by ItaruKaneko** [comment]
I have same problem. I can collaborate to repeat problem and confirm phenomenon after fix.
But it is small problem for me. So please do not feel pressure.

**Comment by kchong75** [comment]
I have the same issue with **Anaconda Navigator on windows10**.
I launched **Jupyter Notebook** through **Anaconda Navigator** and run some python3 scripts.
After that, in **Jupyter Notebook**, I shut down all running notebooks -> clicked quit in Jupyter notebook -> closed my browser.
Then in **Anaconda Navigator**, I click close, and it gets stuck there forever.
I checked task manager, it shows still running python under **anaconda navigator**, which is kind of strange because I think I have already done everything I could to make sure no python files are running.
And, I also failed to re-launch **Jupyter Notebook** in the **Anaconda Navigator** which can't be closed. I need to manually shut down the running python in the task manager.

**Comment by Slepetys** [comment]
I have the same issue. THe Quit application does not quit, after hitting the YES.

**Comment by Arielcchy** [comment]
I have the same issue when anaconda navigator and jupyter are open several hours. I can only shut navigator down through task manager (python app). Anaconda Navigator version 2.1.1
Look forward to the solution. thx.

**Comment by Plitz** [comment]
I also have the same problem and do not use jupyter. Shut down is only possible through task manager.
The problem did not appear with previous (< 2.1.1) versions.

**Comment by beezerlm** [comment]
I have the same issue running Windows 11 and  Anaconda Navigator version 2.1.1
New PC so everything is a fresh install.

**Comment by Plitz** [comment]
I just tried to open anaconda, start spyder, close spyder, exit ananda within minutes, no problem!

**Comment by ImRobot777** [comment]
> I just tried to open anaconda, start spyder, close spyder, exit ananda within minutes, no problem!

Hi,
Yes if you try closing anaconda navigator within minuts it's OK, but if you're trying to close it after some hours it's KO

**Comment by Plitz** [comment]
Now, I opened anaconda, started spyder, after 1 hour I closed spyder, exit anaconda, no problem!

**Comment by ImRobot777** [comment]
> Now, I opened anaconda, started spyder, after 1 hour I closed spyder, exit anaconda, no problem!

I do not know the exact limit LOL but there is one that must depend on our different setups, whatever, when closing right after having opened it, closing anaconda works, if i do the same at the end of my working day it fails closing

**Comment by CheeseMochi** [comment]
Thanks for the report, the feedback, and quick responses. The next release of Navigator, coming soon, includes a fix for a very similar issue: failing to close after being open for hours. We'll drop an update in here when it's available.

**Comment by Stas-Medvedev** [comment]
Same issue as some of the others are having:
- Launch Anaconda Navigator 2.1.1
- Launch Jupyter Notebook 6.4.8
- They stay open most of the workday
- Stop kernels and close notebooks
- Close browser
- Attempt to quit Anaconda Navigator
- Dialog pops up asking if I want to close "notebook" as well
- Checking or not checking it makes no difference, and pressing the "Quit" button does nothing.

One more thing to add: if I then try to re-launch Jupyter Notebook or press the refresh button in the top right corner under "Connect", I get the loading animation in the bottom left corner that never stops.

Thank you!

**Comment by Plitz** [comment]
Now, I opened anaconda, started spyder, after **9** hours (without any activity) I closed spyder, exit anaconda not possible, need to use task manager!

**Comment by ImRobot777** [comment]
> Now, I opened anaconda, started spyder, after **9** hours (without any activity) I closed spyder, exit anaconda not possible, need to use task manager!

try 8 hours, then 7, then 6... there is maybe a time limit in the anaconda navigator source code ;-)

**Comment by ItaruKaneko** [comment]
Same as me. It is OK in 10 mintus. May go wrong after 1 day.

**Comment by CheeseMochi** [comment]
There's a new version of Navigator available, 2.1.2, which should resolve this issue. Can you give that a try and see if it helps?

Release notes, for reference: https://docs.anaconda.com/anaconda/navigator/release-notes/ 
"Addressed issue where Navigator would not close after being open for several hours"

**Comment by Slepetys** [comment]
I tried to download it, but only the previous version was available
(2011.11), so the problem remains.

Roberto Slepetys

**Comment by beezerlm** [comment]
I updated to 2.1.2 opened anaconda for about 20hrs and it shut down just fine.  I did not actually use anything in the navigator though.  Just opened it and let it sit.

**Comment by ItaruKaneko** [comment]
> There's a new version of Navigator available, 2.1.2, which should resolve this issue. Can you give that a try and see if it helps?
> 
> Release notes, for reference: https://docs.anaconda.com/anaconda/navigator/release-notes/ "Addressed issue where Navigator would not close after being open for several hours"

I had updated 2.1.2. I'll report if phenomenon repeated. Unless report, feel happy.

**Comment by Heidelberger** [comment]
> There's a new version of Navigator available, 2.1.2, which should resolve this issue. Can you give that a try and see if it helps?
> 
> Release notes, for reference: https://docs.anaconda.com/anaconda/navigator/release-notes/ "Addressed issue where Navigator would not close after being open for several hours"

I spent 1 day working with 2.1.2.  Afterward, Anaconda shut down normally.  The update appears to work.  Thank you!

**Comment by CheeseMochi** [comment]
Good news and thanks for the feedback. I'll give some others a little more time to respond, but if there are no other issues, I'll consider this closed.

@Slepetys 2011.11 sounds like the last version of the Anaconda installer which ships with a slightly older version of Navigator. Once installed, you can update Navigator directly with `conda update anaconda-navigator`

**Comment by CheeseMochi** [comment]
This is resolved in Anaconda Navigator 2.1.2. Closing.

**Comment by Stas-Medvedev** [comment]
Updated to Anaconda Navigator 2.1.2. Was able to close and re-launch Jupyter notebook, and close Anaconda navigator with no problems after a period that would previously cause an issue. Thank you for taking care of this.
