### ISSUE TITLE
byte indices must be integers or slices, not str

### ISSUE THREAD

**Issue by johannspies** [ContinuumIO/anaconda-issues#1281]
Fresh installation (64-bit) on Debian Testing (Anaconda3-4.2.0-Linux-x86_64.sh):

$ anaconda3/bin/anaconda-navigator
Traceback (most recent call last):
  File "anaconda3/bin/anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "/home/js/anaconda3/lib/python3.5/site-packages/anaconda_navigator/app/main.py", line 70, in main
    window = run_app(splash)
  File "/home/js/anaconda3/lib/python3.5/site-packages/anaconda_navigator/app/main.py", line 38, in run_app
    window = MainWindow(splash=splash)
  File "/home/js/anaconda3/lib/python3.5/site-packages/anaconda_navigator/widgets/main_window.py", line 145, in __init__
    self.api = AnacondaAPI()
  File "/home/js/anaconda3/lib/python3.5/site-packages/anaconda_navigator/api/anaconda_api.py", line 434, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/home/js/anaconda3/lib/python3.5/site-packages/anaconda_navigator/api/anaconda_api.py", line 39, in __init__
    self._conda_api = CondaAPI()
  File "/home/js/anaconda3/lib/python3.5/site-packages/anaconda_navigator/api/conda_api.py", line 1185, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/home/js/anaconda3/lib/python3.5/site-packages/anaconda_navigator/api/conda_api.py", line 267, in __init__
    self.set_root_prefix()
  File "/home/js/anaconda3/lib/python3.5/site-packages/anaconda_navigator/api/conda_api.py", line 374, in set_root_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

**Comment by goanpeca** [comment]
@johannspies, what version of Navigator are you using?

Could you please go to the command prompt and type

`conda info`

And paste the results here, and then

`conda list`

And paste the results here?

Cheers

**Comment by johannspies** [comment]
On Mon, Dec 26, 2016 at 07:38:40AM -0800, Gonzalo Peña-Castellanos wrote:
> @johannspies, what version of Navigator are you using?
> 
> Could you please go to the command prompt and type
> 
> `conda info`
> 
> And paste the results here, and then

 /home/js/anaconda3/bin/conda info
Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /home/js/anaconda3  (writable)
    default environment : /home/js/anaconda3
       envs directories : /home/js/anaconda3/envs
          package cache : /home/js/anaconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False



> 
> `conda list`
> 
> And paste the results here?


# packages in environment at /home/js/anaconda3:
#
_license                  1.1                      py35_1  
_nb_ext_conf              0.3.0                    py35_0  
alabaster                 0.7.9                    py35_0  
anaconda                  4.2.0               np111py35_0  
anaconda-clean            1.0.0                    py35_0  
anaconda-client           1.5.1                    py35_0  
anaconda-navigator        1.3.1                    py35_0  
argcomplete               1.0.0                    py35_1  
astroid                   1.4.7                    py35_0  
astropy                   1.2.1               np111py35_0  
babel                     2.3.4                    py35_0  
backports                 1.0                      py35_0  
beautifulsoup4            4.5.1                    py35_0  
bitarray                  0.8.1                    py35_0  
blaze                     0.10.1                   py35_0  
bokeh                     0.12.2                   py35_0  
boto                      2.42.0                   py35_0  
bottleneck                1.1.0               np111py35_0  
cairo                     1.12.18                       6  
cffi                      1.7.0                    py35_0  
chest                     0.2.3                    py35_0  
click                     6.6                      py35_0  
cloudpickle               0.2.1                    py35_0  
clyent                    1.2.2                    py35_0  
colorama                  0.3.7                    py35_0  
conda                     4.2.9                    py35_0  
conda-build               2.0.2                    py35_0  
configobj                 5.0.6                    py35_0  
contextlib2               0.5.3                    py35_0  
cryptography              1.5                      py35_0  
curl                      7.49.0                        1  
cycler                    0.10.0                   py35_0  
cython                    0.24.1                   py35_0  
cytoolz                   0.8.0                    py35_0  
dask                      0.11.0                   py35_0  
datashape                 0.5.2                    py35_0  
dbus                      1.10.10                       0  
decorator                 4.0.10                   py35_0  
dill                      0.2.5                    py35_0  
docutils                  0.12                     py35_2  
dynd-python               0.7.2                    py35_0  
entrypoints               0.2.2                    py35_0  
et_xmlfile                1.0.1                    py35_0  
expat                     2.1.0                         0  
fastcache                 1.0.2                    py35_1  
filelock                  2.0.6                    py35_0  
flask                     0.11.1                   py35_0  
flask-cors                2.1.2                    py35_0  
fontconfig                2.11.1                        6  
freetype                  2.5.5                         1  
get_terminal_size         1.0.0                    py35_0  
gevent                    1.1.2                    py35_0  
glib                      2.43.0                        1  
greenlet                  0.4.10                   py35_0  
gst-plugins-base          1.8.0                         0  
gstreamer                 1.8.0                         0  
h5py                      2.6.0               np111py35_2  
harfbuzz                  0.9.39                        1  
hdf5                      1.8.17                        1  
heapdict                  1.0.0                    py35_1  
icu                       54.1                          0  
idna                      2.1                      py35_0  
imagesize                 0.7.1                    py35_0  
ipykernel                 4.5.0                    py35_0  
ipython                   5.1.0                    py35_0  
ipython_genutils          0.1.0                    py35_0  
ipywidgets                5.2.2                    py35_0  
itsdangerous              0.24                     py35_0  
jbig                      2.1                           0  
jdcal                     1.2                      py35_1  
jedi                      0.9.0                    py35_1  
jinja2                    2.8                      py35_1  
jpeg                      8d                            2  
jsonschema                2.5.1                    py35_0  
jupyter                   1.0.0                    py35_3  
jupyter_client            4.4.0                    py35_0  
jupyter_console           5.0.0                    py35_0  
jupyter_core              4.2.0                    py35_0  
lazy-object-proxy         1.2.1                    py35_0  
libdynd                   0.7.2                         0  
libffi                    3.2.1                         0  
libgcc                    4.8.5                         2  
libgfortran               3.0.0                         1  
libpng                    1.6.22                        0  
libsodium                 1.0.10                        0  
libtiff                   4.0.6                         2  
libxcb                    1.12                          0  
libxml2                   2.9.2                         0  
libxslt                   1.1.28                        0  
llvmlite                  0.13.0                   py35_0  
locket                    0.2.0                    py35_1  
lxml                      3.6.4                    py35_0  
markupsafe                0.23                     py35_2  
matplotlib                1.5.3               np111py35_0  
mistune                   0.7.3                    py35_0  
mkl                       11.3.3                        0  
mkl-service               1.1.2                    py35_2  
mpmath                    0.19                     py35_1  
multipledispatch          0.4.8                    py35_0  
nb_anacondacloud          1.2.0                    py35_0  
nb_conda                  2.0.0                    py35_0  
nb_conda_kernels          2.0.0                    py35_0  
nbconvert                 4.2.0                    py35_0  
nbformat                  4.1.0                    py35_0  
nbpresent                 3.0.2                    py35_0  
networkx                  1.11                     py35_0  
nltk                      3.2.1                    py35_0  
nose                      1.3.7                    py35_1  
notebook                  4.2.3                    py35_0  
numba                     0.28.1              np111py35_0  
numexpr                   2.6.1               np111py35_0  
numpy                     1.11.1                   py35_0  
odo                       0.5.0                    py35_1  
openpyxl                  2.3.2                    py35_0  
openssl                   1.0.2j                        0  
pandas                    0.18.1              np111py35_0  
partd                     0.3.6                    py35_0  
patchelf                  0.9                           0  
path.py                   8.2.1                    py35_0  
pathlib2                  2.1.0                    py35_0  
patsy                     0.4.1                    py35_0  
pep8                      1.7.0                    py35_0  
pexpect                   4.0.1                    py35_0  
pickleshare               0.7.4                    py35_0  
pillow                    3.3.1                    py35_0  
pip                       8.1.2                    py35_0  
pixman                    0.32.6                        0  
pkginfo                   1.3.2                    py35_0  
ply                       3.9                      py35_0  
prompt_toolkit            1.0.3                    py35_0  
psutil                    4.3.1                    py35_0  
ptyprocess                0.5.1                    py35_0  
py                        1.4.31                   py35_0  
pyasn1                    0.1.9                    py35_0  
pycosat                   0.6.1                    py35_1  
pycparser                 2.14                     py35_1  
pycrypto                  2.6.1                    py35_4  
pycurl                    7.43.0                   py35_0  
pyflakes                  1.3.0                    py35_0  
pygments                  2.1.3                    py35_0  
pylint                    1.5.4                    py35_1  
pyopenssl                 16.0.0                   py35_0  
pyparsing                 2.1.4                    py35_0  
pyqt                      5.6.0                    py35_0  
pytables                  3.2.3.1             np111py35_0  
pytest                    2.9.2                    py35_0  
python                    3.5.2                         0  
python-dateutil           2.5.3                    py35_0  
pytz                      2016.6.1                 py35_0  
pyyaml                    3.12                     py35_0  
pyzmq                     15.4.0                   py35_0  
qt                        5.6.0                         0  
qtawesome                 0.3.3                    py35_0  
qtconsole                 4.2.1                    py35_1  
qtpy                      1.1.2                    py35_0  
readline                  6.2                           2  
redis                     3.2.0                         0  
redis-py                  2.10.5                   py35_0  
requests                  2.11.1                   py35_0  
rope                      0.9.4                    py35_1  
ruamel_yaml               0.11.14                  py35_0  
scikit-image              0.12.3              np111py35_1  
scikit-learn              0.17.1              np111py35_2  
scipy                     0.18.1              np111py35_0  
setuptools                27.2.0                   py35_0  
simplegeneric             0.8.1                    py35_1  
singledispatch            3.4.0.3                  py35_0  
sip                       4.18                     py35_0  
six                       1.10.0                   py35_0  
snowballstemmer           1.2.1                    py35_0  
sockjs-tornado            1.0.3                    py35_0  
sphinx                    1.4.6                    py35_0  
spyder                    3.0.0                    py35_0  
sqlalchemy                1.0.13                   py35_0  
sqlite                    3.13.0                        0  
statsmodels               0.6.1               np111py35_1  
sympy                     1.0                      py35_0  
terminado                 0.6                      py35_0  
tk                        8.5.18                        0  
toolz                     0.8.0                    py35_0  
tornado                   4.4.1                    py35_0  
traitlets                 4.3.0                    py35_0  
unicodecsv                0.14.1                   py35_0  
wcwidth                   0.1.7                    py35_0  
werkzeug                  0.11.11                  py35_0  
wheel                     0.29.0                   py35_0  
widgetsnbextension        1.2.6                    py35_0  
wrapt                     1.10.6                   py35_0  
xlrd                      1.0.0                    py35_0  
xlsxwriter                0.9.3                    py35_0  
xlwt                      1.1.2                    py35_0  
xz                        5.2.2                         0  
yaml                      0.1.6                         0  
zeromq                    4.1.4                         0  
zlib                      1.2.8                         3  

Regards
Johann
-- 
Johann Spies                            Telefoon: 021-808 4699
Databestuurder /  Data manager		Faks: 021-883 3691

Sentrum vir Navorsing oor Evaluasie, Wetenskap en Tegnologie
Centre for Research on Evaluation, Science and Technology 
Universiteit Stellenbosch.

The integrity and confidentiality of this email is governed by these terms / Hierdie terme bepaal die integriteit en vertroulikheid van hierdie epos. http://www.sun.ac.za/emaildisclaimer

**Comment by crazySocket** [comment]
I have exactly the same stacktrace. Did download anaconda recently (01-15 00:01 Anaconda3-4.2.0-Linux-x86_64.sh). I did not investigate thoroughly but it seems anaconda-navigator wants to call conda for some reason (root path?). In my case conda was not in PATH. BTW I have anaconda3 in my home directory too.

So, try running `PATH=~/anaconda3/bin/:$PATH anaconda-navigator`.

**Comment by goanpeca** [comment]
>anaconda-navigator wants to call conda for some reason (root path?)

Yes, navigator depends on conda.

Please update to the latest anaconda navigator, and make sure to clean your `~/.condarc` file

**Comment by goanpeca** [comment]
There is a new release available for Anaconda. You can download it from https://www.continuum.io/downloads

This release includes Anaconda Navigator 1.4.3 which includes several fixes and improvements.

You can update it by typing in the command prompt
`$ conda install anaconda-navigator`

**Comment by goanpeca** [comment]
This should be fixed by the latest version, please reopen if this is not the case.

**Comment by grantrostig** [comment]
Still a problem in Anaconda3-4.3.0-Linux-x86_64.sh see #1470

**Comment by selahlynch** [comment]
Still a problem with Anaconda3-4.3.1-Linux-x86_64.sh on Ubuntu 16.04

**Comment by tobigithub** [comment]
**ERROR "byte indices must be integers or slices, not str"**
Actually this can be solved by adding anaconda/bin  (under LINUX) to the path 

`export PATH=~/anaconda3/bin:$PATH`

**Comment by Highstaker** [comment]
Yeah, this works. It might be a good idea to simply add it to `.bashrc` and forget about it. I think that the current installer has an option that does that for you.

**Comment by likoux** [comment]
I installed Anaconda and i had this error on an ubuntu VM. The problem was resolved when i restarted my VM.
