### ISSUE TITLE
Windows installer fails if using /D argument in version 2023.03

### ISSUE THREAD

**Issue by w0** [ContinuumIO/anaconda-issues#13163]
### Checklist

- [X] I added a descriptive title.
- [X] I searched through [existing issues](https://github.com/ContinuumIO/anaconda-issues/issues) and couldn't find a solution or duplicate issue.
- [X] I searched on the web (e.g. Google) and didn't find any helpful information.
- [X] I searched the [Anaconda documentation](https://docs.anaconda.com/) and didn't find any helpful information.

### Impacted product

- [X] A conda package (built by Anaconda)
- [X] Anaconda Distribution (formerly Anaconda Individual Edition)
- [ ] Miniconda
- [ ] Anaconda.org

### What happened?

When running the windows installation with the following arguments it fails with an exit code of 2

```
Anaconda3-2023.03-Windows-x86_64.exe /InstallationType=AllUsers /RegisterPython=1 /S /D=%ProgramFiles%\Anaconda3\
```

The specified arguments worked without issue in previous versions of the anaconda installer. But in the 2023.03 release it no longer installs. If you remove the /D argument it will install successfully in the default location of %ProgramData%\anaconda3. The documentation for silent install still specifies that /D is a mandatory argument if using /S. Did the argument change? Or is this a Bug?

### Expected behavior or outcome

When using the /D argument the installer should install anaconda to the specified location ex. /D=%ProgramFiles%\Anaconda3\ should install to "C:\Program Files\Anaconda3"

**Comment by marcoesters** [comment]
There is indeed a bug somewhere and I am digging into the problem to figure out where it is exactly.

The installers appear to have a problem if `/D` has a path with spaces (and commas, for some reason). If you give it a path without these characters, the silent installation should still work.

**Comment by marcoesters** [comment]
This should be fixed with an upcoming installer release. I will update this issue when the new installer is out.

**Comment by Angelworks** [comment]
> This should be fixed with the new installer: https://www.anaconda.com/download/
> 
> Feel free to reopen this issue if this is still a problem - thank you!

I still see this issue on 2023.03-1...

**Comment by Darkjono** [comment]
> This should be fixed with the new installer: https://www.anaconda.com/download/
> 
> Feel free to reopen this issue if this is still a problem - thank you!

Unfortunately the new installer has not fixed this problem for me, like Angelworks pointed out.
Can this issue be reopened and reinvestigated?

**Comment by marcoesters** [comment]
@Darkjono , @Angelworks 

Could you provide me with the command you are running to install this?

It is important that you do not quote the path and that the `/D=` option is last.

**Comment by Darkjono** [comment]
> @Darkjono , @Angelworks
> 
> Could you provide me with the command you are running to install this?
> 
> It is important that you do not quote the path and that the `/D=` option is last.

I always used the command below to install previous versions of Anaconda for the past few years (in PS):

.\Anaconda3-2022.10-Windows-x86_64.exe /S /InstallationType=AllUsers /D=C:\progra~1\Anaconda3**\**

The backslash at the end of the path was the only change I had to make, so an easy fix but an annoying one to find, especially since it was not needed in the past.
I believe this ticket can be closed again.

**Comment by Darkjono** [comment]
> @Darkjono , @Angelworks
> 
> Could you provide me with the command you are running to install this?
> 
> It is important that you do not quote the path and that the `/D=` option is last.

I always used to install Anaconda like this in PS, I have not used quotes:

.\Anaconda3-2023.03-1-Windows-x86_64.exe /S /InstallationType=AllUsers /D=C:\progra~1\Anaconda3

So far I have not been able to get the installer to accept the path, it gets kicked out immediately after loading up.
In some cases it defaults to ProgramData, which is not what I'm looking for.
The PS alternatives $Env:Programfiles or [Environment]::ExpandEnvironmentVariables('%ProgramFiles%') also haven't made the path work.
Adding a final backslash to the path also didn't work.

**Comment by Darkjono** [comment]
> @Darkjono , @Angelworks
> 
> Could you provide me with the command you are running to install this?
> 
> It is important that you do not quote the path and that the `/D=` option is last.

I found both problems I had, I always installed Anaconda in PS like this:

./Anaconda.exe /S /InstallationType=AllUsers /D=C:\progra~1\Anaconda3

Since this installer, the shortname progra~1 is not accepted anymore for some reason.
After some time of testing to escape the space in the path, turns out it isn't even necessary to do so.
My full command for PS is now like this:

**.\Anaconda3-2023.03-1-Windows-x86_64.exe /S /InstallationType=AllUsers /D=C:\Program Files\Anaconda3**

I also always made the directory beforehand to set folder permissions in advance.
Even when the directory is empty, the Anaconda installer did not accept that it was empty and simply refused to install.
I removed this step and now my script works.

I hope this can help anyone who is experiencing the same problem.
I believe this ticket can be closed again.

**Comment by Angelworks** [comment]
> @Darkjono , @Angelworks
> 
> Could you provide me with the command you are running to install this?
> 
> It is important that you do not quote the path and that the `/D=` option is last.

My command line is:

Anaconda3-2023.03-1-Windows-x86_64.exe /InstallationType=AllUsers /AddToPath=0 /RegisterPython=1 /S /D=C:\Anaconda3

No trailing slashes or quotes. I am parsing our versions etc using powershell, but that is what is sent to the command line.

**Comment by marcoesters** [comment]
@Darkjono, I have been able to reproduce both problems, so I will look into it.

@Angelworks, I unfortunately cannot reproduce yours. I tried this command with the recent installer and it installed just fine. I tried to reproduce it by opening `cmd.exe` and powershell with administrator rights and running your command. I made sure that `C:\Anaconda3` did not exist before I started the installation.
