### ISSUE TITLE
Mayavi has incomplete dependencies

### ISSUE THREAD

**Issue by christianbrodbeck** [ContinuumIO/anaconda-issues#1365]
The discussion in https://github.com/conda/conda/issues/4300 suggested that Mayavi does not have complete dependency specifications. 

- VTK issues a warning suggesting the dependency should be =6.3
- The errors below suggest that there is also a conflict with numpy 1.9 (I'm using OS X 10.12.2)

```
$ conda create -n test mayavi=4.4
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /Users/christian/anaconda/envs/test:

The following NEW packages will be INSTALLED:

    apptools:   4.2.1-py27_0    
    configobj:  5.0.6-py27_0    
    envisage:   4.4.0-py27_1    
    freetype:   2.5.5-1         
    libpng:     1.6.27-0        
    mayavi:     4.4.0-np19py27_0
    mkl:        11.3.3-0        
    numpy:      1.9.3-py27_3    
    openssl:    1.0.2j-0        
    pip:        9.0.1-py27_1    
    pyface:     4.4.0-py27_0    
    pyqt:       4.11.4-py27_4   
    python:     2.7.13-0        
    python.app: 1.2-py27_4      
    qt:         4.8.7-4         
    readline:   6.2-2           
    setuptools: 27.2.0-py27_0   
    sip:        4.18-py27_0     
    six:        1.10.0-py27_0   
    sqlite:     3.13.0-0        
    tk:         8.5.18-0        
    traits:     4.4.0-py27_0    
    traitsui:   4.4.0-py27_0    
    vtk:        5.10.1-py27_0   
    wheel:      0.29.0-py27_0   
    zlib:       1.2.8-3         

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|#################################################################################| 100%
#
# To activate this environment, use:
# > source activate test
#
# To deactivate this environment, use:
# > source deactivate test
#

$ source activate test
(test) $ conda update mayavi
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /Users/christian/anaconda/envs/test:

The following NEW packages will be INSTALLED:

    pygments: 2.1.3-py27_0    

The following packages will be UPDATED:

    apptools: 4.2.1-py27_0     --> 4.4.0-py27_0
    envisage: 4.4.0-py27_1     --> 4.5.1-py27_0
    mayavi:   4.4.0-np19py27_0 --> 4.5.0-py27_0
    pyface:   4.4.0-py27_0     --> 5.1.0-py27_0
    traits:   4.4.0-py27_0     --> 4.6.0-py27_0
    traitsui: 4.4.0-py27_0     --> 5.1.0-py27_0

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|#################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|#################################################################################| 100%
(test) $ python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> from mayavi import mlab
********************************************************************************
WARNING: Imported VTK version (5.1) does not match the one used
         to build the TVTK classes (6.3). This may cause problems.
         Please rebuild TVTK.
********************************************************************************

RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/christian/anaconda/envs/test/lib/python2.7/site-packages/mayavi/mlab.py", line 27, in <module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move
  File "/Users/christian/anaconda/envs/test/lib/python2.7/site-packages/mayavi/tools/camera.py", line 25, in <module>
    from .engine_manager import get_engine
  File "/Users/christian/anaconda/envs/test/lib/python2.7/site-packages/mayavi/tools/engine_manager.py", line 14, in <module>
    from mayavi.core.engine import Engine
  File "/Users/christian/anaconda/envs/test/lib/python2.7/site-packages/mayavi/core/engine.py", line 28, in <module>
    from mayavi.core.base import Base
  File "/Users/christian/anaconda/envs/test/lib/python2.7/site-packages/mayavi/core/base.py", line 19, in <module>
    from tvtk.pyface.tvtk_scene import TVTKScene
  File "/Users/christian/anaconda/envs/test/lib/python2.7/site-packages/tvtk/pyface/tvtk_scene.py", line 28, in <module>
    from tvtk.pyface import light_manager
  File "/Users/christian/anaconda/envs/test/lib/python2.7/site-packages/tvtk/pyface/light_manager.py", line 130, in <module>
    class CameraLight(HasTraits):
  File "/Users/christian/anaconda/envs/test/lib/python2.7/site-packages/tvtk/pyface/light_manager.py", line 146, in CameraLight
    source = Instance(tvtk.Light, ())
  File "/Users/christian/anaconda/envs/test/lib/python2.7/site-packages/tvtk/tvtk_classes.zip/tvtk_classes/tvtk_helper.py", line 225, in <lambda>
  File "/Users/christian/anaconda/envs/test/lib/python2.7/site-packages/tvtk/tvtk_classes.zip/tvtk_classes/tvtk_helper.py", line 36, in get_class
  File "/Users/christian/anaconda/envs/test/lib/python2.7/site-packages/tvtk/tvtk_classes.zip/tvtk_classes/tvtk_helper.py", line 28, in get_module
  File "/Users/christian/anaconda/envs/test/lib/python2.7/site-packages/tvtk/tvtk_classes.zip/tvtk_classes/light.py", line 12, in <module>
  File "/Users/christian/anaconda/envs/test/lib/python2.7/site-packages/tvtk/array_handler.py", line 28, in <module>
    from tvtk.array_ext import set_id_type_array
ImportError: numpy.core.multiarray failed to import
>>> 
(test)$ conda update numpy
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /Users/christian/anaconda/envs/test:

The following packages will be UPDATED:

    mkl:   11.3.3-0     --> 2017.0.1-0   
    numpy: 1.9.3-py27_3 --> 1.11.3-py27_0

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|#################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|#################################################################################| 100%
(test)$ python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> from mayavi import mlab
********************************************************************************
WARNING: Imported VTK version (5.1) does not match the one used
         to build the TVTK classes (6.3). This may cause problems.
         Please rebuild TVTK.
********************************************************************************

>>> 
```

**Comment by ilanschnell** [comment]
Thanks, for the feedback.  We have specify the VTK version which mayavi depends more explicitly.  Running:
```
conda install -n test vtk=6.3
```
should fix the problem for you.

**Comment by christianbrodbeck** [comment]
Thanks! I still don't see `vtk` 6.3 as a requirement (see below), is this coming after a certain upgrade cycle? I'm also working on conda-forge recipes where hard coding a `vtk` version does not seem like a good idea?

```bash
$ conda info mayavi=4.5
Fetching package metadata ...........

mayavi 4.5.0 py27_0
-------------------
file name   : mayavi-4.5.0-py27_0.tar.bz2
name        : mayavi
version     : 4.5.0
build string: py27_0
build number: 0
channel     : defaults
size        : 12.0 MB
arch        : x86_64
date        : 2016-12-07
license     : BSD
md5         : 6316ad605e96ca144ba40899d4b6d152
platform    : darwin
requires    : ()
url         : https://repo.continuum.io/pkgs/free/osx-64/mayavi-4.5.0-py27_0.tar.bz2
dependencies:
    apptools >=4.4
    envisage >=4.5
    numpy
    pyqt 4.*
    python 2.7*
    python.app
    traitsui >=5.1
    vtk
```

**Comment by gowthamikandru** [comment]
can any one say how to hide/remove the mayavi toolbar?
