### ISSUE TITLE
Anaconda Navigator fails to start installed applications with Windows

### ISSUE THREAD

**Issue by SMH17** [ContinuumIO/anaconda-issues#1514]
When I try to launch an App from Anaconda Navigator clicking the Launch button of related App in home, nothing happens
The apps are correctly installed and work fine if launched manually.

The issue seems caused by a wrong generation of launch scripts in the folder 

`.anaconda\navigator\scripts`

located in the user path.

If I check these scripts have the follow content
```
"C:/Program Files/Anaconda3/bin/activate" "C:/Program Files/Anaconda3"
C:/Program Files/Anaconda3/Scripts/glue
```
The bin folder is missing at all in Anaconda3 folder, and command should be 
`start "C:/Program Files/Anaconda3/Scripts/glue.exe"`

Unfortunately editing manually these bat scripts doesn't fix the issue because Navigator every time you try to launch an App recreates its related script.

version: latest release Anaconda Navigator 1.5 (updated using conda package manager, isn't a new installation)
OS: Windows 10 x64

**Comment by mingwandroid** [comment]
`.exe` is not needed but the quotes are.

**Comment by Pelonza** [comment]
Seeing this makes me wonder if this is also causing my problem with getting the navigator to open at all in Win 10.... #1533 

Thanks for the detailed original message, now I can at least check a few other places to see if someone got goofed up on install/restarting...

**Comment by mingwandroid** [comment]
@Pelonza, how did you install it? All Users or Just Me? To a folder (or as a subfolder of any folder) containing spaces or unicode characters?

For the most trouble-free installation I recommend Just Me, not adding to PATH and avoiding spaces and unicode then using `Anaconda Prompt` if you need a to use a command line interface.

This specific bug seems to be due to spaces in the root installation prefix.

**Comment by Pelonza** [comment]
I actually tried both methods (All Users and Just Me)... and then installed using the default location, so I believe it was installed under C:\Anaconda3

I have the same issue in both cases (navigator not opening). 

Anaconda Prompt does seem to work fine, and I used that to start some things. I didn't try starting the navigator from there though. I'm not on my work computer right now though so can't test that.

**Comment by mingwandroid** [comment]
Multiple attempts at installation cause some of the biggest headaches (but yes, I appreciate they wouldn't be necessary if everything just worked first time).

Particularly, not uninstalling before reinstalling and also not removing the old entries from PATH can cause the old installation to get run instead of the new one, or worse, a mix of the two. The shortcuts can sometimes point at the old stuff and can sometimes end up duplicated.

Never adding things to PATH avoids some of these problems.

**Comment by SMH17** [comment]
This issue doesn't happen if I install Anaconda in `ProgramData`, so there is some problem in the way paths are managed.

**Comment by mingwandroid** [comment]
It's to do with the space.

**Comment by Pelonza** [comment]
Ok. I will check the current path for legacy references, and for spaces in the install path (not sure I can eliminate all of those).

**Comment by mingwandroid** [comment]
@Pelonza if this is the same installation as https://github.com/conda/conda/issues/4894, then your install path is `C:\Users\kschmit1\AppData\Local\Continuum\Anaconda3` which should be OK in this regard.

I am not talking about spaces in entries for other software in your system PATH. Anaconda doesn't care about those.

**Comment by Pelonza** [comment]
It's actually a different install. It's the install on my desktop computer in my office.

The R-Studio issue https://github.com/conda/conda/issues/4894 is occurring on my surface laptop, which is a different install.

**Comment by goanpeca** [comment]
Fixed in the latest release

**Comment by weirdname404** [comment]
I had an issue with Anaconda Navigator, clicking on the icon was not giving any effect despite 1sec loading. I checked the PATH and found there some Anaconda references. Deleting all Anaconda references from the PATH helped to solve the problem, so now Anaconda Navigator is opening without any errors.

**Comment by fenghaolin** [comment]
@goanpeca I downloaded and installed the latest release (using Anaconda 4.4.0 For Windows Graphical Installer), but I got the same issue as @SMH17. So, it seems the latest release has not fixed this problem yet. I am using Win10. I don't know if that is a relevant factor, though. Thanks anyway to both of you.

**Comment by fenghaolin** [comment]
@goanpeca I installed the latest release (Anaconda 4.4.0 For Windows Graphical Installer) using my administrator account on win 10, and  I installed for 'All Users'. Everything seems to work perfectly until I logout and switch to my standard user account---I then got the same issue as @SMH17 reported. So, it seems the latest release has not fixed this problem yet. I use standard account mostly, and rarely use the administrator one for security reasons. This leaves me no choice but uninstalling Anaconda for now, and I will come back and see if future releases fix this issue. Thanks anyway to all of you.

**Comment by ramonankersmit** [comment]
Same problem here; launcing app on Anaconda doesn't work; it does startup In an anaconda prompt window. Installed on windows10 with and without administrator rights; same problem. My windows username has a space, can that be a problem causing this?

**Comment by nehaljwani** [comment]
@ramonankersmit Please install Anaconda to a directory which has no spaces in it's path.

**Comment by 201708GitHub** [comment]
Done that

**Comment by ramonankersmit** [comment]
@nehaljwani I have installed the application in all possible configurations admin, no admin vs default setup directory, directly in first map (no spaces), but it doesn't want to launch any apps in anaconda in any installation, only possible via de command prompt. The only thing I could try is to install it with a logged in user that has no space in the username, maybe that is the issue...

**Comment by sebastianod** [comment]
I am experiencing a similar issue. I'm not too familiar with how to change the PATH or eliminate old ones...I've uninstalled and reinstalled far too many times now. This issue happened after installing VPython two days ago. I also could no longer open chrome and can't even install it...I keep getting command prompts every minute or so from Nvidia updates...Once reinstalled, nothing from Anaconda works, not even the Anaconda prompt.

**Comment by 201708GitHub** [comment]
I am still experiencing the same problem. Moreover, Autocomplete is not working in spyder.
I cannot launch Jupyter notebook.

**Comment by jonasluz** [comment]
Same happening here. I've just installed Anaconda 3.5.0.1 64bit, after uninstalling Anaconda 3.4.x (sorry about not being sure about the older version). The older Anaconda was installed for all users (C:\Program Files), but I installed the newer version just for my user. Afterwards, I found out some older pure Python 3.6 installs that I also removed. 

My new Anaconda installation is in C:\Users\live\Anaconda3 (no space in the path) and it is not in the system's PATH variable, neither in mine.

Anaconda Navigator, Spyder and Jupyter Notebook all have system shortcuts, but none of them work (nothing happens) and none of them appears in the "Add and Remove Programs" system's Settings tab; the only Anaconda related entry in that tab is "Python 3.6.3 (Anaconda3 5.0.1 64-bit)" (this was happening with the older version, too).

In fact, the problem seems to have appeared suddenly in the previous version (the last time I used it before today was months ago and everything were fine); that was the reason I decided to update Anaconda today.

Maybe some Windows update broke it all? My OS is Windows 10 Home edition, version 1703, build 15063.674. 

Hope these new info can help.

**Comment by elelunicy** [comment]
There is simply no way to launch anything in Anaconda Navigator if your Windows username contains a space.

**Comment by Thrilok91** [comment]
I got it solved by installing Anaconda accessible to all users(Default is just one user). In that way it installs in Program Data file rather than user/name...

**Comment by PRANAY100** [comment]
In my case, there is a problem with anconda packages, i have updated my pip package and it staerted working. I have re-installed before but it didn't work. my path is just c:/anaconda3. This seems that few packages could make anaconda3 not to open. my prompt says this error at that point.

Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\anaconda-navigator-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\app\main.py", line 129, in main
    from anaconda_navigator.app.start import start_app
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 32, in <module>
    from anaconda_navigator.widgets.main_window import MainWindow
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 32, in <module>
    from anaconda_navigator.api.anaconda_api import AnacondaAPI
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 33, in <module>
    from anaconda_navigator.api.client_api import ClientAPI
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 24, in <module>
    from anaconda_navigator.api.conda_api import CondaAPI
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 33, in <module>
    from anaconda_navigator.utils.findpip import PIP_LIST_SCRIPT
  File "C:\Anaconda3\lib\site-packages\anaconda_navigator\utils\findpip.py", line 22, in <module>
    import pip
  File "C:\Anaconda3\lib\site-packages\pip\__init__.py", line 45, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "C:\Anaconda3\lib\site-packages\pip\vcs\mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "C:\Anaconda3\lib\site-packages\pip\download.py", line 40, in <module>
    from pip._vendor import requests, six
  File "C:\Anaconda3\lib\site-packages\pip\_vendor\requests\__init__.py", line 98, in <module>
    from . import packages
  File "C:\Anaconda3\lib\site-packages\pip\_vendor\requests\packages.py", line 12, in <module>
    sys.modules['pip._vendor.requests.packages.' + mod] = sys.modules["pip._vendor." + mod]
KeyError: 'pip._vendor.urllib3.contrib'

(base) C:\Users\Pranay Reddy>conda update pip
Solving environment: done

## Package Plan ##

  environment location: C:\Anaconda3

  added / updated specs:
    - pip


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    anaconda-custom            |   py36h363777c_0           9 KB
    pip-9.0.1                  |           py36_5         2.5 MB
    ------------------------------------------------------------
                                           Total:         2.5 MB

The following packages will be UPDATED:

    anaconda: 5.1.0-py36_2         --> custom-py36h363777c_0
    pip:      9.0.1-py36h226ae91_4 --> 9.0.1-py36_5

Proceed ([y]/n)? y


Downloading and Extracting Packages
anaconda custom: ############################################################################################## | 100%
pip 9.0.1: #################################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

AFTER THIS UPDATION IT WORKED. :D

**Comment by geezer67** [comment]
I solved this problem with the following 2 changes.
 C:\Users\Mike>conda update pip  , this updated my  pip package
 C:\Users\Mike>conda update -n base conda  --- updated the  conda package

navigator then starts,,,

**Comment by shauryauppal** [comment]
conda update pip

Really solved my problem thanks to above to people who wrote these two valuable comments.

> conda update conda
> conda update pip
> anaconda-navigator
3 lines and it revives
