### ISSUE TITLE
Windows - Anaconda Navigator Not Opening 

### ISSUE THREAD

**Issue by dwanneruchi** [ContinuumIO/anaconda-issues#1581]
Anaconda Navigator is just hanging for my windows machine - this began happening last week, and after a few restarts of my pc I can usually get Anaconda Navigator to work.

I am running Python 3 and the following shows my current anaconda information: 

<img width="513" alt="anaconda_issues" src="https://cloud.githubusercontent.com/assets/12676672/24684461/3c2732b2-1974-11e7-8585-40afa6418693.PNG">

I am able to open up the command prompt and then run jupyter notebook with python working just fine, so not fully sure what is happening here.

Glad to provide more information as needed.

**Comment by mingwandroid** [comment]
Please show the output from an `Anaconda Prompt` of:

1. conda info
2. conda list --show-channel-urls
3. anaconda-navigator

Thanks in advance.

**Comment by dwanneruchi** [comment]
1. Conda info

![image](https://cloud.githubusercontent.com/assets/12676672/24684831/fdd237f2-1976-11e7-82c9-ad1a93915137.png)

**Comment by mingwandroid** [comment]
Please copy the text rather than taking screen grabs.

**Comment by dwanneruchi** [comment]
1) (C:\Users\david\AppData\Local\Continuum\Anaconda3) C:\Users\david>conda info
Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : C:\Users\david\AppData\Local\Continuum\Anaconda3  (writable)
    default environment : C:\Users\david\AppData\Local\Continuum\Anaconda3
       envs directories : C:\Users\david\AppData\Local\Continuum\Anaconda3\envs
          package cache : C:\Users\david\AppData\Local\Continuum\Anaconda3\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\david\.condarc
           offline mode : False


2) (C:\Users\david\AppData\Local\Continuum\Anaconda3) C:\Users\david>conda list --show-channel-urls
                                                                        # packages in environment at C:\Users\david\AppData\Local\Continuum\Anaconda3:
#
_license                  1.1                      py35_1    defaults
_nb_ext_conf              0.3.0                    py35_0    defaults
alabaster                 0.7.9                    py35_0    defaults
anaconda                  4.3.1               np111py35_0    defaults
anaconda-clean            1.0.0                    py35_0    defaults
anaconda-client           1.6.0                    py35_0    defaults
anaconda-navigator        1.5.0                    py35_0    defaults
anaconda-project          0.4.1                    py35_0    defaults
argcomplete               1.0.0                    py35_1    defaults
astroid                   1.4.9                    py35_0    defaults
astropy                   1.3                 np111py35_0    conda-forge
babel                     2.3.4                    py35_0    defaults
backports                 1.0                      py35_0    defaults
beautifulsoup4            4.5.3                    py35_0    conda-forge
bitarray                  0.8.1                    py35_1    defaults
blaze                     0.10.1                   py35_0    defaults
bokeh                     0.12.4                   py35_0    defaults
boto                      2.45.0                   py35_0    defaults
bottleneck                1.2.0               np111py35_0    conda-forge
bzip2                     1.0.6                    vc14_3  [vc14]  defaults
cffi                      1.9.1                    py35_0    defaults
chardet                   2.3.0                    py35_0    conda-forge
chest                     0.2.3                    py35_0    defaults
click                     6.7                      py35_0    conda-forge
cloudpickle               0.2.2                    py35_0    defaults
clyent                    1.2.2                    py35_0    defaults
colorama                  0.3.7                    py35_0    defaults
comtypes                  1.1.2                    py35_0    defaults
conda                     4.2.13                   py35_0    conda-forge
conda-build               2.0.2                    py35_0    defaults
conda-env                 2.6.0                         0    conda-forge
configobj                 5.0.6                    py35_0    defaults
console_shortcut          0.1.1                    py35_1    defaults
contextlib2               0.5.4                    py35_0    conda-forge
cryptography              1.7.1                    py35_0    defaults
curl                      7.52.1                   vc14_0  [vc14]  conda-forge
cycler                    0.10.0                   py35_0    defaults
cython                    0.25.2                   py35_0    conda-forge
cytoolz                   0.8.2                    py35_0    conda-forge
dask                      0.13.0                   py35_0    conda-forge
datashape                 0.5.4                    py35_0    defaults
decorator                 4.0.11                   py35_0    conda-forge
dill                      0.2.5                    py35_0    defaults
dlib                      19.4.0                    <pip>
docutils                  0.13.1                   py35_0    conda-forge
dxchange                  0.1.2                     <pip>
dynd-python               0.7.2                    py35_0    defaults
entrypoints               0.2.2                    py35_0    defaults
et_xmlfile                1.0.1                    py35_0    defaults
fastcache                 1.0.2                    py35_1    defaults
filelock                  2.0.6                    py35_0    defaults
flask                     0.12                     py35_0    conda-forge
flask-cors                3.0.2                    py35_0    conda-forge
freetype                  2.5.5                    vc14_2  [vc14]  defaults
get_terminal_size         1.0.0                    py35_0    defaults
gevent                    1.2.1                    py35_0    defaults
greenlet                  0.4.11                   py35_0    defaults
h5py                      2.6.0               np111py35_2    defaults
hdf5                      1.8.15.1                 vc14_4  [vc14]  defaults
heapdict                  1.0.0                    py35_1    defaults
icu                       57.1                     vc14_0  [vc14]  defaults
idna                      2.2                      py35_0    defaults
imagesize                 0.7.1                    py35_0    defaults
ipykernel                 4.5.2                    py35_0    conda-forge
ipython                   5.1.0                    py35_0    defaults
ipython_genutils          0.1.0                    py35_0    defaults
ipywidgets                5.2.2                    py35_1    defaults
isort                     4.2.5                    py35_0    conda-forge
itsdangerous              0.24                     py35_0    defaults
jdcal                     1.3                      py35_0    defaults
jedi                      0.9.0                    py35_1    defaults
jinja2                    2.9.4                    py35_0    defaults
jpeg                      9b                       vc14_0  [vc14]  conda-forge
JSAnimation               0.1                       <pip>
jsonschema                2.5.1                    py35_0    defaults
jupyter                   1.0.0                    py35_3    defaults
jupyter_client            4.4.0                    py35_0    defaults
jupyter_console           5.0.0                    py35_0    defaults
jupyter_core              4.2.1                    py35_0    conda-forge
Keras                     2.0.2                     <pip>
Lasagne                   0.1                       <pip>
lazy-object-proxy         1.2.2                    py35_0    conda-forge
libdynd                   0.7.2                         0    defaults
libiconv                  1.14                     vc14_4  [vc14]  conda-forge
libpng                    1.6.27                   vc14_0  [vc14]  defaults
libtiff                   4.0.6                    vc14_3  [vc14]  defaults
libxml2                   2.9.4                    vc14_4  [vc14]  conda-forge
libxslt                   1.1.29                   vc14_3  [vc14]  conda-forge
llvmlite                  0.15.0                   py35_0    defaults
locket                    0.2.0                    py35_1    defaults
lxml                      3.7.2                    py35_0    conda-forge
markupsafe                0.23                     py35_2    defaults
matplotlib                2.0.0               np111py35_0    defaults
menuinst                  1.4.4                    py35_0    defaults
mistune                   0.7.3                    py35_0    defaults
mkl                       2017.0.1                      0    defaults
mkl-service               1.1.2                    py35_3    defaults
mpmath                    0.19                     py35_1    defaults
multipledispatch          0.4.9                    py35_0    conda-forge
nb_anacondacloud          1.2.0                    py35_0    defaults
nb_conda                  2.0.0                    py35_0    defaults
nb_conda_kernels          2.0.0                    py35_0    defaults
nbconvert                 4.2.0                    py35_0    defaults
nbformat                  4.2.0                    py35_0    conda-forge
nbpresent                 3.0.2                    py35_0    defaults
networkx                  1.11                     py35_0    defaults
nltk                      3.2.2                    py35_0    conda-forge
nose                      1.3.7                    py35_1    defaults
notebook                  4.3.1                    py35_2    defaults
numba                     0.30.1              np111py35_0    defaults
numexpr                   2.6.1               np111py35_2    defaults
numpy                     1.11.3                   py35_0    defaults
numpydoc                  0.6.0                    py35_0    conda-forge
odo                       0.5.0                    py35_1    defaults
olefile                   0.44                      <pip>
opencv3                   3.1.0                    py35_0    menpo
openpyxl                  2.4.1                    py35_0    defaults
openssl                   1.0.2k                   vc14_0  [vc14]  defaults
pandas                    0.19.2              np111py35_1    conda-forge
pandas-datareader         0.3.0.post0               <pip>
partd                     0.3.7                    py35_0    conda-forge
path.py                   10.0                     py35_0    defaults
pathlib2                  2.2.0                    py35_0    defaults
patsy                     0.4.1                    py35_0    defaults
pep8                      1.7.0                    py35_0    defaults
pickleshare               0.7.4                    py35_0    defaults
pillow                    4.0.0                    py35_0    defaults
pip                       9.0.1                    py35_1    defaults
pkginfo                   1.3.2                    py35_0    defaults
ply                       3.9                      py35_0    defaults
prompt_toolkit            1.0.9                    py35_0    conda-forge
protobuf                  3.2.0                     <pip>
psutil                    5.0.1                    py35_0    conda-forge
psycopg2                  2.6.2                     <pip>
py                        1.4.32                   py35_0    conda-forge
pyasn1                    0.1.9                    py35_0    defaults
pycosat                   0.6.1                    py35_1    defaults
pycparser                 2.17                     py35_0    conda-forge
pycrypto                  2.6.1                    py35_5    defaults
pycurl                    7.43.0                   py35_2    defaults
pydot                     1.2.3                     <pip>
pyflakes                  1.5.0                    py35_0    conda-forge
pygments                  2.1.3                    py35_0    defaults
pylint                    1.6.4                    py35_1    defaults
pyopenssl                 16.2.0                   py35_0    conda-forge
pyparsing                 2.1.4                    py35_0    defaults
pyqt                      5.6.0                    py35_2    defaults
pytables                  3.2.2               np111py35_4    defaults
pytest                    3.0.5                    py35_0    conda-forge
python                    3.5.2                         0    defaults
python-dateutil           2.6.0                    py35_0    conda-forge
pytz                      2016.10                  py35_0    conda-forge
pywin32                   220                      py35_2    defaults
pyyaml                    3.12                     py35_0    defaults
pyzmq                     16.0.2                   py35_0    conda-forge
qt                        5.6.2                    vc14_3  [vc14]  defaults
qtawesome                 0.4.3                    py35_0    defaults
qtconsole                 4.2.1                    py35_2    defaults
qtpy                      1.2.1                    py35_0    conda-forge
requests                  2.12.4                   py35_0    conda-forge
requests-file             1.4.1                     <pip>
requests-ftp              0.3.1                     <pip>
rope                      0.9.4                    py35_1    defaults
ruamel_yaml               0.11.14                  py35_1    defaults
scikit-image              0.12.3              np111py35_1    defaults
scikit-learn              0.18.1              np111py35_1    defaults
scikit-neuralnetwork      0.7                       <pip>
scipy                     0.18.1              np111py35_1    defaults
seaborn                   0.7.1                    py35_0    conda-forge
setuptools                27.2.0                   py35_1    defaults
simplegeneric             0.8.1                    py35_1    defaults
singledispatch            3.4.0.3                  py35_0    defaults
sip                       4.18                     py35_0    defaults
six                       1.10.0                   py35_0    defaults
snowballstemmer           1.2.1                    py35_0    defaults
sockjs-tornado            1.0.3                    py35_0    defaults
sphinx                    1.5.1                    py35_0    conda-forge
spyder                    3.1.2                    py35_0    defaults
sqlalchemy                1.1.5                    py35_0    conda-forge
statsmodels               0.6.1               np111py35_1    defaults
sympy                     1.0                      py35_0    defaults
tensorflow                1.0.0                     <pip>
tflearn                   0.3                       <pip>
Theano                    0.9.0                     <pip>
tk                        8.5.18                   vc14_0  [vc14]  defaults
toolz                     0.8.2                    py35_0    conda-forge
tornado                   4.4.2                    py35_0    conda-forge
traitlets                 4.3.1                    py35_0    conda-forge
unicodecsv                0.14.1                   py35_0    defaults
vc                        14                            0    conda-forge
vs2015_runtime            14.0.25123                    0    defaults
wcwidth                   0.1.7                    py35_0    defaults
werkzeug                  0.11.15                  py35_0    defaults
wheel                     0.29.0                   py35_0    defaults
widgetsnbextension        1.2.6                    py35_0    defaults
win_unicode_console       0.5                      py35_0    defaults
wrapt                     1.10.8                   py35_0    conda-forge
xlrd                      1.0.0                    py35_0    defaults
xlsxwriter                0.9.6                    py35_0    defaults
xlwings                   0.10.2                   py35_0    defaults
xlwt                      1.2.0                    py35_0    defaults
zlib                      1.2.8                    vc14_3  [vc14]  defaults

3) Sorry running into issues with running anaconda prompt now...will keep trying to add this!

**Comment by dwanneruchi** [comment]
3) anaconda-navigator

(C:\Users\david\AppData\Local\Continuum\Anaconda3) C:\Users\david>anaconda-navigator
Traceback (most recent call last):
  File "C:\Users\david\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 174, in _repos_checked
    self._download_repodata(self._valid_repos)
  File "C:\Users\david\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 198, in _download_repodata
    verify=self._client_api.get_ssl(),
  File "C:\Users\david\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 555, in get_ssl
    self._conda_api.config_set('ssl_verify', value).communicate()
  File "C:\Users\david\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 244, in communicate
    result[0], result[-1], **self._extra_kwargs
  File "C:\Users\david\AppData\Local\Continuum\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 907, in <lambda>
    callback=lambda o, e: o.get('warnings', [])
AttributeError: 'bytes' object has no attribute 'get'


Still hanging with the anaconda green circle...but this is what I have thus far.

**Comment by goanpeca** [comment]
@dwanneruchi could you update to the latest conda and latest navigator to check again?

Pleas open the Anaconda Prompt and type

`conda update conda`

`conda update anaconda-navigator`

**Comment by dwanneruchi** [comment]
I had done the conda update conda....not the second line though. 

Just tried this:

(C:\Users\david\AppData\Local\Continuum\Anaconda3) C:\Users\david>conda update anaconda-navigator
Fetching package metadata .............
Solving package specifications: ..........

Package plan for installation in environment C:\Users\david\AppData\Local\Continuum\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    anaconda-navigator-1.5.1   |           py35_0         4.5 MB

The following packages will be UPDATED:

    anaconda:           4.3.1-np111py35_0 --> custom-py35_0
    anaconda-navigator: 1.5.0-py35_0      --> 1.5.1-py35_0

Proceed ([y]/n)? y

Fetching packages ...
anaconda-navig 100% |###############################| Time: 0:00:00   7.45 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%


I am now able to successfully open anaconda navigator. So was the issue just that my anaconda-navigator was not running 1.5.1?

Thanks for your help!

**Comment by goanpeca** [comment]
@dwanneruchi 1.5.1 contains some hotfixes so we just might have fixe that one :-)

Cheers

**Comment by dwanneruchi** [comment]
So, I had the same issue last night where it hung at the start, eventually opened up, and then just stopped working. 

I restarted my computer a few times (there was a mandatory install for my dell) and then was eventually able to get anaconda navigator up & running. 

Now I am running into a situation where I can't open anaconda navigator or the anaconda prompt. I just did another restart and the issue still persists. Any idea why this might be happening? Things worked well after I updated to 1.5.1 so curious what might be happening.

**Comment by mmadei** [comment]
I'm having the same issue.


(C:\Users\teus_\Anaconda3) C:\Users\teus_>conda list
# packages in environment at C:\Users\teus_\Anaconda3:
#
_license                  1.1                      py35_1
_nb_ext_conf              0.3.0                    py35_0
alabaster                 0.7.9                    py35_0
anaconda                  4.2.0               np111py35_0
anaconda-clean            1.0.0                    py35_0
anaconda-client           1.5.1                    py35_0
anaconda-navigator        1.3.1                    py35_0
argcomplete               1.0.0                    py35_1
astroid                   1.4.7                    py35_0
astropy                   1.2.1               np111py35_0
babel                     2.3.4                    py35_0
backports                 1.0                      py35_0
beautifulsoup4            4.5.1                    py35_0
bitarray                  0.8.1                    py35_1
blaze                     0.10.1                   py35_0
bokeh                     0.12.2                   py35_0
boto                      2.42.0                   py35_0
bottleneck                1.1.0               np111py35_0
bzip2                     1.0.6                    vc14_3  [vc14]
cffi                      1.7.0                    py35_0
chest                     0.2.3                    py35_0
click                     6.6                      py35_0
cloudpickle               0.2.1                    py35_0
clyent                    1.2.2                    py35_0
colorama                  0.3.7                    py35_0
comtypes                  1.1.2                    py35_0
conda                     4.2.9                    py35_0
conda-build               2.0.2                    py35_0
configobj                 5.0.6                    py35_0
console_shortcut          0.1.1                    py35_1
contextlib2               0.5.3                    py35_0
cryptography              1.5                      py35_0
curl                      7.49.0                   vc14_0  [vc14]
cycler                    0.10.0                   py35_0
cython                    0.24.1                   py35_0
cytoolz                   0.8.0                    py35_0
dask                      0.11.0                   py35_0
datashape                 0.5.2                    py35_0
decorator                 4.0.10                   py35_0
dill                      0.2.5                    py35_0
docutils                  0.12                     py35_2
dynd-python               0.7.2                    py35_0
entrypoints               0.2.2                    py35_0
et_xmlfile                1.0.1                    py35_0
fastcache                 1.0.2                    py35_1
filelock                  2.0.6                    py35_0
flask                     0.11.1                   py35_0
flask-cors                2.1.2                    py35_0
freetype                  2.5.5                    vc14_1  [vc14]
get_terminal_size         1.0.0                    py35_0
gevent                    1.1.2                    py35_0
greenlet                  0.4.10                   py35_0
h5py                      2.6.0               np111py35_2
hdf5                      1.8.15.1                 vc14_4  [vc14]
heapdict                  1.0.0                    py35_1
icu                       57.1                     vc14_0  [vc14]
idna                      2.1                      py35_0
imagesize                 0.7.1                    py35_0
ipykernel                 4.5.0                    py35_0
ipython                   5.1.0                    py35_0
ipython_genutils          0.1.0                    py35_0
ipywidgets                5.2.2                    py35_0
itsdangerous              0.24                     py35_0
jdcal                     1.2                      py35_1
jedi                      0.9.0                    py35_1
jinja2                    2.8                      py35_1
jpeg                      8d                       vc14_2  [vc14]
jsonschema                2.5.1                    py35_0
jupyter                   1.0.0                    py35_3
jupyter_client            4.4.0                    py35_0
jupyter_console           5.0.0                    py35_0
jupyter_core              4.2.0                    py35_0
lazy-object-proxy         1.2.1                    py35_0
libdynd                   0.7.2                         0
libpng                    1.6.22                   vc14_0  [vc14]
libtiff                   4.0.6                    vc14_2  [vc14]
llvmlite                  0.13.0                   py35_0
locket                    0.2.0                    py35_1
lxml                      3.6.4                    py35_0
markupsafe                0.23                     py35_2
matplotlib                1.5.3               np111py35_0
menuinst                  1.4.1                    py35_0
mistune                   0.7.3                    py35_0
mkl                       11.3.3                        1
mkl-service               1.1.2                    py35_2
mpmath                    0.19                     py35_1
multipledispatch          0.4.8                    py35_0
nb_anacondacloud          1.2.0                    py35_0
nb_conda                  2.0.0                    py35_0
nb_conda_kernels          2.0.0                    py35_0
nbconvert                 4.2.0                    py35_0
nbformat                  4.1.0                    py35_0
nbpresent                 3.0.2                    py35_0
networkx                  1.11                     py35_0
nltk                      3.2.1                    py35_0
nose                      1.3.7                    py35_1
notebook                  4.2.3                    py35_0
numba                     0.28.1              np111py35_0
numexpr                   2.6.1               np111py35_0
numpy                     1.11.1                   py35_1
odo                       0.5.0                    py35_1
openpyxl                  2.3.2                    py35_0
openssl                   1.0.2j                   vc14_0  [vc14]
pandas                    0.18.1              np111py35_0
partd                     0.3.6                    py35_0
path.py                   8.2.1                    py35_0
pathlib2                  2.1.0                    py35_0
patsy                     0.4.1                    py35_0
pep8                      1.7.0                    py35_0
pickleshare               0.7.4                    py35_0
pillow                    3.3.1                    py35_0
pip                       8.1.2                    py35_0
pkginfo                   1.3.2                    py35_0
ply                       3.9                      py35_0
prompt_toolkit            1.0.3                    py35_0
psutil                    4.3.1                    py35_0
py                        1.4.31                   py35_0
pyasn1                    0.1.9                    py35_0
pycosat                   0.6.1                    py35_1
pycparser                 2.14                     py35_1
pycrypto                  2.6.1                    py35_4
pycurl                    7.43.0                   py35_0
pyflakes                  1.3.0                    py35_0
pygments                  2.1.3                    py35_0
pylint                    1.5.4                    py35_1
pyopenssl                 16.0.0                   py35_0
pyparsing                 2.1.4                    py35_0
pyqt                      5.6.0                    py35_0
pytables                  3.2.2               np111py35_4
pytest                    2.9.2                    py35_0
python                    3.5.2                         0
python-dateutil           2.5.3                    py35_0
pytz                      2016.6.1                 py35_0
pywin32                   220                      py35_1
pyyaml                    3.12                     py35_0
pyzmq                     15.4.0                   py35_0
qt                        5.6.0                    vc14_0  [vc14]
qtawesome                 0.3.3                    py35_0
qtconsole                 4.2.1                    py35_2
qtpy                      1.1.2                    py35_0
requests                  2.11.1                   py35_0
rope                      0.9.4                    py35_1
ruamel_yaml               0.11.14                  py35_0
scikit-image              0.12.3              np111py35_1
scikit-learn              0.17.1              np111py35_1
scipy                     0.18.1              np111py35_0
setuptools                27.2.0                   py35_1
simplegeneric             0.8.1                    py35_1
singledispatch            3.4.0.3                  py35_0
sip                       4.18                     py35_0
six                       1.10.0                   py35_0
snowballstemmer           1.2.1                    py35_0
sockjs-tornado            1.0.3                    py35_0
sphinx                    1.4.6                    py35_0
spyder                    3.0.0                    py35_0
sqlalchemy                1.0.13                   py35_0
statsmodels               0.6.1               np111py35_1
sympy                     1.0                      py35_0
tk                        8.5.18                   vc14_0  [vc14]
toolz                     0.8.0                    py35_0
tornado                   4.4.1                    py35_0
traitlets                 4.3.0                    py35_0
unicodecsv                0.14.1                   py35_0
vs2015_runtime            14.0.25123                    0
wcwidth                   0.1.7                    py35_0
werkzeug                  0.11.11                  py35_0
wheel                     0.29.0                   py35_0
widgetsnbextension        1.2.6                    py35_0
win_unicode_console       0.5                      py35_0
wrapt                     1.10.6                   py35_0
xlrd                      1.0.0                    py35_0
xlsxwriter                0.9.3                    py35_0
xlwings                   0.10.0                   py35_0
xlwt                      1.1.2                    py35_0
zlib                      1.2.8                    vc14_3  [vc14]

(C:\Users\teus_\Anaconda3) C:\Users\teus_>conda infoconda list
CommandNotFoundError: Command Error: error with command 'infoconda'. Command not found: 'infoconda'. Error: Could not locate 'conda-infoconda'

Did you mean one of these?
    info infoconda Error: Could not locate 'conda-infoconda'

Did you mean one of these?
    info

**Comment by psvrao** [comment]
I am facing exactly the same problem! The problem started I have run the followed two commands!
conda update conda
conda update anaconda

I ran them because, spyder disappeared from anaconda navigator home page, so I thought by running these I can upgrade to latest version of anaconda. 
Now I can open the navigator, but it is not launching any of the applications!
conda info
Current conda install:
            platform : win-64
          conda version : 4.3.29
       conda is private : False
      conda-env version : 4.3.29
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : C:\Anaconda3  (writable)
    default environment : C:\Anaconda3
       envs directories : C:\Anaconda3\envs
                          C:\Users\P Srinivasa Rao\AppData\Local\conda\conda\envs
                          C:\Users\P Srinivasa Rao\.conda\envs
          package cache : C:\Anaconda3\pkgs
                          C:\Users\P Srinivasa Rao\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\P Srinivasa Rao\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.29 requests/2.14.2 CPython/3.6.1 Windows/10 Windows/10.0.15063
          administrator : False

**Comment by psvrao** [comment]
(C:\Anaconda3) C:\Anaconda3>conda list --show-channel-urls
# packages in environment at C:\Anaconda3:
#
_license                  1.1                      py36_1    defaults
alabaster                 0.7.10                   py36_0    defaults
anaconda                  custom                   py36_0    defaults
anaconda-client           1.6.3                    py36_0    defaults
anaconda-navigator        1.6.8            py36h4b7dd57_0    defaults
anaconda-project          0.6.0                    py36_0    defaults
asn1crypto                0.22.0                   py36_0    defaults
astroid                   1.4.9                    py36_0    defaults
astropy                   1.3.2               np112py36_0    defaults
babel                     2.4.0                    py36_0    defaults
backports                 1.0                      py36_0    defaults
beautifulsoup4            4.6.0                    py36_0    defaults
bitarray                  0.8.1                    py36_1    defaults
blaze                     0.10.1                   py36_0    defaults
bleach                    1.5.0                    py36_0    defaults
bokeh                     0.12.5                   py36_1    defaults
boto                      2.46.1                   py36_0    defaults
bottleneck                1.2.1               np112py36_0    defaults
bzip2                     1.0.6                    vc14_3  [vc14]  defaults
cffi                      1.10.0                   py36_0    defaults
chardet                   3.0.3                    py36_0    defaults
chest                     0.2.3                    py36_0    defaults
click                     6.7                      py36_0    defaults
cloudpickle               0.2.2                    py36_0    defaults
clyent                    1.2.2                    py36_0    defaults
colorama                  0.3.9                    py36_0    defaults
comtypes                  1.1.2                    py36_0    defaults
conda                     4.3.29           py36h7c1b203_0    defaults
conda-env                 2.6.0                h36134e3_1    defaults
configobj                 5.0.6                    py36_0    defaults
console_shortcut          0.1.1                    py36_1    defaults
contextlib2               0.5.5                    py36_0    defaults
cryptography              1.8.1                    py36_0    defaults
curl                      7.52.1                   vc14_0  [vc14]  defaults
cycler                    0.10.0                   py36_0    defaults
cython                    0.25.2                   py36_0    defaults
cytoolz                   0.8.2                    py36_0    defaults
dask                      0.14.3                   py36_1    defaults
datashape                 0.5.4                    py36_0    defaults
decorator                 4.0.11                   py36_0    defaults
dill                      0.2.5                    py36_0    defaults
distributed               1.16.3                   py36_0    defaults
docutils                  0.13.1                   py36_0    defaults
entrypoints               0.2.2                    py36_1    defaults
et_xmlfile                1.0.1                    py36_0    defaults
fastcache                 1.0.2                    py36_1    defaults
flask                     0.12.2                   py36_0    defaults
flask-cors                3.0.2                    py36_0    defaults
freetype                  2.5.5                    vc14_2  [vc14]  defaults
get_terminal_size         1.0.0                    py36_0    defaults
gevent                    1.2.1                    py36_0    defaults
greenlet                  0.4.12                   py36_0    defaults
h5py                      2.7.0               np112py36_0    anaconda
hdf5                      1.8.15.1                 vc14_4  [vc14]  defaults
heapdict                  1.0.0                    py36_1    defaults
html5lib                  0.999                    py36_0    defaults
icu                       57.1                     vc14_0  [vc14]  defaults
idna                      2.5                      py36_0    defaults
imageio                   2.2.0            py36had6c2d2_0    anaconda
imagesize                 0.7.1                    py36_0    defaults
ipykernel                 4.6.1                    py36_0    defaults
ipython                   5.3.0                    py36_0    defaults
ipython_genutils          0.2.0                    py36_0    defaults
ipywidgets                6.0.0                    py36_0    defaults
isort                     4.2.5                    py36_0    defaults
itsdangerous              0.24                     py36_0    defaults
jdcal                     1.3                      py36_0    defaults
jedi                      0.10.2                   py36_2    defaults
jinja2                    2.9.6                    py36_0    defaults
jpeg                      9b                       vc14_0  [vc14]  defaults
jsonschema                2.6.0                    py36_0    defaults
jupyter                   1.0.0                    py36_3    defaults
jupyter_client            5.0.1                    py36_0    defaults
jupyter_console           5.1.0                    py36_0    defaults
jupyter_core              4.3.0                    py36_0    defaults
lazy-object-proxy         1.2.2                    py36_0    defaults
libpng                    1.6.27                   vc14_0  [vc14]  defaults
libtiff                   4.0.6                    vc14_3  [vc14]  defaults
libxgboost                0.60                 h1133f5d_0    anaconda
llvmlite                  0.18.0                   py36_0    defaults
locket                    0.2.0                    py36_1    defaults
lxml                      3.7.3                    py36_0    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
markupsafe                0.23                     py36_2    defaults
matplotlib                2.0.2               np112py36_0    anaconda
menuinst                  1.4.7                    py36_0    defaults
mistune                   0.7.4                    py36_0    defaults
mkl                       2017.0.1                      0    defaults
mkl-service               1.1.2                    py36_3    defaults
mlxtend                   0.7.0                    py36_0    conda-forge
mpmath                    0.19                     py36_1    defaults
msgpack-python            0.4.8                    py36_0    defaults
msys2-conda-epoch         20160418                      1    defaults
multipledispatch          0.4.9                    py36_0    defaults
navigator-updater         0.1.0                    py36_0    defaults
nbconvert                 5.1.1                    py36_0    defaults
nbformat                  4.3.0                    py36_0    defaults
networkx                  1.11                     py36_0    defaults
nltk                      3.2.3                    py36_0    defaults
nose                      1.3.7                    py36_1    defaults
notebook                  5.0.0                    py36_0    defaults
numba                     0.33.0              np112py36_0    defaults
numexpr                   2.6.2               np112py36_0    anaconda
numpy                     1.12.1                   py36_0    anaconda
numpydoc                  0.6.0                    py36_0    defaults
odo                       0.5.0                    py36_1    defaults
olefile                   0.44                     py36_0    defaults
openpyxl                  2.4.7                    py36_0    defaults
openssl                   1.0.2l                   vc14_0  [vc14]  defaults
packaging                 16.8                     py36_0    defaults
pandas                    0.20.1              np112py36_0    defaults
pandas-datareader         0.4.0                    py36_0    anaconda
pandocfilters             1.4.1                    py36_0    defaults
partd                     0.3.8                    py36_0    defaults
path.py                   10.3.1                   py36_0    defaults
pathlib2                  2.2.1                    py36_0    defaults
patsy                     0.4.1                    py36_0    defaults
pep8                      1.7.0                    py36_0    defaults
pickleshare               0.7.4                    py36_0    defaults
pillow                    4.1.1                    py36_0    defaults
pip                       9.0.1                    py36_1    defaults
ply                       3.10                     py36_0    defaults
prompt_toolkit            1.0.14                   py36_0    defaults
psutil                    5.2.2                    py36_0    defaults
py                        1.4.33                   py36_0    defaults
py-xgboost                0.60            py36np112h982e225_0    anaconda
pyasn1                    0.1.9                    py36_0    defaults
pycodestyle               2.3.1            py36h7cc55cd_0    defaults
pycosat                   0.6.2                    py36_0    defaults
pycparser                 2.17                     py36_0    defaults
pycrypto                  2.6.1                    py36_6    defaults
pycurl                    7.43.0                   py36_2    defaults
pyflakes                  1.5.0                    py36_0    defaults
pygments                  2.2.0                    py36_0    defaults
pylint                    1.6.4                    py36_1    defaults
pyodbc                    4.0.16                   py36_0    defaults
pyopenssl                 17.0.0                   py36_0    defaults
pyparsing                 2.1.4                    py36_0    defaults
pyqt                      5.6.0                    py36_2    defaults
pytables                  3.2.2               np112py36_4    anaconda
pytest                    3.0.7                    py36_0    defaults
python                    3.6.1                         2    defaults
python-dateutil           2.6.0                    py36_0    defaults
pytz                      2017.2                   py36_0    defaults
pywavelets                0.5.2               np112py36_0    defaults
pywin32                   220                      py36_2    defaults
pyyaml                    3.12                     py36_0    defaults
pyzmq                     16.0.2                   py36_0    defaults
qt                        5.6.2                    vc14_4  [vc14]  defaults
qtawesome                 0.4.4                    py36_0    defaults
qtconsole                 4.3.0                    py36_0    defaults
qtpy                      1.2.1                    py36_0    defaults
requests                  2.14.2                   py36_0    defaults
requests-file             1.4.1                    py36_0    anaconda
requests-ftp              0.3.1                    py36_0    anaconda
rope                      0.9.4                    py36_1    defaults
ruamel_yaml               0.11.14                  py36_1    defaults
scikit-image              0.13.0              np112py36_0    defaults
scikit-learn              0.18.1              np112py36_1    defaults
scipy                     0.19.0              np112py36_0    defaults
seaborn                   0.7.1                    py36_0    defaults
setuptools                27.2.0                   py36_1    defaults
simplegeneric             0.8.1                    py36_1    defaults
singledispatch            3.4.0.3                  py36_0    defaults
sip                       4.18                     py36_0    defaults
six                       1.10.0                   py36_0    defaults
snowballstemmer           1.2.1                    py36_0    defaults
sockjs-tornado            1.0.3                    py36_0    defaults
sortedcollections         0.5.3                    py36_0    defaults
sortedcontainers          1.5.7                    py36_0    defaults
sphinx                    1.5.6                    py36_0    defaults
spyder                    3.2.3            py36h132a2c8_0    defaults
sqlalchemy                1.1.9                    py36_0    defaults
statsmodels               0.8.0               np112py36_0    defaults
sympy                     1.0                      py36_0    defaults
tblib                     1.3.2                    py36_0    defaults
testpath                  0.3                      py36_0    defaults
tk                        8.5.18                   vc14_0  [vc14]  defaults
toolz                     0.8.2                    py36_0    defaults
tornado                   4.5.1                    py36_0    defaults
traitlets                 4.3.2                    py36_0    defaults
unicodecsv                0.14.1                   py36_0    defaults
vc                        14                   h2379b0c_1    anaconda
vs2015_runtime            14.0.25123                    0    defaults
wcwidth                   0.1.7                    py36_0    defaults
werkzeug                  0.12.2                   py36_0    defaults
wheel                     0.29.0                   py36_0    defaults
widgetsnbextension        2.0.0                    py36_0    defaults
win_unicode_console       0.5                      py36_0    defaults
wrapt                     1.10.10                  py36_0    defaults
xlrd                      1.0.0                    py36_0    defaults
xlsxwriter                0.9.6                    py36_0    defaults
xlwings                   0.10.4                   py36_0    defaults
xlwt                      1.2.0                    py36_0    defaults
zict                      0.1.2                    py36_0    defaults
zlib                      1.2.8                    vc14_3  [vc14]  defaults

**Comment by psvrao** [comment]
(C:\Anaconda3) C:\Anaconda3>anaconda-navigator
2017-10-11 11:29:06,849 - ERROR client_api._get_api_info:554
HTTPSConnectionPool(host='api.anaconda.org', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001A056E42320>, 'Connection to api.anaconda.org timed out. (connect timeout=0.5)'))

**Comment by psvrao** [comment]
any help on this will be greatly appreciated

**Comment by mingwandroid** [comment]
You have a connection timeout here by the look of it. I don't think this is something we can fix. You are also using a lot of old packages, another run of `conda update anaconda` should fix that, if not, try `conda update --all`

**Comment by psvrao** [comment]
Thanks for your quick response, Ray.

I have tried conda update anaconda, but still the same issue persists!

conda update --all, does it overwrite multiple environments that I have been running under anaconda3 so far? 
What happens to the python notebooks under jupyter instance(I have been launching thru anaconda navigator only till now), when we do these updates? Do we lose them all?
When I launch jupyter notebook from anaconda prompt now(since Navigator is not launching, tried this), it is launching a new jupyter instance where I can't see any of the notebooks that I had been working on till now!!!

Thanks once again for your help.

**Comment by mingwandroid** [comment]
`conda update --all` only updates the `software` in the current environment. It does not do anything with any of your own files which will reside in either %UserProfile% (i.e. for you, `C:\Users\teus_`) or else in the directory you were in when you launched `jupyter` from the `cmd.exe` console / `Anaconda Prompt`.

**Comment by psvrao** [comment]
Thanks, Ray. I shall try update all option now.
I used to launch jupyter from anaconda navigator, so if I want to get back the notebook files of that jupyter instance, where should I look at? Now if I launch jupyter from anaconda prompt, it is not picking up those files, and opening a completely new instance, and I am not able to launch from anaconda navigator, which is the main issue!

**Comment by ktuluv** [comment]
Hello I am having the same issue. 

I have uninstalled and reinstalled Anaconda Navigator, updated packages, Conda and Anaconda and nothing is working. This is what I get when I type 'anaconda-navigator':

Traceback (most recent call last):
  File "C:\Users\vargas.s.12\AppData\Local\Continuum\anaconda3\Scripts\anaconda-navigator-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\vargas.s.12\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\main.py", line 129, in main
    from anaconda_navigator.app.start import start_app
  File "C:\Users\vargas.s.12\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 32, in <module>
    from anaconda_navigator.widgets.main_window import MainWindow
  File "C:\Users\vargas.s.12\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 32, in <module>
    from anaconda_navigator.api.anaconda_api import AnacondaAPI
  File "C:\Users\vargas.s.12\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 33, in <module>
    from anaconda_navigator.api.client_api import ClientAPI
  File "C:\Users\vargas.s.12\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 24, in <module>
    from anaconda_navigator.api.conda_api import CondaAPI
  File "C:\Users\vargas.s.12\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 33, in <module>
    from anaconda_navigator.utils.findpip import PIP_LIST_SCRIPT
  File "C:\Users\vargas.s.12\AppData\Local\Continuum\anaconda3\lib\site-packages\anaconda_navigator\utils\findpip.py", line 22, in <module>
    import pip
  File "C:\Users\vargas.s.12\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\__init__.py", line 45, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "C:\Users\vargas.s.12\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\vcs\mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "C:\Users\vargas.s.12\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\download.py", line 40, in <module>
    from pip._vendor import requests, six
  File "C:\Users\vargas.s.12\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\_vendor\requests\__init__.py", line 98, in <module>
    from . import packages
  File "C:\Users\vargas.s.12\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\_vendor\requests\packages.py", line 12, in <module>
    sys.modules['pip._vendor.requests.packages.' + mod] = sys.modules["pip._vendor." + mod]
KeyError: 'pip._vendor.urllib3.contrib'

**Comment by cogle** [comment]
I'm experiencing the same issue as @ktuluv

**Comment by goanpeca** [comment]
You need to install pip 9.0.1, pip 9.0.2 made breaking changes unfortunately see https://github.com/pypa/pip/issues/5081.

You can open the Anaconda Prompt or terminal and run

```
conda install pip=9.0.1 --force
```

**Comment by obluesky** [comment]
I had the same problem before but somehow solved it. However, I had to reinstall Anaconda today and encountered exactly the same problem. I unfortunately forgot how I solved the problem, so spent whole (Satur)day searching for the solution I used. 
This one, I finally found, and it saved me again. (My problem was Anaconda command prompt would open but nothing, Spyder or Anaconda Navigator, else would launch)

The solution was to type in the Anaconda prompt: 

> pip install pyqt5 

Honestly, I have NO clue what this is, but worked for me twice in a row. I am a window 7 user, and installed the latest Anaconda as of 5/13/2018.

**Comment by chaitanya539** [comment]
@obluesky I tried every thing, but your solution works like a charm --> pip install pyqt5

Thanks a lot!

**Comment by psvrao** [comment]
for me even this is not working!!!

**Comment by regivm** [comment]
pip install pyqt5 worked for me too. Thanks

**Comment by obluesky** [comment]
@psvrao Do you have pip installed? If you don't you need to install it first. 

[](https://pip.pypa.io/en/stable/installing/)

**Comment by psvrao** [comment]
I am sorry, my communication was not correct. pip install pyqt5 executed
successfully. But I still have navigator issue of not opening jupyter
notebook, spyder or any other application in the anaconda navigator home
page!

**Comment by mingwandroid** [comment]
You really do not want to be running `pip install pyqt5`, please use `conda install pyqt` instead.

**Comment by MYounas** [comment]
Thankx @obluesky  the pyqt5 thing work,but why and how only God knows :D

**Comment by KBergers** [comment]
@mingwandroid "conda update --all" helped for me, thanks!

**Comment by shivamsawhney17** [comment]
@obluesky Worked like a charm .! Thanks a ton !

**Comment by alloulla** [comment]
Thank you very much
problem resolved with : pip install pyqt5

**Comment by PerwinCZ** [comment]
Thank you very much, installing pyqt5 solved the problem!

**Comment by lynch1972** [comment]
My Anaconda Navigator is also not Running. Can someone help?

I get this when I try to run anaconda-navigator from anaconda prompt:



Traceback (most recent call last):
  File "C:\Temp\anaconda3\lib\site-packages\qtpy\__init__.py", line 166, in <mod
ule>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Temp\anaconda3\Scripts\anaconda-navigator-script.py", line 6, in <mod
ule>
    from anaconda_navigator.app.main import main
  File "C:\Temp\anaconda3\lib\site-packages\anaconda_navigator\app\main.py", lin
e 22, in <module>
    from anaconda_navigator.utils.conda import is_conda_available
  File "C:\Temp\anaconda3\lib\site-packages\anaconda_navigator\utils\__init__.py
", line 15, in <module>
    from qtpy.QtGui import QIcon
  File "C:\Temp\anaconda3\lib\site-packages\qtpy\__init__.py", line 172, in <mod
ule>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

**Comment by XPav** [comment]
Same issue, same resolution with pip install pyqt5.

Running anaconda-navigator from the command prompt would result in no output, nothing starting, just another command prompt.

**Comment by chaitanyajalluri** [comment]
yeah pip install pyqt5 helped me too

Thanks a lot

**Comment by marlline** [comment]
it worked!!!! OMG. Why why why!!

**Comment by Pimpwhippa** [comment]
my anaconda stucks at loading applications...
I tried pip install pyqt5 but still it doesn't work
here is what I got when I put anaconda-navigator in anaconda prompt, seems like some app missing but not pyqt.
anybody still around to help? thanks!

(base) C:\Users\Pimwipa>anaconda-navigator
2018-07-26 13:40:37,611 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)

2018-07-26 13:40:37,611 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)

2018-07-26 13:40:37,611 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)

2018-07-26 13:40:37,611 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)

2018-07-26 13:40:37,611 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)

2018-07-26 13:40:37,611 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)

2018-07-26 13:40:37,611 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)

2018-07-26 13:40:37,611 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)

2018-07-26 13:40:37,626 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)

2018-07-26 13:40:37,626 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)

2018-07-26 13:40:37,626 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)

2018-07-26 13:40:37,626 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)

2018-07-26 13:40:37,642 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)

2018-07-26 13:40:37,642 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)

2018-07-26 13:40:37,642 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)

2018-07-26 13:40:37,642 - ERROR client_api._load_repodata:151
Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
  File "C:\Users\Pimwipa\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 442, in process_application_info
    self.post_setup(processed_apps)
  File "C:\Users\Pimwipa\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 457, in post_setup
    self.home_tab.setup_tab(apps, prefix=self.current_prefix)
  File "C:\Users\Pimwipa\Anaconda3\lib\site-packages\anaconda_navigator\widgets\tabs\home.py", line 253, in setup_tab
    self.set_applications(prefix=prefix)
  File "C:\Users\Pimwipa\Anaconda3\lib\site-packages\anaconda_navigator\widgets\tabs\home.py", line 267, in set_applications
    missing_apps = [app for app in linked_apps if app not in self.apps]
  File "C:\Users\Pimwipa\Anaconda3\lib\site-packages\anaconda_navigator\widgets\tabs\home.py", line 267, in <listcomp>
    missing_apps = [app for app in linked_apps if app not in self.apps]
TypeError: argument of type 'NoneType' is not iterable

**Comment by mingwandroid** [comment]
If this works for you then great not it's not solving the issue for people
who don't want to use pip

**Comment by thegnord** [comment]
pip install pyqt5
worked for me. So confused by Anaconda, all these packages, and associated craziness.
