### ISSUE TITLE
Problem with anaconda navigator on mac

### ISSUE THREAD

**Issue by Srivelivela** [ContinuumIO/anaconda-issues#1695]
When I try to run anaconda navigator( I have anaconda navigator 1.5.2) from the applications folder on my mac it starts to initialize and then it terminates. When I tried to run it with through terminal I got this : 

Traceback (most recent call last):
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 252, in save_config
    with open(config_file, 'w') as fd:
PermissionError: [Errno 13] Permission denied: '/Users/velivela/.continuum/anaconda-client/config.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/velivela/anaconda3/bin/anaconda-navigator", line 6, in <module>
    sys.exit(anaconda_navigator.app.main.main())
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/main.py", line 52, in main
    start_app(options)
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 90, in start_app
    window = run_app(splash)
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 43, in run_app
    window = MainWindow(splash=splash)
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/main_window.py", line 206, in __init__
    self.environments_tab = EnvironmentsTab(parent=self)
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/tabs/environments.py", line 132, in __init__
    data_directory=CHANNELS_PATH,
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/anaconda_navigator/widgets/manager/packages.py", line 382, in __init__
    self.api.client_set_domain(self.api.client_get_api_url())
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/anaconda_navigator/api/client_api.py", line 365, in set_domain
    binstar_client.utils.set_config(config)
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 260, in set_config
    save_config(data, USER_CONFIG if user else SYSTEM_CONFIG)
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/binstar_client/utils/config.py", line 255, in save_config
    raise BinstarError('%s: %s' % (exc.filename, exc.strerror,))
binstar_client.errors.BinstarError: /Users/velivela/.continuum/anaconda-client/config.yaml: Permission denied

The navigator works when I use sudo but I was wondering if there was a way to get the shortcut in applications to work or for it to work without using sudo everytime. Thank you

**Comment by Srivelivela** [comment]
Also when I use sudo and then open spyder from navigator spyder becomes unresponsive.

**Comment by goanpeca** [comment]
@Srivelivela please remove the `.continuum` folder.

You can go to the terminal and do

`sudo rm -rf ~/.continuum/`

And that should fix the problem

**Comment by Srivelivela** [comment]
Thank you @goanpeca I did that and now navigator works well 👍 . However spyder still does not run and when I run it from terminal I get : 

Failed to write user configuration file.
Please submit a bug report.
Traceback (most recent call last):
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/spyder/utils/external/lockfile.py", line 150, in lock
    symlink(str(os.getpid()), self.name)
FileExistsError: [Errno 17] File exists: '23752' -> '/Users/velivela/.spyder-py3/spyder.lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/spyder/utils/external/lockfile.py", line 177, in lock
    kill(int(pid), 0)
ProcessLookupError: [Errno 3] No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 77, in main
    lock_created = lock.lock()
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/spyder/utils/external/lockfile.py", line 196, in lock
    rmlink(self.name)
PermissionError: [Errno 13] Permission denied: '/Users/velivela/.spyder-py3/spyder.lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/spyder/config/user.py", line 111, in _save
    _write_file(fname)
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/spyder/config/user.py", line 107, in _write_file
    with open(fname, 'w', encoding='utf-8') as configfile:
PermissionError: [Errno 13] Permission denied: '/Users/velivela/.spyder-py3/spyder.ini'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/velivela/anaconda3/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 97, in main
    from spyder.app import mainwindow
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 115, in <module>
    from spyder.utils.qthelpers import qapplication, MENU_SEPARATOR
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/spyder/utils/qthelpers.py", line 26, in <module>
    from spyder.config.gui import get_shortcut
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/spyder/config/gui.py", line 168, in <module>
    set_default_color_scheme(_name, replace=False)
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/spyder/config/gui.py", line 164, in set_default_color_scheme
    set_color_scheme(name, sh.get_color_scheme(name), replace=replace)
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/spyder/config/gui.py", line 158, in set_color_scheme
    CONF.set(section, "names", sorted(list(set(names))))
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/spyder/config/user.py", line 437, in set
    self._save()
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/spyder/config/user.py", line 121, in _save
    raise(e)
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/spyder/config/user.py", line 115, in _save
    os.remove(fname)
PermissionError: [Errno 13] Permission denied: '/Users/velivela/.spyder-py3/spyder.ini'

**Comment by goanpeca** [comment]
@Srivelivela you need the latest spyder version (which I think fixes the error) in the meantime you can do

`sudo rm -rf /Users/velivela/.spyder-py3/spyder.lock`

**Comment by Srivelivela** [comment]
@goanpeca I did that and then used conda spyder update which updated me to version : 
spyder                    3.1.4                    py36_0  

but when I try to start spyder I still get : 
Failed to write user configuration file.
Please submit a bug report.
Traceback (most recent call last):
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 77, in main
    lock_created = lock.lock()
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/spyder/utils/external/lockfile.py", line 150, in lock
    symlink(str(os.getpid()), self.name)
PermissionError: [Errno 13] Permission denied: '24061' -> '/Users/velivela/.spyder-py3/spyder.lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/spyder/config/user.py", line 111, in _save
    _write_file(fname)
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/spyder/config/user.py", line 107, in _write_file
    with open(fname, 'w', encoding='utf-8') as configfile:
PermissionError: [Errno 13] Permission denied: '/Users/velivela/.spyder-py3/spyder.ini'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/velivela/anaconda3/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 97, in main
    from spyder.app import mainwindow
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 115, in <module>
    from spyder.utils.qthelpers import qapplication, MENU_SEPARATOR
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/spyder/utils/qthelpers.py", line 26, in <module>
    from spyder.config.gui import get_shortcut
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/spyder/config/gui.py", line 168, in <module>
    set_default_color_scheme(_name, replace=False)
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/spyder/config/gui.py", line 164, in set_default_color_scheme
    set_color_scheme(name, sh.get_color_scheme(name), replace=replace)
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/spyder/config/gui.py", line 158, in set_color_scheme
    CONF.set(section, "names", sorted(list(set(names))))
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/spyder/config/user.py", line 437, in set
    self._save()
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/spyder/config/user.py", line 121, in _save
    raise(e)
  File "/Users/velivela/anaconda3/lib/python3.6/site-packages/spyder/config/user.py", line 115, in _save
    os.remove(fname)
PermissionError: [Errno 13] Permission denied: '/Users/velivela/.spyder-py3/spyder.ini'

**Comment by goanpeca** [comment]
@ccordoba12 you know what is going on?

**Comment by ameliawilson** [comment]
I am having a problem opening Anaconda Navigator from the Applications icon as well... I also tried in the terminal "anaconda-navigator
-bash: anaconda-navigator: command not found"

I had Anaconda initially then I tried to remove it and reinstall with Python 3.6. Clearly I messed this up and I have no clue how to fix it.

**Comment by kehsan** [comment]
@ameliawilson try this: 

anaconda-navigator --reset
