### ISSUE TITLE
IPython fails to start

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#1745]
_From @rakeshgautam on May 19, 2017 7:8_

I installed Anaconda 4.3.1 for macOS 10.12.5 using Command Line Installer. Unfortunately 'ipython' or 'ipython notebook' or 'jupyter notebook' fails to start. It is giving some permission issue. The error message is given in the attached file. IPython also fails even if I try with sudo. 
[error.txt](https://github.com/conda/conda/files/1013384/error.txt)

_Copied from original issue: conda/conda#5376_

**Comment by kalefranz** [comment]
_From @mingwandroid on May 19, 2017 8:30_

Did you use `sudo` during installation? Please do not do that. If you can try the following that would be helpful:

```
pushd /tmp
curl -SLO https://repo.continuum.io/archive/Anaconda3-4.3.1-MacOSX-x86_64.sh
bash Anaconda3-4.3.1-MacOSX-x86_64.sh -bfp /tmp/ac3
source /tmp/ac3/bin/activate
ipython
```

**Comment by kalefranz** [comment]
_From @rakeshgautam on May 19, 2017 8:39_

Thank you very mingwandroid!!
Could you please tell me how can I install anaconda without sudo in /opt/... directory?

**Comment by kalefranz** [comment]
_From @mingwandroid on May 19, 2017 8:42_

`sudo chown -R $USER:$(id -g -n) /opt`? (but if this damages anything do not hold me responsible. I would only ever recommend installing per-user software to `$HOME`).

**Comment by kalefranz** [comment]
_From @rakeshgautam on May 19, 2017 8:52_

Thanks again for your clear explanation. Even with sudo I am getting the following error:

[rakesh ~]$ sudo jupyter notebook --allow-root
[I 14:20:15.485 NotebookApp] Serving notebooks from local directory: /Users/rakesh
[I 14:20:15.486 NotebookApp] 0 active kernels 
[I 14:20:15.486 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=1d1c4957b6f2117600b11e5bb580604388bc0aac88b337b5
[I 14:20:15.486 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 14:20:15.486 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=1d1c4957b6f2117600b11e5bb580604388bc0aac88b337b5
0:97: execution error: "http://localhost:8888/tree?token=2fb9cfc97577d9b3611c5be3aee36133eab9924796f11f97" doesn’t understand the “open location” message. (-1708)
...

BTW Intel-Python is installed in /opt/... directory and it works without any problem.

**Comment by kalefranz** [comment]
_From @mingwandroid on May 19, 2017 8:58_

After changing the permissions of the /opt folder, you should not need to use `sudo` again (or --allow-root).

**Comment by kalefranz** [comment]
_From @rakeshgautam on May 19, 2017 9:4_

You are right mingwandroid, but why I am getting the error message?

**Comment by kalefranz** [comment]
_From @mingwandroid on May 19, 2017 9:8_

Which error?

My recommendation is that you start from the start. Remove all traces of `Anaconda` from `/opt` and re-install everything into your `$HOME` directory instead:

```
pushd /tmp
curl -SLO https://repo.continuum.io/archive/Anaconda3-4.3.1-MacOSX-x86_64.sh
bash Anaconda3-4.3.1-MacOSX-x86_64.sh -bfp ${HOME}/ac3
source ${HOME}/ac3/bin/activate
ipython
```

.. and if that works then good. Permissions are tricky things and best avoided by installing to `$HOME` and never using `sudo` (which is very dangerous anyway).

**Comment by kalefranz** [comment]
_From @rakeshgautam on May 19, 2017 9:10_

I mean the message after 
[rakesh ~]$ sudo jupyter notebook --allow-root

**Comment by kalefranz** [comment]
_From @mingwandroid on May 19, 2017 9:12_

I am not an expert in `jupyter` but it looks like some permissions problem I guess. Don't use `--allow-root` or `sudo` and you will not have permissions problems.

**Comment by kalefranz** [comment]
_From @rakeshgautam on May 19, 2017 9:36_

I freshly installed anaconda in my $HOME directory and still I am getting the same message error for ipython.

[rakesh ~]$ jupyter notebook
[I 15:04:18.494 NotebookApp] Serving notebooks from local directory: /Users/rakesh
[I 15:04:18.494 NotebookApp] 0 active kernels 
[I 15:04:18.494 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=7f9e08576f931d3eb5b113bfc924db3a5373b8325c4ea946
[I 15:04:18.494 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 15:04:18.495 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=7f9e08576f931d3eb5b113bfc924db3a5373b8325c4ea946
0:97: execution error: "http://localhost:8888/tree?token=c37428fa586105d7b5578ff9136d4f96848ad164acbfa338" doesn’t understand the “open location” message. (-1708)

**Comment by kalefranz** [comment]
_From @mingwandroid on May 19, 2017 9:43_

https://github.com/jupyter/notebook/issues/2438

**Comment by kalefranz** [comment]
_From @mingwandroid on May 19, 2017 9:46_

The contents of `error.txt` attached to the first comment here is:

```
[rakesh ~]$ jupyter notebook
Traceback (most recent call last):
  File "/opt/continuum/condapython3/bin/jupyter-notebook", line 6, in <module>
    sys.exit(notebook.notebookapp.main())
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1290, in initialize
    super(NotebookApp, self).initialize(argv)
  File "<decorator-gen-6>", line 2, in initialize
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/jupyter_core/application.py", line 243, in initialize
    self.migrate_config()
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/jupyter_core/application.py", line 162, in migrate_config
    from .migrate import get_ipython_dir, migrate
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/jupyter_core/migrate.py", line 35, in <module>
    from IPython.paths import get_ipython_dir
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 88, in <module>
    class TerminalInteractiveShell(InteractiveShell):
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 131, in TerminalInteractiveShell
    highlighting: \n %s""" % ', '.join(get_all_styles())
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/pygments/styles/__init__.py", line 79, in get_all_styles
    for name, _ in find_plugin_styles():
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/pygments/plugin.py", line 62, in find_plugin_styles
    for entrypoint in iter_entry_points(STYLE_ENTRY_POINT):
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/pygments/plugin.py", line 45, in iter_entry_points
    import pkg_resources
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2985, in <module>
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2971, in _call_aside
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2998, in _initialize_master_working_set
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 651, in _build_master
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 644, in __init__
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 700, in add_entry
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1990, in find_on_path
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2399, in from_location
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2740, in _reload_version
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2364, in _version_from_file
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2532, in _get_metadata
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1472, in get_metadata_lines
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1468, in get_metadata
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1577, in _get
PermissionError: [Errno 13] Permission denied: '/opt/continuum/condapython3/lib/python3.6/site-packages/llvmlite-0.18.0-py3.6.egg-info/PKG-INFO'
```

and, checking that file we see very restrictive permissions:

```
ls -l lib/python3.6/site-packages/llvmlite-0.18.0-py3.6.egg-info/PKG-INFO 
-rw-------  2 rdonnelly  wheel  768  4 May 21:41 lib/python3.6/site-packages/llvmlite-0.18.0-py3.6.egg-info/PKG-INFO
```

@sklam is this something for you?

**Comment by kalefranz** [comment]
This does indeed look like a packaging problem.

Confirmed that the file at https://repo.continuum.io/pkgs/free/osx-64/llvmlite-0.18.0-py36_0.tar.bz2 has permissions that are too restrictive.

```
kfranz@0283:~/Downloads/llvmlite-0.18.0-py36_0/lib/python3.6/site-packages ❯ ls -al llvmlite-0.18.0-py3.6.egg-info/
total 32
drwxr-xr-x@ 6 kfranz  staff   204B May 19 09:16 ./
drwxr-xr-x@ 4 kfranz  staff   136B May 19 09:16 ../
-rw-------@ 1 kfranz  staff   768B May  4 15:41 PKG-INFO
-rw-------@ 1 kfranz  staff   1.7K May  4 15:41 SOURCES.txt
-rw-------@ 1 kfranz  staff     1B May  4 15:41 dependency_links.txt
-rw-------@ 1 kfranz  staff     9B May  4 15:41 top_level.txt
kfranz@0283:~/Downloads/llvmlite-0.18.0-py36_0/lib/python3.6/site-packages ❯ ls -al llvmlite
total 80
drwxr-xr-x@ 11 kfranz  staff   374B May 19 09:16 ./
drwxr-xr-x@  4 kfranz  staff   136B May 19 09:16 ../
-rw-------@  1 kfranz  staff   308B Dec 28 10:52 __init__.py
drwxr-xr-x@  6 kfranz  staff   204B May 19 09:16 __pycache__/
-rw-------@  1 kfranz  staff   418B May  4 15:41 _version.py
drwxr-xr-x@ 20 kfranz  staff   680B May 19 09:16 binding/
drwxr-xr-x@ 12 kfranz  staff   408B May 19 09:16 ir/
drwxr-xr-x@  6 kfranz  staff   204B May 19 09:16 llvmpy/
-rw-------@  1 kfranz  staff    27K Dec 28 10:52 six.py
drwxr-xr-x@ 10 kfranz  staff   340B May 19 09:16 tests/
-rw-------@  1 kfranz  staff   696B Dec 28 10:52 utils.py
```

There could be other affected files.

Is there a reason we aren't checking this with anaconda-verify/conda-verify (at least warning about it)?

**Comment by sklam** [comment]
@kalefranz, I don't see this problem with the packages we uploaded to anaconda.org: https://anaconda.org/numba/llvmlite/0.18.0/download/linux-64/llvmlite-0.18.0-py36_0.tar.bz2

```bash
buildbot@numba-linux64-gpu:~/sktemp/lib/python3.6/site-packages$ ls -la llvmlite*
llvmlite:
total 68
drwxrwxr-x 7 buildbot buildbot  4096 May 19 10:21 .
drwxrwxr-x 4 buildbot buildbot  4096 May 19 10:21 ..
drwxrwxr-x 3 buildbot buildbot  4096 May 19 10:21 binding
-rw-r--r-- 1 buildbot buildbot   308 May  1 13:20 __init__.py
drwxrwxr-x 3 buildbot buildbot  4096 May 19 10:21 ir
drwxrwxr-x 3 buildbot buildbot  4096 May 19 10:21 llvmpy
drwxrwxr-x 2 buildbot buildbot  4096 May 19 10:21 __pycache__
-rw-r--r-- 1 buildbot buildbot 27760 May  1 13:20 six.py
drwxrwxr-x 3 buildbot buildbot  4096 May 19 10:21 tests
-rw-r--r-- 1 buildbot buildbot   696 May  1 13:20 utils.py
-rw-r--r-- 1 buildbot buildbot   418 May  4 15:37 _version.py

llvmlite-0.18.0-py3.6.egg-info:
total 24
drwxrwxr-x 2 buildbot buildbot 4096 May 19 10:21 .
drwxrwxr-x 4 buildbot buildbot 4096 May 19 10:21 ..
-rw-r--r-- 1 buildbot buildbot    1 May  4 15:37 dependency_links.txt
-rw-r--r-- 1 buildbot buildbot  768 May  4 15:37 PKG-INFO
-rw-r--r-- 1 buildbot buildbot 1747 May  4 15:37 SOURCES.txt
-rw-r--r-- 1 buildbot buildbot    9 May  4 15:37 top_level.txt
```

can you verify that?

**Comment by mingwandroid** [comment]
The problem was on macOS, not Linux. Confirmed on the latest package currently on anaconda.org:

```
curl -SLO https://anaconda.org/numba/llvmlite/0.18.0/download/osx-64/llvmlite-0.18.0-py36_0.tar.bz2
tar -xf llvmlite-0.18.0-py36_0.tar.bz2
ls -l ./lib/python3.6/site-packages/llvmlite-0.18.0-py3.6.egg-info/PKG-INFO
-rw-------  1 rdonnelly  wheel  768  4 May 21:41 ./lib/python3.6/site-packages/llvmlite-0.18.0-py3.6.egg-info/PKG-INFO
```

**Comment by sklam** [comment]
I can confirm it happening inside our buildbot env

**Comment by sklam** [comment]
Updating conda and conda-buld fixed the problem.  For some historical reason, we pinned to:

```
        conda version : 4.1.9
    conda-env version : 2.5.2
  conda-build version : 1.21.14+0.g4dfebe9.dirty
```

Is there anything we need to do on llvmlite side to fix this issue?  
Btw, I believe numba packages are also affected.

**Comment by mingwandroid** [comment]
I think you need to 'physically' modify the permissions and then re-package it. At install time, `conda` does not do anything with permissions (though maybe it should in the future?), perhaps @ilanschnell would be able to help out with this, but it's likely that `tar -xf`, `chmod -R u+r,u+w,g+r,g+w,o+r *` , `tar -cjf` and then re-uploading to anaconda.org would be a good help.

**Comment by sklam** [comment]
I have triggered a rebuild for llvmlite and the osx packages on https://anaconda.org/numba/llvmlite/files?version=0.18.0 should be fixed.  I checked "osx-64/llvmlite-0.18.0-py36_0.tar.bz2".

**Comment by mingwandroid** [comment]
Thanks @sklam.

**Comment by rakeshgautam** [comment]
Thanks to all of you for your kind replies. Unfortunately I am still getting permission issue even after updating llvmlite. I did update using 'sudo conda update --all'.

[rakesh ~]$ jupyter notebook
Traceback (most recent call last):
  File "/opt/continuum/condapython3/bin/jupyter-notebook", line 6, in <module>
    sys.exit(notebook.notebookapp.main())
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1296, in initialize
    self.init_webapp()
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1093, in init_webapp
    self.jinja_environment_options
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/notebook/notebookapp.py", line 167, in __init__
    default_url, settings_overrides, jinja_env_options)
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/notebook/notebookapp.py", line 259, in init_settings
    nbextensions_path=jupyter_app.nbextensions_path,
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/notebook/notebookapp.py", line 807, in nbextensions_path
    from IPython.paths import get_ipython_dir
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 88, in <module>
    class TerminalInteractiveShell(InteractiveShell):
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 131, in TerminalInteractiveShell
    highlighting: \n %s""" % ', '.join(get_all_styles())
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/pygments/styles/__init__.py", line 79, in get_all_styles
    for name, _ in find_plugin_styles():
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/pygments/plugin.py", line 62, in find_plugin_styles
    for entrypoint in iter_entry_points(STYLE_ENTRY_POINT):
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/pygments/plugin.py", line 45, in iter_entry_points
    import pkg_resources
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2985, in <module>
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2971, in _call_aside
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2998, in _initialize_master_working_set
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 651, in _build_master
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 644, in __init__
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 700, in add_entry
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1990, in find_on_path
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2399, in from_location
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2740, in _reload_version
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2364, in _version_from_file
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2532, in _get_metadata
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1472, in get_metadata_lines
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1468, in get_metadata
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1577, in _get
PermissionError: [Errno 13] Permission denied: '/opt/continuum/condapython3/lib/python3.6/site-packages/llvmlite-0.18.0-py3.6.egg-info/PKG-INFO'

**Comment by ilanschnell** [comment]
I've updated the OSX llvmlite packages on defaults from the new packages on the `numba` packages.

**Comment by sushmit86** [comment]
I am also getting this error

**Comment by mingwandroid** [comment]
Did you execute `conda update llvmlite`?

**Comment by Huade** [comment]
Updating conda and conda-buld did not fixed my problem. I still have same error after execute `conda update llvmlite`.

```
0:97: execution error: "http://localhost:8888/tree?token=..." doesn’t understand the “open location” message. (-1708)
```

**Comment by innertron** [comment]
I am also getting the error 
![screen shot 2017-06-05 at 11 33 27 pm](https://cloud.githubusercontent.com/assets/81753/26815083/66f3b44e-4a47-11e7-90c9-0b2a8bb668ad.png)

**Comment by innertron** [comment]
I can't believe that Anaconda would let this error hang around for so long.  I have read countless reports on this an d tried sop many things.  I'm just about to give up on Anaconda

**Comment by drsimonmartin** [comment]
I have the same issue. The command jupyter-notebook fails in the same manner as above. Launching jupiter via Navigator also fails (not a surprise, but worth checking.) 
The llvm permissions look OK. I have also done a clean install of anaconda. I think that leaves the comment by kalefranz about other packages being affected

**Comment by mingwandroid** [comment]
It is very unfortunate when people morph bug reports instead of opening a new issue as it leads to problematic miscommunication (the reason behind that is because this issue started on the mailing list which isn't the best forum for reporting issues).

There are two completely separate issues here, the llvm permissions issue which is fixed and the upstream issue which @kalefranz and I pointed out [here](https://github.com/ContinuumIO/anaconda-issues/issues/1745#issuecomment-302715395), appears to be  Apple's fault and is apparently fixed in the latest 10.12.6 beta: https://github.com/jupyter/notebook/issues/2438#issuecomment-305425917

If you require a workaround in the meantime, again, from that thread, 21 days ago: https://github.com/jupyter/notebook/issues/2438#issuecomment-301736816

@innertron @drsimonmartin, please let us know if this works for you.

**Comment by drsimonmartin** [comment]
Sorry, I had been led to this thread via a google search and many of the problems matched mine. 

Yes, changing the notebook-config file sorted things. Thanks.

Simon
