### ISSUE TITLE
Anaconda fails with spaces in installation path on Windows

### ISSUE THREAD

**Issue by ARF1** [ContinuumIO/anaconda-issues#248]
Installing anaconda in a path with with spaces causes (at least) `conda` to fail:

```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\Example User>echo "%PATH%"
"C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\Win
dowsPowerShell\v1.0\;C:\Program Files\TortoiseHg\;"C:\Users\Example User\Anaconda"
;"C:\Users\Example User\Anaconda\Scripts";"

C:\Users\Example User>conda
failed to create process.
```

**Comment by asmeurer** [comment]
Was that PATH entry created by the installer or did you add it manually?

**Comment by asmeurer** [comment]
The issue might be that you have quotes in your path entries, which are unnecessary.

**Comment by ARF1** [comment]
I added the paths to try whether it would help anything. Apart from adding the quotes, the installation was pristine.

**Comment by endolith** [comment]
Same problem here.  Changing the PATH entries to use 8.3 names fixed it.

**Comment by maysonicboom** [comment]
Happens on Mac too – and given that the default HDD name is "Macintosh HD", why it hasn't been fixed is kinda off-putting.

**Comment by msarahan** [comment]
This has been fixed on windows for a little while now. Please create a new issue for your Mac problems. Please post the version that you are trying to install, the path you are trying to install to, and any other details you feel might be helpful.

**Comment by endolith** [comment]
I installed Anaconda 4.0.0 on a Windows 7 machine and it was not fixed.  Running 'conda' fails with     `failed to create process`.

https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/wlibvnzd7QA

`C:\Users\User Name\Anaconda2\Scripts\conda.exe` does not work

Changing the install path to one without spaces made it work again.

**Comment by msarahan** [comment]
@endolith these are two separate issues.  If the installer fails, it is very different from conda failing after the installer has succeeded.  The potential causes of the latter are much greater: improper quoting somewhere, but exactly where is hard to say.  Maybe PATH - what is your value there?

**Comment by srastgou** [comment]
![image](https://user-images.githubusercontent.com/41519462/43478347-464ac94a-94c3-11e8-8241-4583a8279e8b.png)

**Comment by srastgou** [comment]
how can I fix this problem?

**Comment by srastgou** [comment]
How can I fix this problem, while I cannot install anywhere else
