### ISSUE TITLE
Installation Failed on Mac

### ISSUE THREAD

**Issue by anduong** [ContinuumIO/anaconda-issues#3864]
<img width="620" alt="screen shot 2017-08-03 at 3 08 01 pm" src="https://user-images.githubusercontent.com/6139560/28915429-4c0eebee-7869-11e7-99be-3de6c38ebe86.png">

OS: MacOS El Capitan
Python 2 & 3 Installed
```bash
/usr/local/bin/python
/usr/bin/python
/usr/local/bin/python3
```

What should I do to get Anaconda installed on my computer?

**Comment by mingwandroid** [comment]
Please try again the latest Anaconda 5.0.1 release and if it fails, reopen this issue and paste the contents of /var/log/install.log` here.

BTW, Anaconda is independent of any Pythons you may have installed on your system already. It should not care nor use any of those since it comes with its own.

**Comment by DheerajAgarwal** [comment]
I encountered this issue today. Can this be re-opened by someone with privileges.
```

“Anaconda3-5.0.1-MacOSX-x86_64.pkg”.} {
	    NSFilePath = "./preinstall";
	    NSLocalizedDescription = "An error occurred while running scripts from the package \U201cAnaconda3-5.0.1-MacOSX-x86_64.pkg\U201d.";
	    NSURL = "file://localhost/Users/ouj070/Downloads/Anaconda3-5.0.1-MacOSX-x86_64.pkg#apreinstall.pkg";
	    PKInstallPackageIdentifier = "io.continuum.pkg.apreinstall";
	}
Jan 17 13:52:02 acbc32aa8717 installd[668]: PackageKit: Running idle tasks
Jan 17 13:52:02 acbc32aa8717 Installer[20250]: install:didFailWithError:Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “Anaconda3-5.0.1-MacOSX-x86_64.pkg”." UserInfo={NSFilePath=./preinstall, NSURL=file://localhost/Users/ouj070/Downloads/Anaconda3-5.0.1-MacOSX-x86_64.pkg#apreinstall.pkg, PKInstallPackageIdentifier=io.continuum.pkg.apreinstall, NSLocalizedDescription=An error occurred while running scripts from the package “Anaconda3-5.0.1-MacOSX-x86_64.pkg”.}
Jan 17 13:52:02 acbc32aa8717 installd[668]: PackageKit: Removing client PKInstallDaemonClient pid=20250, uid=2006267947 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
Jan 17 13:52:06 acbc32aa8717 installd[668]: PackageKit: Done with sandbox removals
Jan 17 13:52:13 acbc32aa8717 Installer[20250]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Jan 17 13:52:13 acbc32aa8717 Installer[20250]: IFDInstallController 4164A0 state = 8
Jan 17 13:52:13 acbc32aa8717 Installer[20250]: Displaying 'Install Failed' UI.
Jan 17 13:52:13 acbc32aa8717 Installer[20250]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.
```

**Comment by DheerajAgarwal** [comment]
I am on 10.12 however the issue is resolved. Apparently there were some folders which could not be overwritten. I had to manually remove them and then the installation went fine.

**Comment by ScottM42** [comment]
I encountered this issue today on OSX 10.11.6 El Capitan.  If it's a directory permission issue, how can you find which ones and can that be displayed?

 PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “Anaconda3-5.1.0-MacOSX-x86_64.pkg”." UserInfo={NSFilePath=./preinstall, NSURL=file://localhost/Users/scott/Downloads/Anaconda3-5.1.0-MacOSX-x86_64.pkg#apreinstall.pkg, PKInstallPackageIdentifier=io.continuum.pkg.apreinstall, NSLocalizedDescription=An error occurred while running scripts from the package “Anaconda3-5.1.0-MacOSX-x86_64.pkg”.} {
	    NSFilePath = "./preinstall";
	    NSLocalizedDescription = "An error occurred while running scripts from the package \U201cAnaconda3-5.1.0-MacOSX-x86_64.pkg\U201d.";
	    NSURL = "file://localhost/Users/scott/Downloads/Anaconda3-5.1.0-MacOSX-x86_64.pkg#apreinstall.pkg";
	    PKInstallPackageIdentifier = "io.continuum.pkg.apreinstall";
	}
Installer[80225]: install:didFailWithError:Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “Anaconda3-5.1.0-MacOSX-x86_64.pkg”." UserInfo={NSFilePath=./preinstall, NSURL=file://localhost/Users/scott/Downloads/Anaconda3-5.1.0-MacOSX-x86_64.pkg#apreinstall.pkg, PKInstallPackageIdentifier=io.continuum.pkg.apreinstall, NSLocalizedDescription=An error occurred while running scripts from the package “Anaconda3-5.1.0-MacOSX-x86_64.pkg”.}
installd[80150]: PackageKit: Removing client PKInstallDaemonClient pid=80225, uid=503 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
Installer[80225]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Installer[80225]: IFDInstallController DE658910 state = 8
 Installer[80225]: Displaying 'Install Failed' UI.
Installer[80225]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.

**Comment by charlesfmatula** [comment]
i rebooted and open Anaconda3-2019.03-MacOSX-x86_64.pkg, from the command line
still failed

**Comment by charlesfmatula** [comment]
trying  sudo open Anaconda3-2019.03-MacOSX-x86_64.pkg
if its a permission issue, this should help?

**Comment by charlesfmatula** [comment]
mac os 10.14.4,  still failing

**Comment by EzequielAndres** [comment]
Same here, it is failing. I have Catalina 10.15 Beta..could this be the problem?

**Comment by amojabi** [comment]
Me too, same as above. I have Catalina beta installed, and cannot get anaconda installed, no matter what i do.

**Comment by naviat** [comment]
me too, it's very distasteful

**Comment by jonifreidkes** [comment]
I'm having the same problem, 10.9.5. Tried previous versions (5.0.0) but didn't work either.

**Comment by aliabbasss9** [comment]
> I am on 10.12 however the issue is resolved. Apparently there were some folders which could not be overwritten. I had to manually remove them and then the installation went fine.

hello brother, i cant install it properly can you please guide me?

**Comment by amojabi** [comment]
I had the Beta MacOS on my machine. I think it was causing some sort of conflict. Once I was able to update, the Anaconda installer worked fine.
