### ISSUE TITLE
can't get font information in pygame installed in Anaconda

### ISSUE THREAD

**Issue by johnsonzhj** [ContinuumIO/anaconda-issues#480]
I have installed pygame on anaconda on Mac OS 10.9 following the method explained by the last answer from this link
http://92.42.51.245.cancer.iwanslphotography.com/nph-p.cgi/20/http/stackoverflow.com/questions/29137369/installing-pygame-module-in-anaconda-mac=3frq=3d1

after import pygame,when I type

    pygame.font.get_fonts()
I got the following error, what's wrong with this and how can I solve it?

    /Users/qiangshen/anaconda/lib/python2.7/site-packages/spyderlib/widgets/externalshell/start_ipython_kernel.py:1: RuntimeWarning: use font: dlopen(/Users/qiangshen/anaconda/lib/python2.7/site-packages/pygame/font.so, 2): Library not loaded: /usr/local/lib/libSDL_ttf-2.0.0.dylib Referenced from: /Users/qiangshen/anaconda/lib/python2.7/site-packages/pygame/font.so Reason: image not found (ImportError: dlopen(/Users/qiangshen/anaconda/lib/python2.7/site-packages/pygame/font.so, 2): Library not loaded: /usr/local/lib/libSDL_ttf-2.0.0.dylib Referenced from: /Users/qiangshen/anaconda/lib/python2.7/site-packages/pygame/font.so Reason: image not found) # -- coding: utf-8 -- Traceback (most recent call last):
    
    File "", line 1, in pygame.font.get_fonts()
    
    File "/Users/qiangshen/anaconda/lib/python2.7/site-packages/pygame/init.py", line 102, in getattr raise NotImplementedError(MissingPygameModule)
    
    NotImplementedError: font module not available (ImportError: dlopen(/Users/qiangshen/anaconda/lib/python2.7/site-packages/pygame/font.so, 2): Library not loaded: /usr/local/lib/libSDL_ttf-2.0.0.dylib Referenced from: /Users/qiangshen/anaconda/lib/python2.7/site-packages/pygame/font.so Reason: image not found)

**Comment by varadgunjal** [comment]
I'm having the same issue. Any fixes available for this?

**Comment by melki** [comment]
Same issue =)

**Comment by jvansan** [comment]
This issue is still persisting. Has anyone looked into this?

**Comment by MartinHeroux** [comment]
Same issue here. Any solutions?

**Comment by manjugoudreddy** [comment]
Even I am getting same issues, any solutions please?

**Comment by MartinHeroux** [comment]
You have initialize pygame before trying to change fonts, etc. Have pygame.init () in you code before trying to change fonts.  Worked for me.

**Comment by manjugoudreddy** [comment]
Thanks for the suggestion, however I am calling self.pygame.init() and I still get the error.
Any alternatives solutions please.

**Comment by MartinHeroux** [comment]
Are you using Mac pc or Linux?

**Comment by manjugoudreddy** [comment]
I am on ubuntu.

**Comment by manjugoudreddy** [comment]
I am managed to fix the issue by installing different version (cogsci pygame) of pygame.
Apart of this I installed some other packages missing, which is purely required by my application.

**Comment by saberdhaouadi** [comment]
I had the same issue on mac os sierra, with python2.7 and pygame. I downloaded python2.7-32 bits and now it is ok ,I can import the fonts.

**Comment by QuangHoang** [comment]
same issue on MAC, it hangs the program, got this error when I broke it.

Traceback (most recent call last):
  File "/Users/hoangq/Projects/python/pygame/test/main.py", line 8, in <module>
    game.run()
  File "/Users/hoangq/Projects/python/pygame/test/qg.py", line 22, in run
    print(pygame.font.get_fonts())
  File "/usr/local/lib/python2.7/site-packages/pygame/sysfont.py", line 333, in get_fonts
    initsysfonts()
  File "/usr/local/lib/python2.7/site-packages/pygame/sysfont.py", line 230, in initsysfonts
    fonts = initsysfonts_darwin()
  File "/usr/local/lib/python2.7/site-packages/pygame/sysfont.py", line 146, in initsysfonts_darwin
    fonts = initsysfonts_unix("/usr/X11/bin/fc-list")
  File "/usr/local/lib/python2.7/site-packages/pygame/sysfont.py", line 167, in initsysfonts_unix
    close_fds=True).communicate()
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 800, in communicate
    return self._communicate(input)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1419, in _communicate
    stdout, stderr = self._communicate_with_select(input)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1520, in _communicate_with_select
    rlist, wlist, xlist = select.select(read_set, write_set, [])
KeyboardInterrupt

**Comment by mingwandroid** [comment]
You are attempting to mix Homebrew software with Anaconda Distribution software. Please don't do this it is doomed to failure.

Unfortunately we don't provide pygame as it's very complicated to build.
