### ISSUE TITLE
Spyder can't find PyQT

### ISSUE THREAD

**Issue by sergeyf** [ContinuumIO/anaconda-issues#504]
I did a `conda update --all` today and now Spyder won't open. The following error comes up:

```
C:\Anaconda>spyder
Traceback (most recent call last):
  File "C:\Anaconda\Scripts\spyder-script.py", line 2, in <module>
    start_app.main()
  File "C:\Anaconda\lib\site-packages\spyderlib\start_app.py", line 114, in main
    from spyderlib import spyder
  File "C:\Anaconda\lib\site-packages\spyderlib\spyder.py", line 48, in <module>
    requirements.check_qt()
  File "C:\Anaconda\lib\site-packages\spyderlib\requirements.py", line 50, in check_qt
    % (qt_infos['pyqt']+qt_infos['pyside']))
  File "C:\Anaconda\lib\site-packages\spyderlib\requirements.py", line 25, in show_warning
    raise RuntimeError(message)
RuntimeError: Please check Spyder installation requirements:
PyQt4 4.6+ (or PySide 1.2.0+) is required.
```

PyQT is installed, and everything was working fine an hour ago. I tried to install PySide (I know it's not best practice), and Spyder opens when that exists, but then doing `import matplotlib.pyplot as plt` causes errors with Python being unable to import `matplotlib._png`

Also, see here: https://github.com/spyder-ide/spyder/issues/2765

**Comment by msarahan** [comment]
Please downgrade to PyQt 4.10.  These issues are fixed, and we are in the process of rolling out updates for Anaconda 2.4.  However, it may be another couple of days.  Downgrading PyQt should be an immediate fix for now.

**Comment by sergeyf** [comment]
Understood, thanks. I'll leave this ticket open in case others have the same issue until 2.4 comes out.

**Comment by sergeyf** [comment]
I did conda update anaconda, and still the same error is happening @msarahan

**Comment by msarahan** [comment]
If you are running in the root environment, there is one further issue that may be causing you problems:

https://github.com/ContinuumIO/anaconda-issues/issues/509

Please add (YOUR PREFIX)\Library\bin to your PATH environment variable.

**Comment by sergeyf** [comment]
I added C:\Anaconda\Library\bin and updated PyQT to the latest, and the
same error results!

**Comment by msarahan** [comment]
Did you also update Qt?  Can you try, please:

```
conda update conda
conda update anaconda
```

The latter command will update you to the Anaconda 2.4 release.  This should be equivalent to using the new installers.  These have been thoroughly tested, and spyder works - just something about this update isn't right.

If this is still failing, please post a list of packages installed using 

```
conda list
```

**Comment by sergeyf** [comment]
I did updated anaconda earlier:

```
C:\Anaconda>conda update conda
Fetching package metadata: ....
# All requested packages already installed.
# packages in environment at C:\Anaconda:
#
conda                     3.18.3                   py27_0

C:\Anaconda>conda update anaconda
Fetching package metadata: ....
# All requested packages already installed.
# packages in environment at C:\Anaconda:
#
anaconda                  2.4.0               np110py27_0

C:\Anaconda>conda update qt
Fetching package metadata: ....
# All requested packages already installed.
# packages in environment at C:\Anaconda:
#
qt                        4.8.7                     vc9_4  [vc9]

C:\Anaconda>conda list
# packages in environment at C:\Anaconda:
```

Here is the results of `conda list` (note that pyqt is downgraded at the moment so I can at least open Spyder):

```
C:\Anaconda>conda list
# packages in environment at C:\Anaconda:
#
Error [Error 2] The system cannot find the file specified while executing command git config remote.origin.url
cannot determine version of editable source in c:\users\s\documents\github\kerseq (git command not found in path)
_license                  1.1                      py27_1
alabaster                 0.7.6                    py27_0
anaconda                  2.4.0               np110py27_0
anaconda-client           1.1.0                    py27_0
argcomplete               1.0.0                    py27_1
astropy                   1.0.5               np110py27_1
babel                     2.1.1                    py27_0
backports.ssl-match-hostname 3.4.0.2                   <pip>
bcolz                     0.11.3                   py27_0
beautiful-soup            4.3.2                    py27_1
beautifulsoup4            4.4.1                    py27_0
bitarray                  0.8.1                    py27_1
blaze                     0.8.3                     <pip>
blaze-core                0.8.3                    py27_0
blz                       0.6.2                np19py27_1
bokeh                     0.10.0                   py27_0
boto                      2.38.0                   py27_0
bottleneck                1.0.0               np110py27_0
brewer2mpl                1.4.1                     <pip>
bzip2                     1.0.6                     vc9_2  [vc9]
cdecimal                  2.3                      py27_1
certifi                   2015.9.6.2               py27_0
cffi                      1.2.1                    py27_0
clyent                    0.4.0                    py27_0
colorama                  0.3.3                    py27_0
comtypes                  1.1.2                    py27_0
conda                     3.18.3                   py27_0
conda-build               1.18.1                   py27_0
conda-env                 2.4.4                    py27_0
conda-server              0.14.0                        1
conda311fix               1.0                           0
configobj                 5.0.6                    py27_0
console_shortcut          0.1.1                    py27_1
cryptography              1.0.2                    py27_0
curl                      7.45.0                    vc9_0  [vc9]
cython                    0.23.4                   py27_0
cytoolz                   0.7.4                    py27_0
datashape                 0.4.7               np110py27_1
decorator                 4.0.4                    py27_0
docutils                  0.12                     py27_1
dynd-python               0.6.5                np19py27_0
enum34                    1.0.4                    py27_0
fastcache                 1.0.2                    py27_0
flask                     0.10.1                   py27_1
freetype                  2.5.5                     vc9_0  [vc9]
funcsigs                  0.4                      py27_0
futures                   3.0.3                    py27_0
gensim                    0.12.2               np19py27_0
geopy                     1.11.0                    <pip>
gevent                    1.0.1                    py27_0
gevent-websocket          0.9.3                    py27_0
ggplot                    0.6.8                     <pip>
greenlet                  0.4.9                    py27_0
grin                      1.2.1                    py27_2
h5py                      2.5.0               np110py27_4
hdf5                      1.8.15.1                  vc9_3  [vc9]
idna                      2.0                      py27_0
ipaddress                 1.0.14                   py27_0
ipykernel                 4.1.1                    py27_0
ipython                   4.0.0                    py27_1
ipython-genutils          0.1.0                     <pip>
ipython-notebook          4.0.4                    py27_3
ipython-qtconsole         4.0.1                    py27_4
ipython_genutils          0.1.0                    py27_0
ipywidgets                4.1.0                    py27_0
itsdangerous              0.24                     py27_0
jdcal                     1.0                      py27_0
jedi                      0.9.0                    py27_0
jinja2                    2.8                      py27_0
jpeg                      8d                        vc9_0  [vc9]
jsonschema                2.4.0                    py27_0
jupyter                   1.0.0                    py27_0
jupyter-client            4.1.1                     <pip>
jupyter-console           4.0.3                     <pip>
jupyter-core              4.0.6                     <pip>
jupyter_client            4.1.1                    py27_0
jupyter_console           4.0.3                    py27_0
jupyter_core              4.0.6                    py27_0
keras                     0.2.0                     <pip>
kerseq (c:\users\s\documents\github\kerseq) 0.0.1                     <pip>
launcher                  1.0.0                         4
libpng                    1.6.17                    vc9_1  [vc9]
libsodium                 1.0.3                         0
libtiff                   4.0.6                     vc9_0  [vc9]
llvmlite                  0.7.0                    py27_5
lxml                      3.4.4                    py27_0
markupsafe                0.23                     py27_0
matplotlib                1.4.3               np110py27_3
menuinst                  1.2.1                    py27_0
mistune                   0.7.1                    py27_0
mock                      1.3.0                    py27_0
msvc_runtime              1.0.1                     vc9_0  [vc9]
multipledispatch          0.4.8                    py27_0
nbconvert                 4.0.0                    py27_0
nbformat                  4.0.1                    py27_0
networkx                  1.10                     py27_0
nltk                      3.1                      py27_0
node-webkit               0.10.1                        0
nose                      1.3.7                    py27_0
notebook                  4.0.6                    py27_0
numba                     0.21.0              np110py27_0
numexpr                   2.4.4               np110py27_0
numpy                     1.10.1                   py27_0
odo                       0.3.4                    py27_0
openpyxl                  2.2.6                    py27_0
openssl                   1.0.2d                    vc9_0  [vc9]
pandas                    0.17.0              np110py27_0
patch                     2.5.9                         1
path.py                   8.1.2                    py27_0
patsy                     0.4.0               np110py27_0
pbr                       1.3.0                    py27_0
pep8                      1.6.2                    py27_0
pickleshare               0.5                      py27_0
pillow                    3.0.0                    py27_1
pip                       7.1.2                    py27_0
ply                       3.8                      py27_0
ppca                      0.0.0                     <pip>
psutil                    3.2.2                    py27_0
py                        1.4.30                   py27_0
pyasn1                    0.1.9                    py27_0
pycosat                   0.6.1                    py27_0
pycparser                 2.14                     py27_0
pycrypto                  2.6.1                    py27_3
pycurl                    7.19.5.1                 py27_1
pyflakes                  1.0.0                    py27_0
pygments                  2.0.2                    py27_0
pymc3                     3.0                       <pip>
pyopenssl                 0.15.1                   py27_1
pyparsing                 2.0.3                    py27_0
pyqt                      4.10.4                   py27_1
pyreadline                2.1                      py27_0
pytables                  3.2.2               np110py27_1
pytest                    2.8.1                    py27_0
python                    2.7.10                        3
python-dateutil           2.4.2                    py27_0
pytz                      2015.6                   py27_0
pywin32                   219                      py27_1
pyyaml                    3.11                     py27_2
pyzmq                     14.7.0                   py27_1
qt                        4.8.7                     vc9_4  [vc9]
qtconsole                 4.1.0                    py27_0
requests                  2.8.1                    py27_0
rope                      0.9.4                    py27_1
runipy                    0.1.3                    py27_0
sas7bdat                  2.0.6                     <pip>
scikit-image              0.11.3              np110py27_0
scikit-learn              0.16.1              np110py27_0
scipy                     0.16.0              np110py27_0
seaborn                   0.6.0                np19py27_0
setuptools                18.4                     py27_0
simplegeneric             0.8.1                    py27_0
singledispatch            3.4.0.3                  py27_0
sip                       4.16.9                   py27_1
six                       1.10.0                   py27_0
snowballstemmer           1.2.0                    py27_0
sockjs-tornado            1.0.1                    py27_0
sphinx                    1.3.1                    py27_0
sphinx-rtd-theme          0.1.7                     <pip>
sphinx_rtd_theme          0.1.7                    py27_0
spyder                    2.3.7                    py27_3
spyder-app                2.3.7                    py27_0
sqlalchemy                1.0.9                    py27_0
ssl_match_hostname        3.4.0.2                  py27_0
statsmodels               0.6.1               np110py27_0
sympy                     0.7.6.1                  py27_0
tables                    3.2.2                     <pip>
theano                    0.7.0                     <pip>
tk                        8.5.18                    vc9_0  [vc9]
toolz                     0.7.4                    py27_0
tornado                   4.2.1                    py27_1
traitlets                 4.0.0                    py27_0
ujson                     1.33                     py27_0
unicodecsv                0.14.1                   py27_0
werkzeug                  0.10.4                   py27_0
wheel                     0.26.0                   py27_1
xlrd                      0.9.4                    py27_0
xlsxwriter                0.7.7                    py27_0
xlwings                   0.4.1                    py27_0
xlwt                      1.0.0                    py27_0
zeromq                    4.1.3                     vc9_1  [vc9]
zlib                      1.2.8                     vc9_2  [vc9]
```

**Comment by msarahan** [comment]
I see a number of numpy 1.9 packages in there.  I don't think those are causing this problem, but they may cause other problems.  Is it possible for you to try to simply run the new Anaconda 2.4 installer?

Failing that, what was your prior installation?  I'd like to try to recreate the update that fails.

**Comment by msarahan** [comment]
One other idea: since you did a system-wide installation, it was done with elevated rights.  Some things may fail with permission errors.  Unfortunately, your system is now in a state that is more difficult to figure out what installations only partially succeeded.

In the future, if you do 

```
conda update conda
conda update --all
```

from an elevated command prompt, I think you'll have fewer issues.

**Comment by sergeyf** [comment]
I had 2.2 before, I believe. I will try the installer later today and
report back. Thanks!

**Comment by sergeyf** [comment]
Hi @msarahan,

I uninstalled 2.2, and then reinstalled 2.4 from a fresh .exe in a new directory (without elevated privileges this time). It's all working now. I guess I got into a weird config cul-de-sec. Thanks for your time and help.
