### ISSUE TITLE
Invalid URL's in anaconda-navigator

### ISSUE THREAD

**Issue by Back2Basics** [ContinuumIO/anaconda-issues#5841]
Installed Anaconda Linux version 64 bit Python 3.6

After installation running the `~/anaconda3/bin/anaconda-navigator` command gives:
-----------------------------------------------------------------------------------------------
...
2017-09-20 19:23:51,133 - ERROR download_api._download:192
Invalid url http://content.continuum.io/api/events

2017-09-20 19:23:51,417 - ERROR download_api._download:192
Invalid url http://content.continuum.io/api/videos

2017-09-20 19:23:51,752 - ERROR download_api._download:192
Invalid url http://content.continuum.io/api/webinars
-----------------------------------------------------------------------------
Growing pains with the domain switch?

**Comment by goanpeca** [comment]
@Back2Basics yes, this is related to the domain switch and is fixed in the newer version of Navigator to be released next week.

**Comment by JoomSavvy** [comment]
Any update? I just downloaded and installed a couple of days ago and this problem still exists.

**Comment by goanpeca** [comment]
The latest release is available since Tuesday 26/2017. I recommend you to update to the latests Anaconda Distribution https://www.anaconda.com/download/

**Comment by lyndbacon** [comment]
Got this error today:

2018-01-01 11:41:08,286 - ERROR download_api._download:192
Invalid URL '': No schema supplied. Perhaps you meant http://?

2018-01-01 11:41:08,286 - ERROR download_api._download:197
Invalid url

**Comment by goanpeca** [comment]
@lyndbacon do you have the latests version of navigator?

1.6.11 ?

**Comment by lyndbacon** [comment]
1.6.11.  Just installed it today.

**Comment by lyndbacon** [comment]
Reinstalling from scratch seems to have gotten rid of the message.  Not sure why, tho.  Thx.

**Comment by bstampe** [comment]
I am getting this same URL error message with anaconda 5.01 python 2.7. I have deleted and reinstalled from scratch several times. Anyway I can get this package without downloading 3.6? (My work environment necessitates python 2.7)

Thanks,

Brian

**Comment by goanpeca** [comment]
@bstampe its harmless you can ignore it

**Comment by kklepper** [comment]
Version 1.9.6

from navigator.log

```json
[
    {
        "level": "ERROR",
        "line": 234,
        "message": "Invalid url https://www.anaconda.com/api/webinars",
        "method": "_download",
        "module": "download_api",
        "path": "d:/data/Anaconda3/lib/site-packages/anaconda_navigator/api/download_api.py",
        "time": "2019-04-02 17:28:45,086"
    }
]
```
