### ISSUE TITLE
Anaconda 5.0.0 - not installed packages

### ISSUE THREAD

**Issue by yellowhat** [ContinuumIO/anaconda-issues#6386]
Hi all,
I am trying to install Anaconda 5.0.0 on a Windows 7 64bit machine.
Even if the installation is completed, most packages are not installed.
For example in the start menu there is a folder called `Anaconda2 (64-bit)` and inside there is only `Anaconda Prompt`, if I run this one I get:

`"C:\Anaconda2\Scripts\activate.bat" no recognized`

Infact in `Anaconda2/Scripts` there is no `conda.exe` or `spyder.exe`, but in `C:\Anaconda2\pkgs\spyder-3.2.3-py27hbf30467_0\Scripts` there is the spyder executable but it is not copied to the destination folder.
This problem is quite strange because in the previous release (4.4.0) after the installation everything was ready to run.

Thanks

**Comment by mingwandroid** [comment]
Would it be possible to copy the installation log? Control-C in the dialog should copy everything. If you can please send it to me directly: rdonnelly@anaconda.org

**Comment by yellowhat** [comment]
[install.log](https://github.com/ContinuumIO/anaconda-issues/files/1356910/install.log)

Here is my installation .log

**Comment by yellowhat** [comment]
Same problem with Anaconda 3 5.0.0.

[install3.log](https://github.com/ContinuumIO/anaconda-issues/files/1364562/install3.log)

**Comment by yellowhat** [comment]
Miniconda2-latest-Windows-x86_64 (2017-09-26) seems to work.

Here is the installation log:
[install_mini.log](https://github.com/ContinuumIO/anaconda-issues/files/1366782/install_mini.log)

**Comment by SenWang** [comment]
I have the same problem as @yellowhat

**Comment by keighrim** [comment]
Experiencing a similar problem. Win 10, 64 bit. 
[My installation log](https://gist.github.com/keighrim/d9280904f5f769085f20b9c72c9dc62c)
For some reason, all the packages, including python 3.6 itself, are extracted to `ANACONDA_PATH/pkgs` then not moved to the wherever they are supposed to be. 
Attached results from `tree` from `ANACONDA_PATH`
```
@/d/Dev/Anaconda3 []
$ 11:28:28>> tree -d -L 2
.
|-- Lib
`-- pkgs
    |-- _ipyw_jlab_nb_ext_conf-0.1.0-py36he6757f0_0
    |-- alabaster-0.7.10-py36hcd07829_0
    |-- anaconda-5.0.0-py36hea9b2fc_0
    |-- anaconda-client-1.6.5-py36hd36550c_0
    |-- anaconda-navigator-1.6.8-py36h4b7dd57_0
    |-- anaconda-project-0.8.0-py36h8b3bf89_0
    |-- asn1crypto-0.22.0-py36h8e79faa_1
    |-- astroid-1.5.3-py36h9d85297_0
    |-- astropy-2.0.2-py36h06391c4_4
    |-- babel-2.5.0-py36h35444c1_0
    |-- backports-1.0-py36h81696a8_1
    |-- backports.shutil_get_terminal_size-1.0.0-py36h79ab834_2
    |-- beautifulsoup4-4.6.0-py36hd4cc5e8_1
    |-- bitarray-0.8.1-py36h6af124b_0
    |-- bkcharts-0.2-py36h7e685f7_0
    |-- blaze-0.11.3-py36h8a29ca5_0
    |-- bleach-2.0.0-py36h0a7e3d6_0
    |-- bokeh-0.12.7-py36h012f572_1
    |-- boto-2.48.0-py36h1a776d2_1
    |-- bottleneck-1.2.1-py36hd119dfa_0
    |-- bzip2-1.0.6-vc14hdec8e7a_1
    |-- ca-certificates-2017.08.26-h94faf87_0
    |-- cache
    |-- cachecontrol-0.12.3-py36hfe50d7b_0
    |-- certifi-2017.7.27.1-py36h043bc9e_0
    |-- cffi-1.10.0-py36hae3d1b5_1
    |-- chardet-3.0.4-py36h420ce6e_1
    |-- click-6.7-py36hec8c647_0
   ......
    |-- python-3.6.2-h6679aeb_11
   ......
```

```
@/d/Dev/Anaconda3 []
$ 11:31:07>> tree -L 1 pkgs/python-3.6.2-h6679aeb_11
pkgs/python-3.6.2-h6679aeb_11
|-- DLLs
|-- LICENSE_PYTHON.txt
|-- Lib
|-- Scripts
|-- Tools
|-- include
|-- info
|-- libs
|-- python.exe
|-- python.pdb
|-- python3.dll
|-- python36.dll
|-- python36.pdb
|-- pythonw.exe
|-- pythonw.pdb
`-- tcl
```

**Comment by phongphung** [comment]
same problemt with @keighrim

**Comment by keighrim** [comment]
I managed to workaround this issue by
1. deleting existing anaconda installation and dotfiles(`.anaconda`, `.ipython`, `.jupyter`. etc) in my `$HOME` (I don't have a comprehensive list of anaconda-related dotfiles, so I just eyeballed to find as many as I can).
2. running anaconda installer as a user (not admin). 
3. installing anaconda "only for me", not adding it to `$PATH`

I had to manually add anaconda to `$PATH` afterward.

**Comment by yellowhat** [comment]
Same problem with 5.0.1.

**Comment by yellowhat** [comment]
Even doing as suggested by keighrim.

**Comment by SenWang** [comment]
Problem solved with 5.0.1, I love anaconda :)

**Comment by kawing-chiu** [comment]
Same issue on windows server 2008, anaconda 5.0.1

**Comment by IrksomeZeus** [comment]
Issue is still present in Anaconda 5.2.0 on Windows 10 64bit

duplicate issue: #8460

**Comment by KristijanCetina** [comment]
same issue over here.
Microsoft Windows [Version 10.0.17134.228]
Anaconda3-5.2.0-Windows-x86_64

tried to install miniconda but also installed without conda.exe.
prior to this issue I had installed anaconda but had to reinstall due to dead kernel after update.
