### ISSUE TITLE
Multiple package resolutions - how to resolve?

### ISSUE THREAD

**Issue by kalefranz** [ContinuumIO/anaconda-issues#7173]
_From @lifescholar on November 7, 2017 9:49_

I'm receiving the following warning on issuing the 'conda update --all' command:

`Warning: 2 possible package resolutions (only showing differing packages):`
`  - defaults::quandl-3.2.0-py36h30f7a5e_0, defaults::requests-2.14.2-py36_0`
`  - defaults::quandl-3.1.0-py36_0, defaults::requests-2.18.4-py36h4371aae_1`

Is this as a result of a bug, or is there a way to resolve it?

_Copied from original issue: conda/conda#6273_

**Comment by kalefranz** [comment]
Can you provide the output of `conda info`?

**Comment by kalefranz** [comment]
It's possible we have a packaging issue here.  It appears that @nehaljwani built `quandl-3.2.0`, so hopefully he can chime in here with some additional context.

I wasn't able to find the quandl recipe at https://github.com/AnacondaRecipes.

However, lookin in https://repo.continuum.io/pkgs/main/linux-64/repodata.json, I'm seeing

```
    "quandl-3.2.0-py36h3624063_0.tar.bz2": {
      "build": "py36h3624063_0",
      "build_number": 0,
      "depends": [
        "inflection >=0.3.1",
        "more-itertools",
        "numpy >=1.8",
        "pandas >=0.14",
        "python >=3.6,<3.7.0a0",
        "python-dateutil",
        "requests >=2.7.0,<2.18",
        "six"
      ],
      "license": "MIT",
      "md5": "18f3df76b2ce79925ee107ebf7a7b743",
      "name": "quandl",
      "sha256": "805679b63389b3a17eb5b5107405c5ca48f92f33fe9f59afa763728252b6cf42",
      "size": 39252,
      "subdir": "linux-64",
      "timestamp": 1509567355946,
      "version": "3.2.0"
    },
```

and in comparison, from https://repo.continuum.io/pkgs/free/linux-64/repodata.json

```
    "quandl-3.1.0-py36_0.tar.bz2": {
      "build": "py36_0",
      "build_number": 0,
      "date": "2017-03-13",
      "depends": [
        "inflection >=0.3.1",
        "more-itertools",
        "numpy",
        "pandas >=0.14",
        "python 3.6*",
        "python-dateutil",
        "requests >=2.7.0",
        "six"
      ],
      "license": "MIT",
      "md5": "dfdf967995d9bafafd87ffa933a1d28d",
      "name": "quandl",
      "size": 29211,
      "version": "3.1.0"
    },
```

So the new package adds an upper bound to the requests dependency, and that upper bound should be patched onto the other quandl packages I'm guessing.

**Comment by lifescholar** [comment]
conda info
Current conda install:

               platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.28
         python version : 3.6.3.final.0
       requests version : 2.14.2
       root environment : D:\Users\803375527\AppData\Local\Continuum\anaconda3  (writable)
    default environment : D:\Users\803375527\AppData\Local\Continuum\anaconda3
       envs directories : D:\Users\803375527\AppData\Local\Continuum\anaconda3\envs
                          C:\Users\803375527\AppData\Local\conda\conda\envs
                          C:\Users\803375527\.conda\envs
          package cache : D:\Users\803375527\AppData\Local\Continuum\anaconda3\pkgs
                          C:\Users\803375527\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\803375527\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.14.2 CPython/3.6.3 Windows/10 Windows/10.0.14393
          administrator : False

**Comment by kevin-coder** [comment]
I've meet the same issue.
conda info will output following msg:
Current conda install:

               platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : not installed
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : C:\Software\SoftwareDev\Python  (writable)
    default environment : C:\Software\SoftwareDev\Python
       envs directories : C:\Software\SoftwareDev\Python\envs
                          C:\Users\huzq8\AppData\Local\conda\conda\envs
                          C:\Users\huzq8\.conda\envs
          package cache : C:\Software\SoftwareDev\Python\pkgs
                          C:\Users\huzq8\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.17046
          administrator : False

**Comment by kevin-coder** [comment]
hi, do anyone resolve this issue?

**Comment by rmarshall31** [comment]
I had this issue as well, but it seems to have been resolved now.

**Comment by drorata** [comment]
I had to do `conda update conda` and then it was resolved.

**Comment by huzq85** [comment]
Seems that this issue appeared again...
See following info of conda:
     active environment : None
       user config file : C:\Users\huzq8\.condarc
 populated config files : C:\Users\huzq8\.condarc
          conda version : 4.5.9
    conda-build version : not installed
         python version : 3.6.6.final.0
       base environment : C:\Software\SoftwareDev\Python3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Software\SoftwareDev\Python3\pkgs
                          C:\Users\huzq8\AppData\Local\conda\conda\pkgs
       envs directories : C:\Software\SoftwareDev\Python3\envs
                          C:\Users\huzq8\AppData\Local\conda\conda\envs
                          C:\Users\huzq8\.conda\envs
               platform : win-64
             user-agent : conda/4.5.9 requests/2.19.1 CPython/3.6.6 Windows/10 Windows/10.0.17733
          administrator : False
             netrc file : None
           offline mode : False

**Comment by Selena-21** [comment]
Does anyone really know how to solve this issue with Multiple package resolutions?
I have the following problem:

```
conda update --all
Solving environment: / 
Warning: 4 possible package resolutions (only showing differing packages):
  - numba::pyculib-1.0.2-np113py36_2, numba::pyculib_sorting-1.0.0-8
  - defaults::pyculib_sorting-1.0.0-8, numba::pyculib-1.0.2-np113py36_2
  - defaults::pyculib-1.0.2-np113py36_2, numba::pyculib_sorting-1.0.0-8
  - defaults::pyculib-1.0.2-np113py36_2, defaults::pyculib_sorting-1.0.0done
```
`conda update conda` does not solve this issue.

conda info:

```
     active environment : None
       user config file : /home/svystun/.condarc
 populated config files : 
          conda version : 4.5.11
    conda-build version : 3.15.1
         python version : 3.6.6.final.0
       base environment : /home/svystun/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/svystun/anaconda3/pkgs
                          /home/svystun/.conda/pkgs
       envs directories : /home/svystun/anaconda3/envs
                          /home/svystun/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.6.6 Linux/3.10.0-693.21.1.el7.x86_64 centos/7 glibc/2.17
                UID:GID : 26661:1500
             netrc file : None
           offline mode : False
```

**Comment by Selena-21** [comment]
Does anyone really know how to solve this issue with Multiple package resolutions?
I have the following problem:

```
conda update --all
Solving environment: / 
Warning: 4 possible package resolutions (only showing differing packages):
  - numba::pyculib-1.0.2-np113py36_2, numba::pyculib_sorting-1.0.0-8
  - defaults::pyculib_sorting-1.0.0-8, numba::pyculib-1.0.2-np113py36_2
  - defaults::pyculib-1.0.2-np113py36_2, numba::pyculib_sorting-1.0.0-8
  - defaults::pyculib-1.0.2-np113py36_2, defaults::pyculib_sorting-1.0.0done
```
`conda update conda` does not solve this issue.

conda info:

```
     active environment : None
       user config file : /home/user/.condarc
 populated config files : 
          conda version : 4.5.11
    conda-build version : 3.15.1
         python version : 3.6.6.final.0
       base environment : /home/user/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/user/anaconda3/pkgs
                          /home/user/.conda/pkgs
       envs directories : /home/user/anaconda3/envs
                          /home/user/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.6.6 Linux/3.10.0-693.21.1.el7.x86_64 centos/7 glibc/2.17
                UID:GID : 26661:1500
             netrc file : None
           offline mode : False
```

**Comment by jjhelmus** [comment]
@Selena-21 The `numba` channel seems to be giving multiple possible resolutions, removing that channel will cause this warning to go away.

**Comment by firmbeliever** [comment]
I'm getting this issue.  Did a `conda update conda` before running an update all.  I get this when I try to update all on my root environment (which is python 2.7) or on an additional environment that is 3.6.

`Warning: >10 possible package resolutions (only showing differing packages):
  - anaconda::gsl-2.4-h1de35cc_4, defaults::metis-5.1.0-h0a44026_4, defaults::nltk-3.3.0-py36_0, defaults::suitesparse-5.2.0-he235d88_0
  - anaconda::gsl-2.4-h1de35cc_4, anaconda::nltk-3.3.0-py36_0, defaults::metis-5.1.0-h0a44026_4, defaults::suitesparse-5.2.0-he235d88_0
  - defaults::gsl-2.4-h1de35cc_4, defaults::metis-5.1.0-h0a44026_4, defaults::nltk-3.3.0-py36_0, defaults::suitesparse-5.2.0-he235d88_0
  - anaconda::nltk-3.3.0-py36_0, defaults::gsl-2.4-h1de35cc_4, defaults::metis-5.1.0-h0a44026_4, defaults::suitesparse-5.2.0-he235d88_0
  - anaconda::metis-5.1.0-h0a44026_4, defaults::gsl-2.4-h1de35cc_4, defaults::nltk-3.3.0-py36_0, defaults::suitesparse-5.2.0-he235d88_0
  - anaconda::metis-5.1.0-h0a44026_4, anaconda::nltk-3.3.0-py36_0, defaults::gsl-2.4-h1de35cc_4, defaults::suitesparse-5.2.0-he235d88_0
  - anaconda::gsl-2.4-h1de35cc_4, anaconda::metis-5.1.0-h0a44026_4, defaults::nltk-3.3.0-py36_0, defaults::suitesparse-5.2.0-he235d88_0
  - anaconda::gsl-2.4-h1de35cc_4, anaconda::metis-5.1.0-h0a44026_4, anaconda::nltk-3.3.0-py36_0, defaults::suitesparse-5.2.0-he235d88_0
  - anaconda::gsl-2.4-h1de35cc_4, anaconda::metis-5.1.0-h0a44026_4, anaconda::suitesparse-5.2.0-he235d88_0, defaults::nltk-3.3.0-py36_0
  - anaconda::gsl-2.4-h1de35cc_4, anaconda::suitesparse-5.2.0-he235d88_0, defaults::metis-5.1.0-h0a44026_4, defaults::nltk-3.3.0-py36_0
  ... and othedone`

`     active environment : None
       user config file : /Users/kate/.condarc
 populated config files : /Users/kate/.condarc
          conda version : 4.5.11
    conda-build version : not installed
         python version : 2.7.15.final.0
       base environment : /Users/kate/anaconda  (writable)
           channel URLs : http://conda.anaconda.org/gurobi/osx-64
                          http://conda.anaconda.org/gurobi/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/kate/anaconda/pkgs
                          /Users/kate/.conda/pkgs
       envs directories : /Users/kate/anaconda/envs
                          /Users/kate/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/2.7.15 Darwin/17.7.0 OSX/10.13.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False`

**Comment by bdemircan** [comment]
Getting the same warning with latest conda. 

(base) C:\Users\demircan>conda update --all
Collecting package metadata: done
Solving environment: |
Warning: 2 possible package resolutions (only showing differing packages):
  - defaults::nbconvert-5.3.1-py37_0, defaults::pandoc-2.2.3.2-0
  - defaults::nbconvert-5.4.1-py37_0, defaults::pandoc-1.19.2.1-hb2460c7done

# All requested packages already installed.


(base) C:\Users\demircan>conda info

     active environment : base
    active env location : C:\Users\demircan\Anaconda3
            shell level : 1
       user config file : C:\Users\demircan\.condarc
 populated config files : C:\Users\demircan\.condarc
          conda version : 4.6.7
    conda-build version : 3.17.8
         python version : 3.7.2.final.0
       base environment : C:\Users\demircan\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\demircan\Anaconda3\pkgs
                          C:\Users\demircan\.conda\pkgs
                          C:\Users\demircan\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\demircan\Anaconda3\envs
                          C:\Users\demircan\.conda\envs
                          C:\Users\demircan\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.7 requests/2.21.0 CPython/3.7.2 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False

**Comment by earlev4** [comment]
Hi. Receiving the same issue as bdemircan.  However, the platform is linux-64.

```
> conda update --all
Collecting package metadata: done
Solving environment: | 
Warning: 2 possible package resolutions (only showing differing packages):
  - defaults::nbconvert-5.3.1-py37_0, defaults::pandoc-2.2.3.2-0
  - defaults::nbconvert-5.4.1-py37_0, defaults::pandoc-1.19.2.1-hea2e7c5done

# All requested packages already installed.
```
```
> conda info
     active environment : None
       user config file : /home/earle/.condarc
 populated config files : /home/earle/.condarc
          conda version : 4.6.7
    conda-build version : 3.17.8
         python version : 3.7.2.final.0
       base environment : /home/earle/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/earle/anaconda3/pkgs
                          /home/earle/.conda/pkgs
       envs directories : /home/earle/anaconda3/envs
                          /home/earle/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.7 requests/2.21.0 CPython/3.7.2 Linux/4.15.0-45-generic ubuntu/18.04.2 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
Any assistance would be greatly appreciated.
Thanks!

**Comment by bsecon** [comment]
Same issue with nbconvert for me, platform is osx-64. Additionally, I get the attached warning in spyder. If someone could help resolving this, I would be grateful.
![Bildschirmfoto 2019-03-14 um 14 21 50](https://user-images.githubusercontent.com/10776980/54360352-ff92de80-4664-11e9-8220-7eee2f49269e.png)
 
`conda update --all
Collecting package metadata: done
Solving environment: \ 
Warning: 2 possible package resolutions (only showing differing packages):
  - defaults::nbconvert-5.3.1-py36_0, defaults::pandoc-2.2.3.2-0
  - defaults::nbconvert-5.4.1-py36_0, defaults::pandoc-1.19.2.1-ha5e8f32done

# All requested packages already installed.`
`conda info

     active environment : None
       user config file : /Users/au588006/.condarc
 populated config files : /Users/au588006/.condarc
          conda version : 4.6.8
    conda-build version : 3.17.8
         python version : 3.6.8.final.0
       base environment : /Users/au588006/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/au588006/anaconda3/pkgs
                          /Users/au588006/.conda/pkgs
       envs directories : /Users/au588006/anaconda3/envs
                          /Users/au588006/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.8 requests/2.21.0 CPython/3.6.8 Darwin/18.2.0 OSX/10.14.3
                UID:GID : 1790730921:357318537
             netrc file : None
           offline mode : False
`

**Comment by msarahan** [comment]
The problem is that old builds of nbconvert do not put any constraint on their pandoc version.  New ones do.  The solver is forced to choose between newer nbconvert or newer pandoc, and they're mathematically equivalent here.  We need to fix our repo data, so that all nbconvert builds have an upper bound for pandoc.

**Comment by ccordoba12** [comment]
@msarahan, Jupyter guys decided to increase the upper level of Pandoc to `< 3.0`, but that's still unreleased:

https://github.com/jupyter/nbconvert/pull/964

Older versions should use `< 2.0`, I think.

**Comment by jjhelmus** [comment]
conda-forge has removed the upper bound from the pandoc requirement in the nbconvert recipe, conda-forge/nbconvert-feedstock#28. I'll release a package to `defaults` with the same pinning.

**Comment by jjhelmus** [comment]
A new `nbconvert` package is available in `defaults` which should address the mutliple solutions issue mentioned here.

**Comment by earlev4** [comment]
> Hi. Receiving the same issue as bdemircan. However, the platform is linux-64.
> 
> ```
> > conda update --all
> Collecting package metadata: done
> Solving environment: | 
> Warning: 2 possible package resolutions (only showing differing packages):
>   - defaults::nbconvert-5.3.1-py37_0, defaults::pandoc-2.2.3.2-0
>   - defaults::nbconvert-5.4.1-py37_0, defaults::pandoc-1.19.2.1-hea2e7c5done
> 
> # All requested packages already installed.
> ```
> ```
> > conda info
>      active environment : None
>        user config file : /home/earle/.condarc
>  populated config files : /home/earle/.condarc
>           conda version : 4.6.7
>     conda-build version : 3.17.8
>          python version : 3.7.2.final.0
>        base environment : /home/earle/anaconda3  (writable)
>            channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
>                           https://repo.anaconda.com/pkgs/main/noarch
>                           https://repo.anaconda.com/pkgs/free/linux-64
>                           https://repo.anaconda.com/pkgs/free/noarch
>                           https://repo.anaconda.com/pkgs/r/linux-64
>                           https://repo.anaconda.com/pkgs/r/noarch
>           package cache : /home/earle/anaconda3/pkgs
>                           /home/earle/.conda/pkgs
>        envs directories : /home/earle/anaconda3/envs
>                           /home/earle/.conda/envs
>                platform : linux-64
>              user-agent : conda/4.6.7 requests/2.21.0 CPython/3.7.2 Linux/4.15.0-45-generic ubuntu/18.04.2 glibc/2.27
>                 UID:GID : 1000:1000
>              netrc file : None
>            offline mode : False
> ```
> Any assistance would be greatly appreciated.
> Thanks!

Hi. Just performed a `conda update --all` and the following packages were downloaded and installed. 
Is 'py_2' the correct build for nbconvert?
```
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    matplotlib-3.0.3           |   py37h5429711_0         6.6 MB
    nbconvert-5.4.1            |             py_2         340 KB
    pandas-0.24.2              |   py37he6710b0_0        11.1 MB
    ------------------------------------------------------------
                                           Total:        18.0 MB

```
Now after the installation of the packages and performing another `conda update --all`, no longer receiving the warning.

```
> conda update --all
Collecting package metadata: done
Solving environment: done

# All requested packages already installed.
```
Thank you very much and I appreciate the help!

**Comment by bsecon** [comment]
> A new `nbconvert` package is available in `defaults` which should address the mutliple solutions issue mentioned here.

This solved the issue for me, thanks a lot!

**Comment by mddavila** [comment]
Hi. I have the same issue as tested today: 

`~ λ conda update --all
Collecting package metadata: done
Solving environment: / 
Warning: 2 possible package resolutions (only showing differing packages):
  - conda-forge::llvmlite-0.28.0-py37hf292337_0, conda-forge::numba-0.43.0-py37h0a44026_0, defaults::numpy-1.15.4-py37hacdab7b_0, defaults::numpy-base-1.15.4-py37h6575580_0
  - conda-forge::llvmlite-0.25.0-py37h3fea490_1001, conda-forge::numba-0.40.1-py37h1702cab_1000, defaults::numpy-1.16.2-py37hacdab7b_0, defaults::numpy-base-1.16.2-py37h6575580done

# All requested packages already installed.`

`~ λ conda info

     active environment : None
       user config file : /Users/mddavila/.condarc
 populated config files : /Users/mddavila/.condarc
          conda version : 4.6.8
    conda-build version : 3.17.8
         python version : 3.7.1.final.0
       base environment : /Users/mddavila/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/mddavila/anaconda3/pkgs
                          /Users/mddavila/.conda/pkgs
       envs directories : /Users/mddavila/anaconda3/envs
                          /Users/mddavila/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.8 requests/2.21.0 CPython/3.7.1 Darwin/18.2.0 OSX/10.14.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False`

Could you please help me in solving this issue?

Thanks

**Comment by msjahid** [comment]
You can use this following command this one resolved my issue
`conda update --strict-channel-priority --all`

**Comment by vobine** [comment]
strict-channel-priority didn't fix it for me.  Output:

```
Collecting package metadata (current_repodata.json): done
Solving environment: - 
Warning: >10 possible package resolutions (only showing differing packages):
  - https://repo.continuum.io/pkgs/main/osx-64::asn1crypto-0.24.0-py36_0, https://repo.continuum.io/pkgs/main/osx-64::cycler-0.10.0-py36hfc81398_0, https://repo.continuum.io/pkgs/main/osx-64::gettext-0.19.8.1-h15daf44_3, https://repo.continuum.io/pkgs/main/osx-64::libgfortran-3.0.1-h93005f0_2
  - defaults::gettext-0.19.8.1-h15daf44_3, https://repo.continuum.io/pkgs/main/osx-64::asn1crypto-0.24.0-py36_0, https://repo.continuum.io/pkgs/main/osx-64::cycler-0.10.0-py36hfc81398_0, https://repo.continuum.io/pkgs/main/osx-64::libgfortran-3.0.1-h93005f0_2
  - defaults::cycler-0.10.0-py36hfc81398_0, https://repo.continuum.io/pkgs/main/osx-64::asn1crypto-0.24.0-py36_0, https://repo.continuum.io/pkgs/main/osx-64::gettext-0.19.8.1-h15daf44_3, https://repo.continuum.io/pkgs/main/osx-64::libgfortran-3.0.1-h93005f0_2
  - defaults::cycler-0.10.0-py36hfc81398_0, defaults::gettext-0.19.8.1-h15daf44_3, https://repo.continuum.io/pkgs/main/osx-64::asn1crypto-0.24.0-py36_0, https://repo.continuum.io/pkgs/main/osx-64::libgfortran-3.0.1-h93005f0_2
  - defaults::cycler-0.10.0-py36hfc81398_0, defaults::libgfortran-3.0.1-h93005f0_2, https://repo.continuum.io/pkgs/main/osx-64::asn1crypto-0.24.0-py36_0, https://repo.continuum.io/pkgs/main/osx-64::gettext-0.19.8.1-h15daf44_3
  - defaults::cycler-0.10.0-py36hfc81398_0, defaults::gettext-0.19.8.1-h15daf44_3, defaults::libgfortran-3.0.1-h93005f0_2, https://repo.continuum.io/pkgs/main/osx-64::asn1crypto-0.24.0-py36_0
  - defaults::libgfortran-3.0.1-h93005f0_2, https://repo.continuum.io/pkgs/main/osx-64::asn1crypto-0.24.0-py36_0, https://repo.continuum.io/pkgs/main/osx-64::cycler-0.10.0-py36hfc81398_0, https://repo.continuum.io/pkgs/main/osx-64::gettext-0.19.8.1-h15daf44_3
  - defaults::gettext-0.19.8.1-h15daf44_3, defaults::libgfortran-3.0.1-h93005f0_2, https://repo.continuum.io/pkgs/main/osx-64::asn1crypto-0.24.0-py36_0, https://repo.continuum.io/pkgs/main/osx-64::cycler-0.10.0-py36hfc81398_0
  - defaults::asn1crypto-0.24.0-py36_0, defaults::libgfortran-3.0.1-h93005f0_2, https://repo.continuum.io/pkgs/main/osx-64::cycler-0.10.0-py36hfc81398_0, https://repo.continuum.io/pkgs/main/osx-64::gettext-0.19.8.1-h15daf44_3
  - defaults::asn1crypto-0.24.0-py36_0, https://repo.continuum.io/pkgs/main/osx-64::cycler-0.10.0-py36hfc81398_0, https://repo.continuum.io/pkgs/main/osx-64::gettext-0.19.8.1-h15daf44_3, https://repo.continuum.io/pkgs/main/osx-64::libgfortran-3.0.1-h93005f0_2
  ... and othedone

# All requested packages already installed.
```


conda info:
```
     active environment : None
       user config file : /Users/hrp/.condarc
 populated config files : 
          conda version : 4.7.10
    conda-build version : not installed
         python version : 3.6.8.final.0
       virtual packages : 
       base environment : /Users/hrp/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/hrp/anaconda3/pkgs
                          /Users/hrp/.conda/pkgs
       envs directories : /Users/hrp/anaconda3/envs
                          /Users/hrp/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.10 requests/2.22.0 CPython/3.6.8 Darwin/18.6.0 OSX/10.14.5
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```

**Comment by xueyaodeai** [comment]
I have the same issue

conda info: 
```
     active environment : None
       user config file : /Users/xueyao/.condarc
 populated config files : /Users/xueyao/.condarc
          conda version : 4.7.10
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages :
       base environment : /Users/xueyao/anaconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/xueyao/anaconda/pkgs
                          /Users/xueyao/.conda/pkgs
       envs directories : /Users/xueyao/anaconda/envs
                          /Users/xueyao/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.10 requests/2.22.0 CPython/3.7.3 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

---

conda update --strict-channel-priority --all:
```
Collecting package metadata (current_repodata.json): done
Solving environment: |
Warning: >10 possible package resolutions (only showing differing packages):
  - https://repo.continuum.io/pkgs/main/osx-64::gettext-0.19.8.1-h15daf44_3, https://repo.continuum.io/pkgs/main/osx-64::gmp-6.1.2-hb37e062_1, https://repo.continuum.io/pkgs/main/osx-64::jbig-2.1-h4d881f8_0, https://repo.continuum.io/pkgs/main/osx-64::libgfortran-3.0.1-h93005f0_2
  - defaults::gettext-0.19.8.1-h15daf44_3, https://repo.continuum.io/pkgs/main/osx-64::gmp-6.1.2-hb37e062_1, https://repo.continuum.io/pkgs/main/osx-64::jbig-2.1-h4d881f8_0, https://repo.continuum.io/pkgs/main/osx-64::libgfortran-3.0.1-h93005f0_2
  - defaults::libgfortran-3.0.1-h93005f0_2, https://repo.continuum.io/pkgs/main/osx-64::gettext-0.19.8.1-h15daf44_3, https://repo.continuum.io/pkgs/main/osx-64::gmp-6.1.2-hb37e062_1, https://repo.continuum.io/pkgs/main/osx-64::jbig-2.1-h4d881f8_0
  - defaults::gettext-0.19.8.1-h15daf44_3, defaults::libgfortran-3.0.1-h93005f0_2, https://repo.continuum.io/pkgs/main/osx-64::gmp-6.1.2-hb37e062_1, https://repo.continuum.io/pkgs/main/osx-64::jbig-2.1-h4d881f8_0
  - defaults::jbig-2.1-h4d881f8_0, defaults::libgfortran-3.0.1-h93005f0_2, https://repo.continuum.io/pkgs/main/osx-64::gettext-0.19.8.1-h15daf44_3, https://repo.continuum.io/pkgs/main/osx-64::gmp-6.1.2-hb37e062_1
  - defaults::gettext-0.19.8.1-h15daf44_3, defaults::jbig-2.1-h4d881f8_0, defaults::libgfortran-3.0.1-h93005f0_2, https://repo.continuum.io/pkgs/main/osx-64::gmp-6.1.2-hb37e062_1
  - defaults::jbig-2.1-h4d881f8_0, https://repo.continuum.io/pkgs/main/osx-64::gettext-0.19.8.1-h15daf44_3, https://repo.continuum.io/pkgs/main/osx-64::gmp-6.1.2-hb37e062_1, https://repo.continuum.io/pkgs/main/osx-64::libgfortran-3.0.1-h93005f0_2
  - defaults::gettext-0.19.8.1-h15daf44_3, defaults::jbig-2.1-h4d881f8_0, https://repo.continuum.io/pkgs/main/osx-64::gmp-6.1.2-hb37e062_1, https://repo.continuum.io/pkgs/main/osx-64::libgfortran-3.0.1-h93005f0_2
  - defaults::gmp-6.1.2-hb37e062_1, defaults::jbig-2.1-h4d881f8_0, https://repo.continuum.io/pkgs/main/osx-64::gettext-0.19.8.1-h15daf44_3, https://repo.continuum.io/pkgs/main/osx-64::libgfortran-3.0.1-h93005f0_2
  - defaults::gmp-6.1.2-hb37e062_1, https://repo.continuum.io/pkgs/main/osx-64::gettext-0.19.8.1-h15daf44_3, https://repo.continuum.io/pkgs/main/osx-64::jbig-2.1-h4d881f8_0, https://repo.continuum.io/pkgs/main/osx-64::libgfortran-3.0.1-h93005f0_2
  ... and othedone

# All requested packages already installed.
```

**Comment by Jasonsey** [comment]
when i downgrade conda from 4.7 to 4.6, everything goes well !

**Comment by lvankampenhout** [comment]
I have these warnings:

```
Warning: >10 possible package resolutions (only showing differing packages):
  - https://repo.continuum.io/pkgs/main/osx-64::h5py-2.7.1-py36h39cdac5_0, https://repo.continuum.io/pkgs/main/osx-64::icu-58.2-h4b95b61_1, https://repo.continuum.io/pkgs/main/osx-64::jupyter_client-5.2.2-py36_0, https://repo.continuum.io/pkgs/main/osx-64::pytables-3.4.2-py36hfbd7ab0_2
  - defaults::icu-58.2-h4b95b61_1, https://repo.continuum.io/pkgs/main/osx-64::h5py-2.7.1-py36h39cdac5_0, https://repo.continuum.io/pkgs/main/osx-64::jupyter_client-5.2.2-py36_0, https://repo.continuum.io/pkgs/main/osx-64::pytables-3.4.2-py36hfbd7ab0_2
  - defaults::h5py-2.7.1-py36h39cdac5_0, https://repo.continuum.io/pkgs/main/osx-64::icu-58.2-h4b95b61_1, https://repo.continuum.io/pkgs/main/osx-64::jupyter_client-5.2.2-py36_0, https://repo.continuum.io/pkgs/main/osx-64::pytables-3.4.2-py36hfbd7ab0_2
  - defaults::h5py-2.7.1-py36h39cdac5_0, defaults::icu-58.2-h4b95b61_1, https://repo.continuum.io/pkgs/main/osx-64::jupyter_client-5.2.2-py36_0, https://repo.continuum.io/pkgs/main/osx-64::pytables-3.4.2-py36hfbd7ab0_2
  - defaults::h5py-2.7.1-py36h39cdac5_0, defaults::pytables-3.4.2-py36hfbd7ab0_2, https://repo.continuum.io/pkgs/main/osx-64::icu-58.2-h4b95b61_1, https://repo.continuum.io/pkgs/main/osx-64::jupyter_client-5.2.2-py36_0
  - defaults::h5py-2.7.1-py36h39cdac5_0, defaults::icu-58.2-h4b95b61_1, defaults::pytables-3.4.2-py36hfbd7ab0_2, https://repo.continuum.io/pkgs/main/osx-64::jupyter_client-5.2.2-py36_0
  - defaults::pytables-3.4.2-py36hfbd7ab0_2, https://repo.continuum.io/pkgs/main/osx-64::h5py-2.7.1-py36h39cdac5_0, https://repo.continuum.io/pkgs/main/osx-64::icu-58.2-h4b95b61_1, https://repo.continuum.io/pkgs/main/osx-64::jupyter_client-5.2.2-py36_0
  - defaults::icu-58.2-h4b95b61_1, defaults::pytables-3.4.2-py36hfbd7ab0_2, https://repo.continuum.io/pkgs/main/osx-64::h5py-2.7.1-py36h39cdac5_0, https://repo.continuum.io/pkgs/main/osx-64::jupyter_client-5.2.2-py36_0
  - defaults::jupyter_client-5.2.2-py36_0, defaults::pytables-3.4.2-py36hfbd7ab0_2, https://repo.continuum.io/pkgs/main/osx-64::h5py-2.7.1-py36h39cdac5_0, https://repo.continuum.io/pkgs/main/osx-64::icu-58.2-h4b95b61_1
  - defaults::jupyter_client-5.2.2-py36_0, https://repo.continuum.io/pkgs/main/osx-64::h5py-2.7.1-py36h39cdac5_0, https://repo.continuum.io/pkgs/main/osx-64::icu-58.2-h4b95b61_1, https://repo.continuum.io/pkgs/main/osx-64::pytables-3.4.2-py36hfbd7ab0_2
  ... and othedone
```

conda info
```
     active environment : None
            shell level : 0
       user config file : /Users/leo/.condarc
 populated config files : /Users/leo/.condarc
          conda version : 4.7.11
    conda-build version : not installed
         python version : 3.6.9.final.0
       virtual packages : 
       base environment : /Users/leo/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/leo/anaconda3/pkgs
                          /Users/leo/.conda/pkgs
       envs directories : /Users/leo/anaconda3/envs
                          /Users/leo/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.11 requests/2.22.0 CPython/3.6.9 Darwin/17.7.0 OSX/10.13.6
                UID:GID : 503:20
             netrc file : /Users/leo/.netrc
           offline mode : False
```

downgrading to conda 4.6 with this command
`conda install conda=4.6`
worked to remove the warnings.

**Comment by xueyaodeai** [comment]
conda 4.7 still have the same problem

```
~ took 1m 2s 
➜ conda update --strict-channel-priority --all
Collecting package metadata (current_repodata.json): done
Solving environment: \ 
Warning: >10 possible package resolutions (only showing differing packages):
  - https://repo.continuum.io/pkgs/main/osx-64::get_terminal_size-1.0.0-h7520d66_0, https://repo.continuum.io/pkgs/main/osx-64::gettext-0.19.8.1-h15daf44_3, https://repo.continuum.io/pkgs/main/osx-64::gmp-6.1.2-hb37e062_1, https://repo.continuum.io/pkgs/main/osx-64::jbig-2.1-h4d881f8_0
  - defaults::jbig-2.1-h4d881f8_0, https://repo.continuum.io/pkgs/main/osx-64::get_terminal_size-1.0.0-h7520d66_0, https://repo.continuum.io/pkgs/main/osx-64::gettext-0.19.8.1-h15daf44_3, https://repo.continuum.io/pkgs/main/osx-64::gmp-6.1.2-hb37e062_1
  - defaults::gettext-0.19.8.1-h15daf44_3, https://repo.continuum.io/pkgs/main/osx-64::get_terminal_size-1.0.0-h7520d66_0, https://repo.continuum.io/pkgs/main/osx-64::gmp-6.1.2-hb37e062_1, https://repo.continuum.io/pkgs/main/osx-64::jbig-2.1-h4d881f8_0
  - defaults::gettext-0.19.8.1-h15daf44_3, defaults::jbig-2.1-h4d881f8_0, https://repo.continuum.io/pkgs/main/osx-64::get_terminal_size-1.0.0-h7520d66_0, https://repo.continuum.io/pkgs/main/osx-64::gmp-6.1.2-hb37e062_1
  - defaults::get_terminal_size-1.0.0-h7520d66_0, defaults::gettext-0.19.8.1-h15daf44_3, https://repo.continuum.io/pkgs/main/osx-64::gmp-6.1.2-hb37e062_1, https://repo.continuum.io/pkgs/main/osx-64::jbig-2.1-h4d881f8_0
  - defaults::get_terminal_size-1.0.0-h7520d66_0, defaults::gettext-0.19.8.1-h15daf44_3, defaults::jbig-2.1-h4d881f8_0, https://repo.continuum.io/pkgs/main/osx-64::gmp-6.1.2-hb37e062_1
  - defaults::get_terminal_size-1.0.0-h7520d66_0, https://repo.continuum.io/pkgs/main/osx-64::gettext-0.19.8.1-h15daf44_3, https://repo.continuum.io/pkgs/main/osx-64::gmp-6.1.2-hb37e062_1, https://repo.continuum.io/pkgs/main/osx-64::jbig-2.1-h4d881f8_0
  - defaults::get_terminal_size-1.0.0-h7520d66_0, defaults::jbig-2.1-h4d881f8_0, https://repo.continuum.io/pkgs/main/osx-64::gettext-0.19.8.1-h15daf44_3, https://repo.continuum.io/pkgs/main/osx-64::gmp-6.1.2-hb37e062_1
  - defaults::get_terminal_size-1.0.0-h7520d66_0, defaults::gmp-6.1.2-hb37e062_1, https://repo.continuum.io/pkgs/main/osx-64::gettext-0.19.8.1-h15daf44_3, https://repo.continuum.io/pkgs/main/osx-64::jbig-2.1-h4d881f8_0
  - defaults::gmp-6.1.2-hb37e062_1, https://repo.continuum.io/pkgs/main/osx-64::get_terminal_size-1.0.0-h7520d66_0, https://repo.continuum.io/pkgs/main/osx-64::gettext-0.19.8.1-h15daf44_3, https://repo.continuum.io/pkgs/main/osx-64::jbig-2.1-h4d881f8_0
  ... and othedone
```

**Comment by yaochx** [comment]
conda 4.8.0 still have this issue, maybe this is acceptable
`
(base) ➜  ~ conda update --all
Collecting package metadata (current_repodata.json): done
Solving environment: / 
Warning: 2 possible package resolutions (only showing differing packages):
  - defaults::jupyter_console-6.0.0-py37_0, defaults::prompt_toolkit-2.0.9-py37_0
  - defaults::jupyter_console-5.2.0-py37_1, defaults::prompt_toolkit-3.0.2-pydone

# All requested packages already installed.

(base) ➜  ~ conda --version
conda 4.8.0
(base) ➜  ~ conda list|grep jupyter
jupyter                   1.0.0                    py37_7    defaults
jupyter_client            5.3.4                    py37_0    defaults
jupyter_console           6.0.0                    py37_0    defaults
jupyter_core              4.6.1                    py37_0    defaults
jupyterlab                1.2.4              pyhf63ae98_0    defaults
jupyterlab_server         1.0.6                      py_0    defaults
(base) ➜  ~ 
`

**Comment by ChristianBin** [comment]
Has anyone successfully resolved this question?

**Comment by raummensch** [comment]
I just reinstalled Anaconda on Win 10 and have the same problem as many above. Different to some others in my case the channel is always `defaults::`. I assume I have to read it top/bottom rather than left/right? Note: The problem is the same in base and environments.

```
Warning: 2 possible package resolutions (only showing differing packages):
  - defaults::jupyter_console-5.2.0-py37_1, defaults::prompt_toolkit-3.0.2-py_0
  - defaults::jupyter_console-6.0.0-py37_0, defaults::prompt_toolkit-2.0.9-py37done
```

Question: Should running any of the below lines NOT show the "package resolutions" when running the code (BEFORE), or only AFTER an update was done. I am assuming it is BEFORE, but that has not been clear. When I run the below lines I still see the package resolutions issues, so I do not execute them at the y/n junction.
`conda update --strict-channel-priority --all`
`conda update --all`

conda info (for an environment)
```
     active environment : vitamins
    active env location : C:\anaconda3\envs\vitamins
            shell level : 2
       user config file : C:\Users\raum\.condarc
 populated config files :
          conda version : 4.8.0
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages : __cuda=9.1
       base environment : C:\anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\anaconda3\pkgs
                          C:\Users\raum\.conda\pkgs
                          C:\Users\raum\AppData\Local\conda\conda\pkgs
       envs directories : C:\anaconda3\envs
                          C:\Users\raum\.conda\envs
                          C:\Users\raum\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.0 requests/2.22.0 CPython/3.7.4 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by jjhelmus** [comment]
The multiple solution between jupyter_console and prompt_toolkit has been fixed in AnacondaRecipes/repodata-hotfixes#62

**Comment by tloredo** [comment]
I've been experiencing this problem for several weeks after `conda update conda`. I've copied my `conda info` output below. I find this thread confusing regarding what the solution is, and whether any of these solutions are permanent/sanctioned and/or have side effects that will need to be dealt with down the road:

```
conda update --strict-channel-priority --all 
conda update --all [not clear if this is separate or must follow the previous one]
conda install conda=4.8 [will this require me to manually track the current version going forward?]
```

I'd appreciate clarification/advice on the best way forward.

-Tom

```
$ conda info

     active environment : base
    active env location : /Users/loredo/anaconda
            shell level : 1
       user config file : /Users/loredo/.condarc
 populated config files :
          conda version : 4.8.1
    conda-build version : 3.16.3
         python version : 3.6.9.final.0
       virtual packages : __osx=10.14.6
       base environment : /Users/loredo/anaconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/loredo/anaconda/pkgs
                          /Users/loredo/.conda/pkgs
       envs directories : /Users/loredo/anaconda/envs
                          /Users/loredo/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.1 requests/2.22.0 CPython/3.6.9 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by Daniel19960601** [comment]
`conda update --strict-channel-priority --all
Collecting package metadata (current_repodata.json): done
Solving environment: -
Warning: >10 possible package resolutions (only showing differing packages):
  - https://repo.anaconda.com/pkgs/main/win-64/win-64::chardet-3.0.4-py37_1003, https://repo.anaconda.com/pkgs/main/win-64/win-64::cryptography-2.8-py37h7a1dbc1_0, https://repo.anaconda.com/pkgs/main/win-64/win-64::menuinst-1.4.16-py37he774522_0, https://repo.anaconda.com/pkgs/main/win-64/win-64::pycparser-2.19-py37_0
  - defaults/win-64::menuinst-1.4.16-py37he774522_0, https://repo.anaconda.com/pkgs/main/win-64/win-64::chardet-3.0.4-py37_1003, https://repo.anaconda.com/pkgs/main/win-64/win-64::cryptography-2.8-py37h7a1dbc1_0, https://repo.anaconda.com/pkgs/main/win-64/win-64::pycparser-2.19-py37_0
  - defaults/win-64::pycparser-2.19-py37_0, https://repo.anaconda.com/pkgs/main/win-64/win-64::chardet-3.0.4-py37_1003, https://repo.anaconda.com/pkgs/main/win-64/win-64::cryptography-2.8-py37h7a1dbc1_0, https://repo.anaconda.com/pkgs/main/win-64/win-64::menuinst-1.4.16-py37he774522_0
  - defaults/win-64::menuinst-1.4.16-py37he774522_0, defaults/win-64::pycparser-2.19-py37_0, https://repo.anaconda.com/pkgs/main/win-64/win-64::chardet-3.0.4-py37_1003, https://repo.anaconda.com/pkgs/main/win-64/win-64::cryptography-2.8-py37h7a1dbc1_0
  - defaults/win-64::cryptography-2.8-py37h7a1dbc1_0, defaults/win-64::pycparser-2.19-py37_0, https://repo.anaconda.com/pkgs/main/win-64/win-64::chardet-3.0.4-py37_1003, https://repo.anaconda.com/pkgs/main/win-64/win-64::menuinst-1.4.16-py37he774522_0
  - defaults/win-64::cryptography-2.8-py37h7a1dbc1_0, defaults/win-64::menuinst-1.4.16-py37he774522_0, defaults/win-64::pycparser-2.19-py37_0, https://repo.anaconda.com/pkgs/main/win-64/win-64::chardet-3.0.4-py37_1003
  - defaults/win-64::cryptography-2.8-py37h7a1dbc1_0, https://repo.anaconda.com/pkgs/main/win-64/win-64::chardet-3.0.4-py37_1003, https://repo.anaconda.com/pkgs/main/win-64/win-64::menuinst-1.4.16-py37he774522_0, https://repo.anaconda.com/pkgs/main/win-64/win-64::pycparser-2.19-py37_0
  - defaults/win-64::cryptography-2.8-py37h7a1dbc1_0, defaults/win-64::menuinst-1.4.16-py37he774522_0, https://repo.anaconda.com/pkgs/main/win-64/win-64::chardet-3.0.4-py37_1003, https://repo.anaconda.com/pkgs/main/win-64/win-64::pycparser-2.19-py37_0
  - defaults/win-64::chardet-3.0.4-py37_1003, defaults/win-64::cryptography-2.8-py37h7a1dbc1_0, https://repo.anaconda.com/pkgs/main/win-64/win-64::menuinst-1.4.16-py37he774522_0, https://repo.anaconda.com/pkgs/main/win-64/win-64::pycparser-2.19-py37_0
  - defaults/win-64::chardet-3.0.4-py37_1003, https://repo.anaconda.com/pkgs/main/win-64/win-64::cryptography-2.8-py37h7a1dbc1_0, https://repo.anaconda.com/pkgs/main/win-64/win-64::menuinst-1.4.16-py37he774522_0, https://repo.anaconda.com/pkgs/main/win-64/win-64::pycparser-2.19-py37_0
  ... and othedone

# All requested packages already installed.`
`conda info

     active environment : base
    active env location : C:\Users\77365\Miniconda3
            shell level : 1
       user config file : C:\Users\77365\.condarc
 populated config files : C:\Users\77365\.condarc
          conda version : 4.8.2
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages :
       base environment : C:\Users\77365\Miniconda3  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/noarch
          package cache : C:\Users\77365\Miniconda3\pkgs
                          C:\Users\77365\.conda\pkgs
                          C:\Users\77365\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\77365\Miniconda3\envs
                          C:\Users\77365\.conda\envs
                          C:\Users\77365\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.18362
          administrator : True
             netrc file : None
           offline mode : False`

**Comment by PasaOpasen** [comment]
(base) C:\Windows\system32>conda update conda
Collecting package metadata (current_repodata.json): done
Solving environment: -
Warning: >10 possible package resolutions (only showing differing packages):
  - r/noarch::r-iterators-1.0.10-r36h6115d3f_0, r/win-64::r-colorspace-1.4_1-r36h6115d3f_0, r/win-64::r-processx-3.3.0-r36h6115d3f_0, r/win-64::r-ps-1.3.0-r36h6115d3f_0
  - defaults/win-64::r-ps-1.3.0-r36h6115d3f_0, r/noarch::r-iterators-1.0.10-r36h6115d3f_0, r/win-64::r-colorspace-1.4_1-r36h6115d3f_0, r/win-64::r-processx-3.3.0-r36h6115d3f_0
  - defaults/win-64::r-colorspace-1.4_1-r36h6115d3f_0, r/noarch::r-iterators-1.0.10-r36h6115d3f_0, r/win-64::r-processx-3.3.0-r36h6115d3f_0, r/win-64::r-ps-1.3.0-r36h6115d3f_0
  - defaults/win-64::r-colorspace-1.4_1-r36h6115d3f_0, defaults/win-64::r-ps-1.3.0-r36h6115d3f_0, r/noarch::r-iterators-1.0.10-r36h6115d3f_0, r/win-64::r-processx-3.3.0-r36h6115d3f_0
  - defaults/noarch::r-iterators-1.0.10-r36h6115d3f_0, defaults/win-64::r-colorspace-1.4_1-r36h6115d3f_0, r/win-64::r-processx-3.3.0-r36h6115d3f_0, r/win-64::r-ps-1.3.0-r36h6115d3f_0
  - defaults/noarch::r-iterators-1.0.10-r36h6115d3f_0, defaults/win-64::r-colorspace-1.4_1-r36h6115d3f_0, defaults/win-64::r-ps-1.3.0-r36h6115d3f_0, r/win-64::r-processx-3.3.0-r36h6115d3f_0
  - defaults/noarch::r-iterators-1.0.10-r36h6115d3f_0, r/win-64::r-colorspace-1.4_1-r36h6115d3f_0, r/win-64::r-processx-3.3.0-r36h6115d3f_0, r/win-64::r-ps-1.3.0-r36h6115d3f_0
  - defaults/noarch::r-iterators-1.0.10-r36h6115d3f_0, defaults/win-64::r-ps-1.3.0-r36h6115d3f_0, r/win-64::r-colorspace-1.4_1-r36h6115d3f_0, r/win-64::r-processx-3.3.0-r36h6115d3f_0
  - defaults/noarch::r-iterators-1.0.10-r36h6115d3f_0, defaults/win-64::r-processx-3.3.0-r36h6115d3f_0, r/win-64::r-colorspace-1.4_1-r36h6115d3f_0, r/win-64::r-ps-1.3.0-r36h6115d3f_0
  - defaults/win-64::r-processx-3.3.0-r36h6115d3f_0, r/noarch::r-iterators-1.0.10-r36h6115d3f_0, r/win-64::r-colorspace-1.4_1-r36h6115d3f_0, r/win-64::r-ps-1.3.0-r36h6115d3f_0
  ... and othedone

# All requested packages already installed.




(base) C:\Windows\system32>conda info

     active environment : base
    active env location : C:\ProgramData\Anaconda3
            shell level : 1
       user config file : C:\Users\qtckp\.condarc
 populated config files : C:\Users\qtckp\.condarc
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.7.7.final.0
       virtual packages : __cuda=11.0
       base environment : C:\ProgramData\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\qtckp\.conda\pkgs
                          C:\Users\qtckp\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\qtckp\.conda\envs
                          C:\Users\qtckp\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.7 Windows/10 Windows/10.0.18362
          administrator : True
             netrc file : None
           offline mode : False

**Comment by lazarillo** [comment]
> The problem is that old builds of nbconvert do not put any constraint on their pandoc version. New ones do. The solver is forced to choose between newer nbconvert or newer pandoc, and they're mathematically equivalent here. We need to fix our repo data, so that all nbconvert builds have an upper bound for pandoc.

Thank you, @msarahan !  Yours was the only comment in this thread that actually explained what was happening so that I understood whether or not to worry about this.  I was finding the issue with `importlib`, but of course almost everyone who has this issue will have it with a different package.

The truly useful answer, therefore, is to explain the underlying mechanic:  there are two potential repos, each of which are equivalently "correct" because one is further ahead for one dependency and the other is further ahead for another.

In my case, I am assuming "all is good", but if I have a problem, now I know I can force the other repo to be chosen (or I can force a particular version of a dependency).

People should not "thumbs up" other complaints or problems... it challenges others in tracking down the truly useful answers like what Mike provided above.

**Comment by tightropeboy** [comment]
You should go to your anaconda directory, anaconda3/pkgs and look for the resolution you want to delete, I delete low versions actually.
If you're not sure what resolution to delete make a backup of each.
