### ISSUE TITLE
Missing windows dll aftet conda and vc update

### ISSUE THREAD

**Issue by sergeyfarin** [ContinuumIO/anaconda-issues#7883]
I cannot start python or conda after updated conda and vc:

`C:\A\P\PyCmd> conda update --all
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment C:\Apps\Programs\Miniconda3:

The following NEW packages will be INSTALLED:

    vs2017_runtime: 15.5.2-1

The following packages will be UPDATED:

    conda:          4.3.31-py36_0 --> 4.4.1-py36_0
    vc:             14-h2379b0c_2 --> 14.1-h21ff451_1

Proceed ([y]/n)?

vs2017_runtime 100% |###############################| Time: 0:00:00   2.70 MB/s
vc-14.1-h21ff4 100% |###############################| Time: 0:00:00   0.00  B/s
conda-4.4.1-py 100% |###############################| Time: 0:00:00  10.61 MB/s`

Now, starting python or conda gives error popup:
**The program can't start because api-ms-win-core-rtlsupport-l1-2-0.dll is missing.**

**Comment by nehaljwani** [comment]
I think the latest vs2017_runtime package is suffering from this issue: https://stackoverflow.com/q/45745336/1005215

**Comment by msarahan** [comment]
Thanks for reporting this.  I'm not sure where this file comes from, but we'll find it and include it.  The usual place for this file, C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\ has only api-ms-win-core-rtlsupport-l1-1-0.dll

**Comment by msarahan** [comment]
MS appears to tell us that we should not have those DLLs: https://social.msdn.microsoft.com/Forums/en-US/a28331ae-19a3-4a34-b3ba-1e8fd4430375/missing-apimswincore-dlls

We have pulled these packages for now, and we'll reexamine the right solution after the holidays.

**Comment by sergeyfarin** [comment]
I could not start python, so deleted and copied VC related dlls from another Anaconda install.
It fixed python and conda, but strangely QT designer was still giving error message of not being able to find dll. Did not want to risk and do conda update --all one more time, did this just now. It suggested quite a few changes and worked fine. Now everything works
```
api-ms-win-core-console-l1-1-0.dll
api-ms-win-core-datetime-l1-1-0.dll
api-ms-win-core-debug-l1-1-0.dll
api-ms-win-core-errorhandling-l1-1-0.dll
api-ms-win-core-file-l1-1-0.dll
api-ms-win-core-file-l1-2-0.dll
api-ms-win-core-file-l2-1-0.dll
api-ms-win-core-handle-l1-1-0.dll
api-ms-win-core-heap-l1-1-0.dll
api-ms-win-core-interlocked-l1-1-0.dll
api-ms-win-core-libraryloader-l1-1-0.dll
api-ms-win-core-localization-l1-2-0.dll
api-ms-win-core-memory-l1-1-0.dll
api-ms-win-core-namedpipe-l1-1-0.dll
api-ms-win-core-processenvironment-l1-1-0.dll
api-ms-win-core-processthreads-l1-1-0.dll
api-ms-win-core-processthreads-l1-1-1.dll
api-ms-win-core-profile-l1-1-0.dll
api-ms-win-core-rtlsupport-l1-1-0.dll
api-ms-win-core-string-l1-1-0.dll
api-ms-win-core-synch-l1-1-0.dll
api-ms-win-core-synch-l1-2-0.dll
api-ms-win-core-sysinfo-l1-1-0.dll
api-ms-win-core-timezone-l1-1-0.dll
api-ms-win-core-util-l1-1-0.dll
api-ms-win-crt-conio-l1-1-0.dll
api-ms-win-crt-convert-l1-1-0.dll
api-ms-win-crt-environment-l1-1-0.dll
api-ms-win-crt-filesystem-l1-1-0.dll
api-ms-win-crt-heap-l1-1-0.dll
api-ms-win-crt-locale-l1-1-0.dll
api-ms-win-crt-math-l1-1-0.dll
api-ms-win-crt-multibyte-l1-1-0.dll
api-ms-win-crt-private-l1-1-0.dll
api-ms-win-crt-process-l1-1-0.dll
api-ms-win-crt-runtime-l1-1-0.dll
api-ms-win-crt-stdio-l1-1-0.dll
api-ms-win-crt-string-l1-1-0.dll
api-ms-win-crt-time-l1-1-0.dll
api-ms-win-crt-utility-l1-1-0.dll
msvcp140.dll
ucrtbase.dll
vccorlib140.dll
vcomp140.dll
vcruntime140.dll
```

Conda update --all now:
```
C:\A\P\PyCmd> conda update --all
Solving environment: done

## Package Plan ##

  environment location: C:\Apps\Programs\Miniconda3


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.4.3                |           py36_0         647 KB
    jupyter-1.0.0              |           py36_3           4 KB
    vs2015_runtime-14.0.25420  |                0         2.0 MB
    simplegeneric-0.8.1        |           py36_1           8 KB
    ------------------------------------------------------------
                                           Total:         2.6 MB

The following packages will be REMOVED:

    cachecontrol:     0.12.3-py36hfe50d7b_0
    console_shortcut: 0.1.1-h6bb2dd7_3
    distlib:          0.2.5-py36h51371be_0
    lockfile:         0.12.2-py36h0468280_0
    msgpack-python:   0.4.8-py36h58b1e9d_0
    packaging:        16.8-py36ha0986f6_1
    progress:         1.3-py36hbeca8d3_0

The following packages will be UPDATED:

    conda:            4.4.1-py36_0          --> 4.4.3-py36_0
    jupyter:          1.0.0-py36h422fd7e_2  --> 1.0.0-py36_3
    simplegeneric:    0.8.1-py36heab741f_0  --> 0.8.1-py36_1
    vs2015_runtime:   14.0.25123-hd4c4e62_2 --> 14.0.25420-0

Proceed ([y]/n)?


Downloading and Extracting Packages
conda 4.4.3: ################################################################################################## | 100%
jupyter 1.0.0: ################################################################################################ | 100%
vs2015_runtime 14.0.25420: #################################################################################### | 100%
simplegeneric 0.8.1: ########################################################################################## | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: - DEBUG menuinst_win32:__init__(185): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Ap
ps\Programs\Miniconda3', env_name: 'None', mode: 'None', used_mode: 'user'
DEBUG menuinst_win32:create(299): Shortcut cmd is %windir%\System32\cmd.exe, args are ['"/K"', 'C:\\Apps\\Programs\\Mini
conda3\\Scripts\\activate.bat', 'C:\\Apps\\Programs\\Miniconda3']
done
```

**Comment by pj-parag** [comment]
I am facing this issue after I install nltk. Using conda install -c anaconda nltk

**Comment by 77QingLiu** [comment]
Same issue after update pandas by conda install -c anaconda pandas

**Comment by 77QingLiu** [comment]
Missing DLL problem seems not the problem. please look the following answer from Microsoft officer staff below.
![image](https://user-images.githubusercontent.com/32193271/34382640-4dcc37e8-eb4b-11e7-9c62-111eb44cfdf0.png)

**Comment by pj-parag** [comment]
For me it worked if I install tensorflow as: pip install tensorflow
instead of doing pip install --ignore-installed --upgrade tensorflow
And using pip to install nltk inside env

**Comment by 77QingLiu** [comment]
@pj-parag , How could you start pip if you face this issue? I even couldn't start any python related program now!

**Comment by pj-parag** [comment]
I had to reinstall anaconda again

**Comment by 77QingLiu** [comment]
@pj-parag  thanks for your reminding. I reinstall anaconda agian. Using PIP instead of Conda to update the package, The problem has gone away.

**Comment by mparry** [comment]
@msarahan 

> We have pulled these packages for now, and we'll reexamine the right solution after the holidays.

Is there any update here? Were these packages reverted in the end? It doesn't seem like that's the case (from looking at the channel) and certainly it still seems to fail in the same way if the current `vs2017_runtime` package is installed on Windows 7.

**Comment by msarahan** [comment]
Microsoft helped us identify the issue.  There were runtimes from an incorrect folder being bundled.  We have fixed it, but we are not planning on rolling out the fix until after the Anaconda 5.1 release later this week.

vs2017_runtime is still available, but we have removed the vc 14.1 package, which was the reason why vs2017_runtime was being used at all.

**Comment by mparry** [comment]
Ah, I see. Unfortunately we have some cases where (due to native code in the packages in question) we actually require `vs2017_runtime` directly, so the problem still arises.

I don't suppose this fixed package exists in a pre-release channel somewhere or anything?

**Comment by msarahan** [comment]
The c3i_test2 channel on anaconda.org has the packages.  The vs2017_runtime package is actually going away.  It's called vs2015_runtime, but has version number >=15.  If you depend on or install the correct vc package (14.1, not 14), things should work.

**Comment by sergeyfarin** [comment]
Do not think its still relevant
