### ISSUE TITLE
gcc_linux-64 breaks conda: 'lsb_release -a' returned non-zero exit status 1

### ISSUE THREAD

**Issue by crusaderky** [ContinuumIO/anaconda-issues#8244]
Installing gcc_linux-64 on Ubuntu 17.10 x64 makes conda completely unusable.

To reproduce:
```
$ wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
$ bash Miniconda3-latest-Linux-x86_64.sh -b
$ . miniconda3/bin/activate 
$ conda install -y gcc_linux-64
$ conda list --export
# platform: linux-64
asn1crypto=0.23.0=py36h4639342_0
binutils_impl_linux-64=2.28.1=h04c84fa_2
binutils_linux-64=7.2.0=25
ca-certificates=2017.08.26=h1d4fec5_0
certifi=2017.11.5=py36hf29ccca_0
cffi=1.11.2=py36h2825082_0
chardet=3.0.4=py36h0f667ec_1
conda=4.4.7=py36_0
conda-env=2.6.0=h36134e3_1
cryptography=2.1.4=py36hd09be54_0
gcc_impl_linux-64=7.2.0=hc5ce805_2
gcc_linux-64=7.2.0=25
idna=2.6=py36h82fb2a8_1
libedit=3.1=heed3624_0
libffi=3.2.1=hd88cf55_4
libgcc-ng=7.2.0=h7cc24e2_2
libstdcxx-ng=7.2.0=h7a57d05_2
ncurses=6.0=h9df7e31_2
openssl=1.0.2n=hb7f436b_0
pip=9.0.1=py36h6c6f9ce_4
pycosat=0.6.3=py36h0a5515d_0
pycparser=2.18=py36hf9f622e_1
pyopenssl=17.5.0=py36h20ba746_0
pysocks=1.6.7=py36hd97a5b1_1
python=3.6.3=h6c0c0dc_5
readline=7.0=ha6073c6_4
requests=2.18.4=py36he2e5f8d_1
ruamel_yaml=0.11.14=py36ha2fb22d_2
setuptools=36.5.0=py36he42e2e1_0
six=1.11.0=py36h372c433_1
sqlite=3.20.1=hb898158_2
tk=8.6.7=hc745277_3
urllib3=1.22=py36hbe7ace6_0
wheel=0.30.0=py36hfd4bba0_1
xz=5.2.3=h55aa19d_2
yaml=0.1.7=had09818_2
zlib=1.2.11=ha838bed_2
```

Now simply close the terminal and reopen it:

```
$ . miniconda3/bin/activate 
$ conda update --all

Solving environment: failed
WARNING conda.exceptions:print_error_report(853): KeyError('pkgs_dirs',)
Traceback (most recent call last):
  File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/gateways/connection/session.py", line 50, in __call__
    return cls._thread_local.session
AttributeError: '_thread._local' object has no attribute 'session'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 743, in __call__
    return func(*args, **kwargs)
  File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 78, in _main
    exit_code = do_call(args, p)
  File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 76, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/cli/main_update.py", line 14, in execute
    install(args, parser, 'update')
  File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 236, in install
    force_reinstall=context.force,
  File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 504, in solve_for_transaction
    force_remove, force_reinstall)
  File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 437, in solve_for_diff
    final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
  File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 178, in solve_final_state
    index, r = self._prepare(prepared_specs)
  File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 560, in _prepare
    self.subdirs, prepared_specs)
  File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 214, in get_reduced_index
    new_records = query_all(spec)
  File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 187, in query_all
    return tuple(concat(future.result() for future in as_completed(futures)))
  File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 98, in query
    self.load()
  File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 142, in load
    _internal_state = self._load()
  File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 210, in _load
    mod_etag_headers.get('_mod'))
  File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 391, in fetch_repodata_remote_request
    session = CondaSession()
  File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/gateways/connection/session.py", line 52, in __call__
    session = cls._thread_local.session = super(CondaSessionType, cls).__call__()
  File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/gateways/connection/session.py", line 85, in __init__
    self.headers['User-Agent'] = context.user_agent
  File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/base/context.py", line 611, in user_agent
    return _get_user_agent(self.platform)
  File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/decorators.py", line 56, in _memoized_func
    result = func(*args, **kwargs)
  File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/base/context.py", line 905, in _get_user_agent
    from .._vendor.distro import linux_distribution
  File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/_vendor/distro.py", line 1078, in <module>
    _distro = LinuxDistribution()
  File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/_vendor/distro.py", line 600, in __init__
    if include_lsb else {}
  File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/_vendor/distro.py", line 937, in _get_lsb_release_info
    raise subprocess.CalledProcessError(code, cmd, stdout, stderr)
subprocess.CalledProcessError: Command 'lsb_release -a' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 851, in print_error_report
    message_builder.append(get_main_info_str(error_report['conda_info']))
  File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/cli/main_info.py", line 239, in get_main_info_str
    info_dict['_' + key] = ('\n' + 26 * ' ').join(info_dict[key])
KeyError: 'pkgs_dirs'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/gateways/connection/session.py", line 50, in __call__
        return cls._thread_local.session
    AttributeError: '_thread._local' object has no attribute 'session'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 743, in __call__
        return func(*args, **kwargs)
      File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 76, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/cli/main_update.py", line 14, in execute
        install(args, parser, 'update')
      File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 236, in install
        force_reinstall=context.force,
      File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 504, in solve_for_transaction
        force_remove, force_reinstall)
      File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 437, in solve_for_diff
        final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
      File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 178, in solve_final_state
        index, r = self._prepare(prepared_specs)
      File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 560, in _prepare
        self.subdirs, prepared_specs)
      File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 214, in get_reduced_index
        new_records = query_all(spec)
      File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 187, in query_all
        return tuple(concat(future.result() for future in as_completed(futures)))
      File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 98, in query
        self.load()
      File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 142, in load
        _internal_state = self._load()
      File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 210, in _load
        mod_etag_headers.get('_mod'))
      File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 391, in fetch_repodata_remote_request
        session = CondaSession()
      File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/gateways/connection/session.py", line 52, in __call__
        session = cls._thread_local.session = super(CondaSessionType, cls).__call__()
      File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/gateways/connection/session.py", line 85, in __init__
        self.headers['User-Agent'] = context.user_agent
      File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/base/context.py", line 611, in user_agent
        return _get_user_agent(self.platform)
      File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/decorators.py", line 56, in _memoized_func
        result = func(*args, **kwargs)
      File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/base/context.py", line 905, in _get_user_agent
        from .._vendor.distro import linux_distribution
      File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/_vendor/distro.py", line 1078, in <module>
        _distro = LinuxDistribution()
      File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/_vendor/distro.py", line 600, in __init__
        if include_lsb else {}
      File "/home/crusaderky/miniconda3/lib/python3.6/site-packages/conda/_vendor/distro.py", line 937, in _get_lsb_release_info
        raise subprocess.CalledProcessError(code, cmd, stdout, stderr)
    subprocess.CalledProcessError: Command 'lsb_release -a' returned non-zero exit status 1.

`$ /home/crusaderky/miniconda3/bin/conda update --all`

  environment variables:
conda info could not be constructed.
KeyError('pkgs_dirs',)
```

**Comment by nehaljwani** [comment]
Not saying it is related, but as of Jan 13 2018, Ubuntu 17.04 has reached EOL. http://fridge.ubuntu.com/2018/01/17/ubuntu-17-04-zesty-zapus-reached-end-of-life-on-january-13-2018/

**Comment by crusaderky** [comment]
??? I'm on 17.10

**Comment by mingwandroid** [comment]
Confirmed. The problem is that `lsb_release` uses the system python and we've set a variable it cannot handle:

```
lsb_release -a
Failed to import the site module
Traceback (most recent call last):
  File "/usr/lib/python3.6/site.py", line 561, in <module>
    main()
  File "/usr/lib/python3.6/site.py", line 547, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python3.6/site.py", line 288, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python3.6/site.py", line 264, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python3.6/site.py", line 254, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python3.6/sysconfig.py", line 607, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python3.6/sysconfig.py", line 550, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python3.6/sysconfig.py", line 421, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata_x86_64_conda_cos6_linux_gnu'
```

**Comment by mingwandroid** [comment]
@msarahan, @jjhelmus, @nehaljwani, I think we need to patch our python to use a differently named variable for this so we don't break system pythons. Thoughts?

**Comment by mingwandroid** [comment]
@kalefranz, for now we need to just delete this low level Python env var when calling `lsb_release`, please review https://github.com/conda/conda/pull/6768

**Comment by jjhelmus** [comment]
@mingwandroid I agree, we should use a different variable name so that conflicts like this do not happen.  The current usage of `_PYTHON_SYSCONFIGDATA_NAME` can cause problems, perhaps `_CONDA_PYTHON_SYSCONFIGDATA_NAME` is a good choice.  In Python 3.6 at least we need to retain the ability to override using the original variable name since this is a feature of Python not one we back ported.  

A work around until this is implemented is to unset the variable, `unset _PYTHON_SYSCONFIGDATA_NAME` should work.

**Comment by mingwandroid** [comment]
This has been fixed for a few weeks now. Please run conda update python.

**Comment by mzhibo** [comment]
this issue still exist. with anaconda 5 installer, both anaconda2 and anaconda3. Seem to be a issue with the conda manager.
I had to use the anaconda3-4 installer...
Hope you guys fix this soon

**Comment by mingwandroid** [comment]
As I already said:

> This has been fixed for a few weeks now. Please run conda update python gxx_linux-64 gcc_linux-64 in your base environment

**Comment by DonghunP** [comment]
@mingwandroid  I'm sorry but.. when I run  'conda update python gxx_linux-64 gcc_linux-64'

PackageNotInstalledError: Package is not installed in prefix.
  prefix: /home/anaconda/anaconda3
  package name: gxx_linux-64

It happen. How can I solve?..

**Comment by robertsk50** [comment]
My problem was that `lsb_release` broke when I updated `python3` symlinks to point to the conda python executable. To get it working again I added `lsb_release.py` to the conda site-packages directory similar to [here](https://stackoverflow.com/a/48643001/1265657).
