### ISSUE TITLE
"Thanks for installing"-message box reappears on every startup of Anaconda Navigator

### ISSUE THREAD

**Issue by Khris777** [ContinuumIO/anaconda-issues#8488]
### Actual Behavior

Every time I'm starting Anaconda Navigator I'm getting the "Thanks for installing Anaconda!"-message box with the checkbox asking for help with improving and the two buttons "Ok" and "Ok, and don't show again".

I always uncheck the checkbox and click on "Ok, and don't show again" yet the message shows up again on the next start up.

In my preferences the checkbox "Provide analytics" is set to unchecked.

### Expected Behavior

Message should stop appearing.

##### Anaconda or Miniconda version:

Navigator Version 1.6.12

**Comment by Khris777** [comment]
Problem solved by launching Navigator as administrator once.

**Comment by p-d-moore** [comment]
This still happens on the latest version of Anaconda Navigator (1.9.7) under Windows 10.  I installed Anaconda for "just me" as I do not have administrator access to this PC.  Given Anaconda is installed for an individual user without requiring administrator access and I cannot apply the work around suggested by Khris777 as I do not have administrator access, I suggest this issue is not really fixed.

**Comment by DenShlk** [comment]
Hasn't fixed yet. Anyway, thanks to @Khris777 for the solution, it works. My case: Win 10, Anaconda Navigator 1.9.12
