### ISSUE TITLE
Navigator does not update packages

### ISSUE THREAD

**Issue by yazabaza** [ContinuumIO/anaconda-issues#9087]
In Navigator, Environments > select environment, select "Updatable", right-click packages > "Mark for Update", click "Apply". See "The following packages will be modified", click "Apply". --> Nothing happens! After doing this about 10 times it seems that some of the packages updated behind the scenes, but not all. Update Index does not help. Restart Navigator does not help.

##### Anaconda or Miniconda version:
Anaconda Navigator 1.82
##### Operating System:
MacOS 10.13.3
##### `conda info`
```
     active environment : None
       user config file : /Users/r/.condarc
 populated config files : /Users/r/.condarc
          conda version : 4.4.4
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       base environment : /Users/r/anaconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /Users/r/anaconda3/pkgs
                          /Users/r/.conda/pkgs
       envs directories : /Users/r/anaconda3/envs
                          /Users/r/.conda/envs
               platform : osx-64
             user-agent : conda/4.4.4 requests/2.18.4 CPython/3.6.3 Darwin/17.4.0 OSX/10.13.3
                UID:GID : 502:20
             netrc file : /Users/r/.netrc
           offline mode : False

```

##### `conda list --show-channel-urls`
```
# packages in environment at /Users/r/anaconda3:
#
_ipyw_jlab_nb_ext_conf    0.1.0            py36h2fc01ae_0    defaults
alabaster                 0.7.10           py36h174008c_0    defaults
anaconda                  custom           py36ha4fed55_0    defaults
anaconda-client           1.6.12                   py36_0    defaults
anaconda-navigator        1.8.2                    py36_0    defaults
anaconda-project          0.8.0            py36h99320b2_0    defaults
appnope                   0.1.0            py36hf537a9a_0    defaults
appscript                 1.0.1            py36h9e71e49_1    defaults
asn1crypto                0.22.0           py36hb705621_1    defaults
astroid                   1.5.3            py36h1333018_0    defaults
astropy                   2.0.2            py36hf79c81d_4    defaults
babel                     2.5.0            py36h9f161ff_0    defaults
backports                 1.0              py36ha3c1827_1    defaults
backports.shutil_get_terminal_size 1.0.0            py36hd7a2ee4_2    defaults
beautifulsoup4            4.6.0            py36h72d3c9f_1    defaults
bitarray                  0.8.1            py36h20fa61d_0    defaults
bkcharts                  0.2              py36h073222e_0    defaults
blaze                     0.11.3           py36h02e7a37_0    defaults
bleach                    2.0.0            py36h8fcea71_0    defaults
bokeh                     0.12.10          py36hfd5be35_0    defaults
boto                      2.48.0           py36hdbc59ac_1    defaults
bottleneck                1.2.1            py36hbd380ad_0    defaults
bzip2                     1.0.6                h92991f9_1    defaults
ca-certificates           2018.03.07                    0    defaults
certifi                   2018.1.18                py36_0    defaults
cffi                      1.10.0           py36h880867e_1    defaults
chardet                   3.0.4            py36h96c241c_1    defaults
click                     6.7              py36hec950be_0    defaults
cloudpickle               0.4.0            py36h13b7e56_0    defaults
clyent                    1.2.2            py36hae3ad88_0    defaults
colorama                  0.3.9            py36hd29a30c_0    defaults
conda                     4.4.4                    py36_0    defaults
conda-build               3.0.27           py36hb78d8cd_0    defaults
conda-env                 2.6.0                h36134e3_0    defaults
conda-verify              2.0.0            py36he837df3_0    defaults
contextlib2               0.5.5            py36hd66e5e7_0    defaults
cryptography              2.0.3            py36h22d4226_1    defaults
curl                      7.55.1               h7601780_3    defaults
cycler                    0.10.0           py36hfc81398_0    defaults
cython                    0.26.1           py36hd51f8eb_0    defaults
cytoolz                   0.8.2            py36h290905f_0    defaults
dask                      0.15.3           py36hc3ad2d6_0    defaults
dask-core                 0.15.3           py36hc0be6b7_0    defaults
datashape                 0.5.4            py36hfb22df8_0    defaults
dbus                      1.10.22              h50d9ad6_0    defaults
decorator                 4.1.2            py36h69a1b52_0    defaults
distributed               1.19.1           py36h4ae75d2_0    defaults
docutils                  0.14             py36hbfde631_0    defaults
entrypoints               0.2.3            py36hd81d71f_2    defaults
et_xmlfile                1.0.1            py36h1315bdc_0    defaults
expat                     2.2.4                h8f26bf8_1    defaults
fastcache                 1.0.2            py36h8606a76_0    defaults
filelock                  2.0.12           py36h0d0b4fb_0    defaults
flask                     0.12.2           py36h5658096_0    defaults
flask-cors                3.0.3            py36h7387b97_0    defaults
freetype                  2.8                  h143eb01_0    defaults
get_terminal_size         1.0.0                h7520d66_0    defaults
gettext                   0.19.8.1             hb0f4f8b_2    defaults
gevent                    1.2.2            py36ha70b9d6_0    defaults
glib                      2.53.6               ha08cb78_1    defaults
glob2                     0.5              py36h12393a9_0    defaults
gmp                       6.1.2                h4a9834d_0    defaults
gmpy2                     2.0.8            py36h7ef02cb_1    defaults
greenlet                  0.4.12           py36hf09ba7b_0    defaults
h5py                      2.7.0            py36h6400cee_1    defaults
hdf5                      1.10.1               h6090a45_0    defaults
heapdict                  1.0.0            py36h27a9ac6_0    defaults
html5lib                  0.999999999      py36h79312fd_0    defaults
icu                       58.2                 hea21ae5_0    defaults
idna                      2.6              py36h8628d0a_1    defaults
imageio                   2.2.0            py36h5e01289_0    defaults
imagesize                 0.7.1            py36h3495948_0    defaults
intel-openmp              2018.0.0             h68bdfb3_7    defaults
ipykernel                 4.6.1            py36h3208c25_0    defaults
ipython                   6.1.0            py36hf612aae_1    defaults
ipython_genutils          0.2.0            py36h241746c_0    defaults
ipywidgets                7.0.0            py36h24d3910_0    defaults
isort                     4.2.15           py36hceb2a01_0    defaults
itsdangerous              0.24             py36h49fbb8d_1    defaults
jbig                      2.1                  h4d881f8_0    defaults
jdcal                     1.3              py36h1986823_0    defaults
jedi                      0.10.2           py36h6325097_0    defaults
jinja2                    2.9.6            py36hde4beb4_1    defaults
jpeg                      9b                   haccd157_1    defaults
jsonschema                2.6.0            py36hb385e00_0    defaults
jupyter                   1.0.0            py36h598a6cc_0    defaults
jupyter_client            5.1.0            py36hf6c435f_0    defaults
jupyter_console           5.2.0            py36hccf5b1c_1    defaults
jupyter_core              4.3.0            py36h93810fe_0    defaults
jupyterlab                0.27.0           py36hd3092eb_2    defaults
jupyterlab_launcher       0.4.0            py36h93e02e9_0    defaults
lazy-object-proxy         1.3.1            py36h2fbbe47_0    defaults
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    defaults
libedit                   3.1                  hb4e282d_0    defaults
libffi                    3.2.1                hd939716_3    defaults
libgfortran               3.0.1                h93005f0_2    defaults
libiconv                  1.15                 h99df5da_5    defaults
libpng                    1.6.32               hce72d48_2    defaults
libsodium                 1.0.13               hba5e272_2    defaults
libssh2                   1.8.0                h1218725_2    defaults
libtiff                   4.0.8                h8cd0352_9    defaults
libxml2                   2.9.4                hbd0960b_5    defaults
libxslt                   1.1.29               h95a2935_5    defaults
llvmlite                  0.20.0                   py36_0    defaults
locket                    0.2.0            py36hca03003_1    defaults
lxml                      4.1.0            py36h8179fc0_0    defaults
lzo                       2.10                 hb6b8854_1    defaults
markupsafe                1.0              py36h3a1e703_1    defaults
matplotlib                2.1.0            py36h5068139_0    defaults
mccabe                    0.6.1            py36hdaeb55d_0    defaults
mistune                   0.7.4            py36hccd6237_0    defaults
mkl                       2018.0.0             h5ef208c_6    defaults
mkl-service               1.1.2            py36h7ea6df4_4    defaults
mpc                       1.0.3                hc455b36_4    defaults
mpfr                      3.1.5                h7fa3772_1    defaults
mpmath                    0.19             py36h9185fea_2    defaults
msgpack-python            0.4.8            py36h46767b2_0    defaults
multipledispatch          0.4.9            py36hc5f92b5_0    defaults
navigator-updater         0.1.0            py36h7aee5fb_0    defaults
nbconvert                 5.3.1            py36h810822e_0    defaults
nbformat                  4.4.0            py36h827af21_0    defaults
ncurses                   6.0                  ha932d30_1    defaults
networkx                  2.0              py36hefccab9_0    defaults
nltk                      3.2.4            py36h27d1ea0_0    defaults
nose                      1.3.7            py36h73fae2b_2    defaults
notebook                  5.0.0            py36h462289e_2    defaults
numba                     0.35.0              np113py36_6    defaults
numexpr                   2.6.2            py36h0f4f1da_1    defaults
numpy                     1.13.3           py36h2cdce51_0    defaults
numpydoc                  0.7.0            py36he54d08e_0    defaults
odo                       0.5.1            py36hc1af34a_0    defaults
olefile                   0.44             py36ha08bf50_0    defaults
openpyxl                  2.4.8            py36he899640_1    defaults
openssl                   1.0.2o               h26aff7b_0    defaults
packaging                 16.8             py36he5e8135_0    defaults
pandas                    0.20.3           py36hd6655d8_2    defaults
pandoc                    1.19.2.1             ha5e8f32_1    defaults
pandocfilters             1.4.2            py36h3b0b094_1    defaults
partd                     0.3.8            py36hf5c4cb8_0    defaults
path.py                   10.3.1           py36hd33c240_0    defaults
pathlib2                  2.3.0            py36h877a6d8_0    defaults
patsy                     0.4.1            py36ha1b3fa5_0    defaults
pcre                      8.41                 h29eefc5_0    defaults
pep8                      1.7.0            py36hc268eb1_0    defaults
pexpect                   4.2.1            py36h3eac828_0    defaults
pickleshare               0.7.4            py36hf512f8e_0    defaults
pillow                    4.2.1            py36h0263179_0    defaults
pip                       9.0.1            py36hbd95645_3    defaults
pkginfo                   1.4.1            py36h25bf955_0    defaults
ply                       3.10             py36h10e714e_0    defaults
prompt_toolkit            1.0.15           py36haeda067_0    defaults
psutil                    5.4.0            py36ha052210_0    defaults
ptyprocess                0.5.2            py36he6521c3_0    defaults
py                        1.4.34           py36hecf431b_1    defaults
pycodestyle               2.3.1            py36h83e8646_0    defaults
pycosat                   0.6.3            py36hee92d8f_0    defaults
pycparser                 2.18             py36h724b2fc_1    defaults
pycrypto                  2.6.1            py36h72f2894_1    defaults
pycurl                    7.43.0           py36hdb90038_3    defaults
pyflakes                  1.6.0            py36hea45e83_0    defaults
pygments                  2.2.0            py36h240cd3f_0    defaults
pylint                    1.7.4            py36hdee9077_0    defaults
pyodbc                    4.0.17           py36h5478161_0    defaults
pyopenssl                 17.2.0           py36h5d7bf08_0    defaults
pyparsing                 2.2.0            py36hb281f35_0    defaults
pyqt                      5.6.0            py36he5c6137_6    defaults
pysocks                   1.6.7            py36hfa33cec_1    defaults
pytables                  3.4.2            py36hfbd7ab0_2    defaults
pytest                    3.2.1            py36h9963153_1    defaults
python                    3.6.3                h6804ab2_0    defaults
python-dateutil           2.6.1            py36h86d2abb_1    defaults
python.app                2                py36h7fe2238_6    defaults
pytz                      2017.2           py36h2e7dfbc_1    defaults
pywavelets                0.5.2            py36h2710a04_0    defaults
pyyaml                    3.12             py36h2ba1e63_1    defaults
pyzmq                     16.0.2           py36h087ffad_2    defaults
qt                        5.6.2               h9975529_14    defaults
qtawesome                 0.4.4            py36h468c6fb_0    defaults
qtconsole                 4.3.1            py36hd96c0ff_0    defaults
qtpy                      1.3.1            py36h16bb863_0    defaults
readline                  7.0                  h81b24a6_3    defaults
requests                  2.18.4           py36h4516966_1    defaults
rope                      0.10.5           py36h5764ad1_0    defaults
ruamel_yaml               0.11.14          py36h9d7ade0_2    defaults
scikit-image              0.13.0           py36h398857d_1    defaults
scikit-learn              0.19.1           py36hffbff8c_0    defaults
scipy                     0.19.1           py36h3e758e1_3    defaults
seaborn                   0.8.0            py36h74df97e_0    defaults
setuptools                36.5.0           py36h2134326_0    defaults
simplegeneric             0.8.1            py36he5b5b09_0    defaults
singledispatch            3.4.0.3          py36hf20db9d_0    defaults
sip                       4.18.1           py36h2824476_2    defaults
six                       1.11.0           py36h0e22d5e_1    defaults
snowballstemmer           1.2.1            py36h6c7b616_0    defaults
sortedcollections         0.5.3            py36he9c3ed6_0    defaults
sortedcontainers          1.5.7            py36ha982688_0    defaults
sphinx                    1.6.3            py36hcd1b3e7_0    defaults
sphinxcontrib             1.0              py36h9364dc8_1    defaults
sphinxcontrib-websupport  1.0.1            py36h92f4a7a_1    defaults
spyder                    3.2.4            py36h908396f_0    defaults
sqlalchemy                1.1.13           py36h156b851_0    defaults
sqlite                    3.20.1               h900c3b0_1    defaults
statsmodels               0.8.0            py36h9c68fc9_0    defaults
sympy                     1.1.1            py36h7f3cf04_0    defaults
tblib                     1.3.2            py36hda67792_0    defaults
terminado                 0.6              py36h656782e_0    defaults
testpath                  0.3.1            py36h625a49b_0    defaults
tk                        8.6.7                hcdce994_1    defaults
toolz                     0.8.2            py36h7b95164_0    defaults
tornado                   4.5.2            py36h468dda9_0    defaults
traitlets                 4.3.2            py36h65bd3ce_0    defaults
typing                    3.6.2            py36haa2d9ef_0    defaults
unicodecsv                0.14.1           py36he531d66_0    defaults
unixodbc                  2.3.4                h4cb4dde_1    defaults
urllib3                   1.22             py36h68b9469_0    defaults
wcwidth                   0.1.7            py36h8c6ec74_0    defaults
webencodings              0.5.1            py36h3b9701d_1    defaults
werkzeug                  0.12.2           py36h168efa1_0    defaults
wheel                     0.29.0           py36h3597b6d_1    defaults
widgetsnbextension        3.0.2            py36h91f43ea_1    defaults
wrapt                     1.10.11          py36hc29e774_0    defaults
xlrd                      1.1.0            py36h336f4a2_1    defaults
xlsxwriter                1.0.2            py36h3736301_0    defaults
xlwings                   0.11.4           py36hc75f156_0    defaults
xlwt                      1.2.0            py36h5ad1178_0    defaults
xz                        5.2.3                ha24016e_1    defaults
yaml                      0.1.7                hff548bb_1    defaults
zeromq                    4.2.2                h131e0f7_1    defaults
zict                      0.1.3            py36h71da714_0    defaults
zlib                      1.2.11               h60db283_1    defaults
```

**Comment by goanpeca** [comment]
>"The following packages will be modified", click "Apply". --> Nothing happens! 

What does that mean?

**Comment by yazabaza** [comment]
It means that the dialog box dismisses (goes away), and that's it. Nothing else happens. Updates are not done. Unless they are happening behind the scenes, but there is no indication of any updates happening in the UI, and the packages still appear in the "Updatable" list, even after refreshing the list.

**Comment by goanpeca** [comment]
Ok @yazabaza thanks for the report, we will look into it. Now in the meantime, if you click the latest version instead of the update option. Does it install the latest version ?

**Comment by yazabaza** [comment]
It seems to behave the same way. You still need to click "Apply" at bottom, and then nothing.

**Comment by goanpeca** [comment]
I just tried the same version on Mac, trying to do what you are doing gets me this dialog.

<img width="424" alt="screen shot 2018-04-03 at 16 30 34" src="https://user-images.githubusercontent.com/3627835/38276955-6391c630-375c-11e8-9801-e9eefb7fba5d.png">

Try opening navigator from the terminal, and see if any errors appear

Open a terminal and type

```
anaconda-navigator
```

**Comment by yazabaza** [comment]
Yes, but if you click Apply nothing happens.

**Comment by goanpeca** [comment]
Yes I can reproduce @yazabaza working on a fix

**Comment by joesoap99** [comment]
This happens (or does not happen) in Windows 8.1 also with Navigator 1.82.
There is no progress bar visible for the actual updating process.
(It is available for the large icon programs shown on the Home page)

What I do, is click Apply and wait for 2 minutes. Then I close down Navigator.
Most times when I reopen Navigator it indicates that the upgrade has taken place but not always. I then increase the 2 minutes wait to 4 minutes and so on. For large modules that is risky if it only half upgrades.

**Comment by alport** [comment]
I am having the same problem; after selecting any environment, then all the "upgradable" packages, if I select any of these Upgradable packages and "Apply", I get the scrolling blue progress abr, but no packages are listed. This Install Packages window seems to hang.
I am tempted to just do a new install - in OSX - just delete the Application and redownload??

**Comment by nradonic** [comment]
I'm running Mac OS 10.13.5beta, and have been seeing the same effect since I loaded AN a couple of months ago. The update function never completes. Blue bar of death keeps rolling across the bottom. And 'Cancel' button does not cancel the function. In effect I can't install most missing packages, or update most of the ones that are present. Maybe some update, but a lot just wait.

**Comment by bzeyben** [comment]
It is still a problem with MacOS 10.13.4 and Anaconda Navigator 1.8.4.
The update "Update Packages" window remains empty when a package is selected for update.

**Comment by goanpeca** [comment]
Fixes since version 1.8.4

---

Please remember to update to the latest version of Navigator to include
the latest fixes.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type:

```
conda update conda
conda update anaconda-navigator
conda update navigator-updater
```

**Comment by froggy58400** [comment]
It is still a problem (e.g. update Numpy) with MacOS 10.13.5 and Anaconda Navigator 1.8.7
![screen shot 2018-06-27 at 09 30 45](https://user-images.githubusercontent.com/22303538/41959394-1b7641a4-79ed-11e8-804d-6ecfc4c2bae1.png)
![screen shot 2018-06-27 at 09 31 31](https://user-images.githubusercontent.com/22303538/41959395-1ba9017a-79ed-11e8-803c-35a864fc7897.png)
![screen shot 2018-06-27 at 09 32 50](https://user-images.githubusercontent.com/22303538/41959397-1bd19db0-79ed-11e8-9c9c-e54e692cb475.png)
![screen_shot_2018-06-27_at_09_28_08](https://user-images.githubusercontent.com/22303538/41959398-1bfdff40-79ed-11e8-9c25-ca3247e0aa11.jpg)




I did run the 3 commands suggested above by @goanpeca

**Comment by ananthkm1** [comment]
I am using Anaconda 1.8.7 in windows 8 and facing the same problem like unable to update and install new packages. conda install faker >> gives message like it was already installed, but no shown in anaconda installed packages list.

**Comment by wilfriedh** [comment]
It looks like I have the same problem, 
but the real problem is that Navigator displays a package as updateable while in fact it is already up to date. 
E.g. 
- Navigator displays that Spyder can be updated to 3.2.8 while Sypder's Help-About already displays version 3.2.8. 
- Navigator displays numpy can be updated to 1.14.3 while .../numpy/version.py lists version 1.14.3.

**Comment by goanpeca** [comment]
@wilfriedh could you provide the output of `conda info` and `conda list` ?

**Comment by wilfriedh** [comment]
Another observation:
navigator (meanwhile updated to 1.9.2) shows that matplotlib is installed as version 2.2.2, updateable, but after choosing it for update, the reply is "all requested packages already installed".
Removing the matplotlib package works as required.
After removal, in the list of "not installed" packages, matplotlib version is displayed  as **3.0.0**, but after choosing it for install, version **2.2.2** is installed.

**Comment by Emanuelh77** [comment]
I still have this issue

**Comment by alport** [comment]
The only way I could solve this problem was by deleting and reinstalling - take the easy path - it works!

**Comment by Arkady-A** [comment]
Relaunching conda help me, but same problem here. I've noticed that the problem occurs when some time have passed.

**Comment by Pratiwir** [comment]
Anaconda Navigator 1.9.7
Same issue.
Closeing and restarting Anaconda Navigator solves the problem.

**Comment by shaunbarbour** [comment]
1.9.7
same issue.
closing and restarting does not fix it.

**Comment by AZippelius** [comment]
Also 1.9.7 64bit on Windows
This is still an issue for me. Restarting or reinstalling does not fix it.
However, it only happens in the root enviroment. I can update packages in a newly created enviroment.

**Comment by tlekang** [comment]
I also see this issue on 1.9.7 in 64bit Windows 10, in both the base (root) environment and a new environment I created.

The reason I was trying to use Navigator to update some packages in base (root) was because I was seeing some errors when trying to use conda update in the Anaconda Prompt. But then I created a new environment (using Navigator) and then used conda install in Prompt to get the packages I wanted, which all installed at what appeared to be the latest versions.

Regardless which environment I select, in Navigator, the issue still arises that in the small dialog box that pops up after selecting "apply" at the bottom of the package list (the box that says "the following packages will be updated" in the title bar), but nothing ever appears in that box to then be able to click apply again.

**Comment by sukritranjan** [comment]
I am having the same issue. 

Attempting to do it via the command line and executing the command "conda update --all"

Results in the error: "CondaMultiError: AssertionError()
()"

Any advice?

**Comment by NeelKanwal** [comment]
conda update conda 

gives error, unrecognized command in windows 10. I am facing issue in updating packages in anaconda navigator

**Comment by ifrozeup** [comment]
Just faced the same issue. 
Before trying some fancy fix, try to restart the environment a few times..it works fine for me now.

**Comment by mayest** [comment]
I have the same issue as described in multiple comments above, and have had it since sometime in the summer (2019). I have done several clean installations and downloaded and clean installed the latest Anaconda 2019.10 for Windows (64-bit). I cannot update any packages, and I've tried every "fix" that I've seen. Something is very broken in Conda.

**Comment by joesoap99** [comment]
When you clean installed did you also manually remove all the old files on the C Drive such as .conda, .condarc, conda, licence_conda etc? 
Do a search on the C Drive for conda and any other Anaconda files from python module usage. That got my version working.

**Comment by mayest** [comment]
@joesoap99 Thanks for the suggestion. I'll give that a try, though I'm pretty sure that I've done that previously.

**Comment by dtle142** [comment]
My spyder doesn't have numpy, pandas, matplotlib, etc (all the important ones) and I try to install it via Anaconda Navigator Environment but failed. This is what is showed after I hit _Apply_ button
![image](https://user-images.githubusercontent.com/29204266/71816950-cd9cae00-30b6-11ea-8e5a-e4ff05cc3f89.png)

**Comment by psvrao** [comment]
Facing the same issue as above, after updating navigator to 1.9.7. It is working fine in the root, but facing this issue in other environments. What could be the potential solution?

![image](https://user-images.githubusercontent.com/30388927/72712743-a7d0d800-3b91-11ea-9fab-dea96ccf08d1.png)

**Comment by alexgermann** [comment]
No solution yet? Running into the same issue on 1.9.7.

**Comment by LilithElina** [comment]
Why is this closed? Is there a solution somewhere? I still have that issue.

**Comment by robert99** [comment]
Not sure this was ever fixed officially.
I fixed mine by updating conda in the terminal.
(right click base environment black arrow in Anaconda Environments section)

> conda update conda
and 
> conda update anaconda

I am now using conda 4.8.1 version

**Comment by mlduarte** [comment]
I have the same issue.  have tried conda update conda and conda update anaconda with no luck.  Conda Version 4.8.2.  Windows 10 Pro.  Anaconda version "custom" - not sure why.  I select packages to update, click apply, but window with update packages has no packages listed to be modified.

**Comment by beachcapital** [comment]
I have the same issue. Why was this closed when so many people still have the problem on the latest version of conda?

**Comment by robert99** [comment]
> I have the same issue. have tried `conda update conda` and` conda update anaconda` with no luck. Conda Version 4.8.2. Windows 10 Pro. Anaconda version "custom" - not sure why. I select packages to update, click apply, but window with update packages has no packages listed to be modified. also tried:
> 
> ```
> conda update anaconda-navigator
> conda update navigator-updater
> ```

I think this happens when there actually is a later version of the module but that package is not proven during the pre-installation check as consistent with the other supporting packages you have already installed. The version you actually have got installed has been checked as being consistent. They really should provide a message that states that.

The problem arises because the updaters of the packages do not update or test what newer version of supporting packages actually work - so they stick to out of date ones as being necessary. This is probably why Anaconda do not offer any solution.

**Comment by C-Sharpener** [comment]
I have the same issue, too.
I'm here to give one vote.

**Comment by aktaseren** [comment]
I read all the comments on this issue. Nothing useful and it has been opened for 2 years. 
Hopefully, someone would provide a solution

**Comment by alvgaona** [comment]
Yes, indeed. This is still an issue, reproduced this in macOS Catalina 10.15.4.

```
anaconda-navigator 1.9.12
conda 4.8.3
```

**Comment by FredWint** [comment]
> 
> 
> Not sure this was ever fixed officially.
> I fixed mine by updating conda in the terminal.
> (right click base environment black arrow in Anaconda Environments section)
> 
> > conda update conda
> > and
> > conda update anaconda
> 
> I am now using conda 4.8.1 version

This worked for me. I was then able to select the specific package I wanted to update in Navigator and then update it.

**Comment by yvan-burrie** [comment]
@goanpeca You closed this issue due to a fix that worked at the time, however, myself among many others are still experiencing this issue to this day.

I have tried every suggestion in each comment from this issue and I have looked at StackOverflow too.

No success!

**Comment by robert99** [comment]
Have you tried clicking the Update Index tab in the Environments window?

As far as I can see updates are working for people when they can work. That is comply with all the dependencies upon other versions of Python/ conda/ anaconda/ modules installed. 

The problem is that Anaconda does not communicate this properly. It gives an update arrow telling you there is an update available but when you try to update it tells you all conditions are already satisfied (with your old version being the latest your particular installation can handle).

Update Index seems to update what versions of python /modules etc are needed - so you may get further forward.

**Comment by csoja** [comment]
You may be running into a conflict with a particular version of the anaconda metapackage you have installed.  If you install the "custom" version of the anaconda metapackage, you may find that you do not get as many "all conditions are already satisfied messages.

**Comment by yazabaza** [comment]
FYI I am the original creator/submitter of this issue. My fix was that I stopped using Anaconda and switched to using only the conda command-line version.

**Comment by robertoash** [comment]
I am also experiencing this issue on Mac OS 11.0.1 and Anaconda Navigator 1.10.1

**Comment by Hex-Liu** [comment]
experiencing the same for me on Mac OS 11.0.1 and Anaconda Navigator 1.10.0

**Comment by jpcofr** [comment]
I'm facing the issue on Windows 10 and Anaconda Navigator 1.10.0

**Comment by robert99** [comment]
I have come to the conclusion that this is not exactly a real issue. Anaconda tells you there is a later update but if your version of Python, Conda, Anaconda and other packages you have installed are not compatible, then the upgrade will not, and cannot, take place. The problem is that Anaconda does not give any messages out that this is the case, so folks think there is something wrong..

**Comment by rubencanlas** [comment]
Reporting that this is what's happening to me. I'm on Macos 10.15.7 and Anaconda Navigator 1.10.0. I do my updates using Terminal now.

**Comment by jerrynexis** [comment]
I'm having the same issue on Win10 with Anaconda Navigator 2.0.3 in the base environment. None of the above does work. (Updates work for user-created environments.)

**Comment by yazabaza** [comment]
This issue was marked as closed a long time ago but apparently still exists. Since I am the original submitter and cannot re-open the issue I have created a [new issue ](https://github.com/ContinuumIO/anaconda-issues/issues/12445) referencing this original issue.

**Comment by PolykarposPolykarpidis** [comment]
I have the same issue too! is there any new info about the solution?

**Comment by robert99** [comment]
I think they have changed the system and that updates are not possible any more on Windows.
You can still install new modules using conda but not if Anaconda has already supplied them with the original install.
They have not bothered to tell any one or change the coding.
All you can do is update to the latest fixed versions. There is a new one available now.
I now use WinPython which is more up to date than Anaconda.
