### ISSUE TITLE
Anaconda navigator 4K issue

### ISSUE THREAD

**Issue by akshaybabloo** [ContinuumIO/anaconda-issues#920]
The anaconda navigator is very small when using in a 4K display, and stays small when moving the file from 4K to 1080p screen.

Any idea on how to get rid of this problem?

Thanks.

Edit:

I am trying this on Windows 10.

**Comment by goanpeca** [comment]
Could you try to run this in the console

```bash
set QT_AUTO_SCREEN_SCALE_FACTOR=1
anaconda-navigator
```

**Comment by dkon99** [comment]
I am on win10 and that didn't seem to fix the problem.

**Comment by akshaybabloo** [comment]
Nope. That didn't work for me.

**Comment by pdhixenbaugh** [comment]
Didn't work for me either.

set QT_AUTO_SCREEN_SCALE_FACTOR=1
anaconda-navigator
  File "<ipython-input-1-2aede75ec3de>", line 1
    set QT_AUTO_SCREEN_SCALE_FACTOR=1
                                  ^
SyntaxError: invalid syntax

**Comment by ccordoba12** [comment]
This will be solved once we add packages for Qt5/PyQt5.

**Comment by akshaybabloo** [comment]
Any timeframe on when that can happen?

**Comment by ccordoba12** [comment]
Yes, for the next Anaconda release at the end of September :-)

**Comment by ccordoba12** [comment]
But the packages will be added a couple of weeks before that :-)

**Comment by goanpeca** [comment]
This has been solved in the latest Navigator (1.3)

`conda update anaconda-navigator`

or

`conda update anaconda` to update to the latest anaconda version :-)

**Comment by Joshuaalbert** [comment]
This is still a problem in the 4.2.0. When I first installed on win10 it seemed fine, then upon restarting the computer the layout was tiny.
