### ISSUE TITLE
anaconda3/bin/jupyter-notebook No such file or directory: 'conda'

### ISSUE THREAD

**Issue by Diti24** [ContinuumIO/anaconda-issues#921]
I get the following error after a fresh install of 
 /opt/downloads/Anaconda3-4.1.1-Linux-x86_64.sh
The issue first happened with 4.1.0, 4.0.0 is working fine. 
I posted the same issue here 
https://github.com/conda/conda-build/issues/1035
but I did not get any feedback yet.

anaconda3/bin/jupyter-notebook 
[W 11:12:21.682 NotebookApp] Unrecognized JSON config file version, assuming version 1
Traceback (most recent call last):
  File "anaconda3/bin/jupyter-notebook", line 6, in <module>
    sys.exit(notebook.notebookapp.main())
  File "/home/diti/anaconda3/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, *_kwargs)
  File "/home/diti/anaconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/home/diti/anaconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, *_kwargs)
  File "/home/diti/anaconda3/lib/python3.5/site-packages/notebook/notebookapp.py", line 1069, in initialize
    self.init_configurables()
  File "/home/diti/anaconda3/lib/python3.5/site-packages/notebook/notebookapp.py", line 837, in init_configurables
    parent=self,
  File "/home/diti/anaconda3/lib/python3.5/site-packages/nb_conda_kernels/manager.py", line 19, in **init**
    specs = self.find_kernel_specs() or {}
  File "/home/diti/anaconda3/lib/python3.5/site-packages/nb_conda_kernels/manager.py", line 129, in find_kernel_specs
    self.conda_info = self._conda_info()
  File "/home/diti/anaconda3/lib/python3.5/site-packages/nb_conda_kernels/manager.py", line 29, in _conda_info
    p = subprocess.check_output(["conda", "info", "--json"]
  File "/home/diti/anaconda3/lib/python3.5/subprocess.py", line 626, in check_output
    *_kwargs).stdout
  File "/home/diti/anaconda3/lib/python3.5/subprocess.py", line 693, in run
    with Popen(_popenargs, **kwargs) as process:
  File "/home/diti/anaconda3/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/home/diti/anaconda3/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'conda

**Comment by sidgupta234** [comment]
I am facing the exact the same issue.

**Comment by sidgupta234** [comment]
Got it use `jupyter notebook` instead.

**Comment by Diti24** [comment]
Worked also for me. 
I would propose to remove jupyter-notebook from anaconda. It is confusing.

**Comment by biographie** [comment]
same issue here. I've tried uninstalling and reinstalling, no luck
how did you guys resolve it? 
when i try executing jupiter notebook i get that the command is not found.
any ideas?

**Comment by biographie** [comment]
yes I'm aware that that's a command - for some reason it doesn't recognise it.
below is there error i get when trying to launch jupyter from anaconda navigator:
/Users/bio/anaconda/bin/jupyter_mac.command ; exit;
/Users/bio/.zshrc:86: unmatched "
------------------------------------------------------------
~ » /Users/bio/anaconda/bin/jupyter_mac.command ; exit;
[W 17:36:05.472 NotebookApp] Unrecognized JSON config file version, assuming version 1
Traceback (most recent call last):
  File "/Users/bio/anaconda/bin/jupyter-notebook", line 6, in <module>
    sys.exit(notebook.notebookapp.main())
  File "/Users/bio/anaconda/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/bio/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/Users/bio/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/bio/anaconda/lib/python2.7/site-packages/notebook/notebookapp.py", line 1069, in initialize
    self.init_configurables()
  File "/Users/bio/anaconda/lib/python2.7/site-packages/notebook/notebookapp.py", line 837, in init_configurables
    parent=self,
  File "/Users/bio/anaconda/lib/python2.7/site-packages/nb_conda_kernels/manager.py", line 19, in __init__
    specs = self.find_kernel_specs() or {}
  File "/Users/bio/anaconda/lib/python2.7/site-packages/nb_conda_kernels/manager.py", line 129, in find_kernel_specs
    self.conda_info = self._conda_info()
  File "/Users/bio/anaconda/lib/python2.7/site-packages/nb_conda_kernels/manager.py", line 29, in _conda_info
    p = subprocess.check_output(["conda", "info", "--json"]
  File "/Users/bio/anaconda/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/Users/bio/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Users/bio/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by bollwyvl** [comment]
@Diti24 We've released versions of `nb_conda`, `nb_conda_kernels` and `nb_anacondacloud` through the official Anaconda conda repos that should resolve the issues you are seeing! sorry for the delay!

```shell
conda update nb_conda nb_conda_kernels nb_anacondacloud
```

As-installed kernel names that are eligible for being `default` (e.g. `python2`, `python3`, `ir`, etc.) will be maintained unmodified, so they should always appear there.

The downside is as many as three options for the current env, i.e. if you are in root, you will see _Python 2_ and _Python [root]_ and _Python [default]_, you can now reproducibly capture which environment your kernel should run against.

meta: https://github.com/Anaconda-Platform/anaconda-nb-extensions/issues/166

**Comment by jackjm** [comment]
I got stuck at "conda fetching package metadata" when applying `conda update nb_conda nb_conda_kernels nb_anacondacloud`

So I run `conda update requests` and applied the updates again. 
After that I can launch Jupyter Notebook from Navigator smoothly.

Hope this helps.

**Comment by RodenLuo** [comment]
@biographie 
In your case, try 
`/Users/bio/anaconda/bin/jupyter notebook`

The above command works for me. But launching from Navigator still fails.

@jackjm 
Works for me! Launch from Navigator successfully after doing
`conda update nb_conda nb_conda_kernels nb_anacondacloud`
This starting `conda` should be the path to conda command. For me, using anaconda, it is "/Applications/anaconda/bin/conda". (So the full command becomes `/Applications/anaconda/bin/conda update nb_conda nb_conda_kernels nb_anacondacloud`)

I did not get "conda fetching package metadata" problem. After this, I am able to launch Jupyter Notebook from Navigator. And the `./jupyter notebook` still works after this.

**Comment by yuvipanda** [comment]
I'm running into this now when trying to spawn instances from JupyterHub, which runs via the jupyterhub-singleuser command (https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/singleuser.py). Moving back to 4.0.0 fixed it.

**Comment by yuvipanda** [comment]
This only happens when conda is not in PATH. If conda is in PATH, it works ok. Is having conda in PATH a requirement for using conda? (am pretty new to conda)

**Comment by goanpeca** [comment]
>This only happens when conda is not in PATH. If conda is in PATH, it works ok. Is having conda in PATH a requirement for using conda? (am pretty new to conda)

Yep

**Comment by liupb001** [comment]
`C:\>jupyter notebook
[W 20:34:04.970 NotebookApp] Unrecognized JSON config file version, assuming ver
sion 1
Traceback (most recent call last):
  File "d:\Anaconda2\Scripts\jupyter-notebook-script.py", line 5, in <module>
    sys.exit(notebook.notebookapp.main())
  File "d:\Anaconda2\lib\site-packages\jupyter_core\application.py", line 267, i
n launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "d:\Anaconda2\lib\site-packages\traitlets\config\application.py", line 59
5, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "d:\Anaconda2\lib\site-packages\traitlets\config\application.py", line 74
, in catch_config_error
    return method(app, *args, **kwargs)
  File "d:\Anaconda2\lib\site-packages\notebook\notebookapp.py", line 1069, in i
nitialize
    self.init_configurables()
  File "d:\Anaconda2\lib\site-packages\notebook\notebookapp.py", line 837, in in
it_configurables
    parent=self,
  File "d:\Anaconda2\lib\site-packages\nb_conda_kernels\manager.py", line 19, in
 __init__
    specs = self.find_kernel_specs() or {}
  File "d:\Anaconda2\lib\site-packages\nb_conda_kernels\manager.py", line 129, i
n find_kernel_specs
    self.conda_info = self._conda_info()
  File "d:\Anaconda2\lib\site-packages\nb_conda_kernels\manager.py", line 29, in
 _conda_info
    p = subprocess.check_output(["conda", "info", "--json"]
  File "d:\Anaconda2\lib\subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['conda', 'info', '--json']' returned no
n-zero exit status 1

C:\>`

What the problem when I cmd `jupyter notebook` it throw an error ...

**Comment by zaghetto** [comment]
C:\Windows\system32>jupyter notebook
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\jupyter-notebook-script.py", line 5, in <module>
    sys.exit(notebook.notebookapp.main())
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1296, in initialize
    self.init_webapp()
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1093, in init_webapp
    self.jinja_environment_options
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 167, in __init__
    default_url, settings_overrides, jinja_env_options)
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 259, in init_settings
    nbextensions_path=jupyter_app.nbextensions_path,
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 807, in nbextensions_path
    from IPython.paths import get_ipython_dir
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\__init__.py", line 49, in <module>
    from .terminal.embed import embed
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\terminal\embed.py", line 18, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\terminal\interactiveshell.py", line 94, in <module>
    class TerminalInteractiveShell(InteractiveShell):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\terminal\interactiveshell.py", line 139, in TerminalInteractiveShell
    highlighting: \n %s""" % ', '.join(get_all_styles())
  File "C:\ProgramData\Anaconda3\lib\site-packages\pygments\styles\__init__.py", line 79, in get_all_styles
    for name, _ in find_plugin_styles():
  File "C:\ProgramData\Anaconda3\lib\site-packages\pygments\plugin.py", line 62, in find_plugin_styles
    for entrypoint in iter_entry_points(STYLE_ENTRY_POINT):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pygments\plugin.py", line 45, in iter_entry_points
    import pkg_resources
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2985, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2971, in _call_aside
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 3013, in _initialize_master_working_set
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2544, in activate
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2118, in declare_namespace
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2058, in _handle_ns
  File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2087, in _rebuild_mod_path
AttributeError: '_NamespacePath' object has no attribute 'sort'
